### ISSUE TITLE
MsgType Unknown: 43

### ISSUE THREAD

**Issue by hillerliao** [littlecodersh/ItChat#10]
这是什么消息类型？
'''
MsgType Unknown: 43
{'ActualNickName': u'\u7a0b\u80d6\u5988', u'AppInfo': {u'Type': 0, u'AppID': u''}, u'ImgWidth': 216, u'FromUserName': u'@@d2f5917f3b6d1f0a117e0567327bd2eef68f10d21a2e73bdfa9985e8bebb752c', u'PlayLength': 30, u'ImgStatus': 1, u'RecommendInfo': {u'UserName': u'', u'Province': u'', u'City': u'', u'Scene': 0, u'QQNum': 0, u'Content': u'', u'Alias': u'', u'OpCode': 0, u'Signature': u'', u'Ticket': u'', u'Sex': 0, u'NickName': u'', u'AttrStatus': 0, u'VerifyFlag': 0}, u'Content': u'&lt;?xml version="1.0"?&gt;<br/>&lt;msg&gt;<br/>\t&lt;videomsg aeskey="34306334343638626661666339613136" cdnthumbaeskey="34306334343638626661666339613136" cdnvideourl="30690201000462306002010002042ebfb30202032df02a0204a9e0c2dc0204573d6171043e617570766964656f5f663939646430356439393631373737335f313436333633383936355f313432323435313930353136336361373361653533363031390201000201000400" cdnthumburl="30690201000462306002010002042ebfb30202032df02a0204a9e0c2dc0204573d6171043e617570766964656f5f663939646430356439393631373737335f313436333633383936355f313432323435313930353136336361373361653533363031390201000201000400" length="3874273" playlength="30" cdnthumblength="14622" cdnthumbwidth="216" cdnthumbheight="288" fromusername="wxid_2vbandig705a22" md5="6d774c9d0b4063b0b10afe0329415230" /&gt;<br/>&lt;/msg&gt;<br/>', u'MsgType': 43, u'ImgHeight': 288, u'StatusNotifyUserName': u'', u'StatusNotifyCode': 0, u'NewMsgId': 5493764242847474377, u'Status': 3, u'VoiceLength': 0, u'MediaId': u'', u'MsgId': u'5493764242847474377', u'ToUserName': u'@962bf97e86593c5addb1195a770cc9d5651cdbffc811301dce661a63dbb8505a', u'ForwardFlag': 0, u'FileName': u'', u'Url': u'', u'HasProductId': 0, u'FileSize': u'', u'AppMsgType': 0, 'ActualUserName': u'@8a77ec2e0bdfd17cfbd8aa90185f7dec3cd7ae797e4dc1b9b932686829b6bed5', u'Ticket': u'', u'CreateTime': 1463640438, u'SubMsgType': 0}
'''

**Comment by littlecodersh** [comment]
@hillerliao 我记得视频请求会触发43。
