### ISSUE TITLE
可否将源代码中的if-elif换成case

### ISSUE THREAD

**Issue by medmin** [littlecodersh/ItChat#100]
能否把源代码里，if-elif换成case, 便于扩展选项？

**Comment by littlecodersh** [comment]
具体来说要怎么换case？

**Comment by tempdban** [comment]
@medmin python并没有原生的switch-case语句块。如果用字典模拟switch-case的话，分支一多，会使你痛不欲生的。

**Comment by medmin** [comment]
不好意思，我的python学的比较水。我本意是换成case-switch，这样不用那么多if-elif-elif-elif了。
你这个repo的商用价值其实挺大，但那时，客户可能就需要实现多个关键词，比如十几、二十多个关键词，目前源码里的方式就不那么“优雅”。

**Comment by littlecodersh** [comment]
@medmin 可以尝试用一下tempdban说的字典，字典的值里是可以放方法的
如果感觉解决不了的话也可以具体的描述一下需求，我给你一个大致的演示代码

**Comment by medmin** [comment]
好的，感谢！我学得水，先自己折腾一下吧。

**Comment by tempdban** [comment]
@medmin 昨天也有个人说要商用，大家为什么都要想着钱呢？
想必每一次web微信协议修改，repo主都是很痛苦的。但是
repo主付出了这么多心血，你们一所谓的“商用”，微信想必会大面积封杀，心血全废。
其实微信公众号已经能满足大部分的需求了，您可以考虑使用repo主的公众号项目。
这只是我的一家之言，不代表repo主的想法。
望您高抬贵手。
