### ISSUE TITLE
如何获得群里的群友的头像的图片具体binary数据？

### ISSUE THREAD

**Issue by 9cat** [littlecodersh/ItChat#101]
比如获得：

```python
"HeadImgUrl": "/cgi-bin/mmwebwx-bin/webwxgetheadimg?seq=642242818&sername=@@21ec4b514edf3e7cb867e0512fb85f3a5e6deb657f4e8573d656bcd4558e3594&skey=",
```

但如何获得头像呢？ 前面的域名应该是用什么？

**Comment by littlecodersh** [comment]
@9cat 我更新了一个版本1.1.13，加入了get_head_img方法：
```python
get_head_img(userName=None, chatroomUserName=None, picDir=None):
```
如果你想要获取群聊的头像，仅设置chatroomUserName
如果你想要获取朋友的头像，仅设置userName
如果你想要获取群聊用户的头像，两个值都设置

另，如果不设置picDir，将会返回io.BytesIO()对象，使用getvalue即可获取binary数据

**Comment by wwj718** [comment]
@littlecodersh 请教问题来啦

1. get_head_img在1.2.18中用法还是一样吗
2. userName和chatroomUserName都是id么
3. picDir填写目录的话好像会报错，如果写文件路径，似乎改名为imgPath更合适
4. picDir使用文件路径，存下的文件是0字节

**Comment by soulmachine** [comment]
@littlecodersh 貌似这个回答有点过时了，现在`get_head_img()`不设置`picDir`的话返回的不是`io.BytesIO()`对象，而是`io.BytesIO().getValue()`后的bytes

**Comment by littlecodersh** [comment]
@soulmachine 多谢，已更新！
