### ISSUE TITLE
生成的二维码过大，无法扫码

### ISSUE THREAD

**Issue by longfengfirst** [littlecodersh/ItChat#102]

**Comment by bopo** [comment]
建议使用pyqrcode库比较好，在mac 下 生成终端二维码都乱了

**Comment by longfengfirst** [comment]
在文件夹下有个图片，打开后，扫码，报下面的错误，
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
感觉这个好难

**Comment by tempdban** [comment]
@bopo mac下请用itchat.auto_login(enableCmdQR = -2)

**Comment by tempdban** [comment]
@bopo 这个应该是网络不稳定吧，再试一次

**Comment by littlecodersh** [comment]
@bopo pyqrcode的话是针对的linux主流的终端控制符的专门优化，在其他平台上还是会碰到问题。
关于二维码我的建议是这样的：
* 如果有图形界面，应该图形显示二维码
* 如果没有图形界面，我也提供命令行二维码的选项
* 即使你使用奇怪的终端，我这里使用了ascii字符输出一定是没有问题的
* 图像大小问题的话，无图形界面大都是ssh使用，自行调整连接用终端的显示即可

**Comment by miaohf** [comment]
![image](https://user-images.githubusercontent.com/10840733/47845896-362c3300-de01-11e8-8b87-57a21ce93f5d.png)
我生成的二维码微信扫描无法识别，麻烦littlecodersh帮看下，拜托了
