### ISSUE TITLE
没啥问题

### ISSUE THREAD

**Issue by synodeai** [littlecodersh/ItChat#1020]
调研了一周框架、什么可爱狗/猫，鲲鹏都用了，对接出现问题，业务实现不了，找作者也不给维护，又浪费一周。
后来没办法又去找了一些所谓的源码的，打了钱后，部署本地后，出现问题也不给回复，又被NND坑了，后来问群友才知道是二倒贩子。后来用了wechaty的pad local，发现只给指定用户开放，，最终终于找到了一家靠谱的并上线了，E云管家，感谢楼下大佬指点，保住工作了。。（注意 这个收费服务，不过是只对企业开放，算是有人维护 也放心了些。。）

**Comment by ropz12138** [comment]
我想问一下，e云管家怎么以语音的形式，发送自己制作的音频文件。我看官方文档里，一定要填下载语音的URL？

**Comment by Devo919** [comment]
> 我想问一下，e云管家怎么以语音的形式，发送自己制作的音频文件。我看官方文档里，一定要填下载语音的URL？

任何技术都可以发的 ，silk格式 链接呗

**Comment by ipingxingshikong** [comment]
https://apifox.com/apidoc/shared-9652da8e-1f7c-4ef3-861c-2bfd721c395a?pwd=o9rIzwBh
