### ISSUE TITLE
群聊@判断误报

### ISSUE THREAD

**Issue by hengqujushi** [littlecodersh/ItChat#104]
像“哈哈哈@hengqujushi”这种消息的isAt属性是False，感觉不用匹配空格

**Comment by littlecodersh** [comment]
@hengqujushi 这里的确出现了问题，我做一个修复

**Comment by hengqujushi** [comment]
哇 好快 3ks

**Comment by littlecodersh** [comment]
@hengqujushi 你这里是使用的哪个客户端发送的`“哈哈哈@hengqujushi”`消息？

**Comment by tempdban** [comment]
@hengqujushi @littlecodersh 所有的手机客户端，即便是@在最后也是有空格的啊。而且手机上的@是在消息协议里有个bool，并不是你手动敲出来@+ 昵称，对方就会@到。我认为空格这个是feather，不是bug。

**Comment by iniaks** [comment]
@tempdban  现在有办法能在**群聊**中实现真正的@功能么，似乎纯文本的@xxx并不能够真正的@到对方？

**Comment by littlecodersh** [comment]
@tempdban 我改完才想到是不是会有客户端发送@消息的时候后面什么都不带:joy:
