### ISSUE TITLE
如何找到某个群的名字

### ISSUE THREAD

**Issue by hengqujushi** [littlecodersh/ItChat#105]
找某个群的名字，用来匹配该群的消息，是刚需呀

**Comment by littlecodersh** [comment]
@hengqujushi 用这个：
```python
itchat.search_chatrooms(userName='theUserNameYouGot')
```

**Comment by hengqujushi** [comment]
不是呢，我的意思是我们需要判断某条是信息是否来自于某个群，同样的消息，来自不同群，我的reply内容不一样，这个时候，我就需要对群的名字进行判断。

**Comment by tempdban** [comment]
@hengqujushi 
itchat.search_chatrooms(userName=msg['FromUserName'])

**Comment by hengqujushi** [comment]
恩恩 对不起我明白你们的意思了
