### ISSUE TITLE
synccheck返回0,6

### ISSUE THREAD

**Issue by xia0H** [littlecodersh/ItChat#106]
为什么挂了一段时间后，心跳包返回的一直都是0,6。正常的不是应该返回0,2吗？我用火狐浏览器的firebug查看微信官方的一直都是返回0,2。想请教一下，这是为什么？这样会不会有什么问题。 
我的系统是ububtu16.04，python3.5.1

**Comment by littlecodersh** [comment]
@xia0H 使用没什么问题的，就是有消息提示的意思。
我这里之后研究一下怎么清灰0,2。

**Comment by xia0H** [comment]
@littlecodersh  好的，谢谢你。

**Comment by cc2cc** [comment]
当你接受好友申请的时候会产生一个0,6值，只要正常的当成0,2处理就可以了，其他状态下暂时还没有触发产生过
