### ISSUE TITLE
怎么获取每个好友唯一的标识

### ISSUE THREAD

**Issue by kh13** [littlecodersh/ItChat#108]
在运行中发觉，每次重新登录或者重新启动程序。获取好友的ActualUserName都不一样。有什么属性可以永远都标识同一个好友吗

**Comment by littlecodersh** [comment]
@kh13 今天更新了版本，你可以把github上的最新版本下载到本地。
在1.1.16中，群聊会后台自动更新群成员的Uin，这个值是多次登陆都不变的。
