### ISSUE TITLE
二维码好像不能扫？

### ISSUE THREAD

**Issue by erickwoc** [littlecodersh/ItChat#109]
成功运行，出现
>Please scan the QR Code

字样和看起来像二维码的图案，但是并不是二维码，微信也扫描不出。图案如下：
![qq 20161021155504](https://cloud.githubusercontent.com/assets/16463312/19590882/cb75ffc0-97a6-11e6-9481-37acfc25d1a2.png)

**Comment by littlecodersh** [comment]
你详细看一下主页的README
