### ISSUE TITLE
我想给机器人弄个后台界面应该怎么实现？

### ISSUE THREAD

**Issue by Leon-cloud** [littlecodersh/ItChat#11]
我想给机器人弄个后台管理界面应该怎么实现？就是把机器人放服务器上，然后通过浏览器控制信息回复，记录，等等操作。就是类似公众号那样。

**Comment by littlecodersh** [comment]
@Leon-cloud 可以使用django或者flask。

**Comment by liuyang007** [comment]
![img](https://raw.githubusercontent.com/liuyang007/wxBot/master/1.png)
![img](https://raw.githubusercontent.com/liuyang007/wxBot/master/2.png)
网页登陆,掉线web显示二维码扫描.
不知道还可以添加什么.....

**Comment by Leon-cloud** [comment]
我想弄个微信群游戏管理系统，能记录运算显示各个玩家积分，可以后台充值积分等等。

**Comment by liuyang007** [comment]
两个字解决问题:解耦

**Comment by gobonet** [comment]
用怎么django启动itchat？

**Comment by simpleowen** [comment]
有同样的问题: django里面 怎样启动 itchat

Web 程序部署在 Heroku 中

启动命令 

```python
itchat.auto_login(enableCmdQR=2)
itchat.run(True, False)
```
若在 manage.py 启动, 能正常登录, 但在 view 中调用 itchat 时无任何返回

若在 init__.py, settings.py 中启动, 会使得程序不停的生成二维码给用户扫
