### ISSUE TITLE
如何判断是否已经退出登录

### ISSUE THREAD

**Issue by codebean** [littlecodersh/ItChat#113]
如题，如何判断网页登录是否退出？我看进程还在，就是自动回复没有用了

**Comment by littlecodersh** [comment]
@codebean 一般是不会出现进程还在自动回复没有用的情况的。
你的使用环境中扫码手机是否保持了联网以及网络连接是否稳定？
关于判断是否登出，你可以另开一个线程给特定的账号发送消息。
