### ISSUE TITLE
关于网页版群聊的@成员问题

### ISSUE THREAD

**Issue by cc2cc** [littlecodersh/ItChat#114]
看了作者在其他issues中提到过网页版是无法实现客户端那样的@用户的，关于@群成员本人做了一些工作，跟作者讨论下，希望可以实现网页版实现真正的@群成员功能。

本人使用的安卓手机测试，在群1中at123用户
在群里成功@发送后，选择该条信息，全选保存。格式应该是（@+用户名+“空格”+消息）
手机打开一个txt文本文档，将复制的信息保存，关闭文档
重新打开刚才的文档，全选内容后复制
微信打开群2，粘贴文本内容，删除@到“空格”间的用户名，换成456，点发送
然后看这个@用户是否起到了@的真正效果

实际操作证实   @有效，说明想找的特殊“空格”被成功保存在了txt中，
并没有因为保存时的编码原因被替换掉
然后讲该文本发送到电脑上
在python版的微信中 ‘rb’ 模式读取txt内容，发送到群1中，发现@成员失效了...

判断应该是python在读取到send消息过程中对参数进行了编码（即使我们的代码中没有编码，不能保证request.post登模块有没有进行编码，没有仔细研究过模块的源码）

然后用hex editor 编辑器查看txt的十六进制编码
最终定位到了“0xE2 0x80 0x85"
通过谷歌发现该字符串（吐个槽，百度搜不到任何有用信息）
该字符是Unicode Character 'FOUR-PER-EM SPACE' (U+2005)
[http://www.fileformat.info/info/unicode/char/2005/index.htm](url)
[http://www.runoob.com/charsets/ref-utf-punctuation.html](url)
Python中的编码是
Python source code 	u"\u2005"
现在的问题是怎么通过python 将这个字符加载进消息中去，实现真正@用户的效果

**Comment by tempdban** [comment]
请问您通过什么方式知道自己被@了

**Comment by cc2cc** [comment]
@tempdban 群消息开启了消息免打扰后，正常的群成员交流，你手机在黑屏时是不回提示的，当有群成员@你之后，黑屏也会给你主动推送，类似私聊的效果。而且打开微信后，群消息那会员红字提醒你有人@你啊

**Comment by tempdban** [comment]
@cc2cc 明白
您再网页版试过\u2005 能被@到吗

**Comment by cc2cc** [comment]
@tempdban 不行，网页版的没有@功能，我试了很多方法都没能有效@

**Comment by tempdban** [comment]
@cc2cc 那说明编码转换有可能是微信服务器做的，即便是我们发送带\u2005 的@ 服务器也会转换。

**Comment by cc2cc** [comment]
@tempdban 也不排除有这种可能，
但我试的方法毕竟有限，也许微信服务器没做编码转换，只是我没有找到合适的发送数据的方法，所以发出来讨论一下

**Comment by jian23cn** [comment]
我用第一个手机@另外一个，把空格打印出来，的确是一个特殊字符串，用java是chart(8197)

**Comment by infsafe** [comment]
有结果吗了

**Comment by satomic** [comment]
现在\u2005似乎失效了呢。。。
