### ISSUE TITLE
itchat心跳过于频繁的问题

### ISSUE THREAD

**Issue by cc2cc** [littlecodersh/ItChat#117]
今天在client.py中加了几个打印心跳请求返回的代码，
发现itchat心跳平均4~5s就会进行一次synccheck请求（不管有没有新消息或者操作手机微信）返回值都是都是window.synccheck={retcode:"0",selector:"2"}，
这明显过于频繁，是一个异常状态。
![image](https://cloud.githubusercontent.com/assets/10631200/19624962/8c785ed8-993d-11e6-9ff8-01199ffb941f.png)

正常的流程应该是synccheck一次，保持一个长连接，该连接在没有任何消息的情况下20s左右会返回
window.synccheck={retcode:"0",selector:"0"}
当retcode()和selector都为0是是不发送webwxsync请求的，现状itchat频繁发送请求
执行长连接时如果消息进来，synccheck请求会立即返回，然后执行webwxsync请求进行新消息查询

进行修改后查询正常了，但是时临时改的还不完善
![image](https://cloud.githubusercontent.com/assets/10631200/19624971/bb7036ca-993d-11e6-8c71-bd8ebe6e2975.png)

后续会将改好的代码提交

**Comment by littlecodersh** [comment]
@cc2cc 好的，非常感谢你对项目的支持！
你有加我们的群聊吗？群聊里面最近也在讨论这个问题。

**Comment by cc2cc** [comment]
@littlecodersh 群里那个就是我，我已经改好了，马上提交

**Comment by littlecodersh** [comment]
@cc2cc 已经在[新的提交][commit-101]中完成了测试，主要修改了这样几个问题：

**同步线路选择**
在webwxApp.js中，这部分的代码如下：
```javascript
t = "login.weixin.qq.com",
o = "file.wx.qq.com",
n = "webpush.weixin.qq.com";
e.indexOf("wx2.qq.com") > -1 ?
    (t = "login.wx2.qq.com", o = "file.wx2.qq.com", n = "webpush.wx2.qq.com") :
    e.indexOf("wx8.qq.com") > -1 ?
        (t = "login.wx8.qq.com", o = "file.wx8.qq.com", n = "webpush.wx8.qq.com") :
        e.indexOf("qq.com") > -1 ?
            (t = "login.wx.qq.com", o = "file.wx.qq.com", n = "webpush.wx.qq.com") :
            e.indexOf("web2.wechat.com") > -1 ?
                (t = "login.web2.wechat.com", o = "file.web2.wechat.com", n = "webpush.web2.wechat.com") :
                e.indexOf("wechat.com") > -1 && (t = "login.web.wechat.com", o = "file.web.wechat.com", n = "webpush.web.wechat.com");
```
其中用到了三元运算符，即 `condition?trueResult:falseResult`
我修改为了相应的Python代码

**热启动检测**
由于目前已经能够成功清除selector的值，直接使用synccheck会等待长连接返回值
所以使用即时返回的webwxsync，即原先用于获取信息的接口，完成能否热启动的判断

**修改获取消息线程逻辑**
由于synccheck的长连接机制，不再需要在获取消息线程中手动增加延时，故删去
另，由于上一次更新的疏忽，产生了selector为0时一直返回上一次产生消息的bug，做了修复

**群聊自动更新用户**
由于使用了错误的判断方式导致抛出了非预期的bug，也已经做了修复

[commit-101]: https://github.com/littlecodersh/ItChat/commit/1802989e61ff7eba4ec77976d19cf103e6aed97d
