### ISSUE TITLE
文件下载失败...

### ISSUE THREAD

**Issue by zYeoman** [littlecodersh/ItChat#12]
client.py 280行 
`url = 'https://file2.wx.qq.com/cgi-bin/mmwebwx-bin/webwxgetmedia'`
貌似应该改成
`url = 'https://file.wx.qq.com/cgi-bin/mmwebwx-bin/webwxgetmedia'`

file和file2有什么区别?

**Comment by littlecodersh** [comment]
@zYeoman 
谢谢反馈。
是要和登陆的网址对应，登录的网址是wx2那这里就需要有2。
