### ISSUE TITLE
synccheck请求无法返回

### ISSUE THREAD

**Issue by dingwa990** [littlecodersh/ItChat#125]
登录成功了后，为什么经常出现synccheck心跳请求失败（503、连接关闭等错，抓包也是每个这个包都是红色）。。？？但可以发送消息。。
https://webpush.wx2.qq.com/cgi-bin/mmwebwx-bin/synccheck

**Comment by tempdban** [comment]
@dingwa990 经群里反馈，这是微信服务器的问题

**Comment by littlecodersh** [comment]
@dingwa990 你网页版微信可以上么？

**Comment by dingwa990** [comment]
@littlecodersh @tempdban 我现在在看“如何保持itchat持续在线”的issue。暂未运行itchat，早上出现synccheck无法返回后，我便用IE登录web版，可以登录，但抓包syncckeck还是无法返回的状态，但居然还是能够发消息哈哈直到现在。syncckeck不是心跳吗，有问题居然没断掉。。我ios客户端

**Comment by littlecodersh** [comment]
@dingwa990 可以可以，这真是神奇
