### ISSUE TITLE
sync check失败，{retcode:"1100",selector:"0"}

### ISSUE THREAD

**Issue by hackstoic** [littlecodersh/ItChat#130]
设备系统： android 5.1.1
微信版本： 6.3.27

可以正常扫码登录。登录后就在命令行界面显示LOG  OUT. 

我看了itchat的源码， 在源码中加了一些调试信息。 发现在sync check的时候， retcode和selector有问题。

sync check msg: window.synccheck={retcode:"1100",selector:"0"}

我用iphone登录itchat是ok。 看到的retcode和selector是
sync check msg: window.synccheck={retcode:"0",selector:"2"}。 

想问下问题出在哪里， 有没有什么方法解决这个问题？

**Comment by littlecodersh** [comment]
@hackstoic 你有抓过包吗？加一下我们q群抓个包给我吧

**Comment by tempdban** [comment]
新commit已解决这个问题

**Comment by hackstoic** [comment]
谢谢， 问题已解决。
