### ISSUE TITLE
请教下，web多用户环境的实现问题

### ISSUE THREAD

**Issue by fynjue00** [littlecodersh/ItChat#131]
https://github.com/nodeWechat/wechat4u 这是nodejs版的微信。
它有个vue版本的微信。架设后可以同时支持多个微信号登陆。只要登陆成功后，将浏览器关掉，服务器端，也能继续保持微信号的登陆，在服务器端进行每个登陆微信号的消息同步。
研究过它的代码，每个微信号的基础信息（实例）都是以每个微信号登陆时获取到的uuid为键值，保存在一个列表中。
想请教下，像他这种，在服务端运行多个实例，即使浏览器断开了连接，服务端能还能保持这些实例的运行。python要如何实现。

**Comment by tempdban** [comment]
这和语言无关，是计算机世界比较简单的东西
