### ISSUE TITLE
群的'UserName' 是什么?群内成员的uin 如何获取?

### ISSUE THREAD

**Issue by issmile** [littlecodersh/ItChat#144]
如题,因为要输入数据库做唯一的标识,所以需要群号,和用户的uin
1. 获取群列表以后有个群的'UserName' 看起来像个hash值?是什么hash?可以替代群号?感觉这个像群名字的hash,群改名字后还能根据这个hash找到这个吗?我看别人做机器人的时候用的是群号标识的群,看这个列表里大概是'ChatRoomId',这个要怎么获取?
2. 群内成员也好像是只有'UserName',这个uin该如何获取?'KeyWord'又是什么?请大神解答
3. 如何注册群内XX成员邀请了XX人的Handler?

**Comment by littlecodersh** [comment]
@issmile 
1. 如果用ChatRoomId的话你可以itchat.get_chatrooms()，打印出来看一下
2. UserName不是uin，这个值每次登陆都会变的
3. 用Note注册
