### ISSUE TITLE
No module name import time, Queue

### ISSUE THREAD

**Issue by laohan97** [littlecodersh/ItChat#149]
为什么我会出现这个error 可以帮帮我吗各位大大

**Comment by JordenLCH** [comment]
在Python 2, module 名字是 Queue
Python3 时module 名字是queue

建议用这个方法来增强兼容性

```
is_py2 = sys.version[0] == '2'
if is_py2:
    import Queue as queue
else:
    import queue as queue
```

http://stackoverflow.com/questions/29687837/queue-importerror-in-python-3

**Comment by littlecodersh** [comment]
@laohan97 这是1.2.0我这里更新时候的疏忽，你更新一下1.2.1即可
@JordenLCH 多谢！
