### ISSUE TITLE
使用后感

### ISSUE THREAD

**Issue by pikeszfish** [littlecodersh/ItChat#150]
1. class client 里太多的 'private' method. 不知道是不是非得弄成 'private'
[关于 private-variables](https://docs.python.org/3/tutorial/classes.html#private-variables)
我的场景是只使用到client 但是太多的 private method, 继(魔)承(改)起来很麻烦

2. client.py 里
```
if __name__ == '__main__':
    wcc = WeChatClient()
    wcc.login()
```
意思是这个文件可以单独运行.
但是并不可以.

3. pep8 ......

**Comment by littlecodersh** [comment]
@pikeszfish 
1. 比如哪些私有方法你需要继承，我们可以商量一下怎么修改
2. 包的引用方式决定了不可能这样单文件运行的呀，这是演示如果你在包外引用这个类要怎么使用。有所误导的话我给注释掉吧。
3. pep8是想说我经常超一行的字数限制么？

**Comment by pikeszfish** [comment]
1. 类似
```
# 以下代码会出错
class A(object):
    def __aaa(self):
        print 'aaa'

class B(object):
    def __init__(self):
        self.a = A()

    def bbb(self):
        self.a.__aaa()

b = B()
b.bbb()
```
client.py 里的 `class client` 里太多 private 的method, 我觉得是没有必要, 我会像上述代码来使用 class client, 当使用到 private 的method, 会在 class B 里面找 '_B__aaa'

2. 我不知道你是怎么理解 `if __name__ == '__main__':`... 至少下面 `WeChatClient()` 是完全没有的一个东西.

3. 我不知道你用的什么编辑器, 你可以尝试一下 pep8 规范一下代码
类似 小写的类名/驼峰和下划线命名/...

**Comment by littlecodersh** [comment]
@pikeszfish 
1. 不能让外部调用和继承就是我用private的原因呀，你是觉得我哪个private要改public？我最近在重构，可以在之后的版本里变成public。
2. 模块里面是为了演示怎么调试的呀，我也想可以直接运行，但module引用方式和单文件不一样的。WeChatClient的话是我以前刚写client.py的时候在外面调试复制过来的。至于为什么叫这个名字，应该就是你想的那样啦。
3. 你要相信我们那么多开发者肯定都接触过pep8了，你阅读一下我们的代码之后会发现一个统一的类似规则。我们结合了自己的项目经验在强制换行，类属性这些问题上有一些自己的变通。比如最大的改变就是类属性我们是这样用的`classProperty`，是为了和类方法区分开了。你是较为反对我们的变通还是觉得我们变通的地方有哪些不合适的内容？我们可以做一个交流，在最新的重构中加以修复。另，我特意翻了一下源码，发现client类竟然是小写，的确是我们的疏忽，可能引起你的误解了。

**Comment by tempdban** [comment]
@pikeszfish 兄弟，一个多人维护的项目的编码风格，一般取决于“团队公约“，所谓的pep8 并不是一定要遵守的。
