### ISSUE TITLE
请问有使用ItChat后被微信封号的情况么？

### ISSUE THREAD

**Issue by spacelan** [littlecodersh/ItChat#153]

**Comment by littlecodersh** [comment]
@spacelan 我挂了很久的演示机器人，几千好友也没有出现问题。

**Comment by spacelan** [comment]
那你的演示机器人会频繁地发送消息么？

**Comment by littlecodersh** [comment]
@spacelan 会有机器人互刷。
我这里能保证正常使用的情况下不会出现封号。
如果你不加延时持续高频率发送信息或者加群好友，你只能祈祷没有被后台检测到。

**Comment by flypigarmy** [comment]
15-30分钟一条消息，第二天被封了

**Comment by spacelan** [comment]
@flypigarmy 请问是禁止登录网页版微信么？
