### ISSUE TITLE
Wrong QR code

### ISSUE THREAD

**Issue by anderson916** [littlecodersh/ItChat#155]
不知道为什么我的二维码全是M字符。扫描不成功。在另外一个Linux服务器可以。

<img width="579" alt="screen shot 2016-11-16 at 10 38 58 pm" src="https://cloud.githubusercontent.com/assets/195719/20351374/8883cd80-ac4d-11e6-9e75-a5d67af69d8e.png">

**Comment by littlecodersh** [comment]
@anderson916 把显示终端调整的大一点，现在的终端太小导致二维码最上面半部分被截掉了。

**Comment by anderson916** [comment]
可以了。谢谢。另外有个疑问，为什么我另外一个服务器显示的二维码不是M，是块块。

**Comment by littlecodersh** [comment]
@anderson916 因为显示M的服务器不支持块块显示
