### ISSUE TITLE
可否自动将群聊保存到通讯录

### ISSUE THREAD

**Issue by anderson916** [littlecodersh/ItChat#156]
你好，

设想做一个群聊机器人。用户将机器人加到群里后，可否自动将群聊保存到通讯录？这样使用 get chatrooms 才可以获取到信息。

**Comment by anderson916** [comment]
另外就是收到群聊邀请，可否自动接受从而加入群聊。

**Comment by littlecodersh** [comment]
@anderson916 在收到第一条消息时会自动保存到通讯录。
群聊邀请没有办法通过程序接受。
