### ISSUE TITLE
no "msgid"

### ISSUE THREAD

**Issue by qing6010** [littlecodersh/ItChat#157]
``` bash
 File "/usr/local/lib/python2.7/dist-packages/itchat/components/messages.py", line 225, in send_msg
    r = self.send_raw_msg(1, msg, toUserName)
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/messages.py", line 215, in send_raw_msg
    'LocalID': self.loginInfo['msgid'],
KeyError: 'msgid'
```
I was on version 1.1.19 OK then all the following versions have this issue till now 1.2.2

Also anyone can tell me where can I find the update log?

**Comment by qing6010** [comment]
ok.... I found the issue alr. The program was starting to hot-login from old pkl file. Got to know that the pkl files are not compatible...

**Comment by littlecodersh** [comment]
@qing6010 I checked the codes and it should be the following codes on line 215:
```python
'LocalId': self.loginInfo['msgid']
```
Have you changed source code yourself?
Even in [history][first-msgid], there's never been a `MsgId` key required in `self.loginInfo`.

[first-msgid]: https://github.com/littlecodersh/ItChat/commit/432d5dc3f0fba90cb20b2bd6723d5f6a1dcbdc06

**Comment by qing6010** [comment]
Yes. It was "msgid", then I thought should be "MsgId", I post the latter one by mistake. Any how I found the reason, thank you!

**Comment by littlecodersh** [comment]
Sure, it's good to know problem is solved.

**Comment by littlecodersh** [comment]
这里补一句中文翻译，本issue主要关于：
在升级版本后如果碰到msgid错误，请尝试删除旧版本的pkl文件。
