### ISSUE TITLE
微信gif图的识别与处理

### ISSUE THREAD

**Issue by 6bigfire** [littlecodersh/ItChat#159]
目前通过微信直接发送的gif图片itchat接收到时，识别为'MsgType': 49, 'Type': 'Sharing', 'AppMsgType': 8,属SHARING类型，无法正常的接收保存。
修改messages.py中的produce_msg函数，在elif m['MsgType'] == 49: # sharing分支下，增加：
```python
            elif m['AppMsgType'] == 8:
                download_fn = get_download_fn(core, 
                    '%s/webwxgetmsgimg' % core.loginInfo['url'], m['NewMsgId'])
                msg = {
                    'Type'     : 'Picture',
                    'FileName' : '%s.%s'%(time.strftime('%y%m%d-%H%M%S', time.localtime()),'gif'),
                    'Text'     : download_fn, }

```
以正确识别处理接收到的gif图片

**Comment by tempdban** [comment]
谢谢，建议您提交一个pull request

**Comment by littlecodersh** [comment]
@6bigfire 已更新：[commit][commit]

[commit]: https://github.com/littlecodersh/ItChat/commit/3250ed04a2789c629b9b83dd606ff77b370a1830
