### ISSUE TITLE
如何唯一确定群聊

### ISSUE THREAD

**Issue by kirahan** [littlecodersh/ItChat#16]
请问群聊群聊grouplist里的哪个字段可以唯一确定群聊啊 ？
UserName是@@xxxxxxxx每一次扫码之后都会变，EncryChatRoomId也是每次都在变
PYQuanPin这个字段有可能多个群这个值相同，而且群昵称变化之后这个值也会变动
请问有么有什么方式可以唯一确定一个群，想实现类似签到的功能

另外还有一个问题，调用batchgetcontact这个接口后返回的data中 "OwnerUin"这个字段似乎是群主id（这个id值也固定），但是并没有找到一个接口可以用这个字段来查用户信息，getcontact 这个接口用的参数是UserName：@xxxxxxxxxx来查的

求解答

**Comment by littlecodersh** [comment]
@kirahan 
有三种方法：
1. 确定唯一的群名，通过`PYQuanPin`进行判断
1. 自己建群，并创建一个特定名字的群用于读取自己的`OwnerUin`，通过该`OwnerUin`进行判断
1. 制作可视化界面，显示名字与头像，通过勾选进行判断

**Comment by 1265858594** [comment]
要实现签到, 还要确定用户的 id ,有一个方式, 
1. 将用户的 remarkname 绑定用户id
2. 建立签到群,每次扫码登入时就把 UserName 更新
3. 当用户在群内送出特定信息, 比如 签到 时, 判定该 id 签到完成

**Comment by 951452292** [comment]
``

**Comment by Morriaty-The-Murderer** [comment]
@littlecodersh 
你好，我测试了一下方法二的自己建群，OwnerUin和其他群一样都是0
难道微信已经屏蔽了这个了？

还有没其他确定用户和群唯一标志的的方法呢？

**Comment by Morriaty-The-Murderer** [comment]
@1265858594 
但是RemarkName可能改动比较频繁的，bot重新登录+用户改名就无法确定唯一用户了。
还有一个DisplayName我一直没搞明白是什么

**Comment by littlecodersh** [comment]
@kirahan 目前已经可以获取群用户的Uin

**Comment by soulmachine** [comment]
@littlecodersh 今天试了下，`itchat.update_chatroom(msg['FromUserName'], detailedMember=True)` 返回的`MemberList`，里面的`Uin`全部是0，现在微信是不是把Uin屏蔽了？

**Comment by littlecodersh** [comment]
@soulmachine 群聊的uin已经屏蔽了，用户的uin还可以通过特定的消息获取部分。

**Comment by soulmachine** [comment]
@littlecodersh 明白了，谢谢！

**Comment by lw-lin** [comment]
> 用户的uin还可以通过特定的消息获取部分。

@littlecodersh 请问是哪些特定消息来？谢谢！

**Comment by littlecodersh** [comment]
@lw-lin 这个[消息][message]。

[message]: https://github.com/littlecodersh/ItChat/blob/master/itchat/components/messages.py#L196-L197

**Comment by moc1** [comment]
@littlecodersh 这个特定的消息我打印出来并没有uin，调用的函数连uin都没有，是不是微信都屏蔽了

**Comment by moc1** [comment]
顺便问一下群里面没人管理了吗？我加群都没回复通不通过

**Comment by pengyuwei** [comment]
最后是怎么解决的？

**Comment by wubaojie** [comment]
@littlecodersh 通过搜索陌生人可以获取到陌生人的uin么

**Comment by hcchengithub** [comment]
ChatRoom 雖然只有 nickName 能用，機會在 ChatRoom 的 nickName 只要【部分相符】即可，與個人必須【完全一致】不同。因此，只要 ChatRoom 的 nickName 能有部分特徵不變，就有機會湊合著用。我不知道這個性質是 itchat 還是 WeChat 造成的。

**Comment by MollyMmm** [comment]
请问现在chatroom的uin没有办法获取了? 我尝试在获取用户uin的地方找, 但是没有找到.
