### ISSUE TITLE
微信群成员的NickName是唯一的吗？

### ISSUE THREAD

**Issue by anderson916** [littlecodersh/ItChat#162]
你好，谢谢开发 itchat 。想问一下微信群成员的Nickname是唯一的吗？

预备做个微信小机器人，设定某些成员发给机器人信息时作特别处理。群成员的Nickname会不会重复？

**Comment by littlecodersh** [comment]
@anderson916 不是的，NickName就是用户的名称。
群成员的NickName也可能出现重复。
