### ISSUE TITLE
Failed to establish a new connection: [Errno -2] Name or service not known',))

### ISSUE THREAD

**Issue by nmweizi** [littlecodersh/ItChat#164]
运行12个多小时后，重复出现这个提示，信息已经发不出去了，请帮助看看。手机微信还提示网页在线

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/itchat/components/login.py", line 191, in maintain_loop
    msgList, contactList = self.get_msg()
  File "/usr/local/lib/python2.7/site-packages/itchat/components/login.py", line 245, in get_msg
    r = self.s.post(url, data=json.dumps(data), headers=headers)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxsync?sid=2234534&skey=@crypt_a23452234523453245&pass_ticket=2345234wertwwretwertwetr (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2ba0fcda78d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

前两天是同#163 这个一样的提示，不过不影响发送和接受。

**Comment by littlecodersh** [comment]
@nmweizi 看起来是网络连接问题，突然连不上wx.qq.com了

**Comment by nmweizi** [comment]
这个问题一直存在几个小时了，在有这个问题的时候，ping wx.qq.com不丢包。

**Comment by littlecodersh** [comment]
@nmweizi 现在已经达到最大尝试了，你关闭后重启是否可以连上？

**Comment by nmweizi** [comment]
重启后可以连上

**Comment by littlecodersh** [comment]
@nmweizi 就是有段时间服务器无法连接wx.qq.com，可能是断网一类的原因

**Comment by nmweizi** [comment]
这个能做重试吗？，或再检测到这个问题时，重连？

**Comment by littlecodersh** [comment]
@nmweizi 已经做了重试，是重试达到了最大次数所以才报错的

**Comment by nmweizi** [comment]
能否在歇一会后再重试呢？

**Comment by littlecodersh** [comment]
@nmweizi 微信有心跳包的，歇一段时间以后再重试就断线了

**Comment by nmweizi** [comment]
可是我刚重新后自动连上了

**Comment by nmweizi** [comment]
就是想把这个动作自动化，不需要人干预

**Comment by littlecodersh** [comment]
@nmweizi 没有扫码吗？

**Comment by nmweizi** [comment]
没有扫码，可以确定哦

**Comment by littlecodersh** [comment]
@nmweizi 我这里想了一下没有办法修改，你这里持续打印这个异常实际上就是itchat在不断的重试。
暂时还没有办法让requests不持续抛出该异常，你可以结合你的环境找一下是否有相应的办法。

**Comment by nmweizi** [comment]
http://blog.csdn.net/shi_weihappy/article/details/51009602
和这个博客的说法是不是有些相似呢

**Comment by littlecodersh** [comment]
@nmweizi 字面上显而易见就是网络问题呀：“Max retries exceeded with url”
你想的话可以试试这个解决方法

**Comment by nmweizi** [comment]
https://github.com/kennethreitz/requests/issues/3550

可能是dns解析的问题，我换个dns服务器试下，如果有问题再开issue吧。

**Comment by littlecodersh** [comment]
@nmweizi 好

**Comment by nmweizi** [comment]
help(requests.adapters)

class HTTPAdapter(BaseAdapter)
     |  The built-in HTTP Adapter for urllib3.
     |  
     |  Provides a general-case interface for Requests sessions to contact HTTP and
     |  HTTPS urls by implementing the Transport Adapter interface. This class will
     |  usually be created by the :class:`Session <Session>` class under the
     |  covers.
     |  
     |  :param pool_connections: The number of urllib3 connection pools to cache.
     |  :param pool_maxsize: The maximum number of connections to save in the pool.
     |  :param max_retries: The maximum number of retries each connection
     |      should attempt. Note, this applies only to failed DNS lookups, socket
     |      connections and connection timeouts, never to requests where data has
     |      made it to the server. **By default, Requests does not retry failed
     |      connections.** If you need granular control over the conditions under
     |      which we retry a request, import urllib3's ``Retry`` class and pass
     |      that instead.

**Comment by nmweizi** [comment]
从上面的内容可知道，缺省的时候是没有重试的。
能否在config.py中增加
s = requests.Session()
a = requests.adapters.HTTPAdapter(max_retries=5)
b = requests.adapters.HTTPAdapter(max_retries=5)
s.mount('http://', a)
s.mount('https://', b)

其他单元调用s.post,同时取消其他单元的import requests

**Comment by littlecodersh** [comment]
@nmweizi 在itchat中我也加入了重试，见[这里][retry]。

[retry]: https://github.com/littlecodersh/ItChat/blob/master/itchat/components/login.py#L212-L240

**Comment by nmweizi** [comment]
谢谢，这个地方明白了。
在其他地方调用post的时候，也都有这样的重试吗？，是否有突然网络有瞬断之类的引起退出呢。

**Comment by littlecodersh** [comment]
@nmweizi 内部循环就这里一处

**Comment by nmweizi** [comment]
1、没有读过这个代码，有个猜测想法，不知成立不，谢谢。
2、虽然在整个循环用try包上了，可以确保整个业务逻辑出错时能够整体逻辑重新开始，但当其中某个post出错时，却没有重试机会，这种情况是否会出现丢失消息或业务逻辑中某个post功能出现问题而导致整体业务逻辑出现问题呢，从而出现虽然在线，但是无法收发消息的情况出现？
3、而我上面的处理办法，可以确保每个post都有重试机会，是否在处理上会更可靠呢。

**Comment by littlecodersh** [comment]
@nmweizi 不会无法收发消息的，无论是注册函数还是内部循环都有try包裹。
不过加上重试的确会可能更好一些，我研究一下requests这部分代码。

**Comment by nmweizi** [comment]
我上次的故障就是程序没有退出，但定时发给我的消息已经收不到了。谢谢。

**Comment by littlecodersh** [comment]
@nmweizi 估计是selector返回为6了，增加重试是不会改善收发消息的，最多在用户自定义方法中代替用户重试几次。

**Comment by nmweizi** [comment]
我回头再试试看。
