### ISSUE TITLE
如果直接主动给一个群里发消息，send的参数可以用群名么？

### ISSUE THREAD

**Issue by JasonHXiang** [littlecodersh/ItChat#165]

**Comment by littlecodersh** [comment]
@JasonHXiang 不可以，但是可以通过如下命令获取特定群名的群的详细信息：
```python
itchat.search_chatrooms(name=theNameYouWant)
```
详细的内容建议阅读[文档][doc]。

[doc]: http://itchat.readthedocs.io/zh/latest/6.Member%20stuff/

**Comment by JasonHXiang** [comment]
ok，多谢~我最后看了下messages.py的源码，直接用下面的方法实现了。
chatrooms = itchat.search_chatrooms(name=chatroomName)
itchat.send(MSG, chatrooms[0]['UserName'])

**Comment by CXOldStar** [comment]
@littlecodersh 请问下，群聊的UserName会不断变化吗？或者什么情况下UserName会改变呢？如果是一直不变的话，我想缓存这个字段，这样群名变的话，我都可以对这个群发消息

**Comment by tempdban** [comment]
重启会变

**Comment by JiaxiangBU** [comment]
> 详细的内容建议阅读[文档](http://itchat.readthedocs.io/zh/latest/6.Member%20stuff/)。

目前这个链接挂了
