### ISSUE TITLE
我觉得我发现一个BUG,自己群里发的信息没有群信息

### ISSUE THREAD

**Issue by issmile** [littlecodersh/ItChat#167]
我觉得我发现一个BUG,自己在群里发的信息,是在个人信息里出现的.标记isGroupChat里不会出现.自己发的信息按照逻辑应该带有群信息才对.

**Comment by littlecodersh** [comment]
@issmile 是个bug，我今天修。

**Comment by littlecodersh** [comment]
@issmile 已修复
