### ISSUE TITLE
被扫一扫后，请问如果直接添加对方为好友

### ISSUE THREAD

**Issue by now7print** [littlecodersh/ItChat#168]
机器人开启了加好友免验证，然后对方扫了机器人的二维码。
对方给机器人发文本消息“入群”，机器人邀请对方入群，但是没有任何反应，因为对方还不是机器人的好友。
那么请问，在对方扫一扫机器人二维码后，对方给机器人发文本消息“入群“，如果让机器人直接添加对方为好友？我试过先add_friend(status=2)和add_friend(status=3)再发群邀请都不行，都没成功添加对方为好友。谢谢！

**Comment by littlecodersh** [comment]
@now7print 发送文本消息“入群”是指加好友的时候的消息吗？
一般的处理方法是先加为好友，之后将好友邀请到群聊中。

**Comment by now7print** [comment]
@littlecodersh 
不是加好友的时候的消息。

机器人开启了加好友免验证，然后对方扫了机器人的二维码。

这时候是对方是处于和机器人的聊天窗口的，所以对方发普通的文本：入群
![default](https://cloud.githubusercontent.com/assets/5404285/20657763/653b2e3e-b573-11e6-9c0d-7f0a9598d167.png)
(上图是对方视角)

但是在机器人的角度，它是在聊天窗口里收到对方发的“入群“的信息的。但是这时对方还不在自己的通讯录里。
![default](https://cloud.githubusercontent.com/assets/5404285/20657769/80585174-b573-11e6-8dad-33ad111f0478.png)
(上图是机器人视角)

**Comment by now7print** [comment]
所以，针对收到“入群”的处理逻辑，我先各种 add_friend:

![code](https://cloud.githubusercontent.com/assets/5404285/20657802/d3bd1bb0-b573-11e6-915c-1c6754f75f41.png)

都不生效。。。就是对方不在自己联系人中，那么给对方发送入群邀请的调用就没反应。。。

**Comment by now7print** [comment]
求解这种情况该怎么办。。。非常感谢！！！

**Comment by littlecodersh** [comment]
@now7print 应该status设为2是有反应的，要不你打印一下返回值？
另，实在不行把验证打开，自动通过好友申请。

**Comment by now7print** [comment]
@littlecodersh 好的，我再试试。Closing this issue.
Thanks for this brilliant job !
