### ISSUE TITLE
获取用户微信号

### ISSUE THREAD

**Issue by wwj718** [littlecodersh/ItChat#169]
Hi，有可能在得知用户的userName情况下，获取用户微信号吗

**Comment by wwj718** [comment]
我看到 'Alias' 参数中，只有部分包含好友微信号，大多为空

**Comment by littlecodersh** [comment]
@wwj718 你试试这个，我也不确定能不能获取：
```python
itchat.update_friend(userName)
```

**Comment by wwj718** [comment]
@littlecodersh  好的 感谢~

**Comment by wwj718** [comment]
@littlecodersh 似乎无法获取

**Comment by liwen-tj** [comment]
猜测get_friends返回的username是wechat id进行hash后的结果

**Comment by R1310328554** [comment]
为什么要进行hash？
