### ISSUE TITLE
如何获取用户的订阅号，查看订阅号推送的文章

### ISSUE THREAD

**Issue by strugglingyouth** [littlecodersh/ItChat#17]

**Comment by littlecodersh** [comment]
@strugglingyouth 与获取用户发送的信息类似，建议阅读[手把手教你扩展微信个人号（1）](http://mp.weixin.qq.com/s?__biz=MzA4MjEyNTA5Mw==&mid=2652563730&idx=2&sn=c895f8aa0369017a9fc811db5d4218d9)。
