### ISSUE TITLE
报告3个问题

### ISSUE THREAD

**Issue by gaozhaosg** [littlecodersh/ItChat#170]
根据itchat框架自己做了个python机器人，现在有三个问题

1. 更新到11月28号的版本后，加好友的请求信息itchat收不到了，手机上登录的账号可以正常收到加好友的请求。原来的版本（我上次更新itchat代码是11月14号）没有这个问题。我把所有的msg handler都去掉，加了一个最通用的msg_register，还是收不到
```python
@itchat.msg_register
def general_reply(msg):
    print(msg)
    return 'I received a %s' % msg['Type']
```

2. 每天一过12点，itchat就断线/假死，具体表现为：itchat显示在线，get_friends(update=True)能收到正确的好友列表，但是send_msg发不出信息，好友发过来的信息也收不到，CTRL-C后重新启动程序要求扫描二维码（HotReload一直开着的，一般CTRL-C重启不用重新扫描二维码）

3. 同问题2的症状，itchat每天在7点还会发生一次。这个我已经基本确定和我家路由器有关，我的路由器每天7点重启一次，改变路由器重启时间=>出问题的时间也随着变化。我的路由器每次重启不超过90秒，而且重启的是二级路由，一级路由器(接电信带公网IP的)不重启，因此不会改变IP之类的，查不出来为什么重启路由会导致断线/假死的症状。而且白天有时有需要也会重启路由，却好像没发生过断线的问题

**Comment by littlecodersh** [comment]
@gaozhaosg 
1. 第一个问题是我这里分类的操作出了问题，在1.2.7中修复了这个问题。
2. 网络不稳定的话还是可能存在存活情况，但就要看运气了。如果需要非常稳定的登陆的话其实建议要么使用稳定的网络环境要么使用微信公众号。

**Comment by gaozhaosg** [comment]
好的，多谢。

1. 弱弱地问一句，怎么看itchat的版本号？

2. 关于断线/假死的问题，是否可以有方式记录一些debug数据，便于查找可能的原因。据你们的FAQ说iOS客户端存活率高一些，我今天用一台iPad登录账号，今晚12点看看itchat会不会还是12点就断

我自己还改了一点点代码，可以从外部触发机器人主动下行一些信息，比如定时推送一些数据等等。基于itchat比较早的代码改的，近期你们架构改了之后简单调整了一下还能继续用，但是好像用新架构有更好的实现方式。

**Comment by littlecodersh** [comment]
@gaozhaosg 
1. `itchat.__version__`
2. 你可以在文档最开始加这个：
```python
itchat.set_logging(loggingLevel=logging.DEBUG)
```
3. 如果使用碰到问题的话可以qq私聊我:)

**Comment by gaozhaosg** [comment]
刚刚升级到1.2.7

问题1：已解决
问题2&3：还没有足够时间确认具体原因，过一两天更新

btw, loggingLevel=logging.DEBUG 目前并没有看到多出太多对于判断这个问题有价值的信息

btw2,用新架构的loginCallback重写了主动推送信息的机器人，建议login和exit两个callback都要带上参数。我现在是改了itchat/components/目录下 login.py和hotreload.py
loginCallback()   -->  loginCallback(self)
如果有其他方法不用参数传递而可以让callback function拿到instance请告诉我

btw3，你的qq给一个，有问题更方便沟通，多谢

**Comment by gaozhaosg** [comment]
关于loginCallBack，现在是有callback function就执行callback，然而却替代了正常login后应该做的一些事情（比如清理QR.jpg等），有可能导致一些问题
itchat/components/login.py, line 54-58，我改成了
```python
    if hasattr(loginCallback, '__call__'):
        r = loginCallback(self)
    utils.clear_screen()
    os.remove(picDir or config.DEFAULT_QR)
    logger.info('Login successfully as %s' % self.storageClass.nickName)
```
hotreload.py就没有这个问题，callback function做的不影响正常流程

**Comment by gaozhaosg** [comment]
这两天把机器人搬到一台电信机房的服务器上跑，目前看下来挺稳定的，问题2和3都不再重现，应该是网络原因。

不过想深一步，大部分普通用户的网络条件是不能保证5个9的可用性，但是他们用微信网页版也不是一定一断网络就必须重新登录，itchat是否也可以做到类似的容错性；如果做不到，是否可以检测到被踢出然后让用户重新登录，现在是断了但是用户不知道

**Comment by littlecodersh** [comment]
@gaozhaosg 
callback那个就是这么设计的其实，你可以看core.py里面的注释。
网络的话不要长时间断线就行了，你在家试试网页微信，估计半夜也会自动退出。
README底部有我们的群号，你可以加一下。
