### ISSUE TITLE
可以通过MsgType为51的消息获取wxid，但问题是如何用web版触发51信息

### ISSUE THREAD

**Issue by Morriaty-The-Murderer** [littlecodersh/ItChat#172]
目前观察到的`MsgType`为51，并且`StatusNotifyCode in [2, 4]`的消息里，能获取username和wxid的对应。

但问题是web上目前没有观察到可以主动触发51信息的方式。

在手机上任意点开一个聊天，就能触发51信息，但在web上点开任何聊天都无效。

**Comment by littlecodersh** [comment]
@Morriaty-The-Murderer 可以设置置顶，或者你也可以试试别的操作。
运行的时候把debug打开就可以看到log：
```python
itchat.run(debug=True)
```

**Comment by Morriaty-The-Murderer** [comment]
web上的置顶并不会触发任何消息啊。

**Comment by littlecodersh** [comment]
@Morriaty-The-Murderer 发现了，是我这里搞错了。
你试试别的操作。
