### ISSUE TITLE
发送视频失败

### ISSUE THREAD

**Issue by mytts** [littlecodersh/ItChat#177]
itchat.send('@vid@154148641978.mp4' ,toUserName='filehelper' )

<ItchatReturnValue: {'BaseResponse': {'Ret': -1000, 'RawMsg': 'no BaseResponse in raw response', 'ErrMsg': '返回值不带BaseResponse'}}>

**Comment by littlecodersh** [comment]
@mytts @sjdy521 已更新，顺带把一直搁置的大文件上传也修复了。

**Comment by lizc07** [comment]
使用 `itchat.send_file(pdfurl, toUserName=msg.fromUserName)`发送PDF文件，小文件（比如6M）可以正常发送，大文件（比如31M）不能正常发送，看到返回值如下：
{'BaseResponse': {'Ret': -1000, 'ErrMsg': u'\u8fd4\u56de\u503c\u4e0d\u5e26BaseResponse', 'RawMsg': 'no BaseResponse in raw response'}}
是不是哪里出问题？

itchat version 1.3.5
