### ISSUE TITLE
自动退出问题：登录一段时间自动退出

### ISSUE THREAD

**Issue by hbthlw** [littlecodersh/ItChat#180]
使用命令行扫码登录成功，显示
Login successfully as xxxx
Start auto replying.

但是过一段时间（具体没算过，大概24小时？）就会自动退出，显示LOG OUT!
这是微信的限制，还是应用程序的问题？

**Comment by littlecodersh** [comment]
@hbthlw 请保持手机与客户端稳定联网，能保证数月的稳定登陆。

**Comment by hbthlw** [comment]
好的，谢谢

**Comment by hbthlw** [comment]
@littlecodersh 好的，谢谢

**Comment by sjdy521** [comment]
最近不少人反馈登录保持时间过短，跟踪了几个，发现确实是收到被强制下线的retcode 感觉有可能官方做了改动

**Comment by tempdban** [comment]
以前是超时后不会强制下线，发现收不到消息再把微信连上线就能恢复业务。
现在是超时后直接强制下线。
我觉得强制下线更方便检测。
我这里还是坚持每天下班登录一下微信，每次登录一分钟就杀掉手机微信。一般不主动杀掉itchat，是不会断的。

**Comment by littlecodersh** [comment]
不用担心官方改动了这个，演示号我这里从来没有操作也一直都很稳定。
