### ISSUE TITLE
add_member_into_chatroom请求被限制了怎么办？或者怎么避免？

### ISSUE THREAD

**Issue by leelihang** [littlecodersh/ItChat#182]

**Comment by leelihang** [comment]
{
"BaseResponse": {
"Ret": 1205,
"ErrMsg": "操作太频繁，请稍后再试。"
}
,
"MemberCount": 0,
"MemberList": []
}

**Comment by littlecodersh** [comment]
@leelihang 你是以什么频率加的人？

**Comment by binderclip** [comment]
同被限制了，1205 这个好像解封也很快，回头我查一下请求 log 分析下。

**Comment by discountry** [comment]
超过100人的加一个`useInvitation=True`就好

```python
def add_member_into_chatroom(self, chatroomUserName, memberList,
        useInvitation=False):
    ''' add members into chatroom
        for adding
            - you can't add yourself or member already in chatroom
            - if so, no one will be added
            - if member will over 40 after adding, invitation must be used
            - strict-limited frequency
        for options
            - chatroomUserName: 'UserName' key of chatroom info dict
            - memberList: list of members' info dict
            - useInvitation: if invitation is not required, set this to use
        it is defined in components/contact.py
    '''
    raise NotImplementedError()
```

**Comment by binderclip** [comment]
@discountry 这个是调用太频繁导致的，和 `useInvitation` 没关系。另外好像超过 40 个人就要用 `useInvitation=True`

**Comment by discountry** [comment]
@binderclip soga, 我之前也出了类似的错误，加上以后就没报错了……

**Comment by binderclip** [comment]
@discountry 哈哈哈，这个解除限制比较快，应该是后来再调用的时候已经解除了。

**Comment by ajing2** [comment]
1205这个限制可以破吗？

**Comment by ajing2** [comment]
解封是微信自动解封吗

**Comment by ajing2** [comment]
-1 这样的返回码是什么鬼

**Comment by ajing2** [comment]
{u'MsgID': u'0', u'LocalID': u'14974192870260', u'BaseResponse': {u'ErrMsg': u'', u'Ret': -1, 'RawMsg': u''}}

**Comment by heiliuer** [comment]
这个接口不能用了

**Comment by 18191171661** [comment]
@leelihang @littlecodersh @binderclip @discountry @ajing2 ，请问add_member_into_chatroom这个接口还能用嘛，我的代码没有报错，但是一直没有发送群邀请。谢谢。
itchat.add_member_into_chatroom(get_group_id(u'深度学习与机器学习-小分队'), 
                                        [{'UserName': msg['FromUserName']}], useInvitation=True)

def get_group_id(group_name):
    group_list = itchat.search_chatrooms(name=group_name)
    return group_list[0]['UserName']
