### ISSUE TITLE
`set_pinned` 无法更新 Uin。

### ISSUE THREAD

**Issue by blueset** [littlecodersh/ItChat#183]
尝试对于部分群组，MPS，对其执行 set_pinned 操作，无论 True 或 False 均不能触发 Uin 更新。

由于 API 的不稳定性，重现效果有待证实。

**Comment by blueset** [comment]
Duplicate #172.

**Comment by littlecodersh** [comment]
@blueset 的确是不能更新群聊或者用户的Uin。
由于群聊成员的Uin也已经被微信后端屏蔽，所以set_pinned目前是完全没有获取Uin的作用了。

**Comment by soulmachine** [comment]
@littlecodersh 今天试了下，`itchat.update_chatroom(msg['FromUserName'], detailedMember=True)` 返回的`MemberList`，里面的`Uin`全部是0，倒是某些`Alias`有值，现在微信是不是把Uin屏蔽了？
