### ISSUE TITLE
itchat.upload_file()无法上传超过 512K的mp4文件

### ISSUE THREAD

**Issue by soulmachine** [littlecodersh/ItChat#191]
messages.py 的第250和285行，定义了每个chunk 大小为 512K，这个是没问题的，不知道为啥我调用 itchat.upload_file(videoPath, isVideo=True)， 凡是超过 512K的文件都上传失败。

后来我强行将这两行的两个数字改为 10M, 即10485760 ，这次就能顺利上传了。坏处是每个 chunk 太大，估计容易失败吧。

**Comment by littlecodersh** [comment]
@soulmachine 512k是js里面直接取出来的，我早上又去确认了一下。
你给我下你现在用的itchat版本，是不是我最新的一次更新的问题。

**Comment by soulmachine** [comment]
@littlecodersh config.py:3:VERSION = '1.2.16'

**Comment by littlecodersh** [comment]
@soulmachine 已在qq发了一个测试版的过去，你看下有没有修复这个问题。

**Comment by soulmachine** [comment]
@littlecodersh 好的，我试试

**Comment by sjdy521** [comment]
我按照浏览器里的行为分片成512K上传，结果最后一个分片上传完不返回MediaId…
期待测试结果

**Comment by soulmachine** [comment]
@littlecodersh 测试了一下 `itchat-1.2.17-py2.py3-none-any.whl`，还是不行，把524288改为10485760就成功了

**Comment by littlecodersh** [comment]
@soulmachine 
调大变成一个包传过去肯定是可以的，现在主要的考虑是这会和微信后台预期收到的包不一样。
直接导致的问题就是很可能之后后台突然加了一个过滤条件，一个包传过去微信号就被封掉了。
所以我这里是模拟的js里面设定的包的大小。
你抓包看一下你网页版上传的每一个包里面包含的文件大小是多少吧。

**Comment by sjdy521** [comment]
多个分片上传的时候需要确保每个分片的ClientMediaId保持一致，不然没办法知道每次上传的对应是哪一个分片，会导致上传失败，我看itchat源码似乎没考虑到这点？每次都随机生成

**Comment by littlecodersh** [comment]
@sjdy521 考虑到了

**Comment by littlecodersh** [comment]
@soulmachine @sjdy521 已在最新的更新中修复，v1.2.17。

**Comment by soulmachine** [comment]
@littlecodersh 1.2.17果然可以了，牛逼！
