### ISSUE TITLE
群图片下载

### ISSUE THREAD

**Issue by bbsdkjdx** [littlecodersh/ItChat#192]
请问大牛，这个库能截获群图片消息吗？还有用库登录后能在线多长时间，能设置吗？

**Comment by littlecodersh** [comment]
@bbsdkjdx 可以的。可以很久，你不想保持登陆的时候使用itchat.logout()就可以了。

**Comment by bbsdkjdx** [comment]
谢谢您的解答，我只是想让它一直在线，有时候掉线了，不知道是因为电脑待机导致的还是在线时间有上限导致的。如果有上限，不知道能不能设置这个上限。

**Comment by littlecodersh** [comment]
@bbsdkjdx 电脑待机应该是会导致这个问题的，另外，长时间待机需要主机和手机保持持续联网。
是没有上限可以设置的。

**Comment by bbsdkjdx** [comment]
哦，知道了，非常感谢！期待您的后续佳作！

**Comment by littlecodersh** [comment]
好:)
