### ISSUE TITLE
运行出错版主

### ISSUE THREAD

**Issue by huangdongfang** [littlecodersh/ItChat#193]
代码：
import itchat

itchat.auto_login()

itchat.send('Hello, filehelper', toUserName='filehelper')
报错：
>>> 
█
You don't have access to internet or wechat domain, so exit.
>>> 
询问：
是不是需要配置什么链接，有没有文档

**Comment by littlecodersh** [comment]
@huangdongfang 你python版本多少？

**Comment by rhodesiaxlo** [comment]
我刚学习python，按照题主给的domo测试也是报错,是我的执行方式出错了吗，如果是，该已什么方式来执行呢？谢谢
![image](https://cloud.githubusercontent.com/assets/9957924/23650696/f81be332-035d-11e7-8c69-7b374b890df9.png)

**Comment by rhodesiaxlo** [comment]
（补充）
文件 2.py 的源代码为：

import itchat
itchat.auto_login()
itchat.send('Hello, filehelper', toUserName='filehelper')

**Comment by rhodesiaxlo** [comment]
开发环境：win7 环境 
python版本：3.6.0
![image](https://cloud.githubusercontent.com/assets/9957924/23650823/6a2db324-035e-11e7-8724-6cad5701a7dd.png)
