### ISSUE TITLE
无法获取好友信息

### ISSUE THREAD

**Issue by TerraceCN** [littlecodersh/ItChat#195]
使用UserName无法查询好友信息，无提示信息，无法继续执行代码

**Comment by littlecodersh** [comment]
@TerraceCN 起码把代码带上吧

**Comment by TerraceCN** [comment]
`# -*- coding: utf-8 -*-
import itchat
from itchat import msg_register
from itchat.content import *

@msg_register(TEXT)
def reply_text(msg):
    print(itchat.get_friends(userName=msg["FromUserName"]))
    itchat.send(msg["Text"], msg["FromUserName"])
    
if __name__ == "__main__":
    itchat.auto_login(enableCmdQR=True, hotReload=True)
    itchat.run()`
