### ISSUE TITLE
网页登陆

### ISSUE THREAD

**Issue by wwj718** [littlecodersh/ItChat#196]
hi ～

如果我想实现网页扫码登陆，应该如何做呢，在后台成成二维码传到前端就行吗

**Comment by littlecodersh** [comment]
@wwj718 你看下群文件里面有个flask_qr.py，就是类似的实现。

**Comment by wwj718** [comment]
@littlecodersh  感激不尽！

**Comment by littlecodersh** [comment]
@wwj718 不客气的

**Comment by hosven** [comment]
请问一下这个flask_qr.py 可否放到github上来。我加qq2群并没有通过。非常感谢！

**Comment by jjuu** [comment]
在哪加群
