### ISSUE TITLE
如何在群聊中被@能自动回复呢？

### ISSUE THREAD

**Issue by dingzhw** [littlecodersh/ItChat#197]
作者您好，我看到您的个人号在群聊被@中也能自动回复，这个要怎么实现呢？

**Comment by dingzhw** [comment]
仔细阅读了相关文档和消息类型解决了这个问题，再次感谢作者搭建的框架。

**Comment by littlecodersh** [comment]
@dingzhw 好:)

**Comment by Sesshoumaru** [comment]
我的好友人数超过2500+，获取好友失败。。，有碰到类似的吗?
