### ISSUE TITLE
get_msg 之后没有处理 ModContactList 中的好友信息

### ISSUE THREAD

**Issue by binderclip** [littlecodersh/ItChat#199]
我在 web 微信里面试了试，发现在 `webwxverifyuser` 接收好友请求后的 `webwxsync` 里面会在 `ModContactList` 里面携带上这个用户的信息。

然后我看了下 ItChat 的代码：

https://github.com/littlecodersh/ItChat/blob/master/itchat/components/login.py#L205-L213

发现 otherList 有取出来，但是没有处理。不知道是落下了还是有什么原因？
想问下能像下面这里这个一样处理一下吗？

https://github.com/littlecodersh/ItChat/blob/master/itchat/components/contact.py#L257-L258

**Comment by littlecodersh** [comment]
@binderclip 的确漏过了，多谢！

**Comment by littlecodersh** [comment]
@binderclip 已在新的[更新][commit]中修复，谢谢你的支持！

[commit]: https://github.com/littlecodersh/ItChat/commit/ff1ad7f856961e75aac209351c49eebb69a399ad

**Comment by binderclip** [comment]
@littlecodersh 谢谢作者！
