### ISSUE TITLE
itchat.run 就log out

### ISSUE THREAD

**Issue by alpha92012** [littlecodersh/ItChat#200]
我发现一用这个方法就会log out

**Comment by littlecodersh** [comment]
@alpha92012 把使用的代码带上吧。

**Comment by alpha92012** [comment]
@littlecodersh 就是这个最简单的一个返回收到信息的代码： 
import itchat

@itchat.msg_register(itchat.content.TEXT)
def text_reply(msg):
    return msg['Text']

itchat.auto_login()
itchat.run()

我试了用python3 去编译老通不过，所以我用的是python2， 我不知道这个是不是原因

**Comment by littlecodersh** [comment]
@alpha92012 
你在`import itchat`后面加上这些再运行一下，然后把日志信息发上来给我：
```python
import logging
itchat.set_logging(loggingLevel=logging.DEBUG)
```
python2、python3是共享一份代码的，肯定不是python版本问题。
python3编译不过有没有报错信息？

**Comment by alpha92012** [comment]
如果用python3 报错是： ImportError: No module named 'itchat'
还有，itchat下面没有set_logging这个方法啊

**Comment by alpha92012** [comment]
我用pycharm debug，发现你的daemon thread 在刚登录那会儿会去处理那些发给itchat那个微信号的消息，可是处理完这些信息之后，程序就结束了，thread也被杀掉了

**Comment by littlecodersh** [comment]
@alpha92012 不是itchat没装就是自己的程序也起名成itchat了。
有`set_logging`的。
开了循环的，不会自动结束。

**Comment by alpha92012** [comment]
@littlecodersh 你好，之前的问题我解决了，谢谢。
BTW， 有个小问题不是很明白想问你一下，@itchat.msg_register(tichat.content.TEXT)起到什么作用的啊?

**Comment by tempdban** [comment]
@alpha92012 看代码！！！！！！！！
