### ISSUE TITLE
itchat 有session相关的管理么？

### ISSUE THREAD

**Issue by RominYue** [littlecodersh/ItChat#204]
对当前正在聊天的users的会话管理？

**Comment by littlecodersh** [comment]
@RominYue 正在聊天的User的会话管理具体指什么？

**Comment by RominYue** [comment]
哦，类似于网页session。和每一个用户的聊天会话，都可以看作是一个session。比如现在有这样一个需求。我需要判断用户是否是第一次向我发送信息，如果是第一次的话，需要做一些额外的操作。

**Comment by littlecodersh** [comment]
@RominYue 你可以在加好友的时候返回这些特别的操作。
对话的话就是后台一条消息传过来了，传过来的消息里面没有历史消息的。

**Comment by RominYue** [comment]
好的，谢谢。
