### ISSUE TITLE
itchat.add_friend( userName = '99989000')

### ISSUE THREAD

**Issue by yyanglike** [littlecodersh/ItChat#207]
这个函数返回的是错误的值？[u'ErrMsg']:u''
[u'Ret']:-1
['RawMsg']:u''请问这个可能是什么原因？

**Comment by tempdban** [comment]
@yyanglike 
# 获取自己的用户信息，返回自己的属性字典
itchat.search_friends()
# 获取特定UserName的用户信息
itchat.search_friends(userName='@abcdefg1234567')
# 获取任何一项等于name键值的用户
itchat.search_friends(name='littlecodersh')
# 获取分别对应相应键值的用户
itchat.search_friends(wechatAccount='littlecodersh')
# 三、四项功能可以一同使用
itchat.search_friends(name='LittleCoder机器人', wechatAccount='littlecodersh')

readme都不看的么？

**Comment by yyanglike** [comment]
这个好像是获取本地通信录里面的信息。不是增加好友功能吧？

**Comment by littlecodersh** [comment]
@yyanglike 这个api是建议你用来通过好友和加少量的群好友。
