### ISSUE TITLE
有没有处理红包消息或者转账消息的功能呢？

### ISSUE THREAD

**Issue by pcloth** [littlecodersh/ItChat#21]
如题。感谢这个项目，解决了我很多问题。

**Comment by littlecodersh** [comment]
@pcloth 您好，关于这个问题：
具体而言分三层功能，开源项目只能提供第一层
* 提示有红包和转账
* 获取具体的金额
* 收取红包

**Comment by 1265858594** [comment]
对webwx来说只有第一项能实现
第二三项目前webwx 还不支持
@littlecodersh 对 webwx 还不支持的功能，怎么能实现呢？在手机上开外挂？

**Comment by littlecodersh** [comment]
@1265858594 思路而言，通过反编译安卓源码进一步分析协议是可以实现的。
目前已经有商业项目这样做，不过这部分可以预见不适合开源，所以如果感兴趣需要自己研究了。
但实际上可以通过一些别的方法达到这个功能，比如手机端的抢红包插件（已有开源项目），将抢到的红包的信息传输到服务器即可。
还有一个没有验证的想法，实际上java版微信、智能手表上的微信等，交互的协议都可以分析，可能会有意想不到的收获。

**Comment by pcloth** [comment]
有第一项功能已经够用了：提示有红包和转账。
那么我该怎么操作呢？
@littlecodersh

**Comment by pcloth** [comment]
太感谢了！ @littlecodersh

**Comment by gwljt** [comment]
微信通过扫描二维码进行转账，怎么取得到账到消息通知？我试了所有消息类型都不成功呀 @littlecodersh

**Comment by WyattHuang1** [comment]
666 ！ 可以用来写自动抢红包的脚本
