### ISSUE TITLE
replyFn 抛异常时 log level 过低

### ISSUE THREAD

**Issue by binderclip** [littlecodersh/ItChat#210]
[这里](https://github.com/littlecodersh/ItChat/blob/master/itchat/components/register.py#L69)异常之后用 error 或者 warning 等级的 log 是不是更合适一些？毕竟是正常运行时候出了问题

```
            try:
                r = replyFn(msg)
                if r is not None: self.send(r, msg.get('FromUserName'))
            except:
                logger.debug(traceback.format_exc())
```

参考：
https://docs.python.org/2/howto/logging.html#when-to-use-logging

**Comment by binderclip** [comment]
还有一些出错的情况🙋

https://github.com/littlecodersh/ItChat/blob/master/itchat/components/messages.py#L183
https://github.com/littlecodersh/ItChat/blob/master/itchat/components/login.py#L236

https://github.com/littlecodersh/ItChat/blob/master/itchat/components/hotreload.py#L40
https://github.com/littlecodersh/ItChat/blob/master/itchat/components/hotreload.py#L46
https://github.com/littlecodersh/ItChat/blob/master/itchat/components/hotreload.py#L58

**Comment by littlecodersh** [comment]
@binderclip 多谢支持！已经修改在[新的提交][new-commit]中。
看下这样修改是否有问题？

[register L69][register]: 这里新增了一条warn的提示信息。
[messages L183][messages]: 这里将改为Useless message received。
[login L236][login]: 我将改为error等级。
[hotreload L40][hotreload-l40]: 这段是debug hotreload方法的内容，就不改了。
[hotreload L46][hotreload-l46]: 这段也是。
[hotreload L58][hotreload-l58]: 这段实际就说本地存储的内容已经过时，进入重新登陆，所以还是保留debug。

[new-commit]: https://github.com/littlecodersh/ItChat/commit/71d5c5722a9feaaab622ef9fd7a4b66465bd9275
[register]: https://github.com/littlecodersh/ItChat/blob/master/itchat/components/register.py#L69
[messages]: https://github.com/littlecodersh/ItChat/blob/master/itchat/components/messages.py#L183
[login]: https://github.com/littlecodersh/ItChat/blob/master/itchat/components/login.py#L236
[hotreload-l40]: https://github.com/littlecodersh/ItChat/blob/master/itchat/components/hotreload.py#L40
[hotreload-l46]: https://github.com/littlecodersh/ItChat/blob/master/itchat/components/hotreload.py#L46
[hotreload-l58]: https://github.com/littlecodersh/ItChat/blob/master/itchat/components/hotreload.py#L58
