### ISSUE TITLE
username如何设置

### ISSUE THREAD

**Issue by wuxiongliu1** [littlecodersh/ItChat#211]
我看例子，设置指定的用户名查询用户，这里的userName的值我从哪里知道呢，因为是一段很奇怪的字符串；期待你的回复，谢谢啦；
![image](https://cloud.githubusercontent.com/assets/5119063/22193769/ae7a4aea-e178-11e6-9d28-0f39f235e7a1.png)

**Comment by littlecodersh** [comment]
@wuxiongliu1 
消息的FromUserName, ToUserName和用户的UserName键值。
```python
itchat.search_friends()['UserName']
```
