### ISSUE TITLE
获取登录的二维码的时候，设置存储路径报异常

### ISSUE THREAD

**Issue by wuxiongliu1** [littlecodersh/ItChat#212]
调用获取登录的二维码，设置存储的路径的时候
![image](https://cloud.githubusercontent.com/assets/5119063/22195776/a333a698-e184-11e6-89e8-c407cbae3aba.png)

报没有权限写入文件的异常，以管理员身份运行也不行；
![image](https://cloud.githubusercontent.com/assets/5119063/22195797/b9754aba-e184-11e6-8947-78c66c529523.png)

**Comment by littlecodersh** [comment]
@wuxiongliu1 
```python
picDir='D:\\pic\\qr.jpg'
```
