### ISSUE TITLE
自动回复消息没有反应

### ISSUE THREAD

**Issue by Ericxiaoshuang** [littlecodersh/ItChat#217]
我的版本是python3.5
这是chengxu程序进程
![2017-01-27 15_42_15-_python 3 5 2 shell_](https://cloud.githubusercontent.com/assets/9779726/22363718/57b1f4ce-e4a7-11e6-9c9f-dc2e6044da0f.png)

源码在这里
```
import itchat

@itchat.msg_register(itchat.content.TEXT)
def text_reply(msg):
    return msg['Text']

itchat.auto_login()
itchat.run()
```

**Comment by littlecodersh** [comment]
@Ericxiaoshuang 把logging打开吧。
```python
import logging

import itchat

itchat.set_logging(loggingLevel=logging.DEBUG)
```
