### ISSUE TITLE
itchat.send 无法发送消息

### ISSUE THREAD

**Issue by JieJiSS** [littlecodersh/ItChat#218]
返回的数据均为空，只有Ret为1102。Version 1.2.14, OS= Windows Xp Professional, X86-based PC, Python 3.4.4, 网络通畅。是不是微信API变了？

**Comment by JieJiSS** [comment]
decorator+return的方法也试了，不会raise exception但是没有效果

**Comment by littlecodersh** [comment]
@JieJiSS 1102的话微信是肯定会退出的，你网页版登得上去么？

**Comment by arpit1997** [comment]
2的话微信, 返回的数据均为空 是肯定会退出的的方法也试了返回的数据均为空，只有Ret为1102是没有效果
的的方法也试了返  均为空 是肯定 是肯定会退出 页版登得上去么
>返回的数据均为空，只有Ret为1102。Version 1.2.14, OS= Windows Xp Professional, X86-based PC, Python 3.4.4, 网络通畅。是不是微信API变了？
decorator+return的方法也试了，不会raise exception但是没有效果
