### ISSUE TITLE
为什么检测好友删除没有完整源码

### ISSUE THREAD

**Issue by Ericxiaoshuang** [littlecodersh/ItChat#219]
?

**Comment by tempdban** [comment]
你就懒成这样么

**Comment by littlecodersh** [comment]
@Ericxiaoshuang 因为这是api库呀，这篇[教程][tutorial2]里有相关的讲解。

[tutorial2]: http://itchat.readthedocs.io/zh/latest/tutorial/tutorial2/

**Comment by Ericxiaoshuang** [comment]
@tempdban 看了实践项目文章的讲述[](http://itchat.readthedocs.io/zh/latest/tutorial/tutorial2/),是通过建群来检测好友状态,还有名片,可是我测试的时候没有反应.可能基础不够扎实,所以api看的不是很懂.就冒昧问下有没有拿来即用的源码.@littlecodersh 文章中说在gist上整合有,但是那个文字`gist`链接打不开,用了vpn也打不开.

**Comment by tempdban** [comment]
@Ericxiaoshuang ok,加油
新年快乐
