### ISSUE TITLE
有没有办法将个人名片或自己关注的公众号名片转发出去？

### ISSUE THREAD

**Issue by jireh-he** [littlecodersh/ItChat#22]
本issue记录个人名片、公众号、文章转发的相关讨论。

**Comment by littlecodersh** [comment]
@jireh-he 目前没有研究过，但可能可行，下周我研究一下给你答复如何？

**Comment by jireh-he** [comment]
我用360浏览器的扩展程序，里面有个叫微信机智宝的，可以实现群发和发送个人名片，而且也有管理界面。我之前用你的代码做群发，我把微信文章转成二维码图片，然后群发出去，结果发现图片发了几十个后就发不出去了，返回码都是200，表示有发，但结果是对方都没收到图片，我想微信是不是对群发图片有限制。但文字就没任何问题了。

**Comment by 1265858594** [comment]
@jireh-he 微信做了限制,限制的规则不明,你可以提供一些数据吗？
比如说多久的时间发了多少条信息？

**Comment by littlecodersh** [comment]
@jireh-he 可能是到了上传文件数量的限制，大量发送同一图片的话可以尝试仅上传一次图片。

**Comment by 1265858594** [comment]
@littlecodersh 
我这边测试是已经把范围限制在时间跟数量上，只是不清楚多久时间发多少数量的信息
信息包括图片,纯文字,这些都算

**Comment by littlecodersh** [comment]
@1265858594 好的。
@jireh-he 机智宝的代码见[这里](http://7xrip4.com1.z0.glb.clouddn.com/ItChat/JZB.zip)，感觉可以研究一下。

**Comment by 1265858594** [comment]
@littlecodersh 里面代码压缩了,不好读,伤脑筋

**Comment by littlecodersh** [comment]
@1265858594 对的，我这里得等之后有空再慢慢研究了

**Comment by shqzzy** [comment]
我去安装 机智宝的浏览器插件了，但没有发送记录的包，但名片确实以机器人的身份成功发送指定的用户或群。

**Comment by ganleyang** [comment]
求加入发送名片功能

**Comment by littlecodersh** [comment]
@ganleyang @jireh-he @shqzzy @tempdban 
在最新版本中更新了发送名片的功能，示例代码如下：
```python
import itchat

@itchat.msg_register(itchat.content.CARD)
def reply(msg):
    itchat.send_raw_msg(msg['MsgType'], msg['Content'], msg['FromUserName'])

itchat.auto_login(True)
itchat.run()
```
其实是很古老的做法，当时以为名片和链接分享一样被过滤了，没想到今天无意中试了一下还能用。

**Comment by jireh-he** [comment]
十分感谢！

**Comment by Ailix** [comment]
请问是否可以发送链接分享
