### ISSUE TITLE
有发送语音的接口吗？

### ISSUE THREAD

**Issue by cyhhao** [littlecodersh/ItChat#223]
微信网页版好像没有发语音的途径，有什么办法可以吧 send_recording也加上呢？直接抓微信手机客户端的包？讨论一下吧

**Comment by littlecodersh** [comment]
@cyhhao 那就是另一个项目了，重要的是那个项目显然不适合开源的。
4天了没人回我就关了这个issue了。

**Comment by yunfan** [comment]
发文件似乎可以 网页版也能发文件 而且如果是图的话会自动显示 是语音会提供播放界面

**Comment by cyhhao** [comment]
@yunfan 发文件的话只能当做 mp3 文件发，跟图片还是不同的。感觉还不如给微信网页版提用户反馈，推动他们加上发语音的功能比较靠谱，哈哈

**Comment by allenwq** [comment]
@littlecodersh 还是蛮期待这个功能的，不知道你有没有尝试过？

**Comment by wjcroom** [comment]
同期待

**Comment by YangDejie** [comment]
期待+1

**Comment by rovedream** [comment]
期待+1

**Comment by giantbing** [comment]
期待+1

**Comment by Changjinxing** [comment]
期待+1
