### ISSUE TITLE
itchat.search_friends()不能得到自己的信息了

### ISSUE THREAD

**Issue by nasyxx** [littlecodersh/ItChat#224]
itchat.search_friends()不能得到自己的信息了
而是返回了一个朋友的消息，另外试了下用自己的name=自己的信息，也不能搜索到了
用get_friends()查找后，发现自己不存在friends list里面...
版本是1.2.21

**Comment by littlecodersh** [comment]
@nasyxx 已在新版本中更新，版本号1.2.22
