### ISSUE TITLE
群聊用户的微信账号(id)如何获取呢

### ISSUE THREAD

**Issue by wwj718** [littlecodersh/ItChat#227]
hi 大家好 群聊用户的微信账号(id)如何获取呢

**Comment by littlecodersh** [comment]
@wwj718 群聊的MemberList或者消息的ActualUserName键

**Comment by wwj718** [comment]
感谢回答！@littlecodersh 我想要的是能添加好友的那个id号（手机微信里添加好友），能做到吗
