### ISSUE TITLE
网页版已掉线，但是 itchat 没有及时捕捉到

### ISSUE THREAD

**Issue by RoyXiang** [littlecodersh/ItChat#229]
`exitCallback` 没有被调用，所以 itchat 应该没有捕捉到网页版已离线。此时调用 `itchat.send_msg` 收到如下的响应内容：

```
{'LocalID': '', 'BaseResponse': {'ErrMsg': '', 'Ret': 1101, 'RawMsg': ''}, 'MsgID': ''}
```

**Comment by littlecodersh** [comment]
@RoyXiang 你可以尝试跟踪一下当时的心跳包返回值，常规而言掉线以后心跳就会首先返回掉线的返回值。

**Comment by RoyXiang** [comment]
@littlecodersh 似乎只有在收到 [异常（掉线）心跳包](https://github.com/littlecodersh/ItChat/blob/35bac6bfcf27eefcb992388bb33f6ae6a7787595/itchat/components/login.py#L253) 的时候才会记录日志，这样从日志里好像看不出什么。

**Comment by littlecodersh** [comment]
@RoyXiang 是的，异常以后抓个包，或者把心跳包的所有值都改出来。

**Comment by RoyXiang** [comment]
@littlecodersh 那只能等下次遇到再尝试抓包了，现在已经重新登录了。

**Comment by RoyXiang** [comment]
@littlecodersh 找到了 [这个](https://github.com/HalfdogStudio/wechat-user-bot/commit/3dc9f0c1a78d44b8cc023a8a289ba016788bbc8f)

似乎 `retcode` 如果是 1101 的话也代表掉线了，恰好与上面 `itchat.send_msg` 的响应对得上。

**Comment by littlecodersh** [comment]
@RoyXiang 是的。
你的情况是看起来心跳包并没有返回1101导致没有正常退出，所以我想了解他返回了什么还是就一直挂起了。

**Comment by RoyXiang** [comment]
@littlecodersh 之前看错 itchat 的代码逻辑了。

那有没有可能在所有发送消息的方法外面套一层 wrapper，当发送失败且 `ReturnValue['BaseResponse']['Ret']` 为 `1101` 的时候内部调用 `itchat.logout` 方法。

这样没有从根本上解决问题，下次遇到这种情况再在这里补充反馈好了。

**Comment by RoyXiang** [comment]
似乎 `exitCallback` 不好处理，还是等进一步的反馈吧。

**Comment by RoyXiang** [comment]
https://github.com/Urinx/WeixinBot/issues/150

如果 `selector` 返回的是 `2` 的话，用正常的方法应该是捕捉不到掉线了。

**Comment by littlecodersh** [comment]
@RoyXiang selector是2的时候send_msg返回也是正常的。
send的时候加一层返回值判断是一种可行的解决方案，我测试到现在4天还没出问题。
但毕竟是极少见到的问题，如果能知道为什么本来显示掉线用的心跳包出问题的话，就能少加很多的多余代码了。

**Comment by RoyXiang** [comment]
这个问题最大的可能就是使用 itchat 挂机时微信移动端被彻底关闭/彻底断网了，在这里做个记录。

cc: @littlecodersh @blueset
