### ISSUE TITLE
关于定位唯一账号的问题以及BUG报告

### ISSUE THREAD

**Issue by pcloth** [littlecodersh/ItChat#23]
@Chyroc @littlecodersh 请教一下，关于定位唯一账号的问题。
1、
itchat.get_alias(username=msg['FromUserName'])
能否强制返回微信号而不是昵称或者备注？或者说返回值至少让我知道到底是返回了微信号还是昵称，或者是备注？

2、
itchat.set_oplog(msg['FromUserName'],'测试用户ID')
设置备注名后，在用get_alias获取到的依然是昵称，不是备注名，需要重新运行机器人后才能拿到新的名字

环境是py 3.5.1

**Comment by pcloth** [comment]
我自己改了一下client.py文件中的两个函数，不知道是否符合老大们的设计思路。

`    def get_alias(self, contract=None, username=None):
        """通过username寻找微信号/备注/昵称/username,优先级一次递减
        """
        contract = self.get_contract() if contract is None else contract
        for ct in contract:
            if username == ct.get('UserName'):
                if ct.get('Alias') == '':
                    if ct.get('RemarkName') == '':
                        if ct.get('NickName') == '':
                            return username
                        return [ct.get('NickName'),'NickName']
                    return [ct.get('RemarkName'),'RemarkName']
                return [ct.get('Alias'),'Alias']

    def set_oplog(self, username, rename):
        """设置备注
        """
        url = '%s/webwxoplog?lang=%s&pass_ticket=%s' % (self.loginInfo['url'],
                                                        'zh_CN',
                                                        self.loginInfo['pass_ticket'])
        data = {
            'UserName': username,
            'CmdId': 2,
            'RemarkName': rename,
            'BaseRequest': self.loginInfo['BaseRequest'],
        }
        headers = {
            'ContentType': 'application/json; charset=UTF-8'
        }
        r = self.s.post(url, data=json.dumps(BytesDecode(data)), headers=headers)
        ret = json.loads(BytesDecode(r.content.decode('utf-8', 'replace')))['BaseResponse']['Ret']
        
        # 添加修改备注后，内存中的备注名字也一同修改了。  
        for m in range(len(self.memberList)):
            if self.memberList[m]['UserName']==username:
                self.memberList[m]['RemarkName'] = rename
                
        
        return ret == 0`

**Comment by pcloth** [comment]
`def get_alias(self, contract=None, username=None):
        """通过username寻找微信号/备注/昵称/username,优先级一次递减
        """
        contract = self.get_contract() if contract is None else contract
        for ct in contract:
            if username == ct.get('UserName'):
                if ct.get('Alias') == '':
                    if ct.get('RemarkName') == '':
                        if ct.get('NickName') == '':
                            return username
                        return [ct.get('NickName'),'NickName']
                    return [ct.get('RemarkName'),'RemarkName']
                return [ct.get('Alias'),'Alias']

def set_oplog(self, username, rename):
        """设置备注
        """
        url = '%s/webwxoplog?lang=%s&pass_ticket=%s' % (self.loginInfo['url'],
                                                        'zh_CN',
                                                        self.loginInfo['pass_ticket'])
        data = {
            'UserName': username,
            'CmdId': 2,
            'RemarkName': rename,
            'BaseRequest': self.loginInfo['BaseRequest'],
        }
        headers = {
            'ContentType': 'application/json; charset=UTF-8'
        }
        r = self.s.post(url, data=json.dumps(BytesDecode(data)), headers=headers)
        ret = json.loads(BytesDecode(r.content.decode('utf-8', 'replace')))['BaseResponse']['Ret']
        
        # 添加修改备注后，内存中的备注名字也一同修改了。  
        for m in range(len(self.memberList)):
            if self.memberList[m]['UserName']==username:
                self.memberList[m]['RemarkName'] = rename
                
        
        return ret == 0`

**Comment by pcloth** [comment]
`    def get_alias(self, contract=None, username=None):
        """通过username寻找微信号/备注/昵称/username,优先级一次递减
        """
        contract = self.get_contract() if contract is None else contract
        for ct in contract:
            if username == ct.get('UserName'):
                if ct.get('Alias') == '':
                    if ct.get('RemarkName') == '':
                        if ct.get('NickName') == '':
                            return username
                        return [ct.get('NickName'),'NickName'] #这里开始增加了返回类别
                    return [ct.get('RemarkName'),'RemarkName']
                return [ct.get('Alias'),'Alias']

    def set_oplog(self, username, rename):
        """设置备注
        """
        url = '%s/webwxoplog?lang=%s&pass_ticket=%s' % (self.loginInfo['url'],
                                                        'zh_CN',
                                                        self.loginInfo['pass_ticket'])
        data = {
            'UserName': username,
            'CmdId': 2,
            'RemarkName': rename,
            'BaseRequest': self.loginInfo['BaseRequest'],
        }
        headers = {
            'ContentType': 'application/json; charset=UTF-8'
        }
        r = self.s.post(url, data=json.dumps(BytesDecode(data)), headers=headers)
        ret = json.loads(BytesDecode(r.content.decode('utf-8', 'replace')))['BaseResponse']['Ret']
        
        # 添加修改备注后，内存中的备注名字也一同修改了。  
        for m in range(len(self.memberList)):
            if self.memberList[m]['UserName']==username:
                self.memberList[m]['RemarkName'] = rename

        return ret == 0`

**Comment by pcloth** [comment]
`    def get_alias(self, contract=None, username=None):
        """通过username寻找微信号/备注/昵称/username,优先级一次递减
        """
        contract = self.get_contract() if contract is None else contract
        for ct in contract:
            if username == ct.get('UserName'):
                if ct.get('Alias') == '':
                    if ct.get('RemarkName') == '':
                        if ct.get('NickName') == '':
                            return username
                        return [ct.get('NickName'),'NickName'] #这里开始增加了返回类别
                    return [ct.get('RemarkName'),'RemarkName']
                return [ct.get('Alias'),'Alias']`

**Comment by pcloth** [comment]
`def get_alias(self, contract=None, username=None):
        """通过username寻找微信号/备注/昵称/username,优先级一次递减
        """
        contract = self.get_contract() if contract is None else contract
        for ct in contract:
            if username == ct.get('UserName'):
                if ct.get('Alias') == '':
                    if ct.get('RemarkName') == '':
                        if ct.get('NickName') == '':
                            return username
                        return [ct.get('NickName'),'NickName'] #这里开始增加了返回类别
                    return [ct.get('RemarkName'),'RemarkName']
                return [ct.get('Alias'),'Alias']
`

**Comment by pcloth** [comment]
我自己改了一下这两个函数，不知道是否符合老大们的设计：
`def get_alias(self, contract=None, username=None):
        """通过username寻找微信号/备注/昵称/username,优先级一次递减
        """
        contract = self.get_contract() if contract is None else contract
        for ct in contract:
            if username == ct.get('UserName'):
                if ct.get('Alias') == '':
                    if ct.get('RemarkName') == '':
                        if ct.get('NickName') == '':
                            return username
                        return [ct.get('NickName'),'NickName'] #这里开始增加了返回类别
                    return [ct.get('RemarkName'),'RemarkName']
                return [ct.get('Alias'),'Alias']

def set_oplog(self, username, rename):
        """设置备注
        """
        url = '%s/webwxoplog?lang=%s&pass_ticket=%s' % (self.loginInfo['url'],
                                                        'zh_CN',
                                                        self.loginInfo['pass_ticket'])
        data = {
            'UserName': username,
            'CmdId': 2,
            'RemarkName': rename,
            'BaseRequest': self.loginInfo['BaseRequest'],
        }
        headers = {
            'ContentType': 'application/json; charset=UTF-8'
        }
        r = self.s.post(url, data=json.dumps(BytesDecode(data)), headers=headers)
        ret = json.loads(BytesDecode(r.content.decode('utf-8', 'replace')))['BaseResponse']['Ret']
        
        # 添加修改备注后，内存中的备注名字也一同修改了。  
        for m in range(len(self.memberList)):
            if self.memberList[m]['UserName']==username:
                self.memberList[m]['RemarkName'] = rename

        return ret == 0`

**Comment by 237rxd** [comment]
@littlecodersh 群主，pip更新后，经常扫完码后会出现以下错误，
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "run.py", line 523, in start_itchat
    itchat.auto_login()
  File "/usr/local/lib/python2.7/site-packages/itchat/__init__.py", line 13, in auto_login
    __client.auto_login()
  File "/usr/local/lib/python2.7/site-packages/itchat/client.py", line 77, in auto_login
    self.get_contract()
  File "/usr/local/lib/python2.7/site-packages/itchat/client.py", line 171, in get_contract
    int(time.time()), self.loginInfo['skey'])
KeyError: 'skey'
