### ISSUE TITLE
search_friends无法获得自己的信息

### ISSUE THREAD

**Issue by yangjicai** [littlecodersh/ItChat#230]
按照API的文档，下述方法可以获得自己的信息，但是使用的时候我获得的是好友的属性信息。
输入参数调用也无法找到自己的属性字典。
使用的是python3

```
itchat.auto_login(enableCmdQR=2,hotReload=True)
itchat.search_friends()
itchat.run(debug=True）
```

**Comment by littlecodersh** [comment]
@yangjicai 升级到1.2.22吗？

**Comment by yangjicai** [comment]
嗯。最新的。1.2.22。
friendlist 里没有自己的信息。我用浏览器看得时候，html里的确还是包含自己的username的。是不是抓取的问题呢。

**Comment by littlecodersh** [comment]
@yangjicai 在1.2.23中已修复该问题，感谢你的支持。
bug是之前一次代码回滚的时候多删除了插入自己用户信息的语句。
