### ISSUE TITLE
执行 auto_login 但是没有弹出二维码

### ISSUE THREAD

**Issue by gunC** [littlecodersh/ItChat#231]
执行 auto_login 但是没有弹出二维码

**Comment by gunC** [comment]
pip install pillow

**Comment by littlecodersh** [comment]
@gunC 试试新版本的itchat，换用了pyqrcode内部生成二维码。

**Comment by sjdy521** [comment]
这样做有什么好处吗？只是减少了网络请求延迟？
因为官方生成的二维码包含的形式可能随时会改变，这样把生成方式写死到程序会不会反而不太好 ，另外还增加了新的依赖库

**Comment by sjdy521** [comment]
这样做有什么好处吗？只是减少了网络请求延迟？
因为官方生成的二维码包含的形式可能随时会改变，这样把生成方式写死到程序会不会反而不太好 ，另外还增加了新的依赖库

**Comment by littlecodersh** [comment]
@sjdy521 主要是命令行显示二维码的时候不需要装pil了，pil太大而且比较难装。
新增的依赖库都是纯python的包，也不大，这个倒是不用担心。
二维码内容更改的话，的确可能产生问题。
主要是历史而言很稳定，我倾向于尝试一下更方便的命令行生成二维码的依赖包。
