### ISSUE TITLE
成语接龙有问题

### ISSUE THREAD

**Issue by LanceNTJH** [littlecodersh/ItChat#232]
不知道代码中成语接龙的储存是怎么做的，当你和他接龙的时候很多时候他会自己断掉，是不是有同时在玩的人打断了，没有去记录是谁发的导致2个群或者2个人在玩的时候一边答错导致接龙失败。

**Comment by littlecodersh** [comment]
@LanceNTJH 成语接龙是接tuling123时候的问题了，每个群用userName做标示就好。

**Comment by LanceNTJH** [comment]
这个明白的，在测试你的机器人发现了这个问题，希望你可以改下这个bug。 @littlecodersh
