### ISSUE TITLE
[bug]加好友提示欢迎词功能无法运行

### ISSUE THREAD

**Issue by 631068264** [littlecodersh/ItChat#236]
我想问一句这个是怎样触发的是别人加我，还是我加别人才触发？我试过都不行。。。
@itchat.msg_register(FRIENDS)
def add_friend(msg):
    itchat.add_friend(**msg['Text'])  # 该操作会自动将新好友的消息录入，不需要重载通讯录
    itchat.send_msg('Nice to meet you!', msg['RecommendInfo']['UserName'])

**Comment by littlecodersh** [comment]
@631068264 别人加你，这是个通过好友验证的操作，你需要开好友验证。
