### ISSUE TITLE
1205

### ISSUE THREAD

**Issue by sunfanteng** [littlecodersh/ItChat#237]
请问，我再向群聊中发送图片的时候，为什么老是返回1205的错误？

**Comment by littlecodersh** [comment]
@sunfanteng 把完整的代码发上来，我给你看看。

**Comment by ajing2** [comment]
{u'MsgID': u'0', u'LocalID': u'14974192870260', u'BaseResponse': {u'ErrMsg': u'', u'Ret': -1, 'RawMsg': u''}}   我发图片老是返回-1，群主这个可以破吗

**Comment by ajing2** [comment]
频率控制的这个有什么招吗
