### ISSUE TITLE
重启 itchat 之后会收到重启前接收到的最后一条消息

### ISSUE THREAD

**Issue by RoyXiang** [littlecodersh/ItChat#238]
在退出时利用 `dump_login_status` 把登录状态保存下来，然后重新启动，采用 `auto_login(hotReload=True)` 方式登录，此时会接收到重启前收到的最后一条消息，导致同一条消息收到两次甚至两次以上。

**Comment by RoyXiang** [comment]
补充一下：必须是未读消息

**Comment by littlecodersh** [comment]
@RoyXiang 是这样的，服务器怕你最后一条消息没收到。
如果要解决这个问题，最简单的来说你可以把之前最后一条收到的消息的`NewMsgId`键值存下来，如果和新消息的一模一样那就是重复的消息。
