### ISSUE TITLE
自动添加好友的接口itchat.add_friend，似乎运行无效了

### ISSUE THREAD

**Issue by scaldstack** [littlecodersh/ItChat#243]
连续运行了1个礼拜多都正常，但是昨天下午时发现新加好友不会自动通过了。
去服务器看了下，也没有什么log输出，一切正常的样子。
重启测试了下，还是一样。
在这一个多礼拜的运行期间没有改动过任何代码。

**Comment by githubwing** [comment]
同遇到问题  只是可以发送消息 但是好友申请不通过

**Comment by littlecodersh** [comment]
@scaldstack @githubwing 已更新，升级到1.2.27即可。

**Comment by tylor-e** [comment]
@littlecodersh 我刚好用的1.2.27 半年没用了 然后不能自动添加好友了 请问怎么办呢
```
@itchat.msg_register('Friends')
def add_friend(msg):
    print(msg)
    itchat.add_friend(**msg['Text'])
    itchat.send_msg('你好', msg['RecommendInfo']['UserName'])
```

**Comment by tylor-e** [comment]
@littlecodersh 

```
@itchat.msg_register(FRIENDS)
def add_friend(msg):
    print(msg)
```
我用上述代码, 什么也打印不出来, 不知道问题在哪

**Comment by tylor-e** [comment]
用两个微信号测试了一下 开启了好友验证的号此功能正常 但是没开启好友验证也就是任何人都可以随意添加的那个号功能就不对 表现在添加好友后没有主动发消息过去 是否还有什么参数需要设置呢?@littlecodersh
