### ISSUE TITLE
itchat.search_friends()不返回个人用户信息

### ISSUE THREAD

**Issue by yu-george** [littlecodersh/ItChat#244]
使用`itchat.search_friends()`（不带任何参数）返回的是好友的词典，不是自己的。

**Comment by littlecodersh** [comment]
@yu-george 给我一下你用的itchat版本。

**Comment by yu-george** [comment]
@littlecodersh 1.2.19

**Comment by yu-george** [comment]
@littlecodersh 之前用，只有1个好友的时候还是好的，但是后来加了多个好友之后，就会出现这个问题，我现在即使把好友全部删光，也仍然不会返回我自己的信息。

**Comment by littlecodersh** [comment]
@yu-george 更新最新版本吧，现在已经1.2.27了。
