### ISSUE TITLE
synccheck 和 webwxsync 无规律返回 503

### ISSUE THREAD

**Issue by RoyXiang** [littlecodersh/ItChat#248]
利用 itchat 挂机，发现掉线了，于是重启了服务器上的程序，结果相隔几秒钟就又掉线了。

不确定是否是微信服务器不稳定还是被针对，但是手动登录网页版微信发现了如下行为：

心跳包接口 `synccheck` 和获取消息 `get_msg` 采用的 `webwxsync` 接口总有几个 503 丢过来，请求列表里总有几个是红的，猜测大概是 itchat 无法正确获取登录状态和最新消息的原因。

**Comment by RoyXiang** [comment]
`webwxsync` 是会重试 5 次的，建议给 `synccheck` 加上这个，不然网络状况不好的时候很容易错误地将网页版登出。

**Comment by littlecodersh** [comment]
@RoyXiang 503的话很可能是网不好。
webwxsync和synccheck都有加重试，你可以看一下源码。
synccheck还是长连接，连续五次错误的延时后还是无法连接的话心跳也肯定不行了，所以暂时不考虑增加重试次数。

**Comment by RoyXiang** [comment]
@littlecodersh 当时发生那种情况的时候 itchat 是挂在 VPS 上的，登录成功之后 itchat 立马就掉了，然后我才在本地开了个 Chrome 浏览器查看请求，所以就算是网络问题，也极有可能是微信服务器的问题。

另外，代码里并没有发现 `sync_check` 有重试机制，目前是只要 `sync_check` 的返回内容不对就直接 `self.isAlive = False` 的。

**Comment by littlecodersh** [comment]
@RoyXiang 不是返回内容不对，而是返回了登出标示。

**Comment by RoyXiang** [comment]
`r = self.s.get(url, params=params, headers=headers)` 这个执行完返回的 Response Header 是 503，响应内容为空，所以 `r.text` 取到的是空字符串，然后 `pm = re.search(regx, r.text)` 得到的 `pm` 自然是 `None` 了。

@littlecodersh

**Comment by littlecodersh** [comment]
@RoyXiang 在503情况下你说的是很有道理的，我会在下个版本里面改进这个问题。
我的考虑是这样的，503的返回值是服务器明确返回了内容回来而非网络连接异常，我在想是不是你的中间网络服务中间某个节点给你返回的这个值。
在我维护这个项目的那么长时间内这是我第一次遇到微信返回503而非直接终止连接，而直接终止连接的话会直接抛出异常进入重试。
不过加上非200返回值的重试也并没有问题，所以就加上了。
