### ISSUE TITLE
命令行二维码效果不佳，可否替换所使用的库

### ISSUE THREAD

**Issue by buginux** [littlecodersh/ItChat#253]
https://github.com/Urinx/WeixinBot 这个项目里面使用了 qrcode 的库，在我本机上的显示效果似乎比 pyqrcode 的来得好，可否考虑替换成使用这个库呢？

**Comment by littlecodersh** [comment]
@buginux 出于更好的兼容性考虑，不会换用qrcode，若追求显示效果，联系使用非命令行二维码。
