### ISSUE TITLE
有没有办法将个人名片或自己关注的公众号名片转发出去？

### ISSUE THREAD

**Issue by iliaokun** [littlecodersh/ItChat#260]
这个是您之前的回答，我使用以下代码无法发送名片，能确定下，现在的还支持发送名片的这个功能吗？
> @ganleyang @jireh-he @shqzzy @tempdban
> 在最新版本中更新了发送名片的功能，示例代码如下：
> 
> import itchat
> 
> @itchat.msg_register(itchat.content.CARD)
> def reply(msg):
>     itchat.send_raw_msg(msg['MsgType'], msg['Content'], msg['FromUserName'])
> 
> itchat.auto_login(True)
> itchat.run()
> 其实是很古老的做法，当时以为名片和链接分享一样被过滤了，没想到今天无意中试了一下还能用。
> 另外，多提一句，和链接分享被过滤的原因一样，名片中的内容也是可以随意修改的。

**Comment by littlecodersh** [comment]
@iliaokun 不能用就是现在不行了。

**Comment by iliaokun** [comment]
好的，谢谢哈~
