### ISSUE TITLE
itchat 的注册消息中，如何获得群聊id？

### ISSUE THREAD

**Issue by canglangke** [littlecodersh/ItChat#264]
通过	itchat.get_chatrooms() 我已经获取了所有的群聊的列表，并将id存入了dic
现在的一个问题是，我在注册消息接口，如下新建函数中
 @itchat.msg_register([itchat.content.TEXT, itchat.content.SHARING], isGroupChat=True)
def group_reply_text(msg):
 source = msg['FromUserName']
此处的source我是想获取到群聊的id，而不是发送消息的人的id，请问这个该如何获取到此消息的群聊id

我的目标是 获取到消息，然后获取群聊id，特定的群聊我才响应消息。
谢谢！

**Comment by tempdban** [comment]
msg['FromUserName'] 也是群聊id ，id前两个字符为@@代表是群聊

**Comment by canglangke** [comment]
谢谢回复！但是我在这个接口打印出来显示是一个@ 而且长度比群聊id短一办左右请问这个是咋回事啊谢谢😜

**Comment by zlstll** [comment]
请问这个问题怎么解决的，我也想获取群聊id，使用msg['FromUserName']获取的是发消息人的id

**Comment by NemoHoHaloAi** [comment]
https://github.com/littlecodersh/ItChat/issues/222

看下这个issues
