### ISSUE TITLE
you can't get access to internet or wechat domain, so exit.

### ISSUE THREAD

**Issue by rhodesiaxlo** [littlecodersh/ItChat#265]
题主你好，我是python初学者，参考readme写出的demo报错，报错截图如下

![image](https://cloud.githubusercontent.com/assets/9957924/23651074/4c7a6bb4-035f-11e7-8d2d-803e5bee1e53.png)

我的开发环境:  win7
python版本: 3.6.0 

执行的python脚本 2.py 源代码为：
import itchat
itchat.auto_login()
itchat.send('hello filehelper', toUserName='filehelper')

为什么会报这个错呢？是我的执行方式有错误吗，如果是，正确的执行方式是怎样的呢？
非常感谢  ：)

**Comment by tempdban** [comment]
@rhodesiaxlo 报错的原因是红框的上一行

**Comment by rhodesiaxlo** [comment]
自己挖的坑我自己来填
google一下，找到帖子
[ssl certificate verify failed error](http://stackoverflow.com/questions/27835619/ssl-certificate-verify-failed-error)
根据帖子的说明，上述问题一个可能的原因为ssl证书，在python 2.7 ,python 3.4 及以上版本会强制验证certificate

原文如下：
>Currently when a standard library http client (the urllib , urllib2 , http , and httplib modules) encounters an https:// URL it will wrap the network HTTP traffic in a TLS stream, as is necessary to communicate with such a server. However, during the TLS handshake it will not actually check that the server has an X509 certificate is signed by a CA in any trust root, nor will it verify that the Common Name (or Subject Alternate Name) on the presented certificate matches the requested host.

The failure to do these checks means that anyone with a privileged network position is able to trivially execute a man in the middle attack against a Python application using either of these HTTP clients, and change traffic at will.

This PEP proposes to enable verification of X509 certificate signatures, as well as hostname verification for Python's HTTP clients by default, subject to opt-out on a per-call basis. This change would be applied to Python 2.7, Python 3.4, and Python 3.5.

果断切回 2.6 版本，再次运行，依然是  you can't get access to internet or wechat domain, so exit. 错误，stacktrace 描述为 site-package/config.py 中 connection error, 找到 config.py 文件
```python
import os, platform

VERSION = '1.2.28'
BASE_URL = 'https://login.weixin.qq.com'
OS = platform.system() #Windows, Linux, Darwin
DIR = os.getcwd()
DEFAULT_QR = 'QR.png'

USER_AGENT = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36'
```
url 只能是 https://login.weixin.qq.com，复制地址 粘贴到浏览器，连接报错，原来是公司网络的问题 :<

回到家中，再次测试, 成功！
![Uploading Screen Shot 2017-03-07 at 9.08.37 PM.png…]()

**Comment by rhodesiaxlo** [comment]
1.运行方式没问题
2.公司太坑

**Comment by ghostlyman** [comment]
可能是python版本内部的根证书过期，请尝试下列命令。
```
$ sudo pip uninstall -y certifi
$ sudo pip install certifi==2015.04.28
```

**Comment by l123456789jy** [comment]
电脑不要挂代理，要不然也GG

**Comment by atanx** [comment]
在centos上，python2.7遇到同样的ssl问题，按照@ghostlyman的方法有效，感谢！
`
pip uninstall -y certifi
pip install certifi==2015.04.28
`

**Comment by lightlizm** [comment]
> 电脑不要挂代理，要不然也GG

关了代理，果断又进入了，谢谢~~
