### ISSUE TITLE
保持itChat中如何使用虚拟机登录微信

### ISSUE THREAD

**Issue by haosdent** [littlecodersh/ItChat#272]
您好，您在 #70 提到

>最简单的方案就是使用虚拟机

但是我用虚拟机尝试无法扫描QR code登录微信，假如我把QRcode保存到虚拟机上的文件，然后用微信从文件中扫，微信会报“QR Code not identified”

**Comment by tempdban** [comment]
登录二维码，是不能用微信在微信中直接选择并扫面的，你要用模拟器中的模拟摄像头的功能。

**Comment by haosdent** [comment]
many thx

**Comment by haosdent** [comment]
@tempdban 您好，我用模拟器（Android 4.4）试了下模拟摄像头，发现微信不能扫描，但是摄像机可以，请问您遇到过这种情况吗
<img width="434" alt="android_emulator_-_nexuss_5554_and_android_virtual_device__avd__manager_and_ itchat _ _issue__272_ _littlecodersh_itchat" src="https://cloud.githubusercontent.com/assets/950759/23824350/08e3ac90-06b0-11e7-8795-49e4126962d0.png">

**Comment by haosdent** [comment]
我使用夜神模拟器虽然可以有绿色边框了，但还是扫不了。您方便介绍下您是在哪个操作系统使用哪款模拟器可以扫描二维码登录微信吗？

**Comment by tempdban** [comment]
@haosdent 微信有黑科技的，具体哪个模拟器有用您需要自己试试

**Comment by haosdent** [comment]
Orz @tempdban 我试了Android SDK中的Emulator，Genymotion，夜神都不行，还有其他模拟器推荐不

**Comment by aijisud** [comment]
绕过去吧，把图片到自己邮箱，再实际用手机扫...
