### ISSUE TITLE
enableCmdQR=True输出识别码缺失问题，使用enableCmdQR=2之后依然显示有错误

### ISSUE THREAD

**Issue by leilei175** [littlecodersh/ItChat#274]
本机windows上部署时，使用enableCmdQR=True输出的识别码是完整的，能够正常扫一扫登陆
但部署在aws云服务器上时（redhat ubuntu均试过），输出在终端上的识别码有缺失（角落上缺了一部分）

已安装pillow，securecrt会话编码utf-8
这种情况可能是什么原因造成的

██████████████████████████████████████           
█              ████  █          ██          █      █              █
█  █████  █    ██      ████    █  ██  ████  █████  █
█  █      █  ██        ██      ███        ██    █  █      █  █
█  █      █  ██    █    ████    █  █      ██  █  █      █  █
█  █      █  ████  ███        ██    ███    ██  █      █  █
█  █████  █  ██  ██      ███  █  ██  ██  █  █████  █
█              █  █  █  █  █  █  █  █  █  █  █  █              █
█████████  █        ███      █  █  ██  ███████████
█████        ███  ███    ███    █    █      █    ███  ██
██  ██    ██  █  ██  ██    █        █  ██  ██  █        ██
█    █  █    ███    ████      █    ███      █  █  █  ████
█      ██  █  █          ██        ███  ██        ███    ███
█  ███            █████  █            ██████      █    █  █
███  ████              ██          █      █        ██  █  ███
█        █    █████      ██          █  ███  ███        ███
████  █████  █  ██  ██    ██    ███  ███  ███  █  █
██  ████  ███      █  ██        █  ████        ██        █
████    ██  █        ██          █    █  █      ███  █  ███
██  ██  █        █████  █  █    █  ██      ██  █  █  ███
███  █    █    █    ██  █  ████      ██      █      █      █
██    █          ████    ████████      █  █    ███  ███
█████  ███    █████  ███    █  █  ██  ████  ███  █
█  █████          █  ██    █  ██    ███        ████  ███
█      █    █████    ███  █      █    ██  █        █      ██
█          █  ██                        ██  █        █    ██      █
█  █    ████        ██  █  ██        █  █  █    ██  █    ██
██████    ██  █    ██        █  █      █    █  ██      ███
███      ███  █    ██  ██  ██  █    ██████  ███      █
█          █  █      ██    █████      █  ███          █    ██
█████████  █  █      █              ███  █  ███    ████
█              █    █  █  ██    █    ██        █  █  █      ███
█  █████  █  ██    ██    ██    █    ███    ███  █  █  █
█  █      █  █  █  ██  ███████    █  █  █                ██
█  █      █  ███  █  ███    ██  █  ██      ██    █    ███
█  █      █  ██    ██    ██        █████████    █  █  ██
█  █████  ██    █    █  ███        █  █    ████        ██
█              ███    █  █  ███            ██  █    ███      █

**Comment by QuantumLiu** [comment]
Linux要enableCmdQR=2

**Comment by leilei175** [comment]
使用了enableCmdQR=2依然显示有错误，我观察了一下，右下角部分显示不全。
测试环境是securecrt连接到远程server上。
求大神指点
██████████████████████████████████████████████████████████████████████████████
██              ████  ██  ██    ██████  ██████████  ██  ██████              ██
██  ██████████  ████  ██████    ████████████  ██████  ████████  ██████████  ██
██  ██      ██  ██      ██████      ██  ████  ██████  ██    ██  ██      ██  ██
██  ██      ██  ██  ██            ██  ████    ██████        ██  ██      ██  ██
██  ██      ██  ████  ██    ██████  ██  ██████    ██    ██████  ██      ██  ██
██  ██████████  ██████      ████  ██  ██  ██  ██  ████  ██████  ██████████  ██
██              ██  ██  ██  ██  ██  ██  ██  ██  ██  ██  ██  ██              ██
████████████████████  ██      ██    ████        ██    ██    ██████████████████
████████    ██    ██    ██████████  ████  ██        ████████████████    ██████
████    ████  ██      ████████  ██████████    ██  ██  ██            ██    ████
████  ████  ██  ██  ██      ██      ██  ████          ██        ██  ██  ██  ██
████        ████  ██  ██  ██  ██████████  ██  ████████  ██      ████    ██  ██
██  ██████  ██            ██████    ████    ████████████    ██    ██        ██
██████████  ████    ████      ████  ██      ██    ████        ████  ██  ██████
██████    ██      ██████  ████  ██  ██  ██    ██  ██  ██  ██    ██          ██
██  ██████████████      ██  ████        ██  ██      ████  ██  ████        ████
████████  ██            ████      ██  ████        ██  ████  ██    ████  ██  ██
████      ████████    ██    ██    ████    ██████      ██  ██  ██  ██████  ████
████    ██  ██  ████  ██  ████    ██        ██████  ████  ██████  ████  ██  ██
██  ████  ██████      ██  ██      ██      ██    ██    ██████  ██████  ████████
████  ██  ██              ████      ██████    ██        ██      ██    ████████
████  ████████████      ██    ██    ████        ██          ████    ██      ██
██████  ██  ██  ████  ████████    ██████  ████████  ████  ██    ██  ██████  ██
████          ████    ██      ██    ████████        ██      ████  ████      ██
██████    ██    ██████████      ██  ██        ██████    ██████  ████  ██  ████
██        ████████  ██    ████  ██    ██      ████  ██  ██    ████    ██  ████
██      ██        ██    ████  ██  ██        ██  ████      ████  ██          ██
██  ████  ████████████████  ██████    ██████    ██  ██    ██  ██    ██  ██████
██  ██  ██████            ████        ██    ██    ██  ██            ██  ██████
██████████████████  ████    ████  ██  ██████  ██  ██  ████  ██████        ████
██              ██    ██    ██    ██████████████  ████████  ██  ██      ██  ██
██  ██████████  ████  ██████        ████████  ████      ██  ██████    ██  ████
██  ██      ██  ██  ██  ████    ██  ██  ██  ████    ████            ████  ████
██  ██      ██  ██  ████  ██████████    ████  ████████      ██  ████  ████████
██  ██      ██  ████  ██    ██  ██    ██    ██  ██  ██  ██  ████            ██
██  ██████████  ██████    ████  ██████  ██  ██  ██████  ██████  ██  ██      ██
██              ████  ████    ████    ██████    ████  ████  ██  ████  ████  ██
██████████████████████████████████████████████████████████████████████████████

**Comment by littlecodersh** [comment]
@leilei175 把第二张图放个截图吧

**Comment by littlecodersh** [comment]
@leilei175 5天未回复，关闭本issue
