### ISSUE TITLE
两个网页端登录

### ISSUE THREAD

**Issue by finalion** [littlecodersh/ItChat#276]
现在用itchat做自动回复部署到服务器上，但是如果还想在其他web端登录聊天，itchat肯定会自动退出。有什么比较好的解决方案？能否加入自动重连机制？

**Comment by tempdban** [comment]
改进你的设计，可以实现成另一线程专门做客户端。

**Comment by finalion** [comment]
聊天想用腾讯官方的

**Comment by tempdban** [comment]
那你想想就行了。

**Comment by JosephusZhou** [comment]
两个网页端登录是不可能的，一定会有一个被踢下线

**Comment by littlecodersh** [comment]
@finalion 没有办法，就使用完网页端重新登陆itchat吧。

**Comment by finalion** [comment]
我知道不能同时登录。我现在是写了一个守护进程，前端控制itchat的登录。 有个问题，不知道是怎么回事：三个sh，monitor.sh, run.sh, stop.sh.  shell中单次运行脚本，二维码图片能下载；但加入crontab任务时，就不能下载了。我已经设置了picDir的路径

**Comment by finalion** [comment]
已解决，路径问题。
