### ISSUE TITLE
check_login()后，send方法失效

### ISSUE THREAD

**Issue by sylzd** [littlecodersh/ItChat#277]
经过反复试验，发现是check导致的send失效
错误信息如下：
```python
Traceback (most recent call last):
  File "build\bdist.win-amd64\egg\itchat\components\login.py", line 237, in maintain_loop
    msgList, contactList = self.get_msg()
  File "build\bdist.win-amd64\egg\itchat\components\login.py", line 303, in get_msg
    dic = json.loads(r.content.decode('utf-8', 'replace'))
  File "D:\Anaconda2\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "D:\Anaconda2\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Anaconda2\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

![Uploading RG$CTEXCG5S31N4Z9(%K_NN.png…]()

代码如下
```python
# coding: utf-8
import itchat
import time
import logging
from datetime import datetime


def wx_login():
    itchat.auto_login(enableCmdQR=True, hotReload=True)


def check_online():
    login_status = itchat.check_login()
    if login_status == '200':
        logging.info('login succeed!')
        return True
    else:
        logging.info(datetime.now().strftime("%Y-%m-%d %H:%M:%S") + '------')
        logging.error(login_status)
        time.sleep(60)
        wx_login()
        return False


def send():
    status = check_online()
    print status
    if status is True:
        mp = itchat.search_mps(name= u'***')[0]
        print mp[u'UserName']
        info = itchat.send('3', toUserName=mp['UserName'])
        print info
        # itchat.logout()


if __name__ == '__main__':
    wx_login()
    send()
```

**Comment by tempdban** [comment]
check_login()是登录过程中调用的方法，不是做在线检查用的，auto_login中已经调用一遍了，如果你再调一遍，整个时序都会乱掉，之后返回的东西将不可预期。

**Comment by sylzd** [comment]
@tempdban  这样啊 谢谢  那要通过什么来进行在线监控呢？ 我在API里没有找到其他method了

**Comment by littlecodersh** [comment]
@sylzd auto_login的时候有exitCallback的，但要注意的是现在有些情况下是一段时间无法收到消息以后还会恢复，这种情况下是没有办法通过这个callback检测到问题的。
所以如果你需要明确的检测，建议你使用itchatmp方法给机器人发消息确认其在线。

**Comment by adreamteama** [comment]
可不可以使用itchat.search_friends()，如果返回数组长度为零,断定为已经退出登录。
把这个地方改一下：
    def search_friends(self, name=None, userName=None, remarkName=None, nickName=None,
            wechatAccount=None):
        with self.updateLock:
            if (name or userName or remarkName or nickName or wechatAccount) is None:
                if len(self.memberList) == 0:
                    return {}  # maybe logout！
                else:
                    return copy.deepcopy(self.memberList[0]) # my own account
            elif userName: # return the only userName match
..
..

原来代码：
    def search_friends(self, name=None, userName=None, remarkName=None, nickName=None,
            wechatAccount=None):
        with self.updateLock:
            if (name or userName or remarkName or nickName or wechatAccount) is None:
                    return copy.deepcopy(self.memberList[0]) # my own account
            elif userName: # return the only userName match
..
..
