### ISSUE TITLE
无法下载视频到本地,下载的视频大小为0KB

### ISSUE THREAD

**Issue by aijialin** [littlecodersh/ItChat#279]
elif msg_type == 'Video':
        msg_content = msg['FileName']
        msg['Text'](msg['FileName'])
使用以上代码获取到0KB的视频 没有错误提示。

https://wx2.qq.com/cgi-bin/mmwebwx-bin/webwxgetvideo?msgid=[消息ID]&skey=[skey] 这个接口不能获取到视频文件了吗？
我使用web微信登录发现接受到的视频文件也是一张静态的缩略图,是不是微信已经禁止web端获取视频文件了？

**Comment by aijialin** [comment]
可以获取到文件名称
    if msg_type == 'Video':
        msg_content = msg['FileName']
        msg['Text'](msg['FileName']) #此方法获取到的视频大小为0KB

**Comment by littlecodersh** [comment]
@aijialin 目前的确有些视频无法获取，由于这是微信端接口本身的问题所以我这里没有办法修复了，所以关闭了这一issue。
过段时间微信端接口稳定后这一问题就会好转的。

**Comment by kingconan** [comment]
目前还是不行哈，不过我看 https://github.com/Chatie/wechaty/issues/504 也会有这个问题。
建议先不要关吧？
