### ISSUE TITLE
storage里头的memberList/chatroomList初始化时似乎没给赋值

### ISSUE THREAD

**Issue by tylor-e** [littlecodersh/ItChat#28]
由于我的需求需要判断消息是否来自公众号，对群ID也有需求，所以需要storage里的几个值
测试后发现`memberList/chatroomList`一直都是空的，于是把`client.py`修改了一下
在`auto_login`的`self.get_contract()`后面加上了两行代码：
```python
self.storageClass.memberList=self.memberList
self.storageClass.chatroomList=self.chatroomList
```
测试后可行。

另外判断是否来自公众号我的方法是先取得公众号的列表，之后对发来消息的ID通过是否在已知列表里进行判断。于是我参照memberList和chatroomList增加了publicList这个项，在get_contract()这个函数里和另外两个list一道进行分类。

关于在获取到的list进行普通/群/公众号的分类的过程中，我发现源代码是复制出N个数组，分别把不属于该组的数据remove掉，这就要进行N次遍历，我觉得有点低效，就把这几次遍历写到一起了，get_contract()的代码：

```python
def get_contract(self, update=False):
    if 1 < len(self.memberList) and not update:
        return self.memberList
    url = '%s/webwxgetcontact?r=%s&seq=0&skey=%s' % (self.loginInfo['url'],
                                                     int(time.time()),
                                                     self.loginInfo['skey'])
    headers = {
        'ContentType': 'application/json; charset=UTF-8'
    }
    r = self.s.get(url, headers=headers)
    memberList = json.loads(BytesDecode(r.content.decode('utf-8', 'replace')))['MemberList']
    chatroomList = []
    publicList = []
    while True:
        i = 0
        for m in memberList:
            if (any([str(n) in m['UserName'] for n in range(10)])
                and any([
                    [chr(n) in m['UserName'] for n in range(ord('a'), ord('z') + 1)],
                    [chr(n) in m['UserName'] for n in range(ord('A'), ord('Z') + 1)]
                ])):
                if ('@@' in m['UserName']):
                    chatroomList.append(m)
                elif (m['Sex'] == 0
                      and (m['VerifyFlag'] & 8 != 0)):
                    publicList.append(m)
                elif (m['Sex'] != 0
                      or (m['VerifyFlag'] & 8 == 0)):
                    continue
            memberList.remove(m)
            i += 1
        if i == 0:
            break
    # deal with emoji
    self.memberList = tools.emoji_dealer(memberList)
    self.publicList = publicList
    self.chatroomList = chatroomList
    return memberList
```

以上就是一点修改和疑问，由于不是专业程序员，不知是否正确

**Comment by tylor-e** [comment]
另外groupDict不是很理解是什么，在memberList空的时候groupDict也是空的，目前给memberList赋值后，groupDict有一个群的成员信息，但是我有不止一个群，这个群成员信息会在什么情况下更新呢，为什么会选了一个群来更新成员信息

**Comment by littlecodersh** [comment]
@tylor-e 修改有道理！下一个版本我改进去
`groupDict`是在获取一个群的第一条新消息或者群新成员发言时更新的

**Comment by tylor-e** [comment]
在对memberList进行赋值的时候会清空web_ini里面的一句：self.storageClass.memberList.append(dic['User'])
这个应该是把自己添加到memberList，个人觉得没什么必要，毕竟自己的信息存在storage里面了，于是auto_login()的倒数第二句修改成:out.print_line('Login successfully as %s\n' % (self.storageClass.nickName), False)，否则会因为查不到自己而现实login successfully as None

**Comment by littlecodersh** [comment]
@tylor-e 有些账号在获取`memberList`的时候是获取不到自己的信息的，所以才加了那么一句。
第二句我会改进去的:)

**Comment by tylor-e** [comment]
@littlecodersh 我就是没获取到自己的信息，但是我觉得不需要把自己加到memberList，所以就没管，用自己的信息直接从storage里调

**Comment by littlecodersh** [comment]
@tylor-e 没获取到是因为之前你发现的那个问题，我更新`memberList`和`chatroomList`的时候覆盖了，是个Bug。
使用`self.storageClass.nickName`是有道理的，我会改进去。

**Comment by littlecodersh** [comment]
@tylor-e 
**内容更新***
已就报出的bug进行更新：[Fix memberList&chatroomList bug [RB#28: tylor-e]](https://github.com/littlecodersh/ItChat/commit/b06ccdaecf4e029c5096b546fdc2cc55a7f6d652)，再次表达感谢！

**测试代码**
```python
import itchat

itchat.auto_login()
print(len(itchat.__client.memberList))
print(len(itchat.__client.chatroomList))
```
