### ISSUE TITLE
创建群聊失败（create_chatroom）

### ISSUE THREAD

**Issue by hunshiouren** [littlecodersh/ItChat#280]
在提交前，请确保您已经检查了以下内容!

- [x] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [x] 我已经阅读并按[文档][document] 中的指引进行了操作
- [x] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [x] 本问题确实关于`itchat`, 而不是其他项目.
- [x] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
Please press confirm on your phone.
Loading the contact, this may take a little while.
Login successfully as Ollie 欣
<ItchatReturnValue: {'BaseResponse': {'ErrMsg': '', 'Ret': 1200, 'RawMsg': ''}, 'MsgID': '', 'LocalID': ''}>
```

您的itchat版本为：`[1.2.30]`。

其他的内容或者问题更详细的描述都可以添加在下面：

- 代码
```
# -*- coding: utf-8 -*-

import itchat

itchat.auto_login(True)

nickname_list = ['Ollie 欣', 'Bravo Ciao', '想想不爱吃炸鸡腿儿', 'Ramsey']
members_list = []

for item in itchat.get_friends():
    if item['NickName'] in nickname_list:
        members_list.append(item)

chatroomUserName = itchat.create_chatroom(members_list, '代码尝试')
itchat.send('代码尝试效果', chatroomUserName)
```
- 问题：
     - 如何使用 itchat 创建群聊？(也是确定一下是否还能用？)
     - 尝试打印了 create_chatroom 的返回信息，里面没有 username，需要再利用里面的变量进行哪些操作，才能把创建的群聊调用出来呢？

**Comment by littlecodersh** [comment]
@hunshiouren 你尝试打印一下members_list的值，把里面的内容贴一下给我。

**Comment by hunshiouren** [comment]
非常感谢～！

[{'Alias': '',
  'AppAccountFlag': 0,
  'AttrStatus': 99751,
  'ChatRoomId': 0,
  'City': '',
  'ContactFlag': 7,
  'DisplayName': '',
  'EncryChatRoomId': '',
  'HeadImgFlag': 1,
  'HeadImgUrl': '/cgi-bin/mmwebwx-bin/webwxgeticon?seq=520180&username=@30ba31fa3c82ae227bc3190c951c65a3&skey=@crypt_b0bff968_3fea2a68e70a4c6fc0fc41a0b4aface5',
  'HideInputBarFlag': 0,
  'IsOwner': 0,
  'KeyWord': 'hun',
  'MemberCount': 0,
  'MemberList': [],
  'NickName': 'Ollie 欣',
  'OwnerUin': 0,
  'PYInitial': 'OLLIEX',
  'PYQuanPin': 'Olliexin',
  'Province': '',
  'RemarkName': '',
  'RemarkPYInitial': '',
  'RemarkPYQuanPin': '',
  'Sex': 2,
  'Signature': ' 没个性，不签名',
  'SnsFlag': 17,
  'StarFriend': 0,
  'Statues': 0,
  'Uin': 1697017060,
  'UniFriend': 0,
  'UserName': '@30ba31fa3c82ae227bc3190c951c65a3',
  'VerifyFlag': 0,
  'WebWxPluginSwitch': 0},
 {'Alias': 'BravoCiao',
  'AppAccountFlag': 0,
  'AttrStatus': 104741,
  'ChatRoomId': 0,
  'City': 'Birmingham',
  'ContactFlag': 3,
  'DisplayName': '',
  'EncryChatRoomId': '',
  'HeadImgUrl': '/cgi-bin/mmwebwx-bin/webwxgeticon?seq=658681873&username=@768a12d631b4d09c49d52cc87681e56741f23ba7f82495960f455eaa7acd8624&skey=@crypt_b0bff968_3fea2a68e70a4c6fc0fc41a0b4aface5',
  'HideInputBarFlag': 0,
  'IsOwner': 0,
  'KeyWord': '',
  'MemberCount': 0,
  'MemberList': [],
  'NickName': 'Bravo Ciao',
  'OwnerUin': 0,
  'PYInitial': 'BRAVOCIAO',
  'PYQuanPin': 'BravoCiao',
  'Province': 'England',
  'RemarkName': '',
  'RemarkPYInitial': '',
  'RemarkPYQuanPin': '',
  'Sex': 2,
  'Signature': 'Pure as A Mecury Blink',
  'SnsFlag': 1,
  'StarFriend': 0,
  'Statues': 0,
  'Uin': 0,
  'UniFriend': 0,
  'UserName': '@768a12d631b4d09c49d52cc87681e56741f23ba7f82495960f455eaa7acd8624',
  'VerifyFlag': 0},
 {'Alias': 'ZambdaXiang',
  'AppAccountFlag': 0,
  'AttrStatus': 2147588135,
  'ChatRoomId': 0,
  'City': '海淀',
  'ContactFlag': 3,
  'DisplayName': '',
  'EncryChatRoomId': '',
  'HeadImgUrl': '/cgi-bin/mmwebwx-bin/webwxgeticon?seq=659755696&username=@e7c30485a099b2edefb1642cca54b95a9892d5141f05f519811b73404b8d7f98&skey=@crypt_b0bff968_3fea2a68e70a4c6fc0fc41a0b4aface5',
  'HideInputBarFlag': 0,
  'IsOwner': 0,
  'KeyWord': '',
  'MemberCount': 0,
  'MemberList': [],
  'NickName': '想想不爱吃炸鸡腿儿',
  'OwnerUin': 0,
  'PYInitial': 'XXBACZJTE',
  'PYQuanPin': 'xiangxiangbuaichizhajituier',
  'Province': '北京',
  'RemarkName': '',
  'RemarkPYInitial': '',
  'RemarkPYQuanPin': '',
  'Sex': 2,
  'Signature': '怕什么真理无穷，进一寸有进一寸的欢喜。',
  'SnsFlag': 17,
  'StarFriend': 0,
  'Statues': 0,
  'Uin': 0,
  'UniFriend': 0,
  'UserName': '@e7c30485a099b2edefb1642cca54b95a9892d5141f05f519811b73404b8d7f98',
  'VerifyFlag': 0},
 {'Alias': 'arsbruce',
  'AppAccountFlag': 0,
  'AttrStatus': 99901,
  'ChatRoomId': 0,
  'City': '青岛',
  'ContactFlag': 3,
  'DisplayName': '',
  'EncryChatRoomId': '',
  'HeadImgUrl': '/cgi-bin/mmwebwx-bin/webwxgeticon?seq=659762916&username=@96da9b3aca0c087db84b84654b6a7504&skey=@crypt_b0bff968_3fea2a68e70a4c6fc0fc41a0b4aface5',
  'HideInputBarFlag': 0,
  'IsOwner': 0,
  'KeyWord': 'xia',
  'MemberCount': 0,
  'MemberList': [],
  'NickName': 'Ramsey',
  'OwnerUin': 0,
  'PYInitial': 'RAMSEY',
  'PYQuanPin': 'Ramsey',
  'Province': '山东',
  'RemarkName': '',
  'RemarkPYInitial': '',
  'RemarkPYQuanPin': '',
  'Sex': 1,
  'Signature': '做个理性、自律的知识分子。',
  'SnsFlag': 17,
  'StarFriend': 0,
  'Statues': 0,
  'Uin': 0,
  'UniFriend': 0,
  'UserName': '@96da9b3aca0c087db84b84654b6a7504',
  'VerifyFlag': 0}]

**Comment by littlecodersh** [comment]
@hunshiouren 了解了，再打印一下chatroomUserName的值给我吧。

**Comment by hunshiouren** [comment]
![qq20170317-2 2x](https://cloud.githubusercontent.com/assets/12496491/24027535/2d9486fc-0b03-11e7-9d49-fbeda9115830.png)

**Comment by faner-father** [comment]
@littlecodersh 什么原因？有没有解决办法？

**Comment by faner-father** [comment]
看web微信的cookie多了很多东西，不知道是不是加多了一些验证内容。
我们返回的Ret=1101

**Comment by djtu** [comment]
2017.03.25，现在是不是创建群，及邀请入群不能用了？

**Comment by djtu** [comment]
@hunshiouren 请问 创建群问题解决了吗？

**Comment by hunshiouren** [comment]
> @hunshiouren 请问 创建群问题解决了吗？

换用了 wxpy，但是也有限制。尝试了两个小号都无法创建，只有大号才行。

**Comment by littlecodersh** [comment]
已修复该问题：

```python
import itchat

itchat.auto_login(True)

memberList = []
for name in ('friend1', 'friend2', 'friend3'):
    memberList += itchat.search_friends(name=name)

r = itchat.create_chatroom(memberList, 'test chatroom')

if r:
    r = itchat.send('new chatroom created', r['ChatRoomName'])

print(r)
```

**Comment by sure0000** [comment]
@littlecodersh 能够创建群聊但是报下面的错，请问是什么原因？
```
Traceback (most recent call last):
  File "/Users/PycharmProjects/wechat/main/weChat.py", line 17, in <module>
    r=itchat.send('new chatroom',r['testroom'])
KeyError: 'testroom'
```

**Comment by chenqping** [comment]
2018.9.5 
你好，现在使用itchat那群打印返回的消息如下，是否现在微信的接口已经更新了，建群不能用了
>>> result=itchat.create_chatroom(friends_to_test,"test")
>>> print result
{'BaseResponse': {'Ret': -1000, 'ErrMsg': u'\u8fd4\u56de\u503c\u4e0d\u5e26BaseResponse', 'RawMsg': 'no BaseResponse in raw response'}}

**Comment by shisongsong** [comment]
@chenqping 我也遇到这个问题，可能是微信把这个接口更新了吧，现在你有其他的解决办法吗

**Comment by 3xp10it** [comment]
@littlecodersh 请问现在create_chatroom能用了吗？

**Comment by shisongsong** [comment]
@3xp10it 哈哈，竟然还能收到广播，我也不知道，最近都没用这个了
