### ISSUE TITLE
能否发送微信图文信息？

### ISSUE THREAD

**Issue by wangcheng70kg** [littlecodersh/ItChat#281]
我发现小U管家能实现自动回复类似于公众号的图文消息，贵源码也能实现名片信息的发送。那么是不是也能实现图文消息的发送呢？

**Comment by wangcheng70kg** [comment]
或者，需要结合公众号的“分享给好友”功能一起来实现？

**Comment by littlecodersh** [comment]
@wangcheng70kg 直接发是不能的，那个是通过其他协议完成的，非本项目的内容。
结合公众号的部分你可以研究一下，不过也肯定不是通过个人号直接发送的。
