### ISSUE TITLE
msg['ActualUserName']方法获取不到微信号为emoji用户的userName，返回为空

### ISSUE THREAD

**Issue by codeeer02** [littlecodersh/ItChat#282]
<img width="1390" alt="2017-03-16 4 17 58" src="https://cloud.githubusercontent.com/assets/3224374/23987794/42081dda-0a66-11e7-8c9a-f89b9c7c940c.png">
运行代码和显示结果都已经展示在图中了。
说一下，其他人的userName都可以获取到，提取ActualNickName也成功，但是提取ActualUserName就失败了，返回为空。
但是，抓取整个群用户的时候，是可以找到这位用户的userName的，所以就很奇怪了。
为什么获取ActualUserName有空的时候，是不是itchat的bug呢？

**Comment by codeeer02** [comment]
现在的场景假设是这样：emoji昵称的用户一共是两个，这两个人在群里的昵称是一样的emoji，我通过ActualNickName是不可能分辨出来哪个才是刚刚发言的那个，通过ActualUserName，返回的又都是空，我该怎么定位具体的发言用户呢

**Comment by littlecodersh** [comment]
@codeeer02 ActualUserName可以通过一下程序获取，不需要使用`search_friends`
另外，`search_friends`是搜索好友的，群用户的UserName是无法通过该方法找到对应用户的。
```python
import logging
import itchat
from itchat.content import TEXT

logger = logging.getLogger('itchat')

itchat.auto_login(True)

@itchat.msg_register(TEXT, isGroupChat=True)
def p(msg):
    logger.info((msg['ActualUserName'], msg['ActualNickName']))
    logger.info(msg['Content'])

itchat.run()
```

**Comment by codeeer02** [comment]
蟹蟹，已经解决了~~~~~~就是search_friends的问题。用memberlist就OK了

**Comment by codeeer02** [comment]
给所有人说一下踩坑思路哈，我在做群的发言清理，之前是获取ActualNickName的。但是这样就容易尴尬了，因为其他人用我的昵称，就可以冒用管理员，然后机器人就不会T他出去了。
如果获取ActualUserName的话，search_friends返回的有的人是有id的，有的人是none，这就给我困扰了。后来发现不能用这个方法，这里有毒~ 用search_chatrooms方法就可以获得所有群员的详情，然后比对ActualUserName，然后就可以踢出去了！
