### ISSUE TITLE
fork后就无法收到消息了

### ISSUE THREAD

**Issue by pengyuwei** [littlecodersh/ItChat#284]
想做成守护进程运行，fork后可以看到进程还在，但是却无法收到消息了

> Thu, 16 Mar 2017 15:35:31 register.py[line:101] DEBUG itchat received an ^C and exit.
> Thu, 16 Mar 2017 15:35:31 register.py[line:102] INFO Bye~

> root@l7nu:~$ ps -ef|grep python
> root   25790     1  0 01:20 ?        00:00:00 python robot.py
> root   25795 25683  0 01:21 pts/0    00:00:00 grep --color=auto python

**Comment by littlecodersh** [comment]
@pengyuwei 看提示是已经正常退出了，直接nohup没法完成需求吗？

**Comment by tempdban** [comment]
代码贴一下，是不是把daemon设成True了
Python守护进程不要用posix方式搞，有很多成熟的管理框架给你用，比如supervisor

**Comment by xyzsss** [comment]
nohup不行的话，可以试试 tmux
