### ISSUE TITLE
create_chatroom() 使用的问题

### ISSUE THREAD

**Issue by zhiyinyouzhao** [littlecodersh/ItChat#286]
博主你好，安装Itchat后测试了几个功能，现在我想新建一个群聊。
想问下create_chatroom() 这个函数怎么用，mberlist这个参数，'MemberList': [{'UserName': member['UserName']} for member in memberList],这个该怎么理解呢

**Comment by littlecodersh** [comment]
@zhiyinyouzhao 在1.3.0之后我会将这个方法能够兼容的参数增加。
目前memberList是一个包含用户字典的列表。
