### ISSUE TITLE
Python 3.6 中 get_head_img() 抛出 TypeError 异常

### ISSUE THREAD

**Issue by youfou** [littlecodersh/ItChat#289]
Hello,

在 Python 3.6,  itcaht 1.2.31 中使用 get_head_img()，会抛出 TypeError 异常，似乎是 Python 版本兼容性问题？

具体请见下图。

![image](https://cloud.githubusercontent.com/assets/16631068/24074896/ae099d78-0c4c-11e7-9fb5-73011b60d8a7.png)

**Comment by littlecodersh** [comment]
@youfou 是的，是py3里面字符串不再默认包含二进制串。
 我的锅，更版本的时候测了两遍py2。
更新itchat 1.2.32即可：
```bash
pip install itchat -U
```
