### ISSUE TITLE
群里被别人@时，为什么有的会自动空格，有的却是\u2005？

### ISSUE THREAD

**Issue by pengyuwei** [littlecodersh/ItChat#290]
都是iphone，都是微信6.5的情况下，机器人在群里被别人@时，为什么有的在名字后会自动空格，有的却是\u2005？

比如：
@机器人 空格 内容
@机器人 \u2005 内容

**Comment by littlecodersh** [comment]
@pengyuwei 这就是微信客户端的问题了，不同客户端对于@的处理是不一样的，所以我这里@的判断才会做成这样：[messages.py][source]

```python
atFlag = '@' + (chatroom['self']['DisplayName']
    or core.storageClass.nickName)
msg['isAt'] = (
    (atFlag + (u'\u2005' if u'\u2005' in msg['Content'] else ' '))
    in msg['Content'] or msg['Content'].endswith(atFlag))
```

是使用中遇到了什么问题吗？

[source]: https://github.com/littlecodersh/ItChat/blob/master/itchat/components/messages.py#L227-L231
