### ISSUE TITLE
请问怎么实现定时发动消息的功能？

### ISSUE THREAD

**Issue by djtu** [littlecodersh/ItChat#298]
如题？

**Comment by zhihuaqiu** [comment]
#使用多线程
import _thread    

_thread.start_new_thread(itchat.run, ())   #原itchat.run放到线程里
_thread.start_new_thread(sendTask(), ())  #再开一个线程调用 定时任务函数 自己在函数里面写需要定时发送的消息

例：
def sendTask():
    while True:
        current_time = time.localtime(time.time())
        #定时发送销售
        if((current_time.tm_hour == 17) and (current_time.tm_min == 0) and (current_time.tm_sec == 0)):
            replay = '销售：' + str("%.2f" % db.SaleAmount())
            itchat.send(replay, toUserName="filehelper")
        time.sleep(1)

**Comment by mikuh** [comment]
没有效果

**Comment by pexcn** [comment]
我也有这个需求 https://github.com/pexcn/WeChatBot/commit/52eda5a5c65ee59f6930587da823ac40470f74c2 这样改了，没学过 python, 不知道合不合理？
