### ISSUE TITLE
First "Python ItChat.py" Fails

### ISSUE THREAD

**Issue by tobunka** [littlecodersh/ItChat#3]
After I cloned this repo and installed the packages mentioned as prerequisites, I typed "python ItChat.py" in the command line, but received nothing but an prompted error that reads as follows:

`  File "itchat.py", line 11`
`    print 'Start auto-replying'`
`                              ^`
`SyntaxError: Missing parentheses in call to 'print'`

**Comment by littlecodersh** [comment]
Thank you for your report!
This error is caused because of the version of your python.
`print` is made a function in python 3 ([PEP3105](https://www.python.org/dev/peps/pep-3105/)) and must be called with parentheses.
I will fix the problem today, you may have a try this afternoon.
But I still suggest you to install python 2.7.11 to avoid possible problems and have a better compatibility with other programs.

**Comment by jimmy-py** [comment]
NameError: name 'tuling' is not defined

**Comment by littlecodersh** [comment]
@jimmy-py py3?

**Comment by jimmy-py** [comment]
@littlecodersh python2.7 
`G:\ItChat-robot>python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>`

**Comment by littlecodersh** [comment]
@jimmy-py 把完整的报错给我一下吧

**Comment by jimmy-py** [comment]
@littlecodersh 
`G:\ItChat-robot>python ItChat.py
[INFO] Group talking plugin is open now, please be careful about it.
[WARN] There is something wrong with the format of your plugin/config/tuling.json
[SUCC] Command line QRCode plugin loaded
[SUCC] msgdealers.autoreply plugin loaded
[SUCC] msgdealers.vote plugin loaded
[INFO] But whether it can be properly used need to be tested online
[INFO] Plugin loading finished
Try to fix the plugins and test them with PluginTest.py`

**Comment by jimmy-py** [comment]
G:\ItChat-robot>python PluginTest.py
[INFO] Group talking plugin is open now, please be careful about it.
[WARN] There is something wrong with the format of your plugin/config/tuling.json
[SUCC] Command line QRCode plugin loaded
[SUCC] msgdealers.autoreply plugin loaded
[SUCC] msgdealers.vote plugin loaded
[INFO] But whether it can be properly used need to be tested online
Loading failed
Exit
Traceback (most recent call last):
  File "PluginTest.py", line 101, in <module>
    pluginOrder = [('autoreply', autoreply), ('tuling', tuling.get_response)]
NameError: name 'tuling' is not defined

**Comment by jimmy-py** [comment]
@littlecodersh ItChat-robot\plugin\config 目录下面没有tuling.json

**Comment by littlecodersh** [comment]
@jimmy-py 已更新
