### ISSUE TITLE
能否保持在线状态

### ISSUE THREAD

**Issue by yangxuan8282** [littlecodersh/ItChat#30]
目前在线时间有点短，不活跃的情况下过一段时间就没反应了
看 `README` 提到这是因为微信的心跳机制
另一个类似的基于微信机器人项目 [Hubot-WeChat](https://github.com/KasperDeng/Hubot-WeChat) 提到：`Hubot会定时发心跳给微信服务器， 微信服务器会认为Hubot一直在登录网页版的。` 
虽然没试过那个项目，但想问下能不能实现主动发送心跳，保持在线

**Comment by littlecodersh** [comment]
@yangxuan8282 
心跳包的发送项目里已经自动化了。
在线时间是看网络的稳定的，网络不稳定没法正常传递心跳包才会掉线。

**Comment by yangxuan8282** [comment]
问下网页微信登陆之后是不是独立的，手机端断开网络的话还能保持网页微信在线吗

有时候脚本运行一段时间就没反应了，不知道是因为脚本有问题还是 ItChat 掉线，能不能加一个下线提示

**Comment by littlecodersh** [comment]
@yangxuan8282 可以的，只要手机端不退出登录微信就可以。
itchat在网络环境差的时候是会掉线的，不过各种症状都可能出现，我加进代办里，之后整理一下再更新。
