### ISSUE TITLE
我安装了itchat，但是import出错了；请教大神怎么解决？

### ISSUE THREAD

**Issue by zhouyangzzuzzu** [littlecodersh/ItChat#302]
我安装了itchat，但是import出错了；请教大神怎么解决？

![2017-03-26 1 44 13](https://cloud.githubusercontent.com/assets/12062579/24329093/a61eb64c-122e-11e7-8d09-5fb89de4b8c7.png)

**Comment by mice2100** [comment]
提示明明是说成功了

**Comment by littlecodersh** [comment]
@zhouyangzzuzzu 应该是环境中有多个python，你试着整理一下环境。

**Comment by zhouyangzzuzzu** [comment]
@littlecodersh 大神厉害啊，我确实有多个python版本，shying的IDE是elicpse，可是解释器选择版本有问题。现在ok了。
