### ISSUE TITLE
Ubuntu环境下后台运行，输出重定义到log文件，仍有部分输出没有重定义

### ISSUE THREAD

**Issue by chixinmu** [littlecodersh/ItChat#303]
在提交前，请确保您已经检查了以下内容!

- [x] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [x] 我已经阅读并按[文档][document] 中的指引进行了操作
- [x] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [x] 本问题确实关于`itchat`, 而不是其他项目.
- [x] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
 python3 itchat_learn.py >> itchat.log
Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.

```

您的itchat版本为：`[1.3.1]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

你好，我在Ubuntu的环境下使用输出重定义的方法，将输出内容输出到itchat.log文件，但是输出仍有一部分内容没有到log文件中，而是输出在shell上（如以上），请问这样如何解决，我希望能够以后台运行的方式运行。

**Comment by tempdban** [comment]
我说一个无关itchat的事，你考虑过"标准错误输出"么？

**Comment by chixinmu** [comment]
感谢提供思路，不解为何要将获取二维码的信息定义为标准错误输出？不能定义为标准输出么？
