### ISSUE TITLE
能提供一下支持中文的fields.py下载地址吗？

### ISSUE THREAD

**Issue by sunsonzh** [littlecodersh/ItChat#304]
在提交前，请确保您已经检查了以下内容!

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ ] 我已经阅读并按[文档][document] 中的指引进行了操作
- [x] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [x] 本问题确实关于`itchat`, 而不是其他项目.
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

您的itchat版本为：`[在这里填写版本号]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> [您的内容]

[document]: https://github.com/soimort/you-get/wiki/FAQ
[issues]: https://github.com/soimort/you-get/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by sunsonzh** [comment]
py2.7版的运行后显示不了中文

**Comment by tempdban** [comment]
显示不了中文都成Issue了。。。
怎么显示不了也没描述，这个单子有理由拒掉。

**Comment by sunsonzh** [comment]
楼主在文档里面说替换fields.py文件，可以显示中文吗？我下载不了，请求楼主重新给个下载链接，现在显示的中文是：('\xe5\xa5\xbd\xe5\x8f\x8b\xe6\x95\xb0\xe9\x87\x8f:'

**Comment by fisher335** [comment]
我也替换了文件，返现不行，尝试了网上的几种办法都不行，最后的解决办法是安装低版本的requests
pip install “requests<2”

**Comment by littlecodersh** [comment]
@fisher335 @sunsonzh py2的[fields.py][download]。替换掉本来requests的即可发送中文文件名的文件。

[download]: https://gist.github.com/littlecodersh/9a0c5466f442d67d910f877744011705
