### ISSUE TITLE
Save cookies on disk to avoid repeated relogin

### ISSUE THREAD

**Issue by ccaapton** [littlecodersh/ItChat#31]
Why writing bots, it is often needed to restart the whole script. But each time Itchat will start a new requests.sesion(), and QR need to be re-scanned.

Could it be implemented that cookies are saved on disk and reuse it whenever possible?

**Comment by littlecodersh** [comment]
@ccaapton 
It's possible with all the necessary information stored.
But actually itchat need to re-scan after about two minutes because of the heart-beat loop of wechat.
I will get it done in the next version.

**Comment by littlecodersh** [comment]
@ccaapton I have add this feature in `1.0.12` of py2.
Have a try with the new version of itchat:
```bash
pip install itchat --upgrade
```
You may have a look at this commit for more details: [No more re-scan in repeat login [RB#31: ccaapton]](https://github.com/littlecodersh/ItChat/commit/9baeac88e5f42a8e214133eb11eee6e42b215237)
And the following is the demo program:
```python
import itchat

if itchat.load_login_status():
    @itchat.msg_register('Text')
    def simple_reply(msg):
        print(msg['Text'])
    itchat.run()
else:
    itchat.auto_login()
    itchat.dump_login_status()
    print('Config stored')
```
Truly thanks for your suggestion!
