### ISSUE TITLE
add_friends这个接口时好时坏

### ISSUE THREAD

**Issue by RobinRush** [littlecodersh/ItChat#315]
在提交前，请确保您已经检查了以下内容!

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [x] 我已经阅读并按[文档][document] 中的指引进行了操作
- [x] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [x] 本问题确实关于`itchat`, 而不是其他项目.
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
无须日志
```

您的itchat版本为：`1.3.5`。

其他的内容或者问题更详细的描述都可以添加在下面：

> add_friends这个接口在有些情况下无法使用，最近发现的大概率是某个群里面添加好友，会有来自XX群的XX，在手机上看，有可以快捷填入的功能，但是无法自动通过验证。有些好友则可以自动通过验证。求解。

[document]: https://github.com/soimort/you-get/wiki/FAQ
[issues]: https://github.com/soimort/you-get/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by littlecodersh** [comment]
@RobinRush 提供一下接口的返回值吧

**Comment by CHAO8309** [comment]
itchat.add_friend()这个方法坏了吗？

0、无法接收到好友的添加消息，msg打印出来是空的

1、既然无法接收到好友的添加消息，更无法自动通过好友的添加请求了

3、博主有时间可以检查一下这个接口吗？

**Comment by panghupy** [comment]
@littlecodersh 1205　是不是就是太频繁加人被限制了呢
