### ISSUE TITLE
关键词自动回复插件载入不成功如何修复

### ISSUE THREAD

**Issue by skyworld** [littlecodersh/ItChat#32]
![image](https://cloud.githubusercontent.com/assets/4318550/16683810/3fa5e2fe-4534-11e6-8b3f-c2dde5afc389.png)

python版本 2.7.3

**Comment by littlecodersh** [comment]
@skyworld 你有改过关键词自动回复的条件么？

**Comment by skyworld** [comment]
@littlecodersh 并没有做过任何的修改，我直接代码拉取下来运行的。

**Comment by littlecodersh** [comment]
@skyworld 我这里设置的默认`regex`应该是`(作者|主人)`，给我看下`plugin/config/autoreply.db`文件的内容吧

**Comment by skyworld** [comment]
@littlecodersh 这个db里面的内容。
![Uploading QQ截图20160711001353.png…]()

**Comment by skyworld** [comment]
@littlecodersh 图片上传有问题，我直接贴出来吧。

```
sqlite> select * from default_reply;
(作者|主人)|你可以在这里了解他：https://github.com/littlecodersh
获取文件|@fil@神秘的xlsx.xlsx
获取图片|@img@鼓掌.gif
```

**Comment by skyworld** [comment]
大神能给个可以直接沟通的方式么？ 我的机器人部署在阿里云上，现在就这两个问题：1
自动回复组件加载失败。2：证书问题。

**Comment by littlecodersh** [comment]
@skyworld 我们明天早上十点说如何？你邮箱我q号我来加你吧

**Comment by skyworld** [comment]
已经邮件你了。
