### ISSUE TITLE
我想问如何在Jupyter Notebook中显示QR.png？我尝试了一些Image, Matplotlib的api来显示，但都无果。望赐教啊 =） 谢谢！！

### ISSUE THREAD

**Issue by telescopeuser** [littlecodersh/ItChat#322]
我想问如何在Jupyter Notebook中显示QR.png？我尝试了一些Image, Matplotlib的api来显示，但都无果。望赐教啊 =） 谢谢！！

commandline 模式也有问题：

![image](https://cloud.githubusercontent.com/assets/13273837/25077279/6a9583d0-237c-11e7-9098-9ecee804c0b2.png)

**Comment by telescopeuser** [comment]
cancelled by issue raiser himself.

**Comment by gowithwind** [comment]
```
%%html
<img id="qr" src="QR.png" style="min-height:30px" />
<script>
setInterval(function(){ 
    document.getElementById('qr').src="QR.png?"+Math.random()
}, 5000);
</script>
```
用一段html来刷新获取qr

**Comment by telescopeuser** [comment]
cell里面可以，赞。谢谢！
然后我想把这段代码放去itchat python utils code里面，出错了。不太懂需要怎么改可以让python运行这段html代码。。。可能吗？求教啊

![image](https://cloud.githubusercontent.com/assets/13273837/25082982/455ebd58-23a8-11e7-8acc-f6ad25b771fd.png)

**Comment by telescopeuser** [comment]
## Below is change in utils.py

def print_qr(fileDir):
    if config.OS == 'Darwin':
        subprocess.call(['open', fileDir])

    elif config.OS == 'Linux':
        #
        # www.KudosData.com : to support Jupyter notebook
        #
        # print('www.KudosData.com : %s' % fileDir)
        # subprocess.call(['xdg-open', fileDir])
        try:
            subprocess.call(['xdg-open', fileDir])
        except:
            ****# Below is for Jupyter Notebook, having problem to display image in Jupyter Notebook cell... Need help
            print('www.KudosData.com : %s' % fileDir)
            %%html
            <img id="qr" src=fileDir style="min-height:30px" />
            <script>
            setInterval(function(){document.getElementById('qr').src="QR.png?"+Math.random()}, 5000);
            </script>****
    else:
        os.startfile(fileDir)


## Below is error message:


-rw-r--r--. 1 user user  8781 Apr 17 15:14 README_EN.md
-rw-r--r--. 1 user user 10096 Apr 17 15:14 README.md
-rw-r--r--. 1 user user  7445 Apr 17 15:14 README.rst
-rw-r--r--. 1 user user  1420 Apr 17 15:14 setup.py
(env) [root@localhost itchat]# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    import itchat
  File "/home/user/itchat/itchat/__init__.py", line 2, in <module>
    from .core import Core
  File "/home/user/itchat/itchat/core.py", line 5, in <module>
    from . import config, storage, utils, log
  File "/home/user/itchat/itchat/storage/__init__.py", line 5, in <module>
    from .templates import (
  File "/home/user/itchat/itchat/storage/templates.py", line 4, in <module>
    from ..utils import update_info_dict
  File "/home/user/itchat/itchat/utils.py", line 94
    %%html
    ^
SyntaxError: invalid syntax

**Comment by littlecodersh** [comment]
试试这个思路
```python
import threading

from flask import Flask, make_response
import itchat

qrSource = ''

def start_flask():
    flaskApp = Flask('itchat')
    @flaskApp.route('/')
    def return_qr():
        if len(qrSource) < 100:
            return qrSource
        else:
            response = make_response(qrSource)
            response.headers['Content-Type'] = 'image/jpeg'
            return response
    flaskApp.run()
flaskThread = threading.Thread(target=start_flask)
flaskThread.setDaemon(True)
flaskThread.start()

def qrCallback(uuid, status, qrcode):
    if status == '0':
        global qrSource
        qrSource = qrcode
    elif status == '200':
        qrSource = 'Logged in!'
    elif status == '201':
        qrSource = 'Confirm'
itchat.auto_login(True, qrCallback=qrCallback)
@itchat.msg_register(itchat.content.TEXT)
def reply_text(msg):
    return msg['Text']

itchat.run()
```

**Comment by telescopeuser** [comment]
谢谢！
我研究研究。

因为我是用虚拟机加docker跑jupyter和itchat，在host WebBrowser 用 notebook tunnel去VM，所以有这个问题，应该是host说VM里面的路径无法找到。上面您的建议会适用这个场景吗

**Comment by lg-zhang** [comment]
直接这样吧...
```
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import cv2
import itchat

def show_qr(pic_file):
    im = cv2.imread(pic_file, 0)
    plt.imshow(im, cmap='gray')
    plt.axis('off')
    plt.show()

itchat.utils.print_qr = show_qr
itchat.auto_login()
```
