### ISSUE TITLE
Feature request coexistence of ItChat & Web Wechat

### ISSUE THREAD

**Issue by Meowzz95** [littlecodersh/ItChat#325]
我看到这个实现是通过网页版接口而不是通过模拟操控网页版微信实现的 但是这样就有一个问题就是 如果run着itchat 那么电脑版wechat或者网页版就无法同时登陆

有没有办法把itchat拿到的数据同时暴露到web版微信上 以实现共存？

**Comment by littlecodersh** [comment]
@Meowzz95 和官方web版是肯定不能共存的，至于拿到的数据怎么展示，就是一个简单的展示数据的问题了。
