### ISSUE TITLE
读了很多关于 UIN的issues 但是还是未能找到易行的 获取 好友UIN的方法

### ISSUE THREAD

**Issue by Meowzz95** [littlecodersh/ItChat#329]
doc里说 

> 如果想要通过程序获取，也可以用程序将某个好友或者群聊置顶（取消置顶）。

但是通过程序 `itchat.set_pinned(“@username”, isPinned=True)`  `itchat.set_pinned(“@username”, isPinned=False)` 都没有办法获取到用户的UIN，只有在手机端点开用户的聊天页才会触发程序端的uin update

请问有没有办法通过纯程序的方法来找到某个UserName的UIN？ 或者任何可以当做用户id的值？

**Comment by tempdban** [comment]
现在不能了
