### ISSUE TITLE
requests ssl证书报错

### ISSUE THREAD

**Issue by skyworld** [littlecodersh/ItChat#33]
![image](https://cloud.githubusercontent.com/assets/4318550/16684159/28d55120-4536-11e6-905e-ee414ad2dd88.png)

启动的时候报证书错误

**Comment by littlecodersh** [comment]
@skyworld 那就是你的证书有问题。
这是requests的相关报错，我这里没办法帮你修复。

**Comment by skyworld** [comment]
那我改如何解决这个我问题呢？

**Comment by littlecodersh** [comment]
@skyworld 建议google，如果实在无法修复且认为程序存在bug，建议在[requests](https://github.com/kennethreitz/requests)报issue

**Comment by skyworld** [comment]
好的，我再看看，谢谢大神。
