### ISSUE TITLE
是否有获得用户wechat id的方法

### ISSUE THREAD

**Issue by brianleepzx** [littlecodersh/ItChat#330]
在提交前，请确保您已经检查了以下内容!

- [* ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ *] 我已经阅读并按[文档][document] 中的指引进行了操作
- [ *] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [ *] 本问题确实关于`itchat`, 而不是其他项目.
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```

[在这里粘贴完整日志]
```

您的itchat版本为：`[1.3.5]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> 在调用wechat的get_friends之后发现User class里面并没有user的wechat_id. 而UserName每次登录都不一样.不知道是否可以用UserName作为get_friends的参数

[document]: https://github.com/soimort/you-get/wiki/FAQ
[issues]: https://github.com/soimort/you-get/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by superchaoran** [comment]
怎样获得wechat id啊？ @brianleepzx

**Comment by brianleepzx** [comment]
有的用户没有wechat id,因为wechat id不是必须存在的,如果有的话会在得到的user里面的某个属性显示出来.至于wechat到底用什么internal的id来标识用户我就不知道该怎么得到了 @superchaoran

**Comment by waterwoodsthu** [comment]
我打印出来了整个get_friends()的返回值，并没有wechat id相关的属性。这个可能跟手机号什么的一样属于私密信息吧。
