### ISSUE TITLE
https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxsync  Add this API listening

### ISSUE THREAD

**Issue by jinfagang** [littlecodersh/ItChat#332]
To get the feed back of send message, I think this API could be very useful:

```
https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxsync
```
Have the author consider implement this api post and response?

**Comment by littlecodersh** [comment]
@jinfagang 我这里是用这个接口获取他人发送的信息的，不知道自身发送消息的反馈具体而言是怎么样的数据包？
