### ISSUE TITLE
在DOS界面下登录微信后，网页版微信无法继续使用？

### ISSUE THREAD

**Issue by cqhappysquirrel** [littlecodersh/ItChat#336]
itchat版本为：`1.2.23

在DOS界面下通过扫码登录微信后，网页版微信就被退出来了，要想收取发送消息都只能通过手机，请问有无办法可以让网页版微信共享DOS下微信的登录信息？

非常感谢！

**Comment by lvbuwei** [comment]
没办法，itchat库用的是网页版的协议，相当于就是另一个自定义的网页版微信，网页版微信只能存在一个。

在 2017年4月27日 上午10:49，cqhappysquirrel <notifications@github.com>写道：
