### ISSUE TITLE
itchat每24小时左右会掉线

### ISSUE THREAD

**Issue by allenwq** [littlecodersh/ItChat#340]
感谢作者的贡献，这个客户端功能十分强大！

有一个问题，似乎每24小时左右就会自动掉线退出，不知道是不是微信网页版的限制还是已知问题？

退出时 console显示 `LOG OUT xxx`

**Comment by andiac** [comment]
刚刚开始使用，还没遇到楼主的问题。另外，如果登录的移动设备下线，那么网页端（客户端）也会下线，这是微信的问题么？

**Comment by OpenAndrew** [comment]
也越到这个问题，log out ，请问有没有办法解决？

**Comment by ZhouYL0213** [comment]
@andiac  根据个人经验，手机端的微信优先级比网页端的前，所以手机可以控制网页端的上下线，如果手机版下线了，网页版会跟着下线。
这是应该微信本身的设定，您可以改用浏览器来登录网页版微信，看看能否持续24小时？不过我没试过

**Comment by andiac** [comment]
@ZhouYL0213 谢谢了

**Comment by littlecodersh** [comment]
@allenwq 长时间在线的话需要保持手机微信也同时联网在线。

**Comment by allenwq** [comment]
@littlecodersh 手机微信同时在线，从来没下线过。 不知道你有没有测试过这种情况？

**Comment by andiac** [comment]
用四天了，掉了一次
