### ISSUE TITLE
itchat4j项目

### ISSUE THREAD

**Issue by yaphone** [littlecodersh/ItChat#341]
littlecodersh你好，一直在关注itchat项目，也一直在使用，最近完成了一个java版本的itchat，项目名准备叫[itcat4j](https://github.com/yaphone/itchat4j)  ，欢迎参观指导并留下宝贵意见。
另外，itchat真是一个优秀的项目！

**Comment by littlecodersh** [comment]
@yaphone 已增加友链:) 祝顺利！

**Comment by yaphone** [comment]
谢谢，也祝itchat越来越好！
