### ISSUE TITLE
itchat 怎么在被人拦进群之后自动把群加入通讯录，否则群聊发过来的消息没发检测

### ISSUE THREAD

**Issue by jinfagang** [littlecodersh/ItChat#345]
聊天机器人被人拉进了一个群，这个时候必须手动添加至通讯录，不然会报错，无法接受消息，有木有办法检测被人拉进群聊之后自动将该群加入通讯录。

**Comment by littlecodersh** [comment]
@jinfagang 报错是指什么？
这里的操作应该是在第一次收到这个群聊的消息的时候后台自动更新通讯录。

**Comment by jinfagang** [comment]
就是在更新通讯录的时候提示value error no key of ‘Self’，我catch了一下

**Comment by littlecodersh** [comment]
@jinfagang itchat版本是多少？
