### ISSUE TITLE
请问itchat是否有消息撤回的接口？

### ISSUE THREAD

**Issue by zhongwf** [littlecodersh/ItChat#346]
我用itchat发消息已经成功了，但是我有一个需求，有时候需要把itchat已经发出去的消息撤回，请问有没有撤回接口？

补充:
```python
@itchat.msg_register(NOTE)
def msg_back(msg):
    e = xml.etree.ElementTree.fromstring(msg['Content'].encode('utf8'))
    for oldmsgid in e.findall("./revokemsg/oldmsgid"):
        print oldmsgid.text
```

已经能获得希望撤回消息的ID了，但是不清楚调用什么方法能撤回。

**Comment by zhongwf** [comment]
补充:
@itchat.msg_register(NOTE)
def msg_back(msg):
    e = xml.etree.ElementTree.fromstring(msg['Content'].encode('utf8'))
    for oldmsgid in e.findall("./revokemsg/oldmsgid"):
        print oldmsgid.text

已经能获得希望撤回消息的ID了，但是不清楚调用什么方法能撤回。

**Comment by tempdban** [comment]
正在开发

**Comment by littlecodersh** [comment]
@zhongwf 有的，[v1.3.7][tag]。

[tag]: https://github.com/littlecodersh/ItChat/releases/tag/v1.3.7
