### ISSUE TITLE
从昨天起似乎只能给“文件传输助手”发消息，没法给人或群发送消息了。

### ISSUE THREAD

**Issue by luchuan** [littlecodersh/ItChat#348]
itchat.send('Hello,` someone', toUserName='someone')
<ItchatReturnValue: {u'MsgID': u'', u'LocalID': u'', u'BaseResponse': {u'ErrMsg': u'', u'Ret': -1, 'RawMsg': u''}}>

**Comment by ipv6now** [comment]
我也不能了

**Comment by vicliu6** [comment]
有人還能嗎?

**Comment by lwzswufe** [comment]
我也不能了，但是自动回复的模块还是可以用

**Comment by zhengjunbase** [comment]
嗯，确实是这样的

**Comment by Tidus1984** [comment]
我昨天才知道itchat，只能给文件助手发字符，不能给其他人发我还以为我哪里做错了，终于找到组织了，望求解决方案

**Comment by tempdban** [comment]
收到，立刻排查

**Comment by hanxiao** [comment]
`toUserName`中使用`get_friends`返回的`UserName`值可以发送信息，就是那串@开头的一长串id.
```python
itchat.send('Hello,` someone', toUserName='@32dasdwe3213sdasds123123')
```

**Comment by Tidus1984** [comment]
@hanxiao   '@32dasdwe3213sdasds123123'如何得出的 是直接用get_friends('微信号')吗？材料能说的详细点谢谢

**Comment by littlecodersh** [comment]
@luchuan @ipv6now @vicliu6 @lwzswufe @zhengjunbase @Tidus1984 我这里测试下来没有问题，把测试程序发给我看一下吧。

**Comment by youfou** [comment]
@littlecodersh 应该是Web微信最近调整了协议，不允许再使用 “微信ID” 了
除了发送消息外，现在加好友、建群，这些操作中使用“微信ID”都会报错。

**Comment by littlecodersh** [comment]
@youfou 这个倒是的，以前神奇的可以用微信号当UserName发消息和加人，现在都不行了。

**Comment by HanSon** [comment]
@littlecodersh 但是发名片还是可以用微信号

**Comment by lwzswufe** [comment]
@littlecodersh 我现在使用itchat.send('Hello,` someone', toUserName='@dabdhjbadjhadhhdlajdl')已经正常了。这里有一个问题get_friends('微信号')获取的id 在机器,IP,本人微信号都一致的情况下是不会变的吗？他会不会随着时间变化？

**Comment by littlecodersh** [comment]
@HanSon 哈哈，好的！

**Comment by littlecodersh** [comment]
@lwzswufe 每次登陆都会变化的

**Comment by xiangliu886** [comment]
itchat可以实现转发吗，而不是只发链接？即包含链接里面的部分内容，如标题，图片缩略图等，点开就是网页

**Comment by Tangyiming** [comment]
@HanSon 请问如何发送名片啊

**Comment by HanSon** [comment]
@Tangyiming 我不清楚itchat是否实现，我是自己做的
