### ISSUE TITLE
求教几个关于ItChat音频处理的问题：（1）是否可以保存成其他格式比如raw，wav，flac。（2）保存成MP3的实现机制是什么啊，比如库或者代码文件代码段？（3）保存的MP3是双声道还是单声道？

### ISSUE THREAD

**Issue by telescopeuser** [littlecodersh/ItChat#352]
在提交前，请确保您已经检查了以下内容!

- [x] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [x] 我已经阅读并按[文档][document] 中的指引进行了操作
- [x] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [x] 本问题确实关于`itchat`, 而不是其他项目.
- [x] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

您的itchat版本为：`[在这里填写版本号]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> [您的内容]
已知：
ItChat有保存语音成MP3的功能。赞！
问题：
（1）是否可以保存成其他格式比如raw，wav，flac。
（2）保存成MP3的实现机制是什么啊，比如库或者代码文件代码段？
（3）保存的MP3是双声道还是单声道？
谢谢！

[document]: https://github.com/soimort/you-get/wiki/FAQ
[issues]: https://github.com/soimort/you-get/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by telescopeuser** [comment]
谢谢

**Comment by tempdban** [comment]
原理当然是微信给的就是mp3格式

**Comment by littlecodersh** [comment]
@telescopeuser 就是微信直接传文件过来，我帮你存了下来。

**Comment by AriesChain-Dev** [comment]
> @telescopeuser 就是微信直接传文件过来，我帮你存了下来。

我想问下， 存下来了， 取出来的音质比较差， 这个是压缩了么？ 还是可以怎么修改下呢？ 我需要一个音质比较高的
