### ISSUE TITLE
itchat 安装失败

### ISSUE THREAD

**Issue by chaoMaster** [littlecodersh/ItChat#356]
![image](https://cloud.githubusercontent.com/assets/15158981/25885133/5deefe76-3589-11e7-9dba-0bd4d90a53d5.png)

pip 版本
`➜  /Users/ pip --version
     
pip 9.0.1 from /Library/Python/2.7/site-packages (python 2.7)`

请求 url 返回404，这个怎么破，换源？
`$ curl -I http://mirrors.aliyun.com/pypi/packages/74/ac/789eb98e0f5431d6d1ce36549ead88b2ab3154260f37c7dac9a34fd170b1/requests-2.14.1-py2.py3-none-any.whl\#md5\=81754d76f9a71a2d25f8c413fcf86e2c

HTTP/1.1 404 Not Found
Server: Tengine
Date: Wed, 10 May 2017 05:58:47 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 2446
Connection: keep-alive
X-Powered-By: Express
Set-Cookie: connect.sid=s%3AxGkLxCmCfFl83U9434zSsu2m.44zhSzeU6Wj%2B9Pc25WkFD7jOlcPVMGlCSlNL9LRfrvM; Path=/; HttpOnly`

**Comment by littlecodersh** [comment]
换源
