### ISSUE TITLE
BadStatusLine错误

### ISSUE THREAD

**Issue by pengyuwei** [littlecodersh/ItChat#358]
在提交前，请确保您已经检查了以下内容!

- [ v] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ v] 我已经阅读并按[文档][document] 中的指引进行了操作
- [ v] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [ v] 本问题确实关于`itchat`, 而不是其他项目.
- [ v] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
Thu, 11 May 2017 12:26:40 messages.py[line:277] DEBUG Request to send a text message to @@05bc1516a4323e1cc6cea488403330a8e6235c90536f41fe99da51d561fec1b0: 回复内容
Thu, 11 May 2017 12:48:46 login.py[line:257] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/login.py", line 232, in maintain_loop
    i = sync_check(self)
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/login.py", line 285, in sync_check
    r = self.s.get(url, params=params, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

Thu, 11 May 2017 12:48:47 connectionpool.py[line:758] INFO Starting new HTTPS connection (2): webpush.wx2.qq.com
Thu, 11 May 2017 12:48:47 login.py[line:289] DEBUG Unexpected sync check result: window.synccheck={retcode:"1101",selector:"0"}
Thu, 11 May 2017 12:48:47 login.py[line:266] INFO LOG OUT!
```

您的itchat版本为：`1.3.5`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> 每隔几个小时，就会发生这种错误，原因不明

[document]: https://github.com/soimort/you-get/wiki/FAQ
[issues]: https://github.com/soimort/you-get/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by afeezaziz** [comment]
Hi,

I would like to chime in this issue. I am also facing this issue as every message that I receive when trying the documentation points out this problem. Appreciate your insights, thanks!

**Comment by tempdban** [comment]
这个是网络不稳造成的。
Itchat mast have a stable link, pls check.

**Comment by pengyuwei** [comment]
如果因为网络不稳定，是否可以增加重试的功能以保证服务可用性。
另外，Web版本的微信并没有出现用一阵就断掉的问题，可见应该可以通过重试连接保证服务的连续可用的

**Comment by pengyuwei** [comment]
这个问题几乎每天都出现

**Comment by pengyuwei** [comment]
发现
https://github.com/littlecodersh/ItChat/blob/master/itchat/components/login.py
304行没有处理网络异常情况，直接load请求数据，这会导致问题
而上层函数对异常的处理是超过次数的话直接logout，导致了服务中断。

**Comment by littlecodersh** [comment]
@pengyuwei 目前的重试就是在上层函数的一定次数内重试。
就报错来看连接是被强制中止的，即使增加重试次数也不会让情况有变化。
