### ISSUE TITLE
添加qrCallback方法后二维码图片未生成？

### ISSUE THREAD

**Issue by taofengno1** [littlecodersh/ItChat#364]
itchat版本为：`[1.3.5]`。

![image](https://cloud.githubusercontent.com/assets/1185819/26032758/b670cc40-38cd-11e7-9830-5cd6f0672674.png)

把qrCallback参数去掉还是可以生成的，有没有人遇到过？

**Comment by teli5200** [comment]
有回调，就没有二维码
