### ISSUE TITLE
在线时间不稳定，疑与帐号相关

### ISSUE THREAD

**Issue by kwf2030** [littlecodersh/ItChat#367]
版本：1.36
系统：Win10 x64

两个微信，一个是几年前申请的，自用，一个是新申请的，用于机器人。

测试了4次，老号每次都能稳定运行15小时以上。

新号测试了10几次，运行很不稳定，最短的10分钟，最长的2小时。

这里的稳定是指持续在线时间，期间手机微信没有断网，没有掉线，但itchat的sync check总会在某一时刻返回1101，且固定都是1101，检查synckey，都是正常的，没有任何问题，不知是否是帐号问题导致。

PS：新号使用的地址是wx2，老号是用的是wx。

**Comment by teli5200** [comment]
新疆的貌似就上不去

**Comment by kwf2030** [comment]
@teli5200 有没有什么好的解决方案

**Comment by teli5200** [comment]
我也不太清楚怎么解决啊，郁闷

**Comment by tempdban** [comment]
新号绑银行卡

**Comment by kwf2030** [comment]
@tempdban 还有这个区别？？我试试
