### ISSUE TITLE
update_chatroom问题

### ISSUE THREAD

**Issue by sean0402** [littlecodersh/ItChat#368]
使用itchat.update_chatroom(userName=userName,  detailedMember=True)返回无法找到群成员，之前一直可用，已经确定userName没有问题，同一个userName通过itchat.search_chatrooms(userName=userName)查询是可以查到群组消息的
{'BaseResponse': {'ErrMsg': '无法找到对应的成员', 'RawMsg': 'No chatroom found', 'Ret': -1001}}

**Comment by tempdban** [comment]
#373

**Comment by tempdban** [comment]
#373

**Comment by liiyee** [comment]
遇到了同样的问题，不知道原因，update_chatroom可以反复调用吗？

**Comment by lhzw** [comment]
```   group2 = itchat.search_chatrooms(name=name)```

```# does not work, failed
# sticky to top still got the same error: no chatroom found.
# while True:
#     try:
#         memberList = itchat.update_chatroom(group_UserName, detailedMember=True)
#         print memberList[:5]
#     except TypeError:
#         print memberList
#         time.sleep(3)
print '-' * 78

# this does work
while True:
    memberlist = group2['MemberList']
    if memberlist == []:
        time.sleep(3)
        continue
    for j in memberlist:
        print j['NickName']
    break
```
之前测试的时候就发现过一会儿成员列表就回来了。但是不知道为什么手动调用会出错。还没有详细研读代码。先把可用的方法贴一下。

**Comment by lhzw** [comment]
置顶，或者发消息，才会获取，好像是这样的。
刚才等了好久数据都没有过来，取消置顶，再重新置顶，数据就过来了。

**Comment by klinson** [comment]
发现一种情况是微信被移除群组了，查询成员就会是空的，从而导致触发这个错误。加一步判断MemberCount数量可以避免
