### ISSUE TITLE
登陆报错：Remote end closed connection without response

### ISSUE THREAD

**Issue by MrHelix0625** [littlecodersh/ItChat#37]
TypeError: getresponse() got an unexpected keyword argument 'buffering'
http.client.RemoteDisconnected: Remote end closed connection without response
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

**Comment by MrHelix0625** [comment]
python3.5

**Comment by MrHelix0625** [comment]
另外一个问题，怎么给群发消息，群聊没有id，send参数里tousername 里无法传递群参数

**Comment by littlecodersh** [comment]
@MrHelix0625 连续登陆都是报错吗，还是仅有一次？

**Comment by MrHelix0625** [comment]
登陆已经搞定了，偶尔会出现buffering
