### ISSUE TITLE
是否有主动添加别人为好友的api？

### ISSUE THREAD

**Issue by Stanuns** [littlecodersh/ItChat#371]
请问Itchat是否有主动添加别人为好友的api？
目前提供的api
`def add_friend(self, userName, status=2, verifyContent='', autoUpdate=True):`
是否只是同意别人的加好友请求？

**Comment by tempdban** [comment]
def add_friend(self, userName, status=2, verifyContent='', autoUpdate=True):
        ''' add a friend or accept a friend
            for options
                - userName: 'UserName' for friend's info dict
                - status:
                    - for adding status should be 2
                    - for accepting status should be 3
                - ticket: greeting message
                - userInfo: friend's other info for adding into local storage
            it is defined in components/contact.py
        '''

**Comment by Stanuns** [comment]
@tempdban 这个userName参数我应该从哪边取，怎么获取陌生人的userName呢？谢谢~

**Comment by Hsiny** [comment]
微信网页版只能添加群聊里的非好友，直接搜微信ID是不行的
所以只能通过获取群聊成员获取userName

**Comment by panghupy** [comment]
@Hsiny 请问能从群聊里获得非好友的微信号吗？？
