### ISSUE TITLE
经常会有的图片或视频下载不到 

### ISSUE THREAD

**Issue by kanonlee** [littlecodersh/ItChat#375]
经常会有的图片或视频下载不到 能获取到文件名 但下载下来的文件是空的 大小为0

**Comment by kanonlee** [comment]
时不时会有报错 requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='webpush.wx2.qq.com', port=443): Read timed out. (read timeout=30)

**Comment by rikewang** [comment]
我的也是，视频下载下来是0，其他OK@tempdban

**Comment by Jaychen007** [comment]
我的是下载专辑中的表情是像这样，能获取到文件名 但下载下来的文件是空的 大小为0

**Comment by littlecodersh** [comment]
@kanonlee @rikewang 部分贴图（几乎所有的表情商店里的表情）可能由于版权原因无法直接下载。
视频目前有时存在问题，网页版也无法获取所以暂时无法修复。
