### ISSUE TITLE
通过name来search_chatrooms搜索

### ISSUE THREAD

**Issue by Dkner** [littlecodersh/ItChat#376]
chatrooms = self.robot.search_chatrooms(name='xxx')
经常搜索不到群，但是在群内聊天之后又能搜索到

**Comment by simadad** [comment]
```python
itchat.search_chatrooms('xxx')        # 找不到对应群
 itchat.get_chatrooms(update=True)      # 得不到所有群
```
Linux远程ssh连接，nohup后台运行，第一天测试正常，第二天（新窗口）有些群就搜索不到了，群内聊天也不一定能搜到。

**Comment by littlecodersh** [comment]
@Dkner 你如果换一个手机登陆微信也不是一次性把所有群都更新过去的。
所以如果某个群你想要搜到，你把他保存到通讯录中即可。

@simadad 可以提供详细测试程序吗？

**Comment by simadad** [comment]
@littlecodersh 
就是最简单的程序
### Python3.5
##### mybot.py
```python
import itchat
itchat.auto_login(hotReload=True)
...
```
##### func.py
```python
import mybot
import itchat
rooms = itcaht.search_chatrooms('A')    # 我有个群群名就叫 “A“
print(rooms)
```
### Linux
##### 后台运行 `mybot`
```bash
nohup python mybot.py &
```
##### 计划任务执行 `func`
```bash
0 8 * * 1-6 cd ~/Envs/MyWechatBot/; ~/.Envs/itchat35/bin/python func.py
```
本来前一天在后台运行时还是正常的，结果第二天（不是周日）就找不到群“A”了，在根目录下运行 `ipython` `import` `func` 与 `itchat` 手动 `search_chartrooms(A)` 也找不到，在群里发言后再 `search` 仍然找不到。

**不过，按照您上面说的方法，把群加入通讯录已经可以解决问题了，十分感谢！**

**Comment by pengyuwei** [comment]
楼上放在计划任务里，是如何解决扫码登录的问题的？
