### ISSUE TITLE
请问如何避免自己手机发出的讯息也触发了注册的函数？

### ISSUE THREAD

**Issue by vicliu6** [littlecodersh/ItChat#378]
您好 
文档跟issue都找过了,还是没法避免手机回的消息同时也触发了注册的文字reply函数,请问要怎样过滤呢？
想要达到的效果是itchat自动应答,但是同时手机可以自己回消息而不要触发注册的函数
谢谢

**Comment by tempdban** [comment]
replay里判断一下是不是自己

**Comment by vicliu6** [comment]
謝謝  

sample code is here to help the others

@itchat.msg_register(itchat.content.TEXT)
def text_reply(msg):
    **if msg[u'FromUserName'] == itchat.originInstance.storageClass.userName: return**
    return u ' something you want to reply '
