### ISSUE TITLE
如何实现群内发消息

### ISSUE THREAD

**Issue by lily1982** [littlecodersh/ItChat#379]
请问itchat实现群内发消息了吗，也就是发一个消息到群？

[document]: https://github.com/soimort/you-get/wiki/FAQ
[issues]: https://github.com/soimort/you-get/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by tempdban** [comment]
群和用户的区别是在username的前两个字符上，一个@是好友两个@（@@）是群

**Comment by littlecodersh** [comment]
@lily1982 实现了

```python
import itchat

itchat.auto_login(True)

chatroomList = itchat.get_chatrooms()
if chatroomList:
    chatroomList[0].send('hi')
else:
    print('No chatroom found')
```

**Comment by lily1982** [comment]
我运行了之后，报错如下：AttributeError: 'dict' object has no attribute 'send'

**Comment by littlecodersh** [comment]
@lily1982 版本号多少？

**Comment by lily1982** [comment]
@littlecodersh 是1.2.31

**Comment by lily1982** [comment]
@littlecodersh 我刚刚更新到1.3.7了，现在可以了，谢谢！
