### ISSUE TITLE
如何唯一确定群聊（重复issue#16）

### ISSUE THREAD

**Issue by MrHelix0625** [littlecodersh/ItChat#38]
怎么给群发消息，群聊没有id，send参数里tousername 里无法传递群参数

**Comment by littlecodersh** [comment]
@MrHelix0625 你可以看一下我的演示程序，是可以传userName的
userName每次都会变化，所以如果要确定唯一群聊，可以参考[这里](https://github.com/littlecodersh/ItChat/issues/16)

**Comment by MrHelix0625** [comment]
看着有点复杂，有可以直接调用的入口么？或者用移植的API怎么组合调用，然后传入send的toUserName参数里？

**Comment by littlecodersh** [comment]
@MrHelix0625 你可以根据文档研究一下

**Comment by MrHelix0625** [comment]
我尝试用get_contract()函数导出了所有的联系人，查询了里面没有群聊信息的字典。而且我看后面所有的取值函数（例如根据remarkname，alias等等）都是依据getcontract这个函数，前面说的几个方法，PYQuanPin和Owner都得建立在list里有这个字典为主，麻烦给个解决思路，谢谢！btw，用的是python3.5

**Comment by littlecodersh** [comment]
@MrHelix0625 你尝试一下`get_chatrooms`方法，这个方法可以获取到已收藏的群聊。
没有收藏的群聊会在第一次收到该群聊的消息的时候存储在`itchat.__client.storageClass.groupDict`里。

**Comment by MrHelix0625** [comment]
Please press confirm
Login successfully as Mr.Helix
[]
搞不懂了。。。空的list和dict，蒙圈了

**Comment by littlecodersh** [comment]
@MrHelix0625 你有收藏过群聊么？

**Comment by MrHelix0625** [comment]
@littlecodersh 搞懂了，原来要在手机端吧这个群保存在通讯录里。真是忙活一大圈啊，谢谢了，littlecoder！

**Comment by littlecodersh** [comment]
@MrHelix0625 所以我才在六楼回复中特地加了[“已收藏的群聊”](https://github.com/littlecodersh/ItChat/issues/38#issuecomment-233176703)
这就和一台新手机登陆你的微信号一样，只有收藏的群聊和新的有消息的群聊才会显示出来。

**Comment by MrHelix0625** [comment]
@littlecodersh 嗯嗯，是我太粗心，主要以前没这么用过微信

**Comment by MrHelix0625** [comment]
已经解决了，关了吧，谢谢！

**Comment by littlecodersh** [comment]
@MrHelix0625 好的，有别的问题也欢迎开issue我们再做讨论

**Comment by soulmachine** [comment]
群的"Uin": "6721245685@chatroom" 这种 Uin可以吗？我试了下每次登陆后不会变
