### ISSUE TITLE
无法使用wechatAccount来getfriends

### ISSUE THREAD

**Issue by laohan97** [littlecodersh/ItChat#380]
这个代码无法使用了？
itchat.search_friends(wechatAccount='littlecodersh')

**Comment by danjx** [comment]
同样的疑惑，获取frends以后，里面就没有wechatAccount这个key了，只能用NickName来找用户了吗？可是nickname又不是唯一的，UserName是一大串编码，微信看来是升级了，故意不让别人用

**Comment by chenjian158978** [comment]
@danjx 
难道真是如此，玩了一下感觉没啥功能

**Comment by littlecodersh** [comment]
@laohan97 目前的确是部分微信号后台不返回，对没有办法获取到的数据暂时也没有办法。
