### ISSUE TITLE
使用mac terminal 生成的二维码手机识别不出

### ISSUE THREAD

**Issue by YunyuZhang** [littlecodersh/ItChat#384]
尝试过 itchat.auto_login(enableCmdQR=2)  。 显示在terminal里面的二维码识别不出。

建议在README 让 关于Mac用户的设置改成  
`itchat.auto_login(enableCmdQR= -2)`

希望可以采纳。谢谢

=====分割线======

刚刚又试了一下 有时能识别enableCmdQR=2， 有时能识别 enableCmdQR=-2。

**Comment by tempdban** [comment]
部分系统可能字幅宽度有出入，可以通过将enableCmdQR赋值为特定的倍数进行调整：

# 如部分的linux系统，块字符的宽度为一个字符（正常应为两字符），故赋值为2
itchat.auto_login(enableCmdQR=2)
默认控制台背景色为暗色（黑色），若背景色为浅色（白色），可以将enableCmdQR赋值为负值：

itchat.auto_login(enableCmdQR=-1)

readme说的很清楚
