### ISSUE TITLE
如何做成多服务，就是支持多个微信账号反复的登陆、退出操作。

### ISSUE THREAD

**Issue by xtuyaowu** [littlecodersh/ItChat#393]
您好，不太理解 什么是用户多开。如何做成多服务，就是支持多个微信账号，指定账号反复的登陆、退出操作。还有qq群：549762872 申请了，一直没有通过麻烦通过一下谢谢。

**Comment by tempdban** [comment]
一群满了 加二群
多开，多进程都可以

**Comment by xtuyaowu** [comment]
那比如怎么判断是哪个微信号 退出？

**Comment by tempdban** [comment]
就是你这个思路
