### ISSUE TITLE
二维码识别不了啊

### ISSUE THREAD

**Issue by lijs11** [littlecodersh/ItChat#399]
能不能弄成图片形式，扫描完自动关闭

手机微信怎么拍都不能识别

**Comment by tempdban** [comment]
可以，只要你是图形界面运行itchat

**Comment by lijs11** [comment]
我的意思是运行代码shell里生成了二维码，蓝色那种方块，但是手机拍上去识别不了。难道是我手机问题？

是否是我还要单独写一个生成二维码的？

**Comment by sevck** [comment]
+1

**Comment by lijs11** [comment]
二维码里面有个参数设置一下就好了  原因是底层编译器背景   可以生成白色或者黑色二维码 这两个完全相反 所以手机可能不能识别
