### ISSUE TITLE
想用ItChat 发送 自定义分享链接 求接口

### ISSUE THREAD

**Issue by yuk320** [littlecodersh/ItChat#400]
如题，我看了接口中包含了 文本类型 文件类型 图片 和 表情 但是没有 分享链接类型的 请问 wxwebAPI是否有相关接口，或有实现方法？

**Comment by unliar** [comment]
你发送一个地址链接， 微信会自动识别，并且标蓝。

**Comment by yuk320** [comment]
@unliar 不是简单的 链接，是类型 前端分享插件分享一个链接，MsgType=49 AppMsgType=5 含 Url Title Des 等属性的 类似卡片效果的 分享信息

**Comment by unliar** [comment]
@yuk320  应该是不行的，那种分享卡片效果都是需要微信的一些配置。

**Comment by littlecodersh** [comment]
@yuk320 没有的

**Comment by Yibangyu** [comment]
> 你发送一个地址链接， 微信会自动识别，并且标蓝。

这样也不行，微信现在会自动和谐，但是直接用手机操作有事可以的。
