### ISSUE TITLE
wireshark尝试抓包时找不到qrcode

### ISSUE THREAD

**Issue by orangexuan** [littlecodersh/ItChat#404]
第一次接触网络抓包，不知道是否是操作不当，第一步找到二维码链接的过程就出了问题，wireshark截图如上，不明白深颜色部分是什么含义，是否与找不到qrcode有关？
<img width="1633" alt="2017-06-09 3 50 30" src="https://user-images.githubusercontent.com/13651685/26966130-76a60e82-4d2b-11e7-94aa-e054b53764e4.png">

**Comment by tempdban** [comment]
tcp分片没收全，不是五层协议的错
