### ISSUE TITLE
Voice 和 Recording的区别是什么？是否msgtype34是语音？

### ISSUE THREAD

**Issue by hsmj1412** [littlecodersh/ItChat#408]
您的itchat版本为：1.3.7。
其他的内容或者问题更详细的描述都可以添加在下面：
尝试添加发送语音功能失败，不清楚哪出了问题，有一些方向么？
万分感谢

[document]: https://github.com/soimort/you-get/wiki/FAQ
[issues]: https://github.com/soimort/you-get/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by littlecodersh** [comment]
@hsmj1412 只是为了和mp做一个统一所以增加了一个关键字，目前网页版无法发送语音。
