### ISSUE TITLE
msg['ActualNickName']乱码

### ISSUE THREAD

**Issue by xzjs** [littlecodersh/ItChat#41]
昨天还好好的，今天就变成了乱码，找不到原因所在，来求助

**Comment by xzjs** [comment]
'ActualNickName' (4390482304)={unicode}u'å¼ è³ä¸½2'

**Comment by littlecodersh** [comment]
@xzjs 是更新了itchat版本以后出现的问题么？

**Comment by xzjs** [comment]
我的失误，刚刚更新了代码，看到了修复这个bug的commit，打扰了

**Comment by littlecodersh** [comment]
@xzjs 不不，是我没表达清楚， 我的意思是这个问题是因为更新了版本以后出现的么，还是同一版本第二次使用就出问题了？
新的一个版本的更新里我还没有把群聊的内容做升级，只是将emoji的编码做了修复，所以还是可能出现问题。
在更新群聊之后我会升级1.0.13，到时候我升级完会在这个issue@你

**Comment by littlecodersh** [comment]
@xzjs 已更新1.0.13
