### ISSUE TITLE
测试发现的几个问题

### ISSUE THREAD

**Issue by zxb88918** [littlecodersh/ItChat#412]
在提交前，请确保您已经检查了以下内容!

- [x] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [x] 我已经阅读并按[文档][document] 中的指引进行了操作
- [x] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [x] 本问题确实关于`itchat`, 而不是其他项目.
- [x] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
Request to send a video(mediaId: None) to @@a31710cd4fa06b0ab015d41e70e37a4c30b7017821c78c2677d2b2c6b2998f1b: 170619-065939.mp4
Request to upload a video: 170619-065939.mp4
Request to send a text message to @@a31710cd4fa06b0ab015d41e70e37a4c30b7017821c78c2677d2b2c6b2998f1b: 【测试一群:萝卜】发送了一段视频
{'BaseResponse': {'ErrMsg': u'\u53c2\u6570\u9519\u8bef', 'Ret': -1005, 'RawMsg': 'Empty file detected'}}
```

您的itchat版本为：`[1.3.7]`。

其他的内容或者问题更详细的描述都可以添加在下面：

>主要是想做群消息同步，测试发现以下几个问题： 
1、转发视频，通过msg['Text'](msg['FileName'])方法下载视频到本地，视频大小0k，返回{'BaseResponse': {'ErrMsg': u'\u53c2\u6570\u9519\u8bef', 'Ret': -1005, 'RawMsg': 'Empty file detected'}}
 2、群里面发送的Recording，转发到别的群里会 转发个mp3文件，能否同样转发成Recording；
3、转发Sharing，转发后会变成文本+url的样式，能否原封不动的转发；

[document]: https://github.com/soimort/you-get/wiki/FAQ
[issues]: https://github.com/soimort/you-get/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by Albert-D** [comment]
1、同样的问题，我没有把视频内容转发，只是用msg['Text']方法下载视频到本地，在本地里面保存的视频大小是0k，无法打开，不知道是不是视频的下载函数有问题？
2、应该不行吧，Recording的消息微信本身是不支持转发的；
。。。
怎么@作者大大啊

**Comment by zxb88918** [comment]
还有附件也不能转发。

**Comment by zxb88918** [comment]
@Albert-D 今天把requests下的filed.py文件换了，下载的视频正常，但是转发不出去，不论是@fil@xxx还是@vid@xxx，都不行

**Comment by littlecodersh** [comment]
@zxb88918 发送有报错吗？返回值是什么？
