### ISSUE TITLE
关于长时间在线

### ISSUE THREAD

**Issue by yhu-aa** [littlecodersh/ItChat#415]
“如果要保持本项目超长时间（数月等）在线，建议手机保持联网。”
如你所说手机需要保持联网，那么如果几个月不碰手机是不是也坚持不了多久
这个问题可能和itchat本身无关，不知道能否得到解答，就是想无人值守一直让机器人跑

**Comment by congwang-ai** [comment]
我是做了俩机器人，互相对话，保持唤醒，掉线率还挺低的

**Comment by yhu-aa** [comment]
那要两台登陆微信的手机一直开着吧，是不是要保持屏幕常亮，微信在前台？

**Comment by adustdu2015** [comment]
也应该与微信的授权时长有限制，Oauth2.0的Token是有时长限制的，一段时间之后会失效。微信的授权机制还是很复杂的，所以微信规避了很多风险。

**Comment by yhu-aa** [comment]
那现在有没有一个长期在线的最佳实践方案呢，两个机器人感觉有点麻烦呢

**Comment by littlecodersh** [comment]
@yhu-aa 手机和主机都稳定在线即可，ios就从反馈上而言比安卓要稳定。

**Comment by kingconan** [comment]
@littlecodersh 主机有推荐么。刚才试了一下腾讯云ubuntu上海节点，不稳定。。手机iOS一直在线
