### ISSUE TITLE
请问下,itchat发送图片的大小限制是多少?

### ISSUE THREAD

**Issue by rongwwei** [littlecodersh/ItChat#418]
没什么错误,就是发送400K的图片失败,20k的图片正常,应该是有大小限制,有没有人知道大概是多少?

**Comment by jowenz** [comment]
不知道，刚学这个，官方的Q群加不了，有没有讨论的Q群或微信群

**Comment by littlecodersh** [comment]
@rongwwei 我这里10m的图片也是可以成功的，把itchat版本号和报错给我一下吧。
@jowenz 一群加满了看公告可以加二群，也一样的。

**Comment by rongwwei** [comment]
好吧,今天亲测700k的图片没有问题,我那天发送失败的错误消息是请求参数错误,难道是我那天发送的消息太多了?耽误大家时间不好意思
