### ISSUE TITLE
发送微信表情时这里下载成功, 打开空白

### ISSUE THREAD

**Issue by zhangyake** [littlecodersh/ItChat#421]
#### 发送微信表情时这里下载成功, 打开空白

```

@itchat.msg_register([PICTURE, RECORDING, ATTACHMENT, VIDEO])
def download_files(msg):
    print msg['Text'](msg['FileName'])

```
`{'PostFix': '', 'BaseResponse': {'Ret': 0, 'ErrMsg': u'\u8bf7\u6c42\u6210\u529f', 'RawMsg': 'Successfully downloaded'}`
打印返回下载成功 但是打开文件没内容

**Comment by littlecodersh** [comment]
@zhangyake 由于微信版权限制原因，网页版是无法获取到大部分商店内的表情的。
