### ISSUE TITLE
能不能用python实现自动登录呀？

### ISSUE THREAD

**Issue by adustdu2015** [littlecodersh/ItChat#422]
每次运行脚本，都需要扫描二维码才能登录，而且二维码是有时长限制，能不能实现类似post请求的方式，实现微信登录呀？我这里确实觉得微信扫描登录麻烦一点。

**Comment by redrum0003** [comment]
1. 有缓存登录状态的方法，具体去看说明。
2. post请求不可能了，微信会弄这么弱智的方式让你就过？
3. 扫码是必须的，这是由微信决定的，不是这个项目能解决的。

**Comment by littlecodersh** [comment]
@adustdu2015 缓存过一次登录状态以后就可以实现网页版类似的免扫码即可确认登陆了。
