### ISSUE TITLE
群聊消息msg['isAt']失效，始终为False

### ISSUE THREAD

**Issue by dustless** [littlecodersh/ItChat#425]
您的itchat版本为：`1.3.7`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

接收到群消息，并且是@本号的消息，但msg['isAt']为False

**Comment by pengyuwei** [comment]
我也碰到这个问题，我自己在调用的地方加了转换：

`590     is_at = False                                                               
591     if msg.has_key("isAt"):                                                                                   
592         is_at = msg['isAt']                                                     
593     if msg.has_key("IsAt"):                                                     
594         is_at = msg['IsAt'] `

**Comment by littlecodersh** [comment]
@dustless 关键词统一为大写了，可以这么用：

```python
msg.isAt
msg['IsAt']
```
