### ISSUE TITLE
File "/usr/local/lib/python3.6/site-packages/itchat/components/login.py", line 213, in show_mobile_login     self.loginInfo['url'], self.loginInfo['pass_ticket']) KeyError: 'pass_ticket'

### ISSUE THREAD

**Issue by jinfagang** [littlecodersh/ItChat#427]
itchat 1.3.5 版本。
这个在login.py 里面提示，`self.loginInfo['pass_ticket'])
KeyError: 'pass_ticket'`，是啥情况啊

**Comment by unliar** [comment]
被封了网页登陆....

**Comment by littlecodersh** [comment]
@jinfagang 看起来的确是被封了网页登录，网页版可以登吗？
就提示问题的话我在新版本里面加一下相关检测。

**Comment by jinfagang** [comment]
意思是我这个号被封了吧？那我换个号试一下

**Comment by frankiezdh** [comment]
看来腾讯最近在批量封号

**Comment by ifree** [comment]
所以看起来这着bug还是没有被修掉, 那么说明现在的wechat-bot基本上处于不可用状态?

**Comment by hagilee** [comment]
取二维码的url好像和我抓包的不一样，代码是用https://login.weixin.qq.com/l/+uuid，
但抓包看，二维码是在https://login.weixin.qq.com/qrcode/+uuid获取的

**Comment by pengyuwei** [comment]
我之前碰到一样的问题，原因是被封号了

**Comment by Sakakibara-Hu** [comment]
辣么问题来了，网页登录被封了怎么办呢？是只有等一段时间还是去哪里申诉啊
