### ISSUE TITLE
有些表情下载不了

### ISSUE THREAD

**Issue by xianhu** [littlecodersh/ItChat#429]
下载表情时（.gif格式图片），有些可以下载成功，有些不能下载。在本地有文件名，但文件内容为空。
![0c41ca90-fc63-42e3-a496-749598435301](https://user-images.githubusercontent.com/7223256/27584028-1283c3a8-5b69-11e7-9bcb-899a15b2a369.png)

**Comment by JanzenLiu** [comment]
有些应用商店的表情是下载不了，大概是版权问题

**Comment by xianhu** [comment]
OK，明白了
