### ISSUE TITLE
如何自动下载文件？

### ISSUE THREAD

**Issue by pcloth** [littlecodersh/ItChat#43]
我看了示例代码：
```python
@itchat.msg_register(['Picture', 'Recording', 'Attachment', 'Video'])
def download_files(msg):
    fileDir = '%s%s'%(msg['Type'], int(time.time()))
    msg['Text'](fileDir)
    itchat.send('%s received'%msg['Type'], msg['FromUserName'])
    itchat.send('@%s@%s'%('img' if msg['Type'] == 'Picture' else 'fil', fileDir), msg['FromUserName'])
```
其中fileDir取出来是一个Attachment11215464之类的一个字符串，完整的url应该怎么组合呢？
我的意思是我想要下载到别人传给微信机器人的文件，然后自动处理一些事情。
@littlecodersh 求教，再次感谢这个项目给我带来的便利。

**Comment by littlecodersh** [comment]
@pclot 目前的话修改后缀名就可以使用了。
`Attachment`的话有一个`FileName`键值，里面有发过来的文件的文件名。
这边给出的预先处理和示例代码的确有所不足，我之后做一个修改。
我现在打算下一个版本我把四个需要下载的消息类型的`FileName`做一个填充，你看如何？

**Comment by pcloth** [comment]
给你点赞

**Comment by pcloth** [comment]
FileName也只是一个比如'07-21.xls'这样的文件名，我怎么能下载到这个文件到机器上呢？
@littlecodersh

**Comment by littlecodersh** [comment]
@pcloth 
试试这个：
```python
msg['Text'](msg['FileName'])
```

**Comment by pcloth** [comment]
msg['Text'](msg['FileName'])
返回值是一个None
@littlecodersh

**Comment by littlecodersh** [comment]
@pcloth 
那本地有将文件下载下来吗？
`msg['Text']`中存储的是下载的方法，理论上来说传入文件名就可以完成下载。

**Comment by pcloth** [comment]
就是不知道有没有下载到本地，WINDOWS版本的微信会自动下载到本地，WEB版的也会？感觉应该提交个什么信息才会下载吧。
我的业务逻辑是这样的：用户上传一个文件给微信机器人，机器人自动打开这个文件解析内容后，做相应的处理。
@littlecodersh

**Comment by littlecodersh** [comment]
@pcloth 
是这样的没错，我这里是把下载的具体操作包装好了，存在了msg的Text键值中
但是包装的方法是根据给定的文件具体位置，直接将附件存储为相应的文件
具体的内容在client.py的308 - 326
就业务逻辑而言，可以在下载完成之后再读取本地文件，进行判断

**Comment by pcloth** [comment]
谢谢。看到了，原来是下载到了当前目录。
@littlecodersh 再次感谢。

**Comment by littlecodersh** [comment]
@pcloth 好的，不客气的:)
