### ISSUE TITLE
get_chatrooms 不能获取所有的群

### ISSUE THREAD

**Issue by huobaiyu** [littlecodersh/ItChat#440]
请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

Login successfully as XXXX

Start auto replying.
No uins in 51 message

您的itchat版本为：`[1.3.8]`。

其他的内容或者问题更详细的描述都可以添加在下面：

使用itchat.get_chatrooms(update=True) 只能获取很少几个群，但是微信群里面有几十个群。

**Comment by littlecodersh** [comment]
@huobaiyu 存进通讯录里或者在登陆后首次发生群聊天时会更新该群。
这就和你换了一台手机登陆微信是一个道理。

**Comment by panghupy** [comment]
> 请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:
> 
> Login successfully as XXXX
> 
> Start auto replying.
> No uins in 51 message
> 
> 您的itchat版本为：`[1.3.8]`。
> 
> 其他的内容或者问题更详细的描述都可以添加在下面：
> 
> 使用itchat.get_chatrooms(update=True) 只能获取很少几个群，但是微信群里面有几十个群。

你现在问题解决了吗　能获取全部的群聊了吗
