### ISSUE TITLE
Login 出错

### ISSUE THREAD

**Issue by Nibirus666** [littlecodersh/ItChat#447]
在提交前，请确保您已经检查了以下内容!

- [x] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [x] 我已经阅读并按[文档][document] 中的指引进行了操作
- [x] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [x] 本问题确实关于`itchat`, 而不是其他项目.
- [x] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

itchat.run(debug=True)
Start auto replying.

您的itchat版本为：`1.3.8`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：
login的时候报错
In: itchat.login()
Getting uuid of QR code.
Downloading QR code.
  File "G:\python\Lib\site-packages\png.py", line 2785
    print(e, file=sys.stderr)
                 ^
SyntaxError: invalid syntax

[document]: https://github.com/soimort/you-get/wiki/FAQ
[issues]: https://github.com/soimort/you-get/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by littlecodersh** [comment]
@Nibirus666 升级`png`

```bash
pip install pypng -U
```

**Comment by Nibirus666** [comment]
谢谢！话说这个怎么看出来是png出了问题呢


Sent from Yahoo Mail for iPhone


On Saturday, July 15, 2017, 22:39, LittleCoder <notifications@github.com> wrote:


@Nibirus666 升级png
pip install pypng -U

**Comment by littlecodersh** [comment]
@Nibirus666 因为报错里面提示是第三方包的png.py里出错了

**Comment by Nibirus666** [comment]
噢看到了，谢谢啊我试试


Sent from Yahoo Mail for iPhone


On Saturday, July 15, 2017, 23:17, LittleCoder <notifications@github.com> wrote:


@Nibirus666 因为报错里面提示是第三方包的png.py里出错了

**Comment by Nibirus666** [comment]
你好～我试了下pip install pypng 说已经satisfied 了


Sent from Yahoo Mail for iPhone


On Saturday, July 15, 2017, 22:39, LittleCoder <notifications@github.com> wrote:


@Nibirus666 升级png
pip install pypng -U
