### ISSUE TITLE
How to avoid logout

### ISSUE THREAD

**Issue by pinootto** [littlecodersh/ItChat#448]
Hello,

I am trying to build an application based on itchat. This application should be always logged in wechat.
Is there a way to avoid the logout after a long inactive time?
Or is there a way to make an automatic login without manually scanning the QR code every time?

Best regards,
giovanni

**Comment by pinootto** [comment]
Probably I have solved this problem.

I set the exitCallback in the login in a way that it will call the login again.

Here is my code:

```
def login_callback():
    print('Login successful')

def logout_callback():
    print('Logout')
    itchat.auto_login(hotReload=True, loginCallback=login_callback, exitCallback=logout_callback)

itchat.auto_login(hotReload=True, loginCallback=login_callback, exitCallback=logout_callback)
```

Is there another way to ensure to be always logged in?

**Comment by littlecodersh** [comment]
#415

**Comment by XuDaShu** [comment]
`def majia():
       print("Log out!")
itchat.auto_login(enableCmdQR=2,hotReload=True,exitCallback=majia)`
but i get nothing
