### ISSUE TITLE
How to detect "New member added to chatroom" event?

### ISSUE THREAD

**Issue by kk3hi3123** [littlecodersh/ItChat#449]
I would like to send welcome message when someone joins a chatroom. And then send a friend request to him. So I try to catch the new member event by this:

```
@itchat.msg_register(SYSTEM, isGroupChat=True)
def text_reply(msg):
    # some codes
    print  msg
```

However, event cannot be detected. What parameters should be set in msg_register?

**Comment by luojian520** [comment]
maybe you can create a thread to listen chatrooms' user numbers,when it added,you can compare the users before it happened and after it happened.then you could find the person who come in the charoom just now.then you can do some thing you want.

**Comment by littlecodersh** [comment]
@kk3hi3123 You may register system message like this:

```python
@itchat.msg_register(SYSTEM)
def _(msg):
    print(msg)
```

The following is the format of chatroom update system message:

```python
    return {
        'Type'         : 'System',
        'Text'         : [chatroom['UserName'] for chatroom in l],
        'SystemInfo'   : 'chatrooms',
        'FromUserName' : core.storageClass.userName,
        'ToUserName'   : core.storageClass.userName, }
```
