### ISSUE TITLE
个别微信号获取全部好友的头像获取不到，返回为空，网页登录可以正常获取

### ISSUE THREAD

**Issue by 1462326016** [littlecodersh/ItChat#450]
在提交前，请确保您已经检查了以下内容!

- [x] 我已经阅读并按[文档][document] 中的指引进行了操作
- [x] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [x] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [x] 本问题确实关于`itchat`, 而不是其他项目.
- [x] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
    itchat.auto_login(hotReload=True)
    result, session = itchat.send('hello', toUserName='filehelper')
    print itchat.get_friends()
    input()
    for a in itchat.get_friends():
        url = 'https://wx.qq.com' + a['HeadImgUrl']
        result = session.get(url,headers=headers).content
        try:
            buf = StringIO.StringIO(result)
            img = Image.open(buf)
            print a['UserName'][1:10]
            img.save('1/' + a['UserName'][1:10] + '.png')
            img.close()
        except Exception, e:
            print e
            with open('1/' + a['UserName'][1:10] + '.jpg', 'wb') as f:
                f.write(result)
                f.close()
    itchat.run(debug=True)
```

您的itchat版本为：`[VERSION = '1.3.8']`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

>想获取到所有朋友的头像，但是有的微信号可以正常获取，有的就不可以，返回全是空白，在上面这段代码里显示为全部的Image.open()操作全部抛异常
IOError('cannot identify image file <StringIO.StringIO instance at 0x0000000003FCCF88>',)
IOError('cannot identify image file <StringIO.StringIO instance at 0x0000000003EDFF48>',)
都是类似这种报错，我输出了session.get().content显示全部是空白，不知道为什么，而且是只有那一个微信号是空白，其他的正常获取，不能获取到头像的那个微信号网页上登录微信可以正常获取

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by littlecodersh** [comment]
@1462326016 部分获取不到的话应该就是网页版接口的问题了，你可以尝试一下限制频率下载。

**Comment by 1462326016** [comment]
不是个别头像，是个别账号所有头像获取不到。
