### ISSUE TITLE
syncCheck return retcode=0, and selector=3

### ISSUE THREAD

**Issue by tryuefang** [littlecodersh/ItChat#451]
我实现一个定时发布图片和文字功能，我能够看到数据成功发送，但是调用syncCheck之后，返回retcode=0, and selector=3。这个问题导致每次调用syncCheck之后都是立即返回，而不是等待25秒。请问有selector的可能值吗？或者知道什么原因吗？多谢

**Comment by Changgg** [comment]
这个是同步检查，，执行同步操作并更新syncCheckKey就好了嘛

**Comment by XuDaShu** [comment]
扫码登录失败,返回 retcode:"1102",selector:"0" 是怎么回事?
