### ISSUE TITLE
获取群聊所有人第一天成功，第二天运行代码获取结果为空

### ISSUE THREAD

**Issue by sunlianlong** [littlecodersh/ItChat#452]
首先说下：登陆是一直成功，获取的群聊列表里面也有所搜索的群聊名，想实现的功能是想实时的获取到群聊中的所有成员，代码执行后第一天是成功的，但是到第二天再运行过这个代码获取的群聊结果就为空了。
#### 更新：群已经加到通讯录里面了，今天（2017.08.07）又遇到了相关的问题，我的通讯录里面有6个群聊，但是只能获取到一个，代码仍然是之前的代码没有修改过，这是什么情况？
如果需要其他提供信息请留言

#### 代码：

![image](https://user-images.githubusercontent.com/22101668/28412351-91149a5c-6d76-11e7-8cd3-20d57b815a8e.png)

#### 昨天晚上数据图（数据已被转换成json格式，可以看到 MemberList有数据）：

![image](https://user-images.githubusercontent.com/22101668/28412379-a415bfb4-6d76-11e7-99e8-e001390bc7b7.png)

#### 今天截图（MemberList为空）：

![image](https://user-images.githubusercontent.com/22101668/28412401-b4e94c66-6d76-11e7-971f-25602fedb2f0.png)

**Comment by liu123456789** [comment]
我也碰到了。

**Comment by Dkner** [comment]
把群加到通讯录里
