### ISSUE TITLE
UserName值变化的问题

### ISSUE THREAD

**Issue by anders830** [littlecodersh/ItChat#457]
UserName, 好像是动态的，是不是无法保证持续不变，只要登录登出了就会改变？

**Comment by tempdban** [comment]
对

**Comment by wangjiang0624** [comment]
是的。但NickName是不变的

**Comment by bear-shen** [comment]
所以得想办法获取到微信的用户id……openid也可以……正在找办法……

**Comment by anlinew** [comment]
> 所以得想办法获取到微信的用户id……openid也可以……正在找办法……

有办法吗？

**Comment by bear-shen** [comment]
> > 所以得想办法获取到微信的用户id……openid也可以……正在找办法……
> 
> 有办法吗？

最后我没有用itchat的方案，是用了隔壁php的vbot来做的

在vbot里我现在用的解决方案是加好友的时候每个人添加一个昵称

在收到添加好友请求的时候，微信会仅此一次的发送用户原始id，可以用这个id，或者直接把用户名写死成一个备注，但是用户名备注就emoji和有些无名人士比较烦，实在不行随便给个随机值了事也可以

另外原始id会有一些限制……反正自己摸吧，反正用着备注之后怎么着问题都不会大

**Comment by anlinew** [comment]
> > > 所以得想办法获取到微信的用户id……openid也可以……正在找办法……
> > 
> > 
> > 有办法吗？
> 
> 最后我没有用itchat的方案，是用了隔壁php的vbot来做的
> 
> 在vbot里我现在用的解决方案是加好友的时候每个人添加一个昵称
> 
> 在收到添加好友请求的时候，微信会仅此一次的发送用户原始id，可以用这个id，或者直接把用户名写死成一个备注，但是用户名备注就emoji和有些无名人士比较烦，实在不行随便给个随机值了事也可以
> 
> 另外原始id会有一些限制……反正自己摸吧，反正用着备注之后怎么着问题都不会大

非常感谢，我能想到的也是利用用户备注记录能够唯一标示的id了
