### ISSUE TITLE
许多mp4 视频下载为空，图片什么都正常

### ISSUE THREAD

**Issue by anders830** [littlecodersh/ItChat#458]
用官方给的事列运行测试了下，好友或者群里发送的大部分mp4 视频下载为空0KB始终无法正常下载，但是图片格式的都正常。既然itchat是通过爬网页版微信封装的第三方包，我测试了下微信网页版好像是不支持查看和收发视频的，所以是不是就说明实际是无法正常获得视频的？有少数几个mp4我能正常下载下来，不清楚具体为什么。

**Comment by littlecodersh** [comment]
@anders830 是目前视频接口的问题，网页版整个的微信接口坏了。
