### ISSUE TITLE
求助，萌新不知道如何实现当收到消息后，拉该好友入群聊！期望可以给予简单示例

### ISSUE THREAD

**Issue by wuxuanyu2014** [littlecodersh/ItChat#459]
求助，萌新不知道如何实现当收到消息后，拉该好友入群聊！期望可以给予简单示例

**Comment by tempdban** [comment]
好萌

**Comment by wuxuanyu2014** [comment]
已自行解决····

**Comment by SJK132** [comment]
萌新你好

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
