### ISSUE TITLE
keyError:url

### ISSUE THREAD

**Issue by ysnows** [littlecodersh/ItChat#460]
```python
Traceback (most recent call last):
  File "/Users/ysnows/Documents/PyPj/AntWs/ws/itchat/components/login.py", line 258, in maintain_loop
    i = sync_check(self)
  File "/Users/ysnows/Documents/PyPj/AntWs/ws/itchat/components/login.py", line 306, in sync_check
    url = '%s/synccheck' % self.loginInfo.get('syncUrl', self.loginInfo['url'])
KeyError: 'url'
```

**Comment by maxuewei2** [comment]
你大概是把 auto_login 函数放在后面了。先 auto_login 再执行其他函数就好了。

**Comment by liwzhi** [comment]
还是报错。 itchat.send('Hello, filehelper', toUserName='filehelper')
  简单的tutorial 代码 都run 不起来 囧

**Comment by hcchengithub** [comment]
我的還在用 ok 的 FYR

從我的 iPad 傳送

"Weizhi" <notifications@github.com<mailto:notifications@github.com>> 於 2017/12/11 9:16 寫道：


还是报错。 itchat.send('Hello, filehelper', toUserName='filehelper')
简单的tutorial 代码 都run 不起来 囧

**Comment by FutureIsM** [comment]
> 还是报错。 itchat.send('Hello, filehelper', toUserName='filehelper')
> 简单的tutorial 代码 都run 不起来 囧

你后面解决了吗？我也一样run不起来
