### ISSUE TITLE
命令行生成的二维码，大小如何设置

### ISSUE THREAD

**Issue by yyf1986** [littlecodersh/ItChat#462]
您的itchat版本为：1.2.32。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> 
   itchat.auto_login(hotReload=True,  enableCmdQR=2)
   
   itchat.send('Hello hahah ahahha', toUserName="****")

  在Linux服务器上，一个窗口没办法完全显示这个二维码

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by yyf1986** [comment]
我把代码换成这样
itchat.auto_login(hotReload=True,  picDir='./QR.png')
为了生成图片后，自动打开，不在命令行显示了，但是报错
Downloading QR code.
xdg-mime: mimetype argument missing
Try 'xdg-mime --help' for more information.
xdg-open: no method available for opening './QR.png'

**Comment by yezuoxian** [comment]
调整terminal的字体大小

**Comment by jackiilong** [comment]
命令行下面生成的qrcode怎么扫描不了呢
