### ISSUE TITLE
1.3.9   今天微信登录不成功了

### ISSUE THREAD

**Issue by 18612790635** [littlecodersh/ItChat#468]
在提交前，请确保您已经检查了以下内容!

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ ] 我已经阅读并按[文档][document] 中的指引进行了操作
- [ ] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [ ] 本问题确实关于`itchat`, 而不是其他项目.
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

您的itchat版本为：`[在这里填写版本号]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> [您的内容]

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by 18612790635** [comment]
Traceback (most recent call last):
  File "wchat.py", line 52, in <module>
    sendWChat()
  File "wchat.py", line 36, in sendWChat
    itchat.auto_login(hotReload=True)
  File "/Library/Python/2.7/site-packages/itchat/components/register.py", line 29, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback):
  File "/Library/Python/2.7/site-packages/itchat/components/hotreload.py", line 54, in load_login_status
    self.loginInfo['User'] = templates.User(self.loginInfo['User'])
KeyError: 'User'

**Comment by jianyin2016** [comment]
server refused, loading login status failed.
Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
---------------------------------------------------------------------------
ExpatError                                Traceback (most recent call last)
<ipython-input-4-78b47e09dcc8> in <module>()
     87 
     88 # 扫二维码登录
---> 89 itchat.auto_login(hotReload=True)
     90 # 获取所有通讯录中的群聊
     91 # 需要在微信中将需要同步的群聊都保存至通讯录

C:\Users\yj\Anaconda3\lib\site-packages\itchat\components\register.py in auto_login(self, hotReload, statusStorageDir, enableCmdQR, picDir, qrCallback, loginCallback, exitCallback)
     30             return
     31         self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
---> 32             loginCallback=loginCallback, exitCallback=exitCallback)
     33         self.dump_login_status(statusStorageDir)
     34     else:

C:\Users\yj\Anaconda3\lib\site-packages\itchat\components\login.py in login(self, enableCmdQR, picDir, qrCallback, loginCallback, exitCallback)
     51         isLoggedIn = False
     52         while not isLoggedIn:
---> 53             status = self.check_login()
     54             if hasattr(qrCallback, '__call__'):
     55                 qrCallback(uuid=self.uuid, status=status, qrcode=qrStorage.getvalue())

C:\Users\yj\Anaconda3\lib\site-packages\itchat\components\login.py in check_login(self, uuid)
    135     data = re.search(regx, r.text)
    136     if data and data.group(1) == '200':
--> 137         if process_login_info(self, r.text):
    138             return '200'
    139         else:

C:\Users\yj\Anaconda3\lib\site-packages\itchat\components\login.py in process_login_info(core, loginContent)
    170     core.loginInfo['deviceid'] = 'e' + repr(random.random())[2:17]
    171     core.loginInfo['BaseRequest'] = {}
--> 172     for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
    173         if node.nodeName == 'skey':
    174             core.loginInfo['skey'] = core.loginInfo['BaseRequest']['Skey'] = node.childNodes[0].data

C:\Users\yj\Anaconda3\lib\xml\dom\minidom.py in parseString(string, parser)
   1966     if parser is None:
   1967         from xml.dom import expatbuilder
-> 1968         return expatbuilder.parseString(string)
   1969     else:
   1970         from xml.dom import pulldom

C:\Users\yj\Anaconda3\lib\xml\dom\expatbuilder.py in parseString(string, namespaces)
    923     else:
    924         builder = ExpatBuilder()
--> 925     return builder.parseString(string)
    926 
    927 

C:\Users\yj\Anaconda3\lib\xml\dom\expatbuilder.py in parseString(self, string)
    221         parser = self.getParser()
    222         try:
--> 223             parser.Parse(string, True)
    224             self._setup_subset(string)
    225         except ParseEscape:

ExpatError: no element found: line 1, column 0

**Comment by littlecodersh** [comment]
@18612790635 试一下删掉pkl文件。

**Comment by nan999** [comment]
> @18612790635 试一下删掉pkl文件。
pkl文件怎么找

**Comment by hjing100** [comment]
我的显示：
Traceback (most recent call last):
  File "D:\software\Anaconda36\Anacondasoftware36\lib\site-packages\itchat\components\hotreload.py", line 21, in dump_login_status
    with open(fileDir, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: './logs/loginInfo.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/python_project/28-19Knowledge_Graph_of_zhuxian/03KBQA/KBQA-for-Diagnosis-main/itchat_app.py", line 59, in <module>
    itchat.auto_login(hotReload=True, enableCmdQR=2, statusStorageDir='./logs/loginInfo.pkl')
  File "D:\software\Anaconda36\Anacondasoftware36\lib\site-packages\itchat\components\register.py", line 33, in auto_login
    self.dump_login_status(statusStorageDir)
  File "D:\software\Anaconda36\Anacondasoftware36\lib\site-packages\itchat\components\hotreload.py", line 25, in dump_login_status
    raise Exception('Incorrect fileDir')
Exception: Incorrect fileDir

**Comment by LX162** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zhaohuiwei1990** [comment]
您好，我已收到您的邮件，会尽快回复！

**Comment by hjing100** [comment]
> 我的显示： Traceback (most recent call last): File "D:\software\Anaconda36\Anacondasoftware36\lib\site-packages\itchat\components\hotreload.py", line 21, in dump_login_status with open(fileDir, 'w') as f: FileNotFoundError: [Errno 2] No such file or directory: './logs/loginInfo.pkl'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "D:/python_project/28-19Knowledge_Graph_of_zhuxian/03KBQA/KBQA-for-Diagnosis-main/itchat_app.py", line 59, in itchat.auto_login(hotReload=True, enableCmdQR=2, statusStorageDir='./logs/loginInfo.pkl') File "D:\software\Anaconda36\Anacondasoftware36\lib\site-packages\itchat\components\register.py", line 33, in auto_login self.dump_login_status(statusStorageDir) File "D:\software\Anaconda36\Anacondasoftware36\lib\site-packages\itchat\components\hotreload.py", line 25, in dump_login_status raise Exception('Incorrect fileDir') Exception: Incorrect fileDir

我的版本是1.3.10
