### ISSUE TITLE
主动发送群消息和下线发送消息的方法

### ISSUE THREAD

**Issue by CapGhost** [littlecodersh/ItChat#472]
1.主动给群发送一条消息，我是这样写的
chatroomList=itchat.get_chatrooms()
	if chatroomList:
		chatroomList[0].send(msg)
但是如果想同时给两个群发，就是这样
chatroomList=itchat.get_chatrooms()
	if chatroomList:
		chatroomList[0].send(msg)
		chatroomList[1].send(msg)
我想问一下，为什么chatroomList[0:]send()是无效的？必须要chatroomList[0]，chatroomList[1]这样写才行？

2.通过手机端断开下线时，想给群主动发一条信息表示机器人下线，应该如何处理？

谢谢了

**Comment by zl074081027** [comment]
`chartrooms = itchat.get_chatrooms()
    for room in chartrooms:
       itchat.send('text...', toUserName=room['UserName'])`

这样写就可以了 @CapGhost

**Comment by CapGhost** [comment]
谢谢，原来得利用for循环输出。。。。我对列表的理解不到位啊。。。

**Comment by Changgg** [comment]
第二条的话，你可以这样。在手机端给文件传输助手发送文本消息，机器人接到文件传输助手的文本消息作为指令来操作。比如你可以编码当机器人收到“立即离线”就在群里发送机器人离线通知并请求离线api。

**Comment by CapGhost** [comment]
谢谢下线的思路。
但是我打算设计下线发消息的目的，主要是担心掉线或其他情况导致的机器人下线，因此想下线前发送一条消息，表示机器人离线。而不是为了主动下线做提示。。。。

**Comment by Changgg** [comment]
机器人下线的话已经失去发消息的权限了。。不过，，有个http://sc.ftqq.com/3.version 这个的话可以用get请求给微信发消息，，你可以在收到消息后用另外一个微信机器人发消息。

**Comment by CapGhost** [comment]
感谢指导。

**Comment by XuDaShu** [comment]
我想问下 我在	itchat.auto_login(enableCmdQR=2,hotReload=True,exitCallback=majia)
里边写了 一个 exitCallback=majia,这样的的话不是退出机器人后会执行 majia() 这个函数么?可是我并没有得到执行结果
