### ISSUE TITLE
使用itchat.login()，如果不扫描二维码而直接关闭，隔一段时间会自动弹出二维码，请问为什么，如何避免？ 

### ISSUE THREAD

**Issue by CloveAI** [littlecodersh/ItChat#474]
在提交前，请确保您已经检查了以下内容!

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ ] 我已经阅读并按[文档][document] 中的指引进行了操作
- [ ] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [ ] 本问题确实关于`itchat`, 而不是其他项目.
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

您的itchat版本为：`[在这里填写版本号]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> [您的内容]

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by littlecodersh** [comment]
@CloveAI 因为二维码过期了自动加载了新的。
你可以通过自定义qrCallback关闭默认的弹出二维码，这里给你一个flask二维码的简单示例：

```python
import threading

from flask import Flask, make_response
import itchat

qrSource = ''

def start_flask():
    flaskApp = Flask('itchat')
    @flaskApp.route('/')
    def return_qr():
        if len(qrSource) < 100:
            return qrSource
        else:
            response = make_response(qrSource)
            response.headers['Content-Type'] = 'image/jpeg'
            return response
    flaskApp.run()
flaskThread = threading.Thread(target=start_flask)
flaskThread.setDaemon(True)
flaskThread.start()

def qrCallback(uuid, status, qrcode):
    if status == '0':
        global qrSource
        qrSource = qrcode
    elif status == '200':
        qrSource = 'Logged in!'
    elif status == '201':
        qrSource = 'Confirm'
itchat.auto_login(True, qrCallback=qrCallback)
@itchat.msg_register(itchat.content.TEXT)
def reply_text(msg):
    return msg['Text']

itchat.run()
```

**Comment by Nijisakai** [comment]
太棒了~谢谢
