### ISSUE TITLE
傻黑新一枚，想想知道itchat怎么发送图片。

### ISSUE THREAD

**Issue by Thinkor** [littlecodersh/ItChat#475]
例如我本地有一个1.png
我怎么用itchat发给别人呢？

**Comment by xiaoxiaoyao** [comment]
itchat.send_image(你要发的图片文件, '你要发给谁？')
@Thinkor

**Comment by coogerchou** [comment]
老铁，为啥我按照文档（当然也和这里的答案一致），发送图片时遇到这个问题，显示 KeyError: 'webwx_data_ticket'。发送简单的消息“hello world”是没有问题的。。我用的python 3.6； itchat-1.3.9
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-92-44217afe26df> in <module>()
      6 file = try_draw('ab')
      7 itchat.send_msg("hello world.",'filehelper')
----> 8 itchat.upload_file(file, 'filehelper')
      9 
     10 

/Users/cooger/anaconda/lib/python3.6/site-packages/itchat/components/messages.py in upload_file(self, fileDir, isPicture, isVideo, toUserName, file_, preparedFile)
    329     for chunk in range(chunks):
    330         r = upload_chunk_file(self, fileDir, fileSymbol, fileSize,
--> 331             file_, chunk, chunks, uploadMediaRequest)
    332     file_.close()
    333     if isinstance(r, dict):
/Users/cooger/anaconda/lib/python3.6/site-packages/itchat/components/messages.py in upload_chunk_file(core, fileDir, fileSymbol, fileSize, file_, chunk, chunks, uploadMediaRequest)
    352         ('mediatype', (None, fileSymbol)),
    353         ('uploadmediarequest', (None, uploadMediaRequest)),
--> 354         ('webwx_data_ticket', (None, cookiesList['webwx_data_ticket'])),
    355         ('pass_ticket', (None, core.loginInfo['pass_ticket'])),
    356         ('filename' , (os.path.basename(fileDir), file_.read(524288), 'application/octet-stream'))])

KeyError: 'webwx_data_ticket'
