### ISSUE TITLE
多开怎么具体实现,需要两个微信号么

### ISSUE THREAD

**Issue by XuDaShu** [littlecodersh/ItChat#477]
在提交前，请确保您已经检查了以下内容!

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ ] 我已经阅读并按[文档][document] 中的指引进行了操作
- [ ] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [x] 本问题确实关于`itchat`, 而不是其他项目.
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

您的itchat版本为：`[1.3.8]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> [您好,首先十分感谢您编写这个库,然后我有个问题想请教一下:
1.关于多开,这个怎么实现,知需要仿照文档里边的内容添加到原有的代码里就好了么?
]

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by ximply** [comment]
开多个机器人就可以了，每个都是不同的号

**Comment by Dashu-Xu** [comment]
就是说需要两个微信号

**Comment by littlecodersh** [comment]
@Dashu-Xu 对的
