### ISSUE TITLE
chatroom member fetch failed

### ISSUE THREAD

**Issue by qiusugang** [littlecodersh/ItChat#478]
个人对个人聊天可以收到，群里的信息只收到以下错误：
chatroom member fetch failed with @0a836af4242dd9acaed1592956cbc826

itchat版本： 1.3.9

如何解决？

**Comment by xufan6** [comment]
有类似情况，1.3.9。修改群名称后恢复

**Comment by xin053** [comment]
遇到相同的问题，程序监听群聊的消息并返回相应的消息，程序运行一段时间后，后台输出：
chatroom member fetch failed with @9c0c8581f60dea52dee23c4dbeaa843e4880f4e1142c7ed6082558120f7fc63
然后程序收不到群聊的信息，只有修改群聊名之后才能继续收到，一天大概出现3次左右这样的问题，现在每次都是通过修改群聊名解决的，但是过段时间还是会出现相同问题。

itchat版本: 1.3.9 群聊已收藏到通讯录

**Comment by yanlee26** [comment]
`chatroom member fetch failed with @595434e02f221276e7ae845773081fbe6ae76c80981f8ff23779907892050b73`

**Comment by magneter** [comment]
同样有这个问题。在看大家怎么解决
