### ISSUE TITLE
请问如果第一次扫码登陆后，然后手机微信断网，还能继续使用吗

### ISSUE THREAD

**Issue by PHPower** [littlecodersh/ItChat#479]
请问如果第一次扫码登陆后开始群发消息，然后手机微信断网，还能继续发送吗，如果此时我再扫码登录web微信会不会自动关闭了第一次的功能

**Comment by xiaoxiaoyao** [comment]
实践证明，没啥问题，发送和手机无关，只要程序开着就OK。再次扫码登录会把程序踢下去

**Comment by PHPower** [comment]
那就是上一次的就失效了是吧

**Comment by xiaoxiaoyao** [comment]
对的 @PHPower
