### ISSUE TITLE
好几个函数不懂用法

### ISSUE THREAD

**Issue by featheraaa** [littlecodersh/ItChat#48]
create_chatroom(self, memberList, topic = ''): topic是什么呀
add_friend(self, status, userName, ticket): 这个函数如何传参？
谢谢了，哈哈

**Comment by littlecodersh** [comment]
@featheraaa 
topic是chatroom的名字
add_friend需要的三个参数都被存在了好友申请消息产生的msg的Text键值中了，所以可以这么用：
```python
@itchat.msg_register('Friends')
def add_friend(msg):
    itchat.add_friend(**msg['Text'])
    itchat.send_msg('Nice to meet you!', msg['RecommendInfo']['UserName'])
```

**Comment by featheraaa** [comment]
@littlecodersh 
哦，我知道了，还以为是主动加好友呢，哈~

**Comment by littlecodersh** [comment]
@featheraaa 好的

**Comment by featheraaa** [comment]
@littlecodersh 
create_chatroom 创建出来的群是否自动 保存在 通讯录的群组里
因为有时候 手机上创建群聊的时候 会把创建的群不保存在 通讯录的群组里

**Comment by littlecodersh** [comment]
@featheraaa 不会的
