### ISSUE TITLE
在jupyter notebook中调用的问题

### ISSUE THREAD

**Issue by luofan18** [littlecodersh/ItChat#484]
如果在jupyter notebook里调用，登录时二维码的颜色是反的，即黑的变成了白的，白的变成了黑的，需要把二维码选中，像选中文字一样，颜色就正过来了

**Comment by mapleflow** [comment]
应该先生成二维码图片，然后图片的src输出到网页上。

**Comment by littlecodersh** [comment]
@luofan18 参数用-1即可，可以看一下README。
