### ISSUE TITLE
itchat.create_chatroom创建群聊失败

### ISSUE THREAD

**Issue by featheraaa** [littlecodersh/ItChat#49]
print itchat.create_chatroom(itchat.get_contract(),"lll2l")
是空

**Comment by littlecodersh** [comment]
@featheraaa 那你想让他返回什么？

**Comment by featheraaa** [comment]
@littlecodersh 
返回创建的群名 lll2l 和群id
创建后手机端没有这个群，是不是我弄错了，还是少做了什么？

**Comment by littlecodersh** [comment]
@featheraaa 你有多少个好友？

**Comment by featheraaa** [comment]
def create_chatroom(self, memberList, topic = ''):
        url = ('%s/webwxcreatechatroom?pass_ticket=%s&r=%s'%(
                self.loginInfo['url'], self.loginInfo['pass_ticket'], int(time.time())))
        params = {
            'BaseRequest': self.loginInfo['BaseRequest'],
            'MemberCount': len(memberList),
            'MemberList': [{'UserName': member['UserName']} for member in memberList],
            'Topic': topic, }
        headers = {'content-type': 'application/json; charset=UTF-8'}

        r = self.s.post(url, data=json.dumps(params),headers=headers)
        dic = json.loads(r.content.decode('utf8', 'replace'))
        return dic['ChatRoomName']
最后一句好像在说会返回 群名，
我有四十三个好友，我知道超过四十个就很难了
但 itchat.create_chatroom(itchat.get_contract()[:7],"lll2l")
也没有什么效果，不知道是不是微信又更新了

**Comment by tempdban** [comment]
感觉创建群这方面的疑问好多，这周如有空，我走查一下这部分代码。。。。。。。。。。

**Comment by littlecodersh** [comment]
@featheraaa 那个返回的是群的userName
你在创建群聊的时候不能把自己的userName也放进需要拉进群聊的人里面
简而言之就是itchat.create_chatroom(itchat.get_contract()[1:7], 'lll2l')

**Comment by littlecodersh** [comment]
@tempdban 群聊我一直在用，有问题我应该第一时间就能发现，不过周末得更新一下文档了。
研究一下webwxsendappmsg吧，我在这个协议上面卡了很久了

**Comment by tempdban** [comment]
@littlecodersh okay，但是我最近发现挂了两天之后机器人会莫名的LOGOUT...

**Comment by littlecodersh** [comment]
@tempdban 估计是长时间没有消息交互就被微信后台清理掉了，我的演示机器人已经挂着一个多月了

**Comment by tempdban** [comment]
@littlecodersh 这就尴尬了，我是拿来跑监控的。。。这我还得设计一下。

http://www.2cto.com/Article/201601/486836.html.
这个接口现在明确能用嘛？
出现这个东西微信肯定会封

**Comment by littlecodersh** [comment]
@tempdban 
可以试试加我的演示微信号，然后设置不回复我演示微信号的消息，以及隔一段时间自动发送一条消息
我试了没成功，在乌云上面这个漏洞已经给公开了，可能已经修复了

**Comment by tempdban** [comment]
@littlecodersh 哈哈哈哈，我后来是拿扇贝的公众号，扇贝公众号它会自动回复。
