### ISSUE TITLE
能够接入微信运动

### ISSUE THREAD

**Issue by Yiguan** [littlecodersh/ItChat#492]
微信运动智能显示一周左右的步数，而且是以图表形式显示的。
能够接入微信运动接口，哪怕只是获得个人的历史运动数据！

**Comment by mapleflow** [comment]
想多了，这种数据一般是第三方或者硬件商才提供。

**Comment by ximply** [comment]
web版协议就那些，核对一下就知道哪些能做哪些不能做了
