### ISSUE TITLE
群聊中@isAt后台监听不到

### ISSUE THREAD

**Issue by zhaoyongtao** [littlecodersh/ItChat#494]
Windows在后台使用msg.isAt或msg.IsAt或msg['IsAt']   无法监听到群聊中的@的事件
Windows7 x64   Python3.5.3

Linux下正常

**Comment by littlecodersh** [comment]
@zhaoyongtao 你更新一下itchat版本到1.3.9

**Comment by hcchengithub** [comment]
目前 itchat v1.3.10 , msg.isAt 我查看都是 False 所以來自作者 demo 的這段 code 無反應
```
@itchat.msg_register(TEXT, isGroupChat=True)
def text_reply(msg):
    if msg.isAt:
        msg.user.send(u'@%s\u2005I received: %s' % (
            msg.actualNickName, msg.text))
```
還是有問題呀！是同一個問題嗎？

**Comment by zhaoyongtao** [comment]
我测试的在Windows下监听不到，在Linux环境下可以监听到。你可以在Linux环境跑下试试
