### ISSUE TITLE
itchat.send()中toUserName怎么指定任意一个好友？

### ISSUE THREAD

**Issue by lovelyfrog** [littlecodersh/ItChat#495]
我发现除了filehelper和weixin其他地好友根本不能指定，python2.7和3.5我试过了都不行，求大神解答

**Comment by ximply** [comment]
toUserName 应该是每次登陆都是不一样，登陆后自己根据微信昵称建立与toUserName的对应关系，然后自己再封装个根据昵称发送的接口，应该就可以实现了

**Comment by ximply** [comment]
filehelper weixin之类的是微信内建的，自然没有问题，除此之外貌似还有其他的一些号，你可以自行百度一下

**Comment by qianyitony** [comment]
用search_friends()先找到这个好友的信息，https://itchat.readthedocs.io/zh/latest/intro/contact/

这个function返回一个被包在List里的Dictionary，所以要拿到UserName应该是
search_friends()[0]['UserName']

**Comment by xmlxin** [comment]
可以通过微信昵称或者备注查找这个好友的信息，拿到UserName值

import itchat

itchat.auto_login()

print(itchat.search_friends(name = '臭妮子'))

print("Input name")
nickname = input()

itchat.send('Hello, filehelper', toUserName=nickname)

**Comment by xmlxin** [comment]
可通过备注或昵称查找好友信息的UserName

import itchat

itchat.auto_login()

print(itchat.search_friends(name = '要发送的好友昵称'))

print("Input name")
nickname = input()

itchat.send('Hello, filehelper', toUserName=nickname)

**Comment by TommyTunaToro** [comment]
我是这样写的。在前两位的基础上整合了一下lol
import itchat
itchat.auto_login(hotReload=True)

print("要查找的微信昵称")
nickname = input()

username = itchat.search_friends(name=nickname)[0]['UserName']

itchat.send('你要发送的文字',toUserName=username)
