### ISSUE TITLE
想请问一下，这个‘用户多开’是什么意思？现在很苦恼的事情就是想：pc端登录的时候不挤掉网页端，不知道这个‘用户多开’可不可以做到？

### ISSUE THREAD

**Issue by bixiang** [littlecodersh/ItChat#498]
在提交前，请确保您已经检查了以下内容!

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ ] 我已经阅读并按[文档][document] 中的指引进行了操作
- [ ] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [ ] 本问题确实关于`itchat`, 而不是其他项目.
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

您的itchat版本为：`[在这里填写版本号]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> [您的内容]

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by bixiang** [comment]
想请问一下，这个‘用户多开’是什么意思？现在很苦恼的事情就是想：pc端登录的时候不挤掉网页端，不知道这个‘用户多开’可不可以做到？

**Comment by ximply** [comment]
这个只能登陆一个吧，要嘛pc，要嘛web，微信那边限制的

**Comment by bixiang** [comment]
那有什么办法可以保持网页版一直在线吗？

**Comment by hellohongfu** [comment]
@bixxiang 你找到办法保持网页版一直在线了吗？

**Comment by bixiang** [comment]
没有

**Comment by liuluyeah** [comment]
想请假一下，如何实现多用户的登录，使用flask框架，网页中的二维码，不同用户都可以进行登录
