### ISSUE TITLE
itchat.search_friends获得的聊天对象根本没办法说话。

### ISSUE THREAD

**Issue by YangtseSu** [littlecodersh/ItChat#499]
author = itchat.search_friends(nickName='LittleCoder')[0]
author.send('greeting, littlecoder!')

我把LittleCoder换成了我微信好友里面的一个人，然后
author.send('睡觉')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'dict' object has no attribute 'send'

itchat.send也只能给filehelper说话，别人都不行。

**Comment by qianyitony** [comment]
Traceback (most recent call last):
File "", line 1, in 
AttributeError: 'dict' object has no attribute 'send'

你获取的author是个dict（字典）类型，不支持send方法
然后看一眼API：
`
def send(self, msg, toUserName=None, mediaId=None):
        ''' wrapped function for all the sending functions
            for options
                - msg: message starts with different string indicates different type
                    - list of type string: ['@fil@', '@img@', '@msg@', '@vid@']
                    - they are for file, image, plain text, video
                    - if none of them matches, it will be sent like plain text
                - toUserName: 'UserName' key of friend dict
                - mediaId: if set, uploading will not be repeated
            it is defined in components/messages.py
        '''
`
所以只要
`send('睡觉','你想发送给的人')`
应该就可以了

说实话search_friends()这方法怎么用我也没搞明白...

**Comment by YangtseSu** [comment]
我抄的代码是文档里面的。不好使。
实际上，我用send只有给filehelper才能发送，给别人发送都失败。

**Comment by qianyitony** [comment]
`
author = itchat.search_friends(nickName=u'LittleCoder')[0]
send('greeting, littlecoder!', author['UserName'])
`
不知道为什么search_friends返回的是一个包括在List里面的Dictionary，这样应该就可以了

**Comment by qianyitony** [comment]
author = itchat.search_friends(nickName=u'LittleCoder')[0] 
send('greeting, littlecoder!', author['UserName'])
不知道为什么search_friends返回的是一个被包在List里面的Dictionary，这样应该就行了

**Comment by yujiye** [comment]
import itchat

难道你from chat  import send?

omg
itchat.send(outcontent，userid)

send需要调用itchat的包

**Comment by YangtseSu** [comment]
@qianyitony
api变动了，文档跟不上了。

**Comment by yujiye** [comment]
pip install itchat

**Comment by yujiye** [comment]
you can modify codes from libs/site-packages/itchat/.***.py

too simple
