### ISSUE TITLE
运行的时候提示AttributeError: 'module' object has no attribute 'msg_dealer'

### ISSUE THREAD

**Issue by qdhonker** [littlecodersh/ItChat#5]
/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 /Users/yzl/PycharmProjects/untitled/testitchat.py
Getting uuid
Please press confirmTERM environment variable not set.

Traceback (most recent call last):
Login successfully as ***
  File "/Users/yzl/PycharmProjects/untitled/testitchat.py", line 5, in <module>
    @itchat.msg_dealer(['Text', 'Map', 'Card', 'Note', 'Sharing'])
AttributeError: 'module' object has no attribute 'msg_dealer'

Process finished with exit code 1

提示没有msg_dealer属性是什么问题

**Comment by littlecodersh** [comment]
不好意思，这是我更新文档的疏忽。
在第二个版本里，注册的装饰器被命名为了更加容易理解的msg_register，但是README文档没有更新。
最新的文档更新版本可以见[这里](http://itchat.readthedocs.org/)
