### ISSUE TITLE
self.loginInfo中skey键未能赋值

### ISSUE THREAD

**Issue by littlecodersh** [littlecodersh/ItChat#50]
**两次报错：**
* @bibotai @237rxd 
* bibotai：在client.py中get_login_info(self, s)抓到的s是
```xml
<error><ret>1203</ret><message>check ticket failed</message></error>
```
* 237rxd：经过测试可以使用浏览器登录网页版微信

**报错信息：**
```python
Please press confirm
Traceback (most recent call last):
  File "ItChat.py", line 28, in <module>
    client.login()
  File "/Users/bibotai/tools/ItChat-robot/itchat/client.py", line 40, in login
    voidUserList = self.get_contract()
  File "/Users/bibotai/tools/ItChat-robot/itchat/client.py", line 147, in get_contract
    int(time.time()), self.loginInfo['skey'])
KeyError: 'skey'
```

**Comment by bibotai** [comment]
在client.py中get_login_info(self, s)抓到的s是：u'<error><ret>1203</ret><message>check ticket failed</message></error>'

**Comment by littlecodersh** [comment]
@bibotai 你尝试一下master分支，登陆后是否会出现问题？

**Comment by bibotai** [comment]
master分支没有尝试，网页版可以登录，我试了一下三个微信号有同样的问题，一个正常。

**Comment by tempdban** [comment]
未能复现

**Comment by littlecodersh** [comment]
@bibotai 可以抓包研究一下网页版微信成功登录的过程和itchat登陆的过程有什么区别。
如果方便，可以将有问题的微信号借一个给我，我这里做一个复现吗？

**Comment by bibotai** [comment]
可以借你一个微信号，告诉我一个私人微信号，或者邮箱沟通，bibotaixsf@msn.cn，这个项目很有意思，我愿意向你学习，共同研究。但我上班时间较忙，回家我在调试一下看看有没有更多的信息

**Comment by littlecodersh** [comment]
@bibotai 好的，多谢！

**Comment by 237rxd** [comment]
@littlecodersh 目前又可以正常登陆了，不知道是不是跟我的微信号频繁登陆有关？

**Comment by littlecodersh** [comment]
@237rxd 不清楚，就网上描述我只了解到是过段时间就可以登录的。
如果我能复现这个问题且网页微信可以登录的话，我会尝试修复这个Bug。

**Comment by 237rxd** [comment]
@littlecodersh 好的，多谢，最近我也会一直关注
