### ISSUE TITLE
AttributeError: module 'itchat' has no attribute 'auto_login

### ISSUE THREAD

**Issue by M737** [littlecodersh/ItChat#500]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\auto_aswer.py", line 2, in <module>
    import itchat
  File "C:\Users\Administrator\Desktop\itchat.py", line 3, in <module>
    itchat.auto_login(hotReload=True)
AttributeError: module 'itchat' has no attribute 'auto_login'
这个是什么问题？ 直接在IDLE运行就会提示这个(3.62版本)，把代码一步一步写在shell里或者在jupyter就可以运行.是版本兼容问题吗？

**Comment by XuDaShu** [comment]
这个问题我暂时不知道，不过建议把热登录关掉，容易被封

**Comment by M737** [comment]
知道问题了。  和模块同名 的原因

**Comment by felix-lj** [comment]
问题怎么解决的

**Comment by oyster0118** [comment]
> 知道问题了。 和模块同名 的原因

那怎么解决啊

**Comment by felix-lj** [comment]
命名一个和模块不一样的名字就可以了

**Comment by qazhw** [comment]
扯淡 你命名哪个和模块不同名字？？？骗人嘛不是

**Comment by troilus** [comment]
> 扯淡 你命名哪个和模块不同名字？？？骗人嘛不是

重命名py的名字， 不要写成itchat.py.....
