### ISSUE TITLE
创建群聊删除后仍能get_chatrooms到，但成员变了完全不认识，说明变成另一个群了

### ISSUE THREAD

**Issue by Ch1nny** [littlecodersh/ItChat#501]
不知道是微信的bug还是Itchat的bug
此外，我尝试了多次，有时isowner为0有时为1

删除群成员也是有时奏效，有时没反应，没有成功删除时也没有返回任何ErrMsg信息

**Comment by Ch1nny** [comment]
补充：将新群保存到通讯录后再取消保存，get_chatrooms仍将其计数，但显示群聊名字为空

**Comment by littlecodersh** [comment]
@Ch1nny update一下新群聊。

**Comment by littlecodersh** [comment]
@Ch1nny update一下新群聊。
