### ISSUE TITLE
手机扫描登录后就显示log out 了，求解

### ISSUE THREAD

**Issue by zdyGit** [littlecodersh/ItChat#502]
手机扫描登录以后，就提示下面的信息，然后程序就终止了。
------------------------------------------------------------------------
Login successfully as 
Start auto replying.
LOG OUT!
-----------------------------------------------------------------------
这是为什么啊，请大神指教

**Comment by littlecodersh** [comment]
@zdyGit 现在还有这个问题吗？

**Comment by BibuYing** [comment]
我是删除目录里的itchat.pkl文件，就可以正常登录了

**Comment by zdyGit** [comment]
后来发现取消login的参数hotReload=True,就没那个问题了@littlecodersh

**Comment by littlecodersh** [comment]
@zdyGit 好的
