### ISSUE TITLE
无法获取用户固定的唯一标识

### ISSUE THREAD

**Issue by hello-earth** [littlecodersh/ItChat#504]
但是无法获取用户固定的唯一标识，没办法识别用户身份，所有持久化功能都无法实现，所以.........
嗯  想做的都无法实现

**Comment by mapleflow** [comment]
能做个小玩意而已。

**Comment by wangke0809** [comment]
给好友设置备注，自己定义一个唯一标识怎么样？提供个思路。

**Comment by hello-earth** [comment]
可以设置备注， 但是在好友数量庞大到几千人的时候，登录时无法获取全部好友数据

**Comment by gmadong** [comment]
我就是改备注的 我的2000人都是全部获取的
