### ISSUE TITLE
用户查找

### ISSUE THREAD

**Issue by nlrabbit** [littlecodersh/ItChat#508]
您好，
请问itchat.search_friends()这个功能是从好友列表里查找某特定用户么？
请问itchat是否有根据某帐号（QQ号码、手机号码）搜索用户（即已知一个手机号或者QQ号，查找是否存在用此号码注册的微信用户）、“添加好友” 的功能？谢谢

您的itchat版本为：`[1.3.9]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

**Comment by littlecodersh** [comment]
@nlrabbit 没法通过qq和手机号搜索，只支持搜索昵称。
