### ISSUE TITLE
关于下载附件的内容

### ISSUE THREAD

**Issue by djjeng77** [littlecodersh/ItChat#509]
测试过下载附件的语音，图片都没有问题。
但是下载的视频是个0kb大小的文件。
完全无法播放。
下面是下载代码
path = 'd:\\wx_client\\res_' + str(itchat.search_friends()['Uin'])
        data['fileName'] = msg.fileName
        isExists = os.path.exists(path)
        print(isExists)
        if isExists is False:
            os.makedirs(path)
        msg.download(path + '\\' + msg.fileName)

**Comment by littlecodersh** [comment]
@djjeng77 这是目前网页版的问题，网页版的视频下载接口有事就是不可用的。
