### ISSUE TITLE
你好，请问无法登陆web微信怎么解决？

### ISSUE THREAD

**Issue by coolmaxz** [littlecodersh/ItChat#510]
手机登录之后并没有被冻结帐号。
当前登录环境异常。为了你的帐号安全，暂时不能登录web微信。你可以通过手机客户端或者windows微信登录。

微信版本6.5.15
itchat版本1.3.9

Your wechat account may be LIMITED to log in WEB wechat, error info:
<error><ret>1203</ret><message>当前登录环境异常。为了你的帐号安全，暂时不能登录web微信。你可以通过手机客户端或者windows微信登录。</message></error>

**Comment by doylecnn** [comment]
同样遇到这个问题
感觉开发这边没法解决……
也许要先用桌面版“养”一整子小号才行……

**Comment by 2788** [comment]
貌似就是封了  这里封号指的是web微信,手机端是可以用的

**Comment by doylecnn** [comment]
@2788 养也没用了吗？叹气……没那么多手机号去开微信小号啊……

**Comment by 2788** [comment]
@doylecnn  我看了相关的项目下面的issue, 到目前为止并没有解决方案,如果被封了. 没有解封的方法 不过也不用担心 手机端是能用的 web不能.   养小号哪有这么多手机号开小号啊

**Comment by GitOffice** [comment]
@2788 请问封号了,那就是说itchat机器人功能就没法用了?并且要求是常登录状态?

**Comment by dorispan** [comment]
新注册的账号也不能登录了？
“为了你的帐号安全，新注册的微信号不能登录网页微信”
没有解法吗？

**Comment by 2788** [comment]
@dorispan  目前没有办法,我劝你还是别折腾这个了,我现在都准备不玩这个了, 最近比较严了,很多人反应被封号, 而且前两天已经对新号进行了处理,不让新号登录web微信了,老号没有影响,但是封号的风险很大.

**Comment by yafz** [comment]
微信团队管的太严啦，不好玩，还是玩Slack去～💔

**Comment by SeekPoint** [comment]
我的是老号也是这样，而且两三个都是
