### ISSUE TITLE
 不要用最新版的requests

### ISSUE THREAD

**Issue by featheraaa** [littlecodersh/ItChat#512]
测试了一下2.3以上版本的requests 会出 yi 常

**Comment by littlecodersh** [comment]
@featheraaa 我用[2.18.4][requests]测的，是报了什么异常？

[requests]: https://github.com/requests/requests/releases/tag/v2.18.4

**Comment by mapleflow** [comment]
你应该把你的环境说清楚点, os python requirements , 你这么说很误导人的.

**Comment by featheraaa** [comment]
最新版本的requests连登录的二维码都不能获取 直接出问题

**Comment by featheraaa** [comment]
环境是windows 7

**Comment by fbigun** [comment]
碰到这种issue应该直接关闭。

**Comment by littlecodersh** [comment]
@featheraaa 把itchat和requests的版本号给我一下吧
```bash
python -m pip show itchat requests
```

**Comment by Chyroc** [comment]
无后续，关闭。
