### ISSUE TITLE
发送消息的时候，返回1024是什么原因？

### ISSUE THREAD

**Issue by ysnows** [littlecodersh/ItChat#514]
`{u'MsgID': u'', u'LocalID': u'', u'BaseResponse': {u'ErrMsg': u'', u'Ret': 1204, 'RawMsg': u''}}`

**Comment by littlecodersh** [comment]
@ysnows 频率或者登陆状态出了问题。

**Comment by ysnows** [comment]
ok,了解了，谢谢哈~
