### ISSUE TITLE
微信好友申请自动通过，通过关键词加群功能报错。

### ISSUE THREAD

**Issue by dockersky** [littlecodersh/ItChat#516]
刚刚启动时候好友申请，推送关键字加群，这个功能还好用。但一段时间后，添加好友不能自动通过，也不能通过关键字加群，后台报错：
itchat/itchat/components/contact.py", line 152, in update_local_chatrooms
    'UserName', oldChatroom['ChatRoomOwner']).get('Uin', 0)
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by littlecodersh** [comment]
@dockersky 微信后台回复数据出问题了，数据正常后就会正常。
