### ISSUE TITLE
你好版主！以前一直能登录的，最近好像出了问题。获取不了QR code，显示图片已移动或删除，再次尝试登录时状态也不正常，显示已成功登录，但其实二维码都不能扫。

### ISSUE THREAD

**Issue by Allison418** [littlecodersh/ItChat#519]
在提交前，请确保您已经检查了以下内容!

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ ] 我已经阅读并按[文档][document] 中的指引进行了操作
- [ ] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [ ] 本问题确实关于`itchat`, 而不是其他项目.
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

您的itchat版本为：`[在这里填写版本号]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> [您的内容]

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by Allison418** [comment]
第一次获取二维码不成功后，再次登录显示如下：
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Users\legend\Anaconda2\lib\site-packages\itchat\components\register.py", line 29, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback):
  File "C:\Users\legend\Anaconda2\lib\site-packages\itchat\components\hotreload.py", line 54, in load_login_status
    self.loginInfo['User'] = templates.User(self.loginInfo['User'])
KeyError: 'User'

**Comment by Allison418** [comment]
version: 1.3.9

**Comment by littlecodersh** [comment]
@Allison418 删除pkl文件或者不用hotReload登陆一次试试

**Comment by Allison418** [comment]
@littlecodersh 已经都试过了，还是不行。

**Comment by Allison418** [comment]
@littlecodersh 猜测是get_QRuuid或者get_QR出了问题。QR.png弹出来后说该文件可能已移动或重命名。

**Comment by Allison418** [comment]
@littlecodersh 可是为什么我另一台电脑也是这样？

**Comment by Allison418** [comment]
解决了。可能是上一次没有扫图片就走了，图片没有被删除导致之后一直不正常。
解决方法是到C:/SysWoW64里面删除QR.png，或者auto_login后手动打开更新的QR.png图片然后扫描。
图片被扫走后就恢复正常了。

**Comment by mapleflow** [comment]
那应该每次启动扫码前清除掉缓存来避免此类问题了。
