### ISSUE TITLE
请问，关于 MsgType: 51

### ISSUE THREAD

**Issue by qiu-xm** [littlecodersh/ItChat#521]
目前在尝试获得完整的群聊列表，在调试过程中，发现 get_msg (login.py) 方法获取到了一条 MsgType 为 51的消息，其中的 StatusNotifyUserName 字段可能是我想要的数据，但是在 update_local_uin (contact.py) 方法中，发现因为 msg['Content'] 为空获取不到 uins 值而没有对 StatusNotifyUserName  中的ID进行处理，此处是否有问题？谢谢

**Comment by littlecodersh** [comment]
@qiu-xm 的确是可以处理StatusNotifyUserName，不过51消息里的内容越来越少了，几乎不可用。
