### ISSUE TITLE
itchat.get_QR登陆问题

### ISSUE THREAD

**Issue by dan91ng** [littlecodersh/ItChat#529]
在用itchat.get_QR()登陆时无法使用start_receiving函数
代码：
import itchat
@itchat.msg_register(itchat.content.TEXT)
def text_reply(msg):
    return msg['Text']

#itchat.auto_login()
itchat.get_QR(itchat.get_QRuuid())
itchat.start_receiving()
itchat.run()

报错信息（片段）：
`Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\itchat\components\login.py", line 244, in maintain_loop
    i = sync_check(self)
  File "C:\Python27\lib\site-packages\itchat\components\login.py", line 289, in sync_check
    url = '%s/synccheck' % self.loginInfo.get('syncUrl', self.loginInfo['url'])
KeyError: 'url'`
已疯。如何正确使用get_QR？未找到相关文档，求解。

**Comment by qianyitony** [comment]
https://github.com/littlecodersh/ItChat/blob/master/itchat/components/login.py#L244
https://github.com/littlecodersh/ItChat/blob/master/itchat/components/login.py#L289
报错信息里显示是KeyError = ‘url’，一般指键值和变量不对应，所以还得找一下loginInfo.get的定义
然后我就没找着哪有loginInfo.get...但是他应该没有按预期输出一个字符串

**Comment by dan91ng** [comment]
找到其他方法解决了

**Comment by qinglinrao** [comment]
怎么解决的？
