### ISSUE TITLE
无法通过微信号查找好友

### ISSUE THREAD

**Issue by Shunsheng** [littlecodersh/ItChat#541]
我在使用`search_friends(wechatAccount=XXX)`查找制定微信号的好友时没有返回应有的结果。我看了一下`search_friends()`实现的代码，是通过好友`Alias`属性进行查找的，但通过`webwxgetcontact`接口获取的好友dict中，`Alias`是没有值的，请问
1.  是不是我应该在使用`search_friends()`之前应该添加什么步骤
2. itchat中获取好友微信号的具体实现接口是哪一个

以下是我的代码：
```python
import itchat
# import re, sys, json
# from itchat.content import *

itchat.auto_login(enableCmdQR=2)

 # get_friends(True)

while 1:

	print("Input name")
	nickname = raw_input()

	# print(itchat.search_friends(name=nickname))

	print(itchat.search_friends(wechatAccount=nickname))
```

**Comment by Shunsheng** [comment]
同时，我测试名片功能，发现接收到的名片消息内容中是不包含该名片用户的微信号的？

**Comment by Shunsheng** [comment]
我查到相关issue，表示现在已无法查看微信号。

**Comment by xmlxin** [comment]
确实无法通过微信号查找，可以通过备注或昵称查找

**Comment by hcchengithub** [comment]
wechatAccount=nickname 不對，你若曾把 msg dict dump 下來看就知道 wechatAccount 是個 dynamic ID 不是 nick name。  最好這樣用 ： search_friends('<nickname>')**

**Comment by xmlxin** [comment]
网页版快关停了 ，这个itchat也就不能用吧
