### ISSUE TITLE
机器人能否发送分享的链接？

### ISSUE THREAD

**Issue by yuanfengyun** [littlecodersh/ItChat#547]
如题，如果能，是否可以增加相关接口。

**Comment by Fmajor** [comment]
同求问
刚看了itchatmp的[doc](http://itchatmp.readthedocs.io/zh_CN/latest/apis/messages/)

> 标识符和具体的类型对应见下面：
> IMAGE: img
> VOICE: voc
> VIDEO: vid
> TEXT : txt
> CARD : cad
> MUSIC: msc

似乎是有card接口的?

**Comment by littlecodersh** [comment]
@yuanfengyun 微信后台限制了这个功能，所以目前没有办法。

@Fmajor itchatmp是有的，就是卡券接口，itchat没有。
