### ISSUE TITLE
关于msg_register这个装饰器的问题

### ISSUE THREAD

**Issue by qinyuanpei** [littlecodersh/ItChat#548]
在提交前，请确保您已经检查了以下内容!

- [ *] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ *] 我已经阅读并按[文档][document] 中的指引进行了操作
- [ *] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [* ] 本问题确实关于`itchat`, 而不是其他项目.
- [ *] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
W
python /home/qinyuanpei/文档/Python/WeChatAssistant/Main.py
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/register.py", line 66, in configured_reply
    r = replyFn(msg)
TypeError: handle_TextInput() takes exactly 2 arguments (1 given)
```

您的itchat版本为：`1.2.30`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

假设我希望将处理消息的逻辑封装到一个类中，且处理文本消息的方法为handle_TextInput，处理图片消息的方法为handle_PictureInput，这两个方法此时均为类实例的方法，并且在其内部调用了其它的类实例方法，即需要调用self，此时这两个方法就必须含有两个参数，即self和msg，可是msg_register这个装饰器定义的时候是1个参数，那么怎么样扩展出一个我自己的装饰器，可以支持两个参数呢？通过查找相关的资料，我大概了解了装饰器是个什么东西，下面是我写的一个版本：
```
def custom_msg_register(args):
        def register_wrapper(self,args):
            def register(args):
                itchat.msg_register(args)
            return register
        return register_wrapper
```
我的Python着实没有到达这样的深度，所以面对这个问题，我有点不知所措，请问能否稍微提示我一下，该如何去解决这样一个问题，谢谢，我的电子邮件是qinyuanpei@163.com，期望得到您的答复，再次表示感谢。

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by littlecodersh** [comment]
@qinyuanpei 不管具体怎么实现的话，你的想法落在使用上是怎么样的？
给我写一个演示代码吧。
