### ISSUE TITLE
itchat生成的二维码可以在命令行显示也可以通过扫描图片，但是不能从"识别图中二维码"识别？

### ISSUE THREAD

**Issue by cjj0596** [littlecodersh/ItChat#549]
如题，识别图中二维码是不是用其他方法来调用的？
因为扫一扫功能每次都可以登录网页微信，但是当成图片发给其他人，再长按使用“识别图中二维码”就说这个是无效二维码，这是正常的吗？还是我操作有误？

**Comment by ChiHoc** [comment]
识别二维码登录这个操作应该是微信客户端本身做了拦截。
二维码内容本身是类似这样的链接：https://login.weixin.qq.com/l/YZDTOzsukA==。
微信客户端扫码之后识别出是login.weixin.qq.com域名，会自动跳转到授权登录。
而识别二维码没有做这样的识别，相当于直接打开了这个页面。所有就会出现“无效二维码”字样。

**Comment by hcchengithub** [comment]
itchat 跑起來，擺了一夜沒做事，早上來實驗室一看，停掉了，錯誤訊息如下：
Unexpected sync check result: window.synccheck={retcode:"1102",selector:"0"}
LOG OUT!

- Windows 10
- Python 3.6 , 最單純的 DOSBox 下執行
- itchat 1.3.10
