### ISSUE TITLE
怎样主动给特定联系人发送消息？

### ISSUE THREAD

**Issue by KennethYeah** [littlecodersh/ItChat#55]
看了文档 基本都是被动的接收消息 并回复，怎么主动给别人发送消息呢？ send对象中怎么给username值？
我尝试用itchat.get_frineds(),但是返回值不知道怎么处理。

**Comment by littlecodersh** [comment]
@KennethYeah send的话传入目标用户的UserName，返回值你可以花时间阅读一下，这个没有什么技巧。

**Comment by hillerliao** [comment]
@KennethYeah 解决了吗？我也很想实现主动发送消息的功能，无从下手。

**Comment by littlecodersh** [comment]
@hillerliao 试试这个
```python
import itchat, time, threading

@itchat.msg_register('Text')
def text_reply(msg):
    print(msg['Text'])

def send_notification(nickName):
    memberList = itchat.get_friends(nickName = nickName)
    # if not full match, you may use this
    # memberList = filter(lambda m: nickName in m['NickName'], itchat.get_contract()[1:])
    for member in memberList:
        itchat.send('Now the time is: ' + time.strftime(
            '%y%m%d-%H%M%S', time.localtime()), member['UserName'])
        time.sleep(.5)
    time.sleep(3)

itchat.auto_login(True)

positiveSendingThread = threading.Thread(target=send_notification,
    args=('nickNameYouWant',))
positiveSendingThread.setDaemon(True)
positiveSendingThread.start()

itchat.run()
```

**Comment by KennethYeah** [comment]
@hillerliao 我通过另外的途径解决的
这里添加一个userlist 记录通讯用户名称，然后用户发送一个join给软件端，软件就把用户名记录下来。
主程序中另开一个线程，定时像这个列表中的所有用户发送消息。
userlist = []


class msg_deal(threading.Thread):
    def __init__(self):
        threading.Thread.__init__(self)

    def run(self):
        try:
            while 1:
                itchat.configured_reply()
                time.sleep(.1)
        except KeyboardInterrupt:
            print('Bye~')


class msg_send(threading.Thread):
    def __init__(self, userlist, stcd, stname):
        threading.Thread.__init__(self)
        self._userlist = userlist
        self.stcd = stcd
        self.stname = stname
        self.warning_time = {}
        for st in stcd:
            self.warning_time[st] = '2016-01-01 0:00:00'

    def run(self):
        connect = sqlite3.connect('data.db3')
        cursor = connect.cursor()
        sql = ("SELECT MAX(TM),Z FROM ST_RIVER_R WHERE STCD = ?")
        while True:
            warn_msg = []
            for key in self.stcd:
                try:
                    cursor.execute(sql, (key,))
                    info = cursor.fetchone()
                except BaseException as err:
                    print('SQL语句执行错误:', err)
                else:
                    water_time = info[0]
                    water = info[1]
                    if water > self.stcd[key] and water_time > self.warning_time[key]:
                        warn_msg.append(water_time + self.stname[key] + '%sm' % water)
                        self.warning_time[key] = water_time
            for _msg in warn_msg:
                for item in self._userlist:
                    itchat.send_msg(_msg, item)
            time.sleep(30)


@itchat.msg_register(['Text', 'Map', 'Card', 'Note', 'Sharing'])
def text_reply(msg):
    if 'quit' in msg['Text']:
        userlist.remove(msg['FromUserName'])
    elif 'join' in msg['Text']:
        userlist.append(msg['FromUserName'])
    else:
        itchat.send('%s' % msg['Text'], msg['FromUserName'])


@itchat.msg_register(['Picture', 'Recording', 'Attachment', 'Video'])
def download_files(msg):
    fileDir = '%s%s' % (msg['Type'], int(time.time()))
    msg['Text'](fileDir)
    itchat.send('%s received' % msg['Type'], msg['FromUserName'])
    itchat.send('@%s@%s' % ('img' if msg['Type'] == 'Picture' else 'fil', fileDir), msg['FromUserName'])


@itchat.msg_register('Friends')
def add_friend(msg):
    itchat.add_friend(**msg['Text'])
    itchat.get_contract()
    itchat.send_msg('Nice to meet you!', msg['RecommendInfo']['UserName'])


@itchat.msg_register('Text', isGroupChat=True)
def text_reply(msg):
    if msg['isAt']:
        if 'join' in msg['Content']:
            userlist.append(msg['FromUserName'])
        elif 'quit' in msg['Content']:
            userlist.remove(msg['FromUserName'])
        else:
            itchat.send(u'@%s\u2005I received: %s' % (msg['ActualNickName'], msg['Content']), msg['FromUserName'])


if __name__ == '__main__':
    itchat.auto_login(hotReload=True)
    print('开始自动回复')
    stcd = {'00010001': 4.4, '00010002': 4.6, '00010003': 4.4}
    stname = {'00010001': '奥运桥', '00010002': '三联桥', '00010003': '东风河桥'}
    _msg_deal = msg_deal()
    _msg_send = msg_send(userlist=userlist, stcd=stcd, stname=stname)
    _msg_deal.start()
    _msg_send.start()
    _msg_deal.join()
    _msg_send.join()

**Comment by KennethYeah** [comment]
@hillerliao 我通过另外的途径解决的
这里添加一个userlist 记录通讯用户名称，然后用户发送一个join给软件端，软件就把用户名记录下来。
主程序中另开一个线程，定时像这个列表中的所有用户发送消息。

**Comment by KennethYeah** [comment]
@littlecodersh 其实主要问题就是怎么知道这个确切的nickname，我想最好是能读用户的通讯录，然后返回通讯录里面每人的详细信息 比如微信名，微信号，昵称等。有了这些名称，使用itchat.send 语句就没有问题了。
还有就是：
 for member in memberList:
        itchat.send('Now the time is: ' + time.strftime('%y%m%d-%H%M%S', time.localtime()), member['UserName'])
        time.sleep(.5)
每次send后不加一个延时 好像容易漏发消息。我每次给两个用户发送两条消息，不加延时 就会出现接收不到消息的情况。

**Comment by KennethYeah** [comment]
@littlecodersh 其实主要问题就是怎么知道这个确切的nickname，我想最好是能读用户的通讯录，然后返回通讯录里面每人的详细信息 比如微信名，微信号，昵称等。有了这些名称，使用itchat.send 语句就没有问题了。
还有就是：
 for member in memberList:
        itchat.send('Now the time is: ' + time.strftime('%y%m%d-%H%M%S', time.localtime()), member['UserName'])
        time.sleep(.5)
每次send后不加一个延时 好像容易漏发消息。我每次给两个用户发送两条消息，不加延时 就会出现接收不到消息的情况。

**Comment by littlecodersh** [comment]
@KennethYeah 
通过以下命令可以获得完整的所有通讯录：
```python
itchat.get_contract()
```
如果需要获取某一个特定用户的信息，可以使用这个命令：
```python
itchat.get_friends(name = None, userName = None, remarkName = None, nickName = None, wechatAccount = None)
```
以上两个命令获取的用户信息包括微信名、微信号和昵称，对应键值分别为：NickName, Alias以及RemarkName
延时的话的确是这样，不加延时会因为调用太频繁而失败

**Comment by hillerliao** [comment]
@KennethYeah  我好想错过啥，你的回复删掉了代码？

**Comment by hillerliao** [comment]
@littlecodersh  `itchat.get_contract()` 无法获取通讯录里的群？

**Comment by hillerliao** [comment]
`nohup python test.py` 在nohup.out里会出现下面的错误信息

```
Traceback (most recent call last):
  File "test.py", line 71, in <module>
    itchat.auto_login(True)
  File "/Users/hillerliao/Nutstore/py-prj/test-prj/ItChat-autosend/itchat/__init__.py", line 9, in auto_login
    if __client.load_login_status(statusStorageDir): return
  File "/Users/hillerliao/Nutstore/py-prj/test-prj/ItChat-autosend/itchat/client.py", line 43, in load_login_status
    out.print_line('Login successfully as %s\n'%self.storageClass.nickName, True)
  File "/Users/hillerliao/Nutstore/py-prj/test-prj/ItChat-autosend/itchat/out.py", line 12, in print_line
    ).decode(sys.stdin.encoding or 'utf8', 'replace'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 22-24: ordinal not in range(128)
```

不带nohup没有问题

**Comment by littlecodersh** [comment]
@hillerliao 用get_chatrooms 吧

**Comment by hillerliao** [comment]
@littlecodersh 微信群ID似乎是一窜加密后的字符串，每次重新登录都不一样。

**Comment by littlecodersh** [comment]
@hillerliao 是的，和UserName类似

**Comment by simpleowen** [comment]
@littlecodersh 



itchat.get_friends 函数不带以下参数吧

> (name = None, userName = None, remarkName = None, nickName = None, wechatAccount = None)

源码：

```
def get_contact(self, update=False):
    if not update:
        return utils.contact_deep_copy(self, self.chatroomList)
    def _get_contact(seq=0):
        url = '%s/webwxgetcontact?r=%s&seq=%s&skey=%s' % (self.loginInfo['url'],
            int(time.time()), seq, self.loginInfo['skey'])
        headers = {
            'ContentType': 'application/json; charset=UTF-8',
            'User-Agent' : config.USER_AGENT, }
```

**Comment by littlecodersh** [comment]
@simpleowen 是的，我的笔误，是`search_friends`
