### ISSUE TITLE
往群里面发文件的时候文件的大小有限制了吗，怎么忽然发不了大于500K的文件了呢？

### ISSUE THREAD

**Issue by lily1982** [littlecodersh/ItChat#550]
您好，在利用ITCHAT给群里发送文档时，大于500K的文件忽然发不了了（以前是没问题的，就这几天不行了），也不报错，对于500K以下的文件发送还是正常的，我的python版本是2.7，itchat的版本是1.3.7，请问一下是哪里开始限制了吗？还是说ITCHAT版本要升级了？还是微信本身的问题？
发送的代码如下：
chatrooms[0].send_file(r'd:/aaa.doc')

**Comment by lily1982** [comment]
谢谢哈，我升级了一下ITCHAT到1.3.10版本，解决了，非常感谢！

**Comment by holybibles** [comment]
为什么我这新版本也是超过500k的图片发送失败。

**Comment by lily1982** [comment]
itchat版本是不是该更新了？我之前遇到过类似的问题，升级下itchat到最新版本就解决了




| |
lixiaoli60
|
|
邮箱：lixiaoli60@163.com
|

签名由 网易邮箱大师 定制

在2018年07月20日 10:32，holybibles 写道：

为什么我这新版本也是超过500k的图片发送失败。
