### ISSUE TITLE
网页版关停影响评估

### ISSUE THREAD

**Issue by isharer** [littlecodersh/ItChat#556]
在提交前，请确保您已经检查了以下内容!

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ ] 我已经阅读并按[文档][document] 中的指引进行了操作
- [ ] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [x] 本问题确实关于`itchat`, 而不是其他项目.
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

您的itchat版本为：`所有版本`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> [您的内容]
今天看到一个报道说，因为安全问题会逐步关停微信网页版。不知，该项目是否还可以继续使用，维护。报道地址：http://tech.ifeng.com/a/20171127/44778901_0.shtml
[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by ninikin** [comment]
是的。所以基于网页微信的机器人逐步要退出历史舞台了。

**Comment by conan1154** [comment]
不是腾讯已经出来辟谣了吗

**Comment by ligengdipan** [comment]
现在ItChat是不是不能用了，我这边一登陆就退出了。

**Comment by hcchengithub** [comment]
我剛試了還好的。有裝了 Wechat App 的 PC 有時候好像就不能玩 itchat ，這時直接用 Wechat 網頁版也會出現這個訊息：
<error><ret>1203</ret><message>為了你的帳號安全，新註冊的WeChat帳號不能登入網頁WeChat。你可以使用Windows WeChat或Mac WeChat在電腦端登入。 Windows WeChat下載網址：https://pc.weixin.qq.com  Mac WeChat下載網址：https://mac.weixin.qq.com</message></error>
同一個帳號改用 Ubuntu (沒有裝 WeChat App) 就好了，所以我猜是 WeChat App 排斥 WeChat Web 但時間上又不一定。

**Comment by hcchengithub** [comment]
即使 网页版关停 如果改由 WeChat App 提供 API 也不錯

**Comment by ligengdipan** [comment]
恩，谢谢，我之前用的一个微信账户其他功能正常，死活不能用ItChat登陆了，其他微信账号都行，这何解。

**Comment by hankzhaoo** [comment]
我的也是一登录就退出了
