### ISSUE TITLE
如何发送分享、链接（Sharing）类型的消息？

### ISSUE THREAD

**Issue by softshare** [littlecodersh/ItChat#557]
如题，发送文本、图片、文件、小视频都没有问题，但是分享类的消息如何发送？
已经查到msgtype=49，但是始终不知道怎么调用，万般尝试也没有效果，求助！

**Comment by ligengdipan** [comment]
请问你那边还能用机器人吗，我现在机器人连登陆都登录不聊了，求赐教。

**Comment by ctlPython** [comment]
你是被封了

**Comment by hcchengithub** [comment]
@ligengdipan 1） 直接上 WeChat Web 可以登入嗎？ 2）你這 PC 裝了 WeChat App 嗎？ 3）移除掉重開機後會不會好？

**Comment by littlecodersh** [comment]
@softshare 分享类消息是因为微信后台限制无法发送，目前没有解决方案。

**Comment by hh-1106** [comment]
现在可以发送了吗？
