### ISSUE TITLE
能否实现基于客户端协议重写ItChat

### ISSUE THREAD

**Issue by sskk741** [littlecodersh/ItChat#558]
在提交前，请确保您已经检查了以下内容!

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ ] 我已经阅读并按[文档][document] 中的指引进行了操作
- [ ] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [ ] 本问题确实关于`itchat`, 而不是其他项目.
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

您的itchat版本为：`[在这里填写版本号]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> [您的内容]
根据腾讯计划，网页版微信接口可能要关闭，能否实现基于微信客户端协议重写ItChat？

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by EncoderPtd** [comment]
我也看过微信手机客户端，其使用的是微信自己的mmtls协议来通信，基于tls改的。就目前来说，并没有任何办法可以分析其通信具体内容。有人有研究过有什么方式可以做吗？

**Comment by Cphilo** [comment]
+1 不过感觉这个难度太大，建议可以采用AccessibilityService的接口来做

**Comment by littlecodersh** [comment]
@sskk741 我没有这个技术，另外，写出来那样的项目肯定也是没法开源的。
