### ISSUE TITLE
騰訊新聞亂入，造成 itchat bot 卡住，怎避免？

### ISSUE THREAD

**Issue by hcchengithub** [littlecodersh/ItChat#559]
有人碰到這個問題嗎？
騰訊新聞亂入，造成 itchat bot 卡住。幸好按過 Ctrl-C 之後，還能繼續。
這怎避免？
目前機器正在跑，我晚點找機會把 itchat debug enable 起來看它怎麼說。。。。

**Comment by littlecodersh** [comment]
@hcchengithub 有进一步的报错吗？

**Comment by hcchengithub** [comment]
我發現亂入 itchat bot 的「騰訊新聞」可以關掉：
「我」 > 「設置] > 「通用」 > 「輔助功能」> 「騰訊新聞」 > 「停用」
