### ISSUE TITLE
当前登录环境异常。为了你的帐号安全，暂时不能登录web微信。你可以通过Windows微信、Mac微信或者手机客户端微信登录。

### ISSUE THREAD

**Issue by zhon9** [littlecodersh/ItChat#561]
已被禁止登陆，发消息发太多了，哈哈哈，大家注意

**Comment by ajun2006** [comment]
为什么用QQ浏览器的微信就可以登录呢？QQ浏览器的微信是不是跟web微信用的协议不同呢？

**Comment by hcchengithub** [comment]
@ajun2006 甚麼瀏覽器應該沒差, 你繼續用 IE 也是時好時壞吧? 我的理論是: 有裝了 "Windows WeChat" 的 PC 就有可能禁止 WeChat Web，您覺得是這樣嗎?

**Comment by littlecodersh** [comment]
@zhon9 这就是被检测出使用机器人的情况，只能等解封了，短的几天，长的半年。
