### ISSUE TITLE
怎么把分享链接回复出去啊？

### ISSUE THREAD

**Issue by jerry100chan** [littlecodersh/ItChat#562]
在提交前，请确保您已经检查了以下内容!

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ ] 我已经阅读并按[文档][document] 中的指引进行了操作
- [ ] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [ ] 本问题确实关于`itchat`, 而不是其他项目.
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

您的itchat版本为：`[在这里填写版本号]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> [您的内容]

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by littlecodersh** [comment]
@jerry100chan 目前由于微信后端限制，网页版微信无法发送分享链接。

**Comment by jerry100chan** [comment]
噢噢，酱紫啊。谢谢你的回复，谢谢。
------------------
你越想得到的东西，越是难得到、、、、、
 也许你改变一下方式，会有意想不到的效果，正所谓“总有一些收获源自你的选择”
                              命里有时总需有，命里无是莫强求


 




------------------ 原始邮件 ------------------
发件人: "LittleCoder";<notifications@github.com>;
发送时间: 2017年12月15日(星期五) 下午5:18
收件人: "littlecodersh/ItChat"<ItChat@noreply.github.com>;
抄送: "好好唱一首"<670809626@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [littlecodersh/ItChat] 怎么把分享链接回复出去啊？ (#562)




@jerry100chan 目前由于微信后端限制，网页版微信无法发送分享链接。
