### ISSUE TITLE
cannot send msg

### ISSUE THREAD

**Issue by 317687428** [littlecodersh/ItChat#564]
Recently (from last week) After scanning code to login successfully, it was always stuck there with no any progressing like generating pkl file or sending msg. Before it works normally. Any suggestion? Thanks in advance.

**Comment by hcchengithub** [comment]
Turn on the 'debug' switch and examine messages during your tests.
e.g. itchat.run(debug=True)

**Comment by 317687428** [comment]
@hcchengithub thank you for reply. i found that the method itchat.get_friends() didn't return any value, is it because the web wechat API was blocked?

**Comment by hcchengithub** [comment]
@317687428  itchat.get_friends() works but only the name=xxxxx argument works fine and it fits only *exact* nickName.

**Comment by 317687428** [comment]
@hcchengithub thanks, but it works normally by logging with another account.
