### ISSUE TITLE
續 #561 建議 itChat 的 send() 做 anti-robot 延遲

### ISSUE THREAD

**Issue by hcchengithub** [littlecodersh/ItChat#568]
即使 WeChat 是你家的，你也必定會禁止 user 用 itchat 這類的 Robot。你不想禁，總會有 user 搞到你不得不禁。原因是 Robot 若沒寫好，瞬間就可以產生海量的封包把你的 Server 搞死。

我同事建議我在 send() 任何東西前都留點 random 的 dely time (幾秒到十幾秒不等) 自我約束。
同時也可能因此避免被 server 端判定為 Robot 而對帳號下禁令, 人家不得不然。

> 当前登录环境异常。为了你的帐号安全，暂时不能登录web微信。你可以通过Windows微信、Mac微信或者手机客户端微信登录。 question
> #561 by zhon9 was closed 3 days ago

**Comment by shirubei** [comment]
我的帐号在去年月被封了，好几个月都一直没给解开。现在终于可以用了。根据楼上的解决方案，在send之前加一个15秒~50秒的随机时间以模拟通常的键盘输入
time.sleep(random.randrange(15,50))

**Comment by jjuu** [comment]
天啊，15秒的延迟！

**Comment by shirubei** [comment]
> @shirubei 目前这个方法还有效吗，有没有再次被封？

不好意思，许久没有过来这里逛了。还有用。后来我把数据调整到 15--35秒。太长了也等得烦，哈哈

**Comment by shirubei** [comment]
再啰嗦一句，记得当时试过，10秒都不一定安全，我的建议是15秒起步，最长多久可以随便。
