### ISSUE TITLE
怎么设置proxy

### ISSUE THREAD

**Issue by WestbyWei** [littlecodersh/ItChat#569]
由于在公司内网，无法连接weixin服务器，请问怎么加入代理？

**Comment by littlecodersh** [comment]
@WestbyWei vpn，或者其他代理

**Comment by kgbkgbkgb** [comment]
在公司内网是可以通过代理连接微信服务器的，步骤详见[老司机的简书](https://www.jianshu.com/p/daa5c41dbe3f)
