### ISSUE TITLE
能一直保持在线状态吗

### ISSUE THREAD

**Issue by yangyunxiao** [littlecodersh/ItChat#57]

**Comment by littlecodersh** [comment]
@yangyunxiao 能，如果需要长时间保持登陆的话建议与某个可以自动回复的公众号交互，否则会因为长时间没有消息被微信后台清理。

**Comment by KennethYeah** [comment]
@littlecodersh 一般大约多上时间不通讯会被清理

**Comment by littlecodersh** [comment]
@KennethYeah 目前没有找到具体的规律，大致在12h左右

**Comment by tylor-e** [comment]
难怪我总觉得挂一段时间就掉线了
