### ISSUE TITLE
好友发送的名片，自动发送添加好友申请失败

### ISSUE THREAD

**Issue by luminshiwo** [littlecodersh/ItChat#572]
在提交前，请确保您已经检查了以下内容!

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ ] 我已经阅读并按[文档][document] 中的指引进行了操作
- [ ] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [ ] 本问题确实关于`itchat`, 而不是其他项目.
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:
"D:\Program Files\Python36\python.exe" C:/Users/think/Desktop/myitchat.py
Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Loading the contact, this may take a little while.
Login successfully as ****
Start auto replying.
No uins in 51 message

[在这里粘贴完整日志]
@itchat.msg_register(itchat.content.CARD,isFriendChat = True)
def addFriend(msg):
    print(msg['Text'])
    print(msg['Content'])
    itchat.add_friend(userName = msg['Text']['UserName'])
    print(msg['RecommendInfo']['UserName'])

您的itchat版本为：`[1.2.32]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：
我发了一个名片过去，显示这样的信息：
{'UserName': '@718384279c6279fe405bac2ad3d2deb307c1edc76d872fb3e42c90b6f196dcae', 'NickName': '青藏源阿冲', 'QQNum': 0, 'Province': '广东', 'City': '广州', 'Content': '', 'Signature': '', 'Alias': '', 'Scene': 17, 'VerifyFlag': 0, 'AttrStatus': 32, 'Sex': 1, 'Ticket': '', 'OpCode': 0}
<?xml version="1.0"?>
<msg bigheadimgurl="http://wx.qlogo.cn/mmhead/ver_1/rG84hmLLOJZWE3fDyamDCGqvpphN2tLIiaTl2wxMeWlwAx0vYuQkwnZax36r8oBDE10YFkdFMUzWicJHKdjKGc4LmsDnWvp1xSkrW2M7Hw7HA/0" smallheadimgurl="http://wx.qlogo.cn/mmhead/ver_1/rG84hmLLOJZWE3fDyamDCGqvpphN2tLIiaTl2wxMeWlwAx0vYuQkwnZax36r8oBDE10YFkdFMUzWicJHKdjKGc4LmsDnWvp1xSkrW2M7Hw7HA/132" username="v1_ddf6c10fbb36ca2d8cd1f702c4cc70691e05797b78d28483bd1d20e8dec3b8b3ffb6e18f1905ecd0979302a748b635db@stranger" nickname="青藏源阿冲"  shortpy="QCYAC" alias="" imagestatus="3" scene="17" province="广东" city="广州" sign="" sex="1" certflag="0" certinfo="" brandIconUrl="" brandHomeUrl="" brandSubscriptConfigUrl="" brandFlags="0" regionCode="CN_Guangdong_Guangzhou" antispamticket="v2_6c9636bb3a49510e7c781dafebb348d77bcffa93daa044c182bab5c5aa8783f8a427c0dbf3cc3aca72b168c616a4b118@stranger" />
但是没有向“青藏源阿冲”发送好友申请。

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by howardhu** [comment]
我也遇到同样的问题，接收到名片后，add_friend后，对方没有收到好友请求。

**Comment by howardhu** [comment]
我手机上运行的微信版本为6.6.1

**Comment by howardhu** [comment]
@littlecodersh 能不能帮忙看看呢
下面是日志
[2018-01-02 22:34:01,135] urllib3.connectionpool:DEBUG: https://wx2.qq.com:443 "POST /cgi-bin/mmwebwx-bin/webwxverifyuser?r=1514903640&pass_ticket=roolpjetheyeoMlY5j%2FNOrjrlDaJJntMpSd4AgN3jfU%3D HTTP/1.1" 200 48
[2018-01-02 22:34:01,291] urllib3.connectionpool:DEBUG: https://wx2.qq.com:443 "POST /cgi-bin/mmwebwx-bin/webwxbatchgetcontact?type=ex&r=1514903641 HTTP/1.1" 200 491
[2018-01-02 22:34:01,541] urllib3.connectionpool:DEBUG: https://webpush.wx2.qq.com:443 "GET /cgi-bin/mmwebwx-bin/synccheck?r=1514903640713&skey=%40crypt_acd45b48_0d8191d7c06cba8cf4a67f919e52b42a&sid=N9sy7M2neaK2okQ7&uin=47623456&deviceid=e657104893725027&synckey=1_647980808%7C2_647981575%7C3_647981537%7C11_647972622%7C201_1514903640%7C1000_1514889002%7C1001_1514889074%7C1004_1514369498&_=1514903640713 HTTP/1.1" 200 43

**Comment by littlecodersh** [comment]
#574
