### ISSUE TITLE
如何让自动回复的功能在后台运行？

### ISSUE THREAD

**Issue by xdongz** [littlecodersh/ItChat#580]
@itchat.msg_register(itchat.content.TEXT)
def text_reply(msg):
    return msg.text

在运行itchat.run()之后，就开始了监听的模式。
请问如何让自动回复功能运行在子线程中，使得terminal中仍然能正常输出主线程的结果，只有当子线程被触发时才会输出自动回复的消息？

**Comment by littlecodersh** [comment]
@xdongz 如下命令不会阻塞主线程
```python
itchat.run(blockThread=False)
```
