### ISSUE TITLE
多选消息后合并转发, 怎么收到并获取这个内容?

### ISSUE THREAD

**Issue by gclsoft** [littlecodersh/ItChat#581]
多选消息后合并转发, 怎么收到并获取这个内容, 现在提示的是:"该类型暂不支持,请在手机上查看"
但是我用电脑版的微信就是支持的.
ItChat能不能支持获取合并转发?

**Comment by tiseheaini** [comment]
ItChat 是基于 微信 web 的 API，微信 web不支持的消息类型是没办法实现的。
好了，这个 issue 关了吧
