### ISSUE TITLE
怎么@其他人

### ISSUE THREAD

**Issue by FavorMylikes** [littlecodersh/ItChat#582]
version 1.3.10
怎么@其他人
怎么确定接受到的文本中的@有效

**Comment by qhzxc0015** [comment]
同问，可以发送@name，但是没有@效果代码是u'@%s\u2005 %'

**Comment by xinruoyusixian** [comment]
编码有问题吧我用的时候加@都起作用的(@%s %s)%(toUser,msg)

**Comment by FavorMylikes** [comment]
@xinruoyusixian 真的？你的toUser是群内昵称吗？

**Comment by aklnighaz** [comment]
@xinruoyusixian 请问能看看源码吗？！我试了都不行啊

**Comment by littlecodersh** [comment]
@FavorMylikes 只能形式上进行@，无法产生实际效果。

**Comment by fireairforce** [comment]
@fireairforce
