### ISSUE TITLE
itchat登录微信，如何实现远程扫码？

### ISSUE THREAD

**Issue by whan1234** [littlecodersh/ItChat#584]
最近在玩itchat，我已经把用户界面用html界面实现了，并且应用了flask框架，它可以是一个web应用。
但是，itchat的扫码登录环节，二维码是生成在python代码本地路径的，这样不管谁通过网络远程访问，二维码是显示在服务器端的。
前天查到了某位大神的文章：
https://juejin.im/post/5952153b6fb9a06bc3408036
他也用itchat做了不少功能，并且已经实现了远程用户扫码登录（有图有真相，可惜网站打不开了）。
所以这是可以实现的！但是我还是不知道怎么实现。
有没有大神可以指点思路一二？

**Comment by hcchengithub** [comment]
二維碼是個 .png 檔或文字檔，依你看能取得該檔是否就可以了？
取得該檔是可以的。

**Comment by whan1234** [comment]
道理没错。但是不改itchat不知道怎么实现。。。
> 二維碼是個 .png 檔或文字檔，依你看能取得該檔是否就可以了？
取得該檔是可以的。

**Comment by whan1234** [comment]
经过几天努力解决了这个问题。itchat的login函数里生成qr图片和扫码是在一起的，现在需要qr生成后返回一个response给远程用户，扫码后再进行后续登录处理，所以不改它是不行的。我把它拆成了两部分。

**Comment by hcchengithub** [comment]
@whan1234 您既然已經成功，方向自然很有價值。 
能再多提示一點點更好。

**Comment by bryant03** [comment]
@whan1234 请问大神是怎么拆开的，直接改的源代码么，我也有相同的问题。

**Comment by whan1234** [comment]
是的，改itchat的源代码。login函数拆成两部分，生成qr图片为界，先返回response，扫描成功后再后续处理。 @hcchengithub @bryant03 有兴趣可以关注公众号：常有自在心，我这个项目上线后欢迎试用~

**Comment by bryant03** [comment]
@whan1234 多谢提醒，我后来遇到一个问题，我是想做一个APP的微信登录，服务器后台生成二维码然后发给客户端扫描，然后登陆等等，但是后来发现图片发送到手机上后是不能调用微信扫一扫的，所以就放弃这个想法了。

**Comment by whan1234** [comment]
@bryant03 是的，我显示在电脑端，用手机扫电脑登录，是成功的。在手机上识别应该是不行的。

**Comment by bryant03** [comment]
@whan1234 是的，听说是为了防止盗号，必须打开摄像头扫描才行，非常遗憾，不得不弃坑了。

**Comment by LivenBom** [comment]
其实可以不用修改itchat的源代码就能获取登陆二维码，实现在web界面显示。
登陆二维码是由"https://login.weixin.qq.com/l/" + "uuid" 拼接而成的,而用户的uuid 在itchat框架中也是有对应的接口获取，所以你们懂的.....

**Comment by kesyupeng** [comment]
> 其实可以不用修改 itchat 的源代码就能获取登陆二维码，实现在 web 界面显示。
> 登陆二维码是由 "https://login.weixin.qq.com/l/"+"uuid" 拼接而成的，而用户的 uuid 在 itchat 框架中也是有对应的接口获取，所以你们懂的.....

我用itchat.get_QRuuid()方法获取的uuid附加到 "https://login.weixin.qq.com/l/"后面，再转为二维码，但是扫码登录不了，请问是我的操作有问题吗？
