### ISSUE TITLE
添加好友功能失效

### ISSUE THREAD

**Issue by MacmillanBIN** [littlecodersh/ItChat#585]
请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:
```
No uins in 51 message
```

itchat版本为：'1.3.10'。
此条函数运行后并未收到好友请求，网页版的微信好像也不能加好友了
itchat.add_friend(userName="@65635xxxxxxxxxxxxxxxxx7cd9f")
尝试过其他参数例如
itchat.add_friend("@65635xxxxxxxxxxxxxxxxx7cd9f", status=2, verifyContent='hello', autoUpdate=True)

均无反应 回应包为{'BaseResponse': {'Ret': -1, 'ErrMsg': '', 'RawMsg': ''}}

**Comment by MacmillanBIN** [comment]
有的可用 有的不可用 通过群聊获取群成员username
然后加好友

**Comment by rockiecxh** [comment]
我收到错误消息{u'BaseResponse': {u'ErrMsg': u'', u'Ret': -1, 'RawMsg': u''}}

**Comment by littlecodersh** [comment]
@MacmillanBIN 主动加好友现在次数限制很严重，另外，使用的UserName每次登陆会变化。
