### ISSUE TITLE
有没有办法让itchat收到链接时自动打开这个链接？

### ISSUE THREAD

**Issue by cc9200** [littlecodersh/ItChat#590]
我们在微信客户端，收到一个饿了么链接，点进去就可以收一个优惠券，这个优惠券自动放到与微信地址绑定的饿了么的账户里面去了。
请问如何让itchat实现这个   点进去   的功能？电脑端的浏览器打开微信里面的链接识别不到相应的微信号

**Comment by littlecodersh** [comment]
@cc9200 无法实现，根据描述该操作限定了在客户端完成。
