### ISSUE TITLE
命令行输出的二维码变形

### ISSUE THREAD

**Issue by fxc0719** [littlecodersh/ItChat#597]
在提交前，请确保您已经检查了以下内容!

- [x] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [x] 我已经阅读并按[文档][document] 中的指引进行了操作
- [x] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [x] 本问题确实关于`itchat`, 而不是其他项目.
- [x] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

您的itchat版本为：`[1.3.10]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> Mac平台，想在一些没有屏幕的平台运行，但是发现在命令行下的二维码变形,不正确

![](https://ws3.sinaimg.cn/large/006tNc79ly1foly33a1fhj30uc10m79b.jpg)

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by littlecodersh** [comment]
@fxc0719 尝试如下代码：
```python
# 部分的系统，块字符的宽度为一个字符（正常应为两字符），故赋值为2
itchat.auto_login(enableCmdQR=2)
```

**Comment by fxc0719** [comment]
目前mac系统正常的，感谢！

**Comment by shirubei** [comment]
Raspberry Pi的Debian系统上也正常了。

**Comment by Vxer-Lee** [comment]
`itchat.auto_login(enableCmdQR=2)`
这句代码 要加哪里呢？哪个文件上

**Comment by Vxer-Lee** [comment]
@emrysf
