### ISSUE TITLE
在linux运行出现FileNotFoundError的错误

### ISSUE THREAD

**Issue by Ronghengzhen** [littlecodersh/ItChat#599]
![snipaste_20180302_111051](https://user-images.githubusercontent.com/30968676/36881731-a8a8d8e6-1e0a-11e8-803e-82b871d5ad21.png)

**Comment by littlecodersh** [comment]
@Ronghengzhen 没有图形界面的话肯定没有安装xdg-open，建议使用命令行二维码

**Comment by Ronghengzhen** [comment]
怎么用？
