### ISSUE TITLE
登录出错

### ISSUE THREAD

**Issue by Licoy** [littlecodersh/ItChat#601]
在提交前，请确保您已经检查了以下内容!

- [x] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [x] 我已经阅读并按[文档][document] 中的指引进行了操作
- [x] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [x] 本问题确实关于`itchat`, 而不是其他项目.
- [x] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
Start auto replying.
Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Your wechat account may be LIMITED to log in WEB wechat, error info:
<error><ret>1203</ret><message>为了你的帐号安全，此微信号已不允许登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com</message></error>
Request to send a text message to filehelper: Hello, filehelper
```

您的itchat版本为：`[1.3.10]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> [登录的时候出错，出现如上提示]

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by zyxbcde** [comment]
Getting uuid of QR code.
Downloading QR code.
██████████████████████████████████████████████████████████████████████████████
██              ████        ██  ██████  ██    ████  ██  ██████              ██
██  ██████████  ████  ██  ██    ████████        ████  ████████  ██████████  ██
██  ██      ██  ██        ████      ██      ████████  ██    ██  ██      ██  ██
██  ██      ██  ██  ██  ████      ██  ██████  ██████        ██  ██      ██  ██
██  ██      ██  ████  ████████████  ██    ██████  ██    ██████  ██      ██  ██
██  ██████████  ██████  ████  ██  ██  ██  ██████  ████  ██████  ██████████  ██
██              ██  ██  ██  ██  ██  ██  ██  ██  ██  ██  ██  ██              ██
████████████████████  ██            ██████      ██    ██    ██████████████████
████████    ██    ██      ██    ██  ████████  ██  ██████████████████    ██████
████████  ██  ██    ████████████    ██████      ██    ██    ████      ██  ████
████            ██  ██      ██    ██  ██████    ████  ██        ████    ██  ██
████  ██      ██  ██      ██  ██████      ██  ████  ██    ██    ██      ██  ██
██  ██      ██      ██    ██████  ██  ██    ██████  ████    ██    ████      ██
████████      ██    ██        ████    ██    ██      ██        ████  ██  ██████
██████  ██  ██    ██████  ████  ██    ████    ██  ██  ██  ██    ██          ██
██  ██    ████████  ██████  ██████████████  ██  ████████  ██  ████        ████
██████            ██  ██████    ██████  ████      ██  ████  ██    ████  ██  ██
████      ██  ██████  ██    ██    ████  ████  ██      ██  ██  ██  ██████  ████
████    ██  ██        ██          ██      ████  ██  ████  ██████  ████  ██  ██
████  ██  ██████  ██  ██████  ██  ██    ████  ████    ██████  ██████  ████████
████  ██  ██    ██      ██    ██    ████  ██            ██      ██    ████████
██    ████████████        ██████    ████      ████    ██    ████    ██  ██████
████    ██  ██    ██  ██████  ██  ████████████  ██  ████  ████  ██  ██████  ██
██            ████    ██  ████      ████    ██      ██            ████    ████
██      ████    ████████        ██  ██      ██  ████    ██████  ██    ████  ██
██        ████████  ██    ██████████  ██      ████  ██          ██  ████  ████
██    ████        ██  ██████  ██  ██        ██  ████        ██    ██        ██
██  ██        ██████  ████  ████  ████  ████    ██  ██    ██  ████████  ██████
██  ████    ██      ██    ████  ██  ████    ██    ██  ██            ██  ██████
██████████████████  ██      ████    ████████  ████    ████  ██████        ████
██              ██  ██      ██  ████████████████    ██████  ██  ██      ██  ██
██  ██████████  ████████████    ██  ████████  ██        ██  ██████    ██  ████
██  ██      ██  ██      ████    ██    ████  ████    ████            ████  ████
██  ██      ██  ██  ██    ██████████    ██████████████      ██  ████  ████████
██  ██      ██  ████  ██████    ██    ████  ██  ██  ██  ██  ████            ██
██  ██████████  ██████  ██  ██████████    ████  ██████  ██████  ██  ██      ██
██              ████  ████  ██  ██    ██    ████████  ████  ██  ████  ████  ██
██████████████████████████████████████████████████████████████████████████████
Please scan the QR code to log in.
程序启动后二维码出现问题，并不能呈现一个正方形，每行长短不一，无法扫描。

**Comment by shirubei** [comment]
账号被冻结了

**Comment by Chyroc** [comment]
限制web登录了，参考：https://github.com/littlecodersh/ItChat/issues/651
