### ISSUE TITLE
No module named 'itchat.content'

### ISSUE THREAD

**Issue by cn163** [littlecodersh/ItChat#607]
在提交前，请确保您已经检查了以下内容!

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ ] 我已经阅读并按[文档][document] 中的指引进行了操作
- [ ] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [ ] 本问题确实关于`itchat`, 而不是其他项目.
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

您的itchat版本为：1.3.10。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> 
$pip3 list
certifi (2018.1.18)
chardet (3.0.4)
idna (2.6)
itchat (1.3.10)
pip (9.0.1)
pypng (0.0.18)
PyQRCode (1.2.1)
requests (2.18.4)
setuptools (28.8.0)
urllib3 (1.22)

import itchat,sys
from itchat.content import *

Traceback (most recent call last):
  File "./itchat.py", line 1, in <module>
    import itchat,sys
  File "/data/python/itchat.py", line 2, in <module>
    from itchat.content import *
ModuleNotFoundError: No module named 'itchat.content'; 'itchat' is not a package

**Comment by cn163** [comment]
通过运行python3 ./itchat.py报以上错误，如果直接在python3一行行运行就正常

**Comment by tukeyone** [comment]
同样的问题，求解

**Comment by CorkiZhang** [comment]
类似的问题，之前运行很正常，现在不知道就怎么报这种错误

**Comment by mcmuralishclint** [comment]
Hi, Did you solve this problem?

**Comment by 1320611670** [comment]
怎么通过python3一行运行
