### ISSUE TITLE
保持超长时间在线的疑问

### ISSUE THREAD

**Issue by pexcn** [littlecodersh/ItChat#610]
~~你好，刚关注这个项目，还没有用过。
有个疑问，想弃用微信，当别人发消息过来或者群里 @ 你的时候自动回复一句话。请问登录了之后可以保持长期在线吗？即使手机已经登出或者卸载微信。~~

**Comment by pexcn** [comment]
已经用上，有个疑问，扫码登录后，手机的客户端可以离线，而服务器端有没有必要每个几分钟向一个账号发一条消息来保持登录状态？这样有意义吗？https://github.com/pexcn/WeChatBot/commit/52eda5a5c65ee59f6930587da823ac40470f74c2

**Comment by xizirumeng** [comment]
天有不测风云，与其纠结保持在线，不如做好掉线重登。。。

**Comment by pexcn** [comment]
@xizirumeng 掉线重新登录不是需要扫二维码吗？能做成自动？

**Comment by xizirumeng** [comment]
把图片通过二维码发至你的邮箱不就行了

**Comment by pexcn** [comment]
好吧，果然还是没办法做成自动
