### ISSUE TITLE
登陆后通讯录内容错误

### ISSUE THREAD

**Issue by littlecodersh** [littlecodersh/ItChat#63]
@djtu 在Issue#1中提出，确认为bug故新建issue

## 原文

@littlecodersh @PeteLing 我的情况好像是一样的，这里是我测试的代码

**测试代码**
```python
@itchat.msg_register('Text')
def text_reply(msg):
    contracets = itchat.get_contract()
    for contract in contracets:
        info = itchat.get_friends(userName = contract['UserName'])
        print 'UserName:',contract['UserName'],'and NickName:',info['NickName']
    print 'msg-FromUserName:', msg['FromUserName']
    print 'msg-Content:', msg['Content']
    print 'itchat.get_contract()[1]-NickName:',itchat.get_contract()[1]['NickName']
    print 'itchat.get_contract()[1]-UserName:',itchat.get_contract()[1]['UserName']
```

**结果**
```bash
UserName: @9bfed77c63ea8e22f445489306bab0ba730ba8b4ba5672a561df2e1816e1c839 and NickName: 晨曦
UserName:   @ a4428b91ead7c17663bb087818335382  and NickName: 翩翩精品
UserName: @ 170e2fe33df1f1bee9379d3826bd5888  and NickName: 乐知-李刚
UserName: @17d427b3637b8ad570f9596fd337284b41af89b9518d0b80b4e1ad68588b65a5 and NickName: 囡囡
UserName: @ff7a9af23299a2edc017c5809af5934b96ab6f0e6c4b5b319066e31df3a99db7 and NickName: A 链家前程街店王红影13614268406
msg-FromUserName: @ 0506fd8606cae22de6eeedc9d252d885
msg-Content: 获取图片
itchat.get_contract()[1]-NickName: 翩翩精品
itchat.get_contract()[1]-UserName: @a4428b91ead7c17663bb087818335382
```

**问题分析**

其中“翩翩精品”的msg['FromUsername']: `@0506fd8606cae22de6eeedc9d252d885`
而itchat.get_contract()[1]-UserName: `@a4428b91ead7c17663bb087818335382`
两者不一样的，同时 send 消息给2个 UserName，只有msg['FromUsername']能收到信息，另一个send 失败。
不知道是我操作的问题，还是bug，希望帮忙解答！~谢谢

**Comment by littlecodersh** [comment]
@djtu 已复现问题，在满足以下条件的情况下会出现该问题
* 开启热拔插功能
* 存在过时不可用的itchat.pkl
初步估计是重载通讯录的时候出现的问题

**Comment by littlecodersh** [comment]
@djtu @PeteLing 已在[新的提交][new_commit]中修复该问题，非常感谢你们对这个项目的支持！

**测试用程序**
```python
import itchat

@itchat.msg_register('Text')
def text_reply(msg):
    print('Msg received: %s\nUserName: %s\nNickName: %s' % (
        msg['Text'], msg['FromUserName'], (itchat.get_friends(
        userName = msg['FromUserName']) or {}).get('NickName', 'NOT FOUND')))

itchat.auto_login(True)
for member in itchat.get_contract():
    print('UserName: %s, NickName: %s' % (
        member['UserName'], member['NickName']))
itchat.run()
```

**具体问题**

bug出现在热拔插的通讯录重载
由于即使加载热拔插不成功后通讯录也被赋值且未在登录中强制重载通讯录
本次更新同时修改了同样存在问题的聊天室与cookies重载

[new_commit]: https://github.com/littlecodersh/ItChat/commit/af7bb054cd1ef62f01e6431a78c07acf8741c004

**Comment by djtu** [comment]
@littlecodersh 刚测试下，用我自己的代码，结果还是一样的。之前执行的操作有：
pip install itchat --upgrade
git pull
两步都执行了，然后运行我的代码，还是一样的结果。 

运行@littlecodersh 代码结果也是不行
![111](https://cloud.githubusercontent.com/assets/4414532/17589125/80bcdde2-6005-11e6-9cbc-a77102af49a5.png)
Login successfully as 晨曦              
UserName: @9bfed77c63ea8e22f445489306bab0ba730ba8b4ba5672a561df2e1816e1c839, NickName: 晨曦
UserName: @a4428b91ead7c17663bb087818335382, NickName: 翩翩精品
UserName: @170e2fe33df1f1bee9379d3826bd5888, NickName: 乐知-李刚
UserName: @17d427b3637b8ad570f9596fd337284b41af89b9518d0b80b4e1ad68588b65a5, NickName: 囡囡
UserName: @ff7a9af23299a2edc017c5809af5934b96ab6f0e6c4b5b319066e31df3a99db7, NickName: A 链家前程街店王红影13614268406
Start auto replying
Msg received: [微笑]
UserName: @ 0506fd8606cae22de6eeedc9d252d885
NickName: NOT FOUND

其中用“翩翩精品”微信发的信息

**Comment by littlecodersh** [comment]
@djtu 你尝试输出一下版本号：
```python
print(itchat.__version__)
```

**Comment by djtu** [comment]
个人感觉好像有什么保存后没有更新，包括联系人列表，现在机器人号不止这几个好友，还有公众号

**Comment by tempdban** [comment]
@djtu itchat.pkl 删过么

**Comment by djtu** [comment]
@tempdban 这个要怎么删除呢，最好直接放到代码里

**Comment by littlecodersh** [comment]
@djtu 可能我这里复现出来的问题和你碰到的不是同一个
试试从空的环境开始从头做一次测试，把测试步骤记录一下给我吧
我这里之前做的测试步骤是这个：
* 清理环境（保证测试的初始运行环境可以相同）
* 新建[测试程序][test_program]
* 使用测试程序登陆微信
* 手机端推出微信
* 再次使用测试程序登录微信
* 测试是否有联系人错位的问题

[test_program]: https://github.com/littlecodersh/ItChat/issues/63#issuecomment-239104319

**Comment by djtu** [comment]
刚才又都更新了一下，提示获得二维码失败了

**Comment by littlecodersh** [comment]
@djtu 重试以后还是失败吗？

**Comment by djtu** [comment]
服务出了点问题，无法远程，等弄好了再测试，先别话呢issue 谢谢

**Comment by littlecodersh** [comment]
@djtu 好

**Comment by djtu** [comment]
把这个bug关掉吧，应该木问题了，我在windows测试通过了，linux服务器一直ssh链接不上，无法测试，不过应该没有问题了。非常感谢
