### ISSUE TITLE
如何解决被封问题

### ISSUE THREAD

**Issue by ymli1981** [littlecodersh/ItChat#632]
这个问题无解了吗？那还怎么玩？
网上有一些专门做群转发服务的商家，好像可以避免这个问题
他们是怎么实现的呢？

**Comment by ilovezqh** [comment]
这个问题 解封不就得了吗？ 好友辅助，网上专门做群转发的商家也是这个套路

**Comment by Chyroc** [comment]
类似 https://github.com/littlecodersh/ItChat/issues/651
