### ISSUE TITLE
itchat获取的信息中为什么没有微信号字段呢？

### ISSUE THREAD

**Issue by stevenluan07** [littlecodersh/ItChat#636]
itchat获取的信息中为什么没有微信号字段呢？
备注可以改、用户名可以改，微信号是不会改的。没有微信号就很麻烦。

**Comment by nikingstore** [comment]
同文，因为UserName貌似是动态的，现在只能每次用search_friends()查询，如果改名后，无法精准锚定某个用户，求解决方法.

**Comment by 1049451037** [comment]
类似的问题都在解决中：
https://github.com/littlecodersh/ItChat/issues/626
https://github.com/littlecodersh/ItChat/issues/653

**Comment by Chyroc** [comment]
类似 https://github.com/littlecodersh/ItChat/issues/605
