### ISSUE TITLE
添加表情包到微信？

### ISSUE THREAD

**Issue by foreverlms** [littlecodersh/ItChat#640]
如果能够实现自动添加一系列gif或者图片到微信表情包那就太好了。

**Comment by Chyroc** [comment]
如果是发送表情的功能，还可以考虑；添加表情包到微信，微信客户端也没这功能吧。

**Comment by coderchaser** [comment]
@Chyroc 是的，微信客户端都没有这功能，平时添加表情图片都得一张张得来。“发送表情图片”这个功能也很不错了！:laugh:

**Comment by coderchaser** [comment]
@GDoom 没有吧
