### ISSUE TITLE
登录后提示Logout

### ISSUE THREAD

**Issue by rodgu** [littlecodersh/ItChat#642]
Itchat版本：1.3.9
问题表述：登录后直接报Logout并退出
信息：Unexpected sync check result: window.synccheck={retcode="1100",selector:"0"}
代码很简单就是 
itchat.auto_login(hotLogin=True)    
itchat.run()
运行环境：windows 2012 server

**Comment by jbRotk** [comment]
问题解决了么

**Comment by Chyroc** [comment]
同 https://github.com/littlecodersh/ItChat/issues/619 ，关闭

**Comment by lifuqiang2016** [comment]
解决了吗？
