### ISSUE TITLE
author.send('greeting, littlecoder!')

### ISSUE THREAD

**Issue by good1uck** [littlecodersh/ItChat#643]
author = itchat.search_friends(nickName='LittleCoder')[0]
author.send('greeting, littlecoder!')

AttributeError: 'dict' object has no attribute 'send'

求解决方法

**Comment by lazyrong** [comment]
itchat.send('greeting, littlecoder!',toUserName = author.UserName)



lazytech@foxmail.com
 
From: Ivar
Date: 2018-04-23 17:36
To: littlecodersh/ItChat
CC: Subscribed
Subject: [littlecodersh/ItChat] author.send('greeting, littlecoder!') (#643)
author = itchat.search_friends(nickName='LittleCoder')[0]
author.send('greeting, littlecoder!')
AttributeError: 'dict' object has no attribute 'send'
求解决方法

**Comment by good1uck** [comment]
@lazyrong 
您的方法中
toUserName = author.UserName 依然报错 AttributeError: 'dict' object has no attribute 'send' ，
改成 author[toUserName='UserName']就成功了，不知道是不是我出的问题

**Comment by good1uck** [comment]
@lazyrong 我发现是itchat的版本问题...

更新到最新就没有任何问题了，这个issue不应该存在
