### ISSUE TITLE
关于回复消息包含超链接的问题

### ISSUE THREAD

**Issue by wuxubj** [littlecodersh/ItChat#655]
在提交前，请确保您已经检查了以下内容!

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ ] 我已经阅读并按[文档][document] 中的指引进行了操作
- [ ] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [ ] 本问题确实关于`itchat`, 而不是其他项目.
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

代码：
```
@itchat.msg_register([TEXT, MAP, CARD, NOTE, SHARING, PICTURE, RECORDING, ATTACHMENT, VIDEO], isMpChat=True)
def text_reply(msg):
	friends_list = itchat.get_friends(update=True)
	name = itchat.search_friends(name=u'小明')
	tuisong = "<a href='www.baidu.com'>百度</a>"
	XiaoMing = name[0]["UserName"]
	print(tuisong)
	itchat.send(tuisong, XiaoMing)
```
输出：
```
<a href=''>百度</a >
```
输出自动删除了链接地址，并在</a>的反括号前面引入了空格。难道是微信微信后台故意屏蔽的？请问怎么解决？

您的itchat版本为：`[在这里填写版本号]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> [您的内容]

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by chenbotao828** [comment]
似乎手机上打都不行了，什么情况？

**Comment by Chyroc** [comment]
微信限制了，会干掉一些`<tag>`
