### ISSUE TITLE
移植到服务器上运行，建议登录时隐藏二维码的显示

### ISSUE THREAD

**Issue by jantacy** [littlecodersh/ItChat#661]
看了下代码，貌似是如果是终端二维码，则不会显示图片二维码，也没法将图片保存到本地，如果是图片二维码，则必须会显示，但放到linux服务器上会报错，因为没有输出设备。建议加个字段isShow=False，这样可以保存到本地，然后通过文件传输到本地或者邮件的形式发送给管理员，管理员收到邮件后扫描邮件中的二维码，进而验证登录以及掉线后半自动登录。看了下，需要改的地方有login()、get_QR()以及auto_login()三个函数。 @littlecodersh 希望有空考虑下这个问题，感谢你的奉献，谢谢。

**Comment by Chyroc** [comment]
在服务器上运行的时候，也会保存文件了：https://github.com/littlecodersh/ItChat/pull/658/files

你可以「然后通过文件传输到本地或者邮件的形式发送给管理员，管理员收到邮件后扫描邮件中的二维码，进而验证登录以及掉线后半自动登录」了
