### ISSUE TITLE
拉人进讨论组失败

### ISSUE THREAD

**Issue by JImumu** [littlecodersh/ItChat#663]
在提交前，请确保您已经检查了以下内容!

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [x] 我已经阅读并按[文档][document] 中的指引进行了操作
- [x] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [x] 本问题确实关于`itchat`, 而不是其他项目.
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
打印ReturnValue如下：
`{u'MemberCount': 0, u'MemberList': [], u'BaseResponse': {u'ErrMsg': u'', u'Ret':1, u'RawMsg': u''}}`
在源码中打印`chatroomUserName`参数，中文显示乱码
```

您的itchat版本为：`[在这里填写版本号]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> 打印ReturnValue如下：
`{u'MemberCount': 0, u'MemberList': [], u'BaseResponse': {u'ErrMsg': u'', u'Ret':1, u'RawMsg': u''}}`
在源码中打印`chatroomUserName`参数，中文显示乱码

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by JImumu** [comment]
已排除中文乱码导致拉人进讨论组失败的可能

**Comment by JImumu** [comment]
拉人进讨论组的代码如下：
`@itchat.msg_register(itchat.content.FRIENDS)
def add_friend(msg):
    msg.user.verify()
    print itchat.add_member_into_chatroom('We are the world!', [msg.RecommendInfo])`

**Comment by uliian** [comment]
我看来貌似是因为web微信直接关闭了邀请进群功能导致的

**Comment by kingmo888** [comment]
微信网页版群邀请现在是ok的呀。
