### ISSUE TITLE
近期网页版使用之后，隔天就会被封，希望官方备注或给出方案，不然被封的数量持续上升

### ISSUE THREAD

**Issue by niesen1990** [littlecodersh/ItChat#668]

**Comment by zuo000** [comment]
同被封…

**Comment by lwjydhcg** [comment]
同。。

**Comment by LinusMelb** [comment]
同被封 但是像微友助手等软件是可以模拟ipad登录的 不知道这个接口能不能拿到

**Comment by LinusMelb** [comment]
![image](https://user-images.githubusercontent.com/17083284/40732963-e9cf3212-6477-11e8-8f9e-4a0c606a1094.png)
建了一个群大家可以来讨论一下

**Comment by yelantingfeng** [comment]
所以一用就会被封吗，这么可怕的吗？

**Comment by Chyroc** [comment]
限制web登录了，参考 https://github.com/littlecodersh/ItChat/issues/651

**Comment by LukeDev2K** [comment]
二维码过期了，有新的吗
