### ISSUE TITLE
关于api

### ISSUE THREAD

**Issue by hwt9520** [littlecodersh/ItChat#669]
在提交前，请确保您已经检查了以下内容!

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [x] 我已经阅读并按[文档][document] 中的指引进行了操作
- [x] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [x] 本问题确实关于`itchat`, 而不是其他项目.
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

您的itchat版本为：`[在这里填写版本号]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> [您的内容]
1.在https://www.pythonanywhere.com上托管一段代码，想用itchat发消息，报错，打开debug，依旧
2.觉得不是代码问题，联系管理员
3.Does the site you're trying to access have a public API? If it does, then post a link to the documentation and we'll consider it for inclusion into the whitelist.
4.public API ？？？
查了https://www.pythonanywhere.com/whitelist/
有api.weixin.qq.com
为什么这个不管用？？？哪个又是对的？？

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

13:52 ~ $ python itchatdebug.py
```
Start auto replying.
Traceback (most recent call last):
  File "/home/hwt9520/itchat/utils.py", line 130, in test_connect
    r = requests.get(config.BASE_URL)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 465, in send
    raise ProxyError(e, request=request)
ProxyError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot conn
ect to proxy.', error('Tunnel connection failed: 403 Forbidden',)))
You can't get access to internet or wechat domain, so exit.
```

**Comment by Chyroc** [comment]
ssl问题，参考：https://github.com/littlecodersh/ItChat/issues/265
