### ISSUE TITLE
微信号对应的字段属性

### ISSUE THREAD

**Issue by brothertian** [littlecodersh/ItChat#67]
通过get_contract得到的微信联系人信息，哪个属性对应“微信号”？
目前测试唯一比较像的属性就是Alias属性，可是只有部分微信账号的这个属性等于“微信号”，还有些微信账号的这个属性为u""。因此比较疑惑。

**Comment by littlecodersh** [comment]
@brothertian 
Alias属性对应微信号。
关于部分微信号为空的问题，我做了一个测试，发现有两种可能。

**一种可能**

一种是本来就没有微信号。

微信号并非每个微信都会有，因为注册微信的过程是这样的：
1. 输入手机号或QQ号
2. 输入验证码
3. 完成注册，使用微信
4. 设置微信号

所以如果不设置第四步就不会产生微信号，属性即为`''`

**另一种可能**

另一种我尚未找到原因，有些有信号号的账号依旧获取不到Alias键值。

之后会做两个尝试：
* 寻找其他获取好友列表的方式
* 测试何种账号会无法获取微信号

**测试程序**

```python
import sys

import itchat

itchat.auto_login(True)
for member in itchat.get_contract():
    if member.get('Alias', ''): continue
    print(('* %s' % (member['RemarkName'] or member['NickName']))
        .encode(sys.stdout.encoding, 'replace')
        .decode(sys.stdout.encoding, 'replace'))
```

**Comment by brothertian** [comment]
目前无法获取微信号的账户，属于后一种情况，从手机端登录的微信账户可以查看到正确的微信号，从程序获取值为u""。而且近期新注册的2个微信号均能够得到微信号，有问题的微信号属于很久之前申请的账户，那时候申请微信账户甚至无需手机号和qq号。怀疑是否与申请微信号的时候微信的版本有关？

**Comment by featheraaa** [comment]
老微信本来有可能没有微信 号，凭QQ或邮箱来登录，这不是一个bug

**Comment by littlecodersh** [comment]
@featheraaa 说的没错，有些微信的确是没有微信号的。
但实际上有些微信号在手机上可以看到微信号，但是返回的数据包中微信号的值为空。
如果这个问题不能解决的话可能Alias字段会几乎不可用。

**Comment by geekfly2016** [comment]
有什么办法可以确定群聊以及群聊成员的唯一性吗？就是在机器人掉线之后重新扫码启动也能匹配到具体的成员。

**Comment by 9cat** [comment]
很希望能解决取得微信号的问题。 @littlecodersh  @geekfly2016  在网页版本上是的确能看到对方的微信号的， 没有微信号的另当然别论， 但有的为何会看不到呢？

**Comment by littlecodersh** [comment]
@9cat 话说网页版本上的微信号是怎么看的？

**Comment by 9cat** [comment]
如果从群里面开始模拟：
1. 点击那个发话人的头像
2. 然后弹出来一个小popup
3. 里面第二行就是微信号了


不知有没有可能可以抓取到这个信息。

@littlecodersh

**Comment by geekfly2016** [comment]
@9cat 你是指在群聊面板，点击消息列表的发消息人的头像，弹出的窗口吗，那只有一个昵称， 后台也没有发新的请求，没有微信号吧。

**Comment by littlecodersh** [comment]
@9cat 我这里试了一下也没能找到微信号，可以截个图吗？

**Comment by 9cat** [comment]
![image](https://cloud.githubusercontent.com/assets/1379110/19376633/58bf7f78-9194-11e6-8b33-1bdb425e0ca6.png)
@littlecodersh

**Comment by geekfly2016** [comment]
@9cat 你这是客户端吧，我们要从网页版获取。

**Comment by geekfly2016** [comment]
@littlecodersh 看到其他人做的东西，uin和微信号都有显示，不确定是不是通过网页版拿到的数据。

**Comment by littlecodersh** [comment]
@geekfly 可以试着登录上去看一下是什么登录。
网页版目前的问题是某些特定的微信号获取不到，大部分的微信号还是可以获取的。

**Comment by geekfly2016** [comment]
好友的微信号可以拿到，微信群成员的拿不到吧。

**Comment by littlecodersh** [comment]
@geekfly2016 对的，群成员没有这个字段。

**Comment by 9cat** [comment]
@littlecodersh  @geekfly2016 
抱歉， 我一直把PC客户端当作WEB形式了。有可能反编译PC 端来实现吗？

另外 。 我试了一下网页版。 即使是好友联系人， alias显示的也不一定是微信号。 而是对方改的昵称。也就是无法作为唯一性ID使用。

有可能使用头像作为唯一性的ID ， 每次下载头像的HASH 会一样吗？ 还是每次都 会变化？

**Comment by geekfly2016** [comment]
头像的图片地址每次登录也会变的。


在2016年10月15日 13:46，9CAT 写道:

@littlecodersh@geekfly2016
抱歉， 我一直把PC客户端当作WEB形式了。有可能反编译PC 端来实现吗？

另外 。 我试了一下网页版。 即使是好友联系人， alias显示的也不一定是微信号。 而是对方改的昵称。也就是无法作为唯一性ID使用。

有可能使用头像作为唯一性的ID ， 每次下载头像的HASH 会一样吗？ 还是每次都 会变化？

**Comment by 9cat** [comment]
@geekfly2016  我指的是图像的binary内容每次都变吗？

**Comment by geekfly2016** [comment]
这个没尝试过，比如换头像了肯定变了。


在2016年10月16日 01:09，9CAT 写道:

@geekfly2016 我指的是图像的binary内容每次都变吗？

**Comment by geekfly2016** [comment]
@littlecodersh @9cat 新发现，当微信群有成员变动和群名改变时，微信在消息中会返回新的群成员列表，会包括Uin。

**Comment by littlecodersh** [comment]
@geekfly2016 非常感谢你的发现，我按照这个发现在`1.1.16`中重新梳理了群聊的存储方式。
现在群聊会后台自动更新并能够获取到各用户的Uin。

**Comment by geekfly2016** [comment]
@littlecodersh 当群聊成员超过40人时（含）,此时会使用https://wx2.qq.com/cgi-bin/mmwebwx-bin/webwxupdatechatroom?fun=invitemember这个API，请求参数也有变化，AddMemberList变为InviteMemberList，同时被邀请入群的人会收到入群链接。看了你的代码对这个没有处理。顺便想问下selector=6是什么情况呢。

**Comment by geekfly2016** [comment]
@littlecodersh 目前我这边的打算是每次机器人登录时修改群聊名称，这样获取到每个成员的uin，看你修改的代码写了个detailed标志来执行get_detailed_member_info方法，你是在什么时候为True呢，我还是想能不能不通过改名或者加减成员的方式拿到uin，这你有什么新发现吗？

**Comment by littlecodersh** [comment]
@geekfly2016 我之后的版本增加一下这个功能。
selector的状态我一直没有做过分析，类似的问题还有如何清除这个状态，有兴趣的话我们可以一起做个研究。
目前不需要修改群聊名称，itchat后台会自动更新群聊成员的Uin，不过。
理论上来说现在是不需要手动更新微信群聊的，但为了保持API稳定我还是保留了这个方法。
目前的群聊的调用基本来说是这样的：
* 获取方法为`get_chatrooms`，将会返回完整的群聊列表。
* 其中每个群聊为一个字典
* 传入update键为True将可以更新群聊列表并返回通讯录中保存的群聊列表，手动更新不会获取Uin
* 群聊列表为后台自动更新，如果中途意外退出存在极小的概率产生本地群聊消息与后台不同步
* 为了保证群聊信息在热启动中可以被正确的加载，即使不需要持续在线的程序也需要运行`itchat.run()`
* 如果不想要运行上述命令，请在退出程序前调用`itchat.dump_login_status()`，更新热拔插需要的信息

**Comment by geekfly2016** [comment]
不用感谢，我也是在做这一方面的，只是发现了这个方案可行，以后可以精确匹配群成员了。对于一些不懂得也经常在你的项目里找思路。


在2016年10月21日 20:35，LittleCoder 写道:

@geekfly2016 非常感谢你的发现，我按照这个发现在1.1.16中重新梳理了群聊的存储方式。
现在群聊会后台自动更新并能够获取到各用户的Uin。

**Comment by Morriaty-The-Murderer** [comment]
@littlecodersh 程序初始化时怎么拿到群聊成员的Uin的？没有群信息变更，ModContactList为空

**Comment by littlecodersh** [comment]
@Morriaty-The-Murderer 需要修改群聊名字或者增加删除群聊人员

**Comment by 9cat** [comment]
@littlecodersh 

1. 目前有没有现成的任何function 可以通过user取得某UserName取得Uin?
例如：
uin =  getUin(Username = name)
然后程序可以 根据这个Uin作唯一性操作。

2. 这个ModContactList是取得整群友的UINl的list吗？ 

3.有一个完整的小DEMO 例子可以展示 的吗？

**Comment by Morriaty-The-Murderer** [comment]
@littlecodersh 这个我知道。。。。ModContactList这个是我最先发现的。。。。但一直没找到好的隐蔽手段，去更改群信息获取Uin，程序为了获取Uin去修改群名实在是太显眼了
相关[issue](https://github.com/liuwons/wxBot/issues/128)

**Comment by geekfly2016** [comment]
目前找到的方案只能去主动修改群名或者加好友进群。
在2016年10月26日 10:29，Morry Wang 写道:

@littlecodersh 程序初始化时怎么拿到群聊成员的Uin的？没有群信息变更，ModContactList为空

**Comment by spacelan** [comment]
@littlecodersh @Morriaty-The-Murderer @geekfly2016 给你们提个方案吧

使用`webwxoplog`直接取消群聊置顶（不需要事先置顶），然后等待下一个sync的`ModContactList`

我做JavaScript版本API库发现的

**Comment by Morriaty-The-Murderer** [comment]
厉害！ @spacelan

**Comment by yangsPy** [comment]
首先谢谢作者写出这么强大的库。
我在做基于itchat的管理系统。
于是我也遇到了寻找唯一ID的问题。
我现在的解决办法是设置备注，因为目前来看只有备注是所有好友都能有而且对自己来说是可控的。
希望能有更方便快捷的方法。

**Comment by geekfly2016** [comment]
@yangsPy 可能我们的难点都在群成员的问题上，普通好友的可以加备注解决，但是有试过短时间频繁的加备注，不会出现1205操作频繁吗？

**Comment by yangsPy** [comment]
哦哦，这边的调备注频率不高，只有向机器人注册的时候才设置一下。所以没有测试。

**Comment by soulmachine** [comment]
@yangsPy 你的办法是新用户注册的时候，把该用户名的备注名设置一下，保证备注名在你的系统里是unique，是这样吗？

**Comment by yangsPy** [comment]
@soulmachine 是的

**Comment by 9cat** [comment]
@soulmachine 设置备注有相关的代码片段作参考 吗？

**Comment by 9cat** [comment]
@yangsPy 设置备注有相关的代码片段作参考 吗？

**Comment by yangsPy** [comment]
@9cat 我做的是校内用户管理系统，设为学号就行了，相应什么ID都行

**Comment by soulmachine** [comment]
@9cat `itchat.set_alias(msg['FromUserName'], 微信号)`

**Comment by Yibangyu** [comment]
> 首先谢谢作者写出这么强大的库。
> 我在做基于itchat的管理系统。
> 于是我也遇到了寻找唯一ID的问题。
> 我现在的解决办法是设置备注，因为目前来看只有备注是所有好友都能有而且对自己来说是可控的。
> 希望能有更方便快捷的方法。

您好，请问怎么用程序去实现动态修改用户备注嘞？

**Comment by michael0806** [comment]
请问现在itchat还能获取微信号吗？
