### ISSUE TITLE
itchat.run()的阻塞问题

### ISSUE THREAD

**Issue by thygyc** [littlecodersh/ItChat#675]
在提交前，请确保您已经检查了以下内容!

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ ] 我已经阅读并按[文档][document] 中的指引进行了操作
- [ ] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [ ] 本问题确实关于`itchat`, 而不是其他项目.
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

您的itchat版本为：`[在这里填写版本号]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> [您的内容]

我的itchat版本是最新版本的，我想实现一个功能，定时提醒，到了指定的时间，会向文件传输助手发送一则提醒。但是itchat.run()我看了看代码，run实际上是循环执行一个列表里的函数，register是把函数注册到列表里，好像只能在收到消息后才能激活。有没有什么好的解决方案呢？

**Comment by 1049451037** [comment]
itchat.run(blockThread=False)

**Comment by 1049451037** [comment]
```python
itchat.run(blockThread=False)
```

**Comment by thygyc** [comment]
谢谢，之前看源码的时候太不仔细了

**Comment by QGB** [comment]
\Anaconda2\Lib\site-packages\nbconvert\preprocessors\tests\files
--

**Comment by Homosum** [comment]
请问一下我自己的scheduler定时任务和itchat.run()不能同时执行，自己的scheduler()和itcha.run()谁写在上面执行谁，下面的语句就不继续执行了。这个该怎么办。我目前试了multiprocessing和上面说的blockThread=False好像都不行。

**Comment by chenyusheng** [comment]
在子线程里跑 scheduler，我就是这样子解决

**Comment by dippac** [comment]
https://blog.csdn.net/ybdesire/article/details/82228840 只能帮你到这了，老铁
