### ISSUE TITLE
有没有办法同时能用 itchat 和电脑客户端登录

### ISSUE THREAD

**Issue by hanzichi** [littlecodersh/ItChat#685]
你好，想请教下有没有办法同时能用 itchat 和电脑客户端登录？

谢谢🙏

**Comment by Chyroc** [comment]
不行，一登录网页，电脑版就直接退出了

**Comment by hanzichi** [comment]
@Chyroc 感谢回复，我的需求是定时定向发送一些文字给好友，用 itchat 实现非常容易，但是希望同时保持 pc 客户端在线，是不是就没有办法了？或者有没有什么别的思路？希望能指导下 谢谢🙏
