### ISSUE TITLE
如何在运行脚本期间依然在手机客户端提示消息？

### ISSUE THREAD

**Issue by caiqiqi** [littlecodersh/ItChat#687]
因为运行itchat之后相当于是网页登录了，所以就不能在手机客户端进行消息的铃声震动提示了。但是有时候还是希望能够及时通过铃声和震动来提示，怎么办呢？

**Comment by Chyroc** [comment]
手机端有一个控制是否提醒的选项，在主页面最上面的tab

**Comment by caiqiqi** [comment]
感谢感谢！
