### ISSUE TITLE
求问add_member_into_chatroom怎么用？

### ISSUE THREAD

**Issue by tylor-e** [littlecodersh/ItChat#69]
想实现发送“群”就拉人到指定群的功能，这个版本看到有add_member_into_chatroom和delete_member_from_chatroom的函数。但是要的两个变量是chatRoomName和，memberList

我尝试写入了一个群的名字，把一个人的ID `@xxxxxxxxxxxxxxxxxx` 做成list（即[`@xxxxxxxxxxxxxxx`]），这两个值传入，报错

看了下源代码，memberList里的member要有UserName属性，那我如何从发来消息的msg里，也就是msg['FromUserName']来转化成这个memberList呢？另外chatRoomName是单纯的在客户端看见那个群名字吗？

最后我看着保持在线这个问题上，作者建议是定时向自动回复的公众号发消息，既然如此，给公众号也来一个List保存在storage里吧，其实我已经自己添加了这个功能，不过如果作者添加的话，我也就不用每个版本更新都手动去改了

**Comment by tylor-e** [comment]
增加publicList的作用是判断消息是否来自于公众号。因为我弄了自动回复机器人，公众号再一自动回复，就会出现双方互相伤害的悲惨场面，于是我加了个判断是否是公众号的判断

**Comment by littlecodersh** [comment]
@tylor-e 有两个方法：
1. 使用`get_friends(userName=msg['FromUserName'])`
2. 直接构造一个`{'UserName': msg['FromUserName']}`其实也可以

**Comment by littlecodersh** [comment]
@tylor-e 近期比较忙，估计没有时间更新公众号部分，要等忙完更新了。
公众号更新的问题我留着Issue #66 ，更新完在那里做回复再关闭。

**Comment by tylor-e** [comment]
@littlecodersh 对于邀请进群，chatRoomName应该怎么弄？直接是群的名字吗？我试了一下没有反应，是不是这个命令只能新建群而不能邀请进现有群？

**Comment by littlecodersh** [comment]
@tylor-e 是群的UserName

**Comment by tylor-e** [comment]
@littlecodersh 试了还是不行，邀请入群并没有反应

**Comment by littlecodersh** [comment]
@tylor-e 你看一下用手机能邀请他人入群吗？多次尝试后可能会导致一段时间内特定功能被屏蔽。
如果可以的话给我看下具体的程序吧。
另，被邀请入群的人不能包含群内已有的人以及本人。
你也可以打印一下源码中http请求的返回值，看下是什么问题。

**Comment by tylor-e** [comment]
@littlecodersh 代码用得很简单，就一句` itchat.add_member_into_chatroom(p.getGroupID('游玩派'),[{'UserName':msg['FromUserName']}])`
其中的p.getGroupID是这样的
```
#获取群ID
def getGroupID(GroupName):
    groupList = itchat.__client.storageClass.chatroomList
    for m in groupList:
        if (GroupName == m['NickName']):
            return m['UserName']
    return False
```
测试的这个号也符合被邀请的条件
最后返回值print出来如下：
`{'BaseResponse': {'Ret': -23, 'ErrMsg': ''}, 'MemberCount': 1, 'MemberList': [{'Uin': 0, 'RemarkPYInitial': '', 'NickName': 'Zen', 'RemarkPYQuanPin': '', 'UserName': '@026b6f5360a8ee456e1a0bd8e9efaf39', 'MemberStatus': 0, 'PYInitial': '', 'KeyWord': '', 'DisplayName': '', 'AttrStatus': 0, 'PYQuanPin': ''}]}`

**Comment by tylor-e** [comment]
如果群人数大于100是不是就不能这么邀请了？

**Comment by littlecodersh** [comment]
@tylor-e 我记得大于一定人数没法扫码进群，你尝试一下网页版微信可以邀请吗？

**Comment by tylor-e** [comment]
@littlecodersh 试了下，确实是到100人的限制问题，看来没办法自动加人了

**Comment by 282144757** [comment]
现在itchat.add_member_into_chatroom这个函数不能用了吗？
我打印出来的返回值是：
{'BaseResponse': {'Ret': 1, 'ErrMsg': '', 'RawMsg': ''}, 'MemberCount': 0, 'MemberList': []}

**Comment by alexwang2013** [comment]
@littlecodersh 
在使用itchat.add_member_into_chatroom的时候，出现了如下的问题。
{u'MemberCount': 0, u'MemberList': [], u'BaseResponse': {u'ErrMsg': u'', u'Ret': 1, 'RawMsg': u''}}

这个怎么处理呢？

**Comment by huafengho** [comment]
我现在也遇到这个问题，返回的结果报错：
`<ItchatReturnValue: {'BaseResponse': {'Ret': 1, 'ErrMsg': '', 'RawMsg': ''}, 'MemberCount': 0, 'MemberList': []}>`
请问现在网页版拉人的接口失效了吗

**Comment by james-pb-git** [comment]
@littlecodersh 
同问
itchat.add_member_into_chatroom(chatroom_username, [friends[1]])
返回
<ItchatReturnValue: {'BaseResponse': {'Ret': 1, 'ErrMsg': '', 'RawMsg': ''}, 'MemberCount': 0, 'MemberList': []}>
是否已关闭了拉人API?
