### ISSUE TITLE
有关代码规范化

### ISSUE THREAD

**Issue by gmdzy2010** [littlecodersh/ItChat#697]
看了一下源码，可读性还是比较好的，不过感觉可以更规范一点，不知道作者有没有这个计划，当然仅仅是从review 的角度来看，这个不算什么issue

keywords: code normalization, refactor

**Comment by Chyroc** [comment]
看这个：https://github.com/littlecodersh/ItChat/pull/308

遵循作者的规定来吧

**Comment by gmdzy2010** [comment]
好吧，只是看着有点不习惯，那就尊重作者的习惯好了，其实我也是想稍微重构一下推一个分支来着🤪
