### ISSUE TITLE
有没有扫描二维码的接口？

### ISSUE THREAD

**Issue by ohblue** [littlecodersh/ItChat#698]
想要对聊天对象中发来的二维码执行扫码操作，有相应接口吗？

**Comment by Chyroc** [comment]
只有手机能够扫描呢

**Comment by RicardoScofileld** [comment]
就是微信扫一扫可以从相册中上传图片进行扫描，是否支持这一功能

**Comment by cordova2009** [comment]
> 只有手机能够扫描呢

是这样 itchat生成的二维码图片 我保存到手机  再通过微信的扫一扫从相册中扫码这个报错 提示无法识别  但是直接用手机扫描电脑上的不会  这个怎么解决

**Comment by ohblue** [comment]
> 只有手机能够扫描呢

pc版微信可以在聊天窗口上对二维码图片右键-扫描二维码来获取其中的url，不知道itchat能否支持这个接口？
