### ISSUE TITLE
如何保持itchat持续在线

### ISSUE THREAD

**Issue by littlecodersh** [littlecodersh/ItChat#70]
@featheraaa 在Issue中提出，确认为bug故新建issue，目前已修复
## 解决方案

保持登陆itchat的手机端持续联网。（最简单的方案就是使用虚拟机）
保持itchat所在网络环境稳定。（不会出现长时间断线即可）
如果仍旧不放心，可以设置一定时间向特定的用户（公众号）发送消息显示存活。
或者使用理论上也不存在掉线问题的公众号版本itchatmp。
## bug总览

目前并不了解应该如何修复该bug，该Issue处于讨论阶段。

思路与想法主要如下：
1. 是否能够找到利用网页版微信协议并能保持长期稳定登陆的项目（不限语言与开源）
2. 是否有可能的解决方法
3. 程序是否能判断出是否出现了该种情况

由于问题较为复杂，为了便于交流，我这里给出一个建议的回复模板：

```
2.1 是否有可能的解决方法（保持与公众号通信，保证活跃不被清理）

经过尝试，仅通过该方法无法保持登陆。
保持登陆时间为两天。
```
## 原文

**featheraa**

不知道是不是我人品不好，掉线率很高 ，我一台电脑登5.6个
一个号最多一天半就要掉，有没有什么好一点的解决方案？
请指教

消息是发不出去也接收不到

我是用tklinter和pyinstaller打包出来无dos窗口

**brothertian**

我这边程序也有类似问题，长时间运行后，收不到消息，发不出消息，send返回值为False，没有任何提示信息，阿里云windows运行环境

**LittleCoder**

我这里目前是阿里最基础的ubuntu服务器挂的机器人，没有做过特殊的优化。
python 3.5.1, requests 2.11.0, itchat 1.1.3。
上次重置时间为160813，目前可用。
之前也出现过不满一周即无法接收消息的情况。
使用程序见[这里](https://gist.github.com/littlecodersh/ec8ddab12364323c97d4e36459174f0d)。
## 可能的解决方案
1. 保持与公众号通信，保证活跃不被清理（不可行）
2. 增加心跳包的频率（不可行）

（有新想法之后我再增补）
## 初步结果

由于之前的讨论在Issue 1中，我这里就之前的内容做一个搬运
### 保持与公众号通信，保证活跃不被清理

**featheraa**

用久了后会停在那里 对消息没有响应
我至少半个钟内会发一次信息

**brothertian**

这两天做了测试，让机器人端自动每小时发一次消息，约半天左右就不能成功发出了，send返回值为false.
期间机器人端无接收数据
### 增加心跳包的频率

**featheraa**

运行两天了，修改刷新频率后 掉线似乎好了一点 六个掉两个

**Comment by littlecodersh** [comment]
近期我这里比较忙，没法及时回复，抱歉！

**Comment by featheraaa** [comment]
不知道网页版挂两天是否会掉线，如果网页版挂两天会掉的话那就是后台问题，但有时候我有些号可以挂60多小时。
我有一个想法，每隔24小时刷新一次通讯录，联系人，重新webinit(), 重新通知手机网页状态，不知道这样是否会有效？
我现在出差，这些问题我暂时无法解决，望有人出来解决，如果没有人试验，我会继续测试

**Comment by tempdban** [comment]
@featheraaa @littlecodersh 哈哈哈哈年中看来大家都很忙，我也忙的不行了....
@featheraaa 其实就是重新调用一次itchat.run(),我试试。

**Comment by 5368** [comment]
这个是个问题，自己给自己发消息能不能维持在线?

**Comment by featheraaa** [comment]
@tempdban 结果出来后告诉一下

**Comment by klausgao** [comment]
很关注这个问题，我也是在折腾网页版不掉线，才找到这里的。
我用autoHotKey做了给小实验，网页版微信开着，然后每隔1分半钟刷新一次页面，30秒轮询检测如果检测到一个登陆后的页面的点变色（判断是否突然页面卡住），就马上刷新一次页面。
当前最好的成绩是14小时。

**Comment by klausgao** [comment]
有一个想法，没有验证的，我看了itchat的useragent是linux的，按照微信的尿性，linux和mac都没有出客户端，这样他们的web版应该有比较宽松的政策。另外一个佐证就是 https://github.com/geeeeeeeeek/electronic-wechat 这个项目，他们是弄一个框来包着web版的微信，用于linux和mac，在issues里很少有人提及掉线的问题。
所以我建议是不是能用mac的useragent来测试看看。
顺手放上一个：
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_6; en-US) AppleWebKit/533.20.25 (KHTML, like Gecko) Version/5.0.4 Safari/533.20.27

**Comment by brothertian** [comment]
目前测试情况
1.上周三运行到上周四，运行约大半天，send开始有问题。
2.上周四运行到这周一，运行约4天多，send开始有问题。
测试均采用每小时自动发送一次消息方式。

**Comment by bibotai** [comment]
我也来关注这个问题，我这最好成绩72小时，linux环境，linode服务器，我都想挂两个服务器互相发消息，如果有一个发现另一个挂了，自动发邮件给我，如果能在程序中解决这个问题那更好了

**Comment by tempdban** [comment]
@klausgao 再我的master分支上有修改过ua的代码，您也可以帮忙试试，没问题我再提pr

**Comment by tempdban** [comment]
@featheraaa 还没掉，我合代码杀了一次，现在重新计时

**Comment by bibotai** [comment]
@tempdban 保持几天了？

**Comment by klausgao** [comment]
最新报告，我的微信web版已经活了36小时了。感觉只要它的长连接心跳不断，可能就不死。
另外有一个因素，不懂是不是会被微信的程序员考虑进去。我之前登录这个微信号是用安卓手机的，因为老是掉线，就用了一台旧的iPhone5s来登录，想用来用fiddler抓包的。实验过后发现抓不了，就没理那个web版，那个存活到现在的web版最后登录进去就是用iPhone客户端的。
想请问各种，你们扫码登录进去的手机端分别是安卓还是iPhone？

**Comment by tempdban** [comment]
@bibotai 不到两天，现在已重新计时。
@klausgao 安卓。

**Comment by brothertian** [comment]
@klausgao 安卓系统.

**Comment by featheraaa** [comment]
@littlecodersh @tempdban 重大发现，我的号已经上了五天没掉了，我是重新调用itcaht.run来弄的，但手机好像必须在线才有用，可能是通知手机时，手机要回鐀，如果手机在那个时候关机的话，那就完 了，如果不run里面不调用手机通知的话会怎么样呢？ 这个不确定 ，要试，我们的目标是手标是手机即使关机也要在线一年

**Comment by featheraaa** [comment]
@klausgao  我有三部安卓与三个苹果，都 一样

**Comment by featheraaa** [comment]
https://github.com/liuwons/wxBot/issues/108
我在这里提了一个问题，粗略看了一下，刷新频率他的快很多

**Comment by klausgao** [comment]
@featheraaa 我之前是周末在家测试，用的安卓，就猛地掉，后来上班了用苹果，现在2天多了，一直活着。
但是也可能是我周末的时候也在家一起下着东西，占用比较大的带宽，所以微信的心跳就不行了。
我今天下午开始远程桌面家里的电脑，也是下大量的东西占用带宽，看看还能活不？
明天上来汇报。

**Comment by tempdban** [comment]
@featheraaa 我把长连接的间隔改小到了0.5-1秒，正在测试。

**Comment by klausgao** [comment]
@featheraaa 我之前是周末在家测试，用的安卓，就猛地掉，后来上班了用苹果，现在2天多了，一直活着。
但是也可能是我周末的时候也在家一起下着东西，占用比较大的带宽，所以微信的心跳就不行了。
我今天下午开始远程桌面家里的电脑，也是下大量的东西占用带宽，看看还能活不？
明天上来汇报。

**Comment by klausgao** [comment]
抓到了，经过昨晚用迅雷BT把家里的网络占满后，终于把我的web微信弄掉线了。一直开着fiddler抓包，在这里分享一下。
最后一个正常的包是23:00:58.928发出的，23:01:30.286长链接response。
然后下一个包就是不正常的了，23:01:30.327发出，没有返回。
（这些心跳都是Get /cgi-bin/mmwebwx-bin/synccheck?r.....这样的URL）
之后web微信在23:02:10.368进行尝试，
Raw Request如下：
CONNECT webpush.wx2.qq.com:443 HTTP/1.0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Trident/7.0; Touch; rv:11.0) like Gecko
Content-Length: 0
Host: webpush.wx2.qq.com
Proxy-Connection: Keep-Alive
Pragma: no-cache

Raw的Response如下：
HTTP/1.1 502 Fiddler - DNS Lookup Failed
Date: Wed, 31 Aug 2016 15:02:22 GMT
Content-Type: text/html; charset=UTF-8
Connection: close
Cache-Control: no-cache, must-revalidate
Timestamp: 23:02:22.200
[Fiddler] DNS Lookup for "webpush.wx2.qq.com" failed. System.Net.Sockets.SocketException 不知道这样的主机。

这个重试一直重复了很多次，我列出来
23:02:10.368  23:02:50.398  23:03:30.371  23:04:10.390  23:04:50.408  23:05:30.425  23:06:10.430  23:06:50.429  23:07:30.454  

一直到23:08:10.463，出现了一个新的状态
Raw的Request：
CONNECT webpush.wx2.qq.com:443 HTTP/1.0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Trident/7.0; Touch; rv:11.0) like Gecko
Content-Length: 0
Host: webpush.wx2.qq.com
Connection: Keep-Alive
Pragma: no-cache
A SSLv3-compatible ClientHello handshake was found. Fiddler extracted the parameters below.

Raw的Response：
HTTP/1.0 200 Connection Established
FiddlerGateway: Direct
StartTime: 23:08:11.950
Connection: close
fiddler.network.https> HTTPS handshake to webpush.wx2.qq.com (for #1491) failed. System.IO.IOException 由于远程方已关闭传输流，身份验证失败。

之后终于从HTTP连上HTTPS，访问 GET /cgi-bin/mmwebwx-bin/synccheck?r=....，然后Raw的Response是这样的：
HTTP/1.1 200 OK
Connection: keep-alive
Access-Control-Allow-Origin: *
Content-Type: text/javascript
Content-Length: 46
window.synccheck={retcode:"1101",selector:"0"}

如果是正常状态，Response是这样的：
HTTP/1.1 200 OK
Connection: keep-alive
Access-Control-Allow-Origin: *
Content-Type: text/javascript
Content-Length: 43
window.synccheck={retcode:"0",selector:"0"}

之后web微信就会redirect到登陆的界面，整个过程结束。

**Comment by klausgao** [comment]
我分析前面抓过的包，很奇怪，有过很多次断链的情况，一般是断个1分钟（2-3次重试），这样是没有问题的。
然后发现一个很厉害的，重试了9次，15:52:55.465到15:56:55.620，持续了4分钟，最后也救回来了。

**Comment by klausgao** [comment]
这里总结，完全断线很可能是2个因素造成的。
1是服务器心跳过久没有办法连到，服务器端就标记了断线。
2是客户端判定了成功心跳的间隔，如果超过一个时间，就判定断线，并发送一个结果给服务器（window.synccheck={retcode:"1101",selector:"0"}），客户端清理cookie，重新回到登陆界面。

**Comment by klausgao** [comment]
所以，如果是
1、服务器端判断心跳超时的，我们就没办法控制了。
2、客户端判断心跳超时，并返回retcode:"1101"给服务器的，我们可以hack它的js，还能屏蔽它返回retcode:"1101"给服务器。

**Comment by klausgao** [comment]
这里上传我的抓包的记录文件，直接安装fiddler后，双击打开就行了。
请大神们多多分析分析。
[https://github.com/klausgao/electron-linvodb-manager/blob/master/wx_packages.saz](抓包文件)

**Comment by klausgao** [comment]
继续分析：
在微信web版的[webwxApp2e4e03.js](https://res.wx.qq.com/zh_CN/htmledition/v2/js/webwxApp2e4e03.js)里，找到:
syncCheck:function () {
    var e = t.defer(), c = this, s = o.API_synccheck + "?" + ["r=" + a.now(), "skey="
        + encodeURIComponent(n.getSkey()), "sid=" + encodeURIComponent(n.getSid()), "uin="
        + n.getUin(), "deviceid=" + n.getDeviceID(), "synckey=" + encodeURIComponent(n.getFormateSyncKey())].join("&");
    return window.synccheck && (window.synccheck.selector = 0), $.ajax({
        url: s,
        dataType: "script",
        timeout: 35e3
    }).done(function () {
        window.synccheck && "0" == window.synccheck.retcode ? "0" != window.synccheck.selector ? c.sync().then(function (t) {
            e.resolve(t)
        }, function (e) {
            console.log("syncCheck sync nothing", e)
        }) : e.reject(window.synccheck && window.synccheck.selector) : !window.synccheck 
        || "1101" != window.synccheck.retcode && "1102" != window.synccheck.retcode ? window.synccheck 
        && "1100" == window.synccheck.retcode ? r.loginout(0) : (e.reject("syncCheck net error"), i.report(i.ReportType.netError, {
            text: "syncCheck net error",
            url: s
        })) : r.loginout(1)
    }), e.promise
}

好吧即使我也写nodejs，也是看得眼晕。

**Comment by featheraaa** [comment]
@tempdban @klausgao 我刚刚又掉了一线，重新调用run后完美上线，但手机要在线，就这里麻烦

**Comment by featheraaa** [comment]
@tempdban 我现在的频率是有消息 0.8秒 无消息1.5秒

**Comment by featheraaa** [comment]
@klausgao 掉线的话，五分钟之内还能救 回来

**Comment by klausgao** [comment]
好了，研究webwxApp2e4e03.js里的代码，可以确定的是：
1、微信服务器是不会对web微信进行强制下线处理的，就是说，微信服务器的session至少不是短期内会主动去掉的，应该是持久化了的。
2、是否超时的计时，是由微信web端进行计算的，并且在计算超时超时后，ajax Post回去给服务器，报超时退出。
POST /cgi-bin/mmwebwx-bin/webwxlogout?redirect=1&type=1&skey=%40crypt_537d5239_41563ff92ce2316d7ccb3d8025118731 HTTP/1.1

具体可以去看看源码。

那现在就很简单了，**# 只要hack掉webwxApp2e4e03.js里的1个函数，就基本上不会再掉线了。**

**Comment by littlecodersh** [comment]
@klausgao 非常感谢你对项目的支持！
```
好了，研究webwxApp2e4e03.js里的代码，可以确定的是：
1. 微信服务器是不会对web微信进行强制下线处理的，就是说，微信服务器的session至少不是短期内会主动去掉的，应该是持久化了的。
2. 是否超时的计时，是由微信web端进行计算的，并且在计算超时超时后，ajax Post回去给服务器，报超时退出。
POST /cgi-bin/mmwebwx-bin/webwxlogout?redirect=1&type=1&skey=%40crypt_537d5239_41563ff92ce2316d7ccb3d8025118731 HTTP/1.1

具体可以去看看源码。

那现在就很简单了，
只要hack掉webwxApp2e4e03.js里的几个函数，就基本上不会再掉线了。
```
关于这个js，有两个问题希望可以解答一下：
1. 是如何通过前端代码得出了后端`微信服务器是不会对web微信进行强制下线处理的`的逻辑的？
2. 本项目不会调用webwxlogout，但实际也会退出，是否说明其实不用研究前端的退出机制？

**Comment by littlecodersh** [comment]
@featheraaa 还能救得回来这个点感觉背后有东西可以研究。
可以具体描述一下当时情况么？

**Comment by littlecodersh** [comment]
我这里是iPad的微信，原版itchat，演示用机器人持续时间都在一周以上，所以之前一直觉得是网络不稳定才会挂掉，最近才开成issue。

**Comment by klausgao** [comment]
@littlecodersh 确实是网络不稳定才会掉线，这个是肯定的。我今天是分析了js代码，是看到了一些有关这方面的函数，但是毕竟代码混淆了，同时也分析得不够深，所以可能会有一些问题。

> 本项目不会调用webwxlogout，但实际也会退出，是否说明其实不用研究前端的退出机制？
这个确实是值得分析一下。另外也可能说明了你发现的，都能活1周以上，说明服务器端是有可能会在心跳时间过长后，断线的。之前cookie里有个值，wxloadtime=1472440157_expired，是会记录了第一次加载的时间的。

**Comment by littlecodersh** [comment]
@klausgao 好的，关于wxloadtime我的想法是：
* 由于每次掉线时间都不同且差距较大，假设是仅通过登录时间确定掉线，那么是采用了随机数方式
* 就已知登录时间，有数小时到一个月多不等，就从业务上看不出随机数的必要，可能性较小
* 假设有多种下线机制，那么顺序上应该先清除短期掉线的原因，否则由于别的掉线原因影响，逻辑上无法找到排除干扰的研究方式
我建议这个可以先放在备忘里，在起码确定一个下线机制后，可以再做研究。
之后研究的话，可以更改cookies中相关的键值，看与显示时间差距为多少时开始无法登陆。

**Comment by klausgao** [comment]
@littlecodersh 你的分析很对哦！应该就是这样了，多种的下线机制。然后我分析的那个js，就是其中一种。而这个项目因为完全是使用了模拟的，所以少了这种客户端的下线机制，就更稳定，能活得更久。
我大概2年前也在写py，用flask写web，但是已经2年不玩了，现在主要写nodejs。
我之所以关注这个issue，是因为最近需要抓微信web的包，但是发现web端很容易掉线，就搜索后来到这里了。
很高兴认识你们，py我是帮不上忙了哈哈，只能帮你们分析分析，写写段子了哈哈。

**Comment by littlecodersh** [comment]
@klausgao 好的，有进展了我到时候一定@你

**Comment by featheraaa** [comment]
@littlecodersh 能救回来，也就是autologin(True),但有时候掉线五分钟以后，重新上线的，如果手机在线的话，48小时后会退出，但重新调 用run可以完美上线，我在想如果run里面去除通知手机上线，即拿手机关机不知道会怎么样

**Comment by littlecodersh** [comment]
@featheraaa 好的
* 掉线是指程序开着但是无法接受和发送吗？
* 48小时后退出是那一次救回来以后经过48小时就退出了吗？
* 通知手机上线并非登陆的必须步骤，不加就在微信上不会立即显示网页版微信登陆，之后可以删除试试

**Comment by featheraaa** [comment]
最近发现了windows版的微信，功能多很多，不会抓包，不然都可以研究这个

**Comment by littlecodersh** [comment]
@featheraaa 主要不是抓包的问题是加密的问题，以及这个研究了也不可能放出来当开源的其实

**Comment by featheraaa** [comment]
@littlecodersh 
掉线是指程序开着但是无法接受和发送吗？
    是的，修改了一下源码，如果2000秒内无消息退出run ,再次调 用run

48小时后退出是那一次救回来以后经过48小时就退出了吗？
    我挂了七天了，但每一次run结束后，再重新调用run完美解决，今天是第七天，大约每次过40+多少时它             都 要退一次

通知手机上线并非登陆的必须步骤，不加就在微信上不会立即显示网页版微信登陆，之后可以删除试
我觉得问题很有可能在这里，因为通知手机时，手机正好关机，要是不回应，可能就不让登录了

**Comment by littlecodersh** [comment]
@featheraaa 了解，多谢！

**Comment by featheraaa** [comment]
@littlecodersh 不用谢 itchat 造福广大码农，感谢作者

**Comment by klausgao** [comment]
最近研究这个，用fiddler抓包，发现win10上，Chrome和Firefox已经没办法用fiddler了，一开fiddler是没办法去访问类似Google这些https网站的，直接提示net error，只有ie才可以，所以这几天抓的包都是IE的。应该是https的技术进步了，mitm类的攻击已经无效了。



可用于iOS的myMail发送


2016年9月2日 星期五 +0800 12:21 发件人 LittleCoder  <notifications@github.com>:

**Comment by tempdban** [comment]
@littlecodersh @featheraaa 
有个问题很明确，就是两次poll之间间隔五秒太长了。

**Comment by tempdban** [comment]
@littlecodersh @featheraaa 
我不知道掉了多久也救回来了
醒来发现没向我报告运行状态，然后我就登录微信，去服务器重启整个程序，瞬间就收到了。
![jietu](https://cloud.githubusercontent.com/assets/4144536/18222273/0dff840e-71c5-11e6-9a3f-843f4faa55ab.png)

**Comment by tempdban** [comment]
def killSelf():
    running[0] = False

if __name__ == '__main__':
    while True:
        running[0] = True
        timer=Timer(86400,killSelf)
        timer.start()
        itchat.auto_login(enableCmdQR = -2, hotReload = True, running = running)
        complex_reply(running)
        if running[0] == 3:
            break
        print "begin(join)"
        running[1].join()
        print "end(join)"

修改了下消息线程的实现，现在是每24小时重新auto_login，从今天开始计时。

**Comment by featheraaa** [comment]
@tempdban 如果手机不在线这样是否有效？
我的已经登录十几天了，依然没事

**Comment by klausgao** [comment]
现在感觉真的就是网络状况问题了，我在公司的web服务器上开的，已经5天了。



可用于iOS的myMail发送


2016年9月6日 星期二 +0800 03:58 发件人 featheraaa  <notifications@github.com>:

**Comment by tempdban** [comment]
@featheraaa @littlecodersh @klausgao 50多个小时后无法接收消息.
真的就是因为手机不在线的原因：
1.缩短两次长连接间隔，现在是0.5-1 s。
2.发现不能接收到信息，在保证手机在线的话直接重启itchat，不用重新扫码就能继续收到信息，并且漏收的信息也会重新发过来。
3.你们能坚持这么长时间的原因.......是因为您们是ios，我是安卓

**Comment by brothertian** [comment]
这几天测试，没有调整程序，运行情况良好，连续运行一周左右。安卓手机端，曾长时间离线.
现在确实怀疑机器人程序部署的阿里云服务器网络连接之前曾经不稳定，目前运行了一个icmp检测程序，希望能够记录服务器网络出现问题的时间，以及网络恢复时候与手机端是否在线的关联性。

**Comment by tempdban** [comment]
@brothertian 手机离线超过50小时了吗

**Comment by brothertian** [comment]
@tempdban 未超过，约离线10多个小时。

**Comment by featheraaa** [comment]
我用阿里云挂了十几天了，只是要手机在线，我的是安卓

**Comment by tempdban** [comment]
@brothertian @featheraaa @littlecodersh 基本两天之内上线一次就可以。
那现在怎么办...这个限制感觉不好饶啊

**Comment by tempdban** [comment]
@featheraaa 因为苹果的推送机制，微信服务器不太能有效的检测出来客户端是否离线。安卓就不一样了。。

**Comment by 9cat** [comment]
出现同样的问题， 能否侦测到已断开， 然后自重启能否解决这问题？

**Comment by tempdban** [comment]
@9cat 请保证手机在线。

**Comment by brothertian** [comment]
@9cat 自启未必能自动解决问题，断开超过一段时间需要刷二维码，还是不能达到无人值守的效果。从目前来看，个人感觉也许即时检测机器人端的网络可达性，当出现网络问题的时候及时短信提醒运维人员，同时保持手机端微信在线，是比较容易的解决方案。

**Comment by tempdban** [comment]
@9cat 
@brothertian 每天记住点开一下，出现网页登录的框再杀掉就可以了

**Comment by brothertian** [comment]
@tempdban 每天点开一下，指的是机器人程序端么？

**Comment by tempdban** [comment]
@brothertian 我指的是微信。。。。。。

**Comment by 9cat** [comment]
@brothertian  感谢， 我目前是24小时开着一台手机。 在想能否用KVM模拟一个ANDROID 放在服务器上一直开着。  然后目前用自重启方式，每1小时重启一次先对付一下。 看有没有最终能更好的解决方案。

目前我用 Bash while + sleep:

while true
do 
    python itchatrun.py
    sleep 3600
    pkill -9 python
done

独立docker里面，只能运行一个python.

**Comment by featheraaa** [comment]
最后方案是保持手机在线，这是最终解决方案

**Comment by littlecodersh** [comment]
我这里上次重启是8月13日，目前存活，已超过一个月。
正面来说，featheraaa的安卓和我的ios在保持在线的状态下都能保持长时间（十日以上）的登录。
另一方面，回忆之前的断线记录，大都和手机断电关机有关。
所以这一结论基本可以肯定是一个断线机制。
虽然可能性较小，但我的意思并不是就排除了存在其他的断线机制的可能性。
出于修复这一问题的目的，我非常赞同brothertian的意见，应当增加一个检测机器人端存活的方法。
那么除了指定公众号检测是否互动正常外，各位有没有别的想法？

**Comment by jyjunyz** [comment]
@littlecodersh 或者同时启动两个机器人，一个作为业务端，一个作为管理端，管理端专门负责在线检测和问题记录（不过感觉和公众号的方法没啥区别。。）

**Comment by littlecodersh** [comment]
@jyjunyz 是的，反正也有写开源的公众号，可以随便用

**Comment by brothertian** [comment]
目前测试下来确实主要就是手机在线的问题，保持手机在线后，长时间运行效果较好。

另一方面，即使这样在长时间运行后，比如几周，仍然可能有微信消息发不出去，send函数false，奇怪的是如果持续重试send，在不重新登录微信的条件下有可能在一段时间之后能够发送成功，这段时间有可能达到一天或者几天之久，只是这时候发送成功的效果也不持久。举例来说100条信息需要发送，一开始发送不成功，过段时间发送成功10条，其余仍然发送不了，又过段时间发送成功30条，其余还是发送不了，这时候还是需要重新登录微信才能恢复正常运行。

总结了一下，为了保持长时间稳定运行，采用下面几条措施，效果还是不错的：
1.保持手机端微信在线
2.保持微信机器人端网络情况良好
3.若出现send不成功，自动重启微信机器人，且发送提醒到运维人员处，要求其刷二维码登录。这时候若采用免登录重启不能恢复正常。
比较简单的办法就是发一封139邮箱的邮件，通过邮件系统的短信告知运维人员，经过长期测试139邮箱的短信送达率还是不错的。
4.由微信机器人端定时发送运维报告给运维人员的个人微信，作为提醒的补充。若运维人员未收到定时提醒，那么需要主动去查一下微信机器人。同理，也可以考虑定时发送运维信息到微信公众号，由其转发给运维系统，这样可以与运维系统集成，运维人员通过公众号发布运维页面或者自行研发的运维页面对系统进行检查。此项方法比较适合公司用。

其它方法还有待各位高手补充。

**Comment by zhanghsgithub** [comment]
通过最近的研究发现有几种掉线的情况：
1、synccheck 在多次同步时出现错误会掉线
2、synccheck 返回的值中selector 一直为7时会掉线
3、get_msg出现错误多次以后会掉线
这第一种和第三种都可以通过重启程序来解决，唯独第二个selector值一直返回为7，这个时候程序和服务器之间是有通信的，只是一直返回7，当用手机登录微信时，程序又可以收到在其它设备上登录的消息，应该是程序给服务器返回的值不正确，目前无解，只能是通过报警，通过手机重新登录。
目前的监控方式主要是能过微信的企业号，定时向该程序发送消息，然后检测消息是否送达，如何未收到消息，重启该程序。
目前程序运行良好，唯独无法解决selector返回值一直为7的问题。
不知道大家有没有遇到过这种情况。

**Comment by dingwa990** [comment]
最新的心跳请求间隔时间为25秒

**Comment by tempdban** [comment]
@zhanghsgithub http://blog.csdn.net/wonxxx/article/details/51787041 这篇文章里解释了selector = 7的作用，您觉得靠谱么

**Comment by zhanghsgithub** [comment]
@tempdban 不靠谱，手机是离线的状态，没有进入离开聊天室一说，另外我也用其它号测试过把这个号拉入聊天室，并没有selector=7的现象出现。

**Comment by lishuo9527** [comment]
也遇到了同样的问题，小伙伴有没有好的解决办法？

**Comment by littlecodersh** [comment]
@lishuo9527 你看一下最上面的消息，那里有写解决方案。

**Comment by dingziding990** [comment]
我是如果掉线后自动发送邮件给运维，大家有没有推荐的相对稳定的邮件服务？？我用的163，经常晚上发送失败！！

**Comment by lishuo9527** [comment]
@littlecodersh 感觉上面的办法也不是很稳。

**Comment by zhanghsgithub** [comment]
@dingziding990 可以利用微信的企业号进行报警，很稳定。

**Comment by littlecodersh** [comment]
@lishuo9527 我们这里测试过能够长期稳定登陆的

**Comment by lishuo9527** [comment]
@littlecodersh 是使用虚拟机嘛？

**Comment by littlecodersh** [comment]
@lishuo9527 不是，我这里有空的机器，就是手机在线。

**Comment by lishuo9527** [comment]
@littlecodersh 我试试吧，目前好像已经有3天没有掉线了。

**Comment by littlecodersh** [comment]
@lishuo9527 好的

**Comment by 757350134** [comment]
长期稳定吗？

**Comment by littlecodersh** [comment]
@757350134 长期稳定的

**Comment by KevinGong2013** [comment]
QQ: 609776708
微信机器人，7*24小时在线 开发讨论
掉线秒级自动登录～

**Comment by fatmind** [comment]
> 1.保持手机端微信在线
@featheraaa  具体是指：手机不要待机，微信客户端一直在前台运行吗？

**Comment by grandyang** [comment]
@tempdban 
请问能贴下完整的代码吗？

**Comment by freevictor** [comment]
参与讨论的各位，一起到这个QQ群交流下吧 543713695。
主题：微信机器人开发，微信hacks

**Comment by february30** [comment]
> 
> 
> ```python
> def killSelf():
>     running[0] = False
> 
> if __name__ == '__main__':
>     while True:
>         running[0] = True
>         timer=Timer(86400,killSelf)
>         timer.start()
>         itchat.auto_login(enableCmdQR = -2, hotReload = True, running = running)
>         complex_reply(running)
>         if running[0] == 3:
>             break
>         print "begin(join)"
>         running[1].join()
>         print "end(join)"
> ```
> 
> 修改了下消息线程的实现，现在是每24小时重新auto_login，从今天开始计时。

报错啊，running没有定义。代码调试过了吗
