### ISSUE TITLE
get_chatrooms， search_chatrooms找不到老群

### ISSUE THREAD

**Issue by binqiangsun** [littlecodersh/ItChat#707]
在提交前，请确保您已经检查了以下内容!

- [x] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [x] 我已经阅读并按[文档][document] 中的指引进行了操作
- [x] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [x] 本问题确实关于`itchat`, 而不是其他项目.
- [x] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

您的itchat版本为：`1.3.10`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

>>> room = itchat.get_chatrooms(update=True)
>>> print len(room)
8

获取所有的群只有8个群， 但远不止8个， 搜索也是一样， 发现只能找到最近刚建的群

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by joeyac** [comment]
你其他群都保存到联系人列表了么

**Comment by binqiangsun** [comment]
哦哦， 保存了就可以找到了
