### ISSUE TITLE
login设置timeout问题

### ISSUE THREAD

**Issue by citisy** [littlecodersh/ItChat#716]
有没有不用修改源码可以设置登陆超时办法，望解答。

**Comment by leniy** [comment]
pip安装的，很久没有更新了。
从仓库中下载最新的

**Comment by leniy** [comment]
@littlecodersh 亲人，pip啥时候更新一下啊

**Comment by cordova2009** [comment]
同问 但是热登录这种好像会导致微信被封  不知微信网页版是怎么实现的
