### ISSUE TITLE
创建群聊报错

### ISSUE THREAD

**Issue by nenuwangd** [littlecodersh/ItChat#727]
创建群聊不成功。创建群聊返回的信息，打印如下：
```
{'BaseResponse': {'ErrMsg': '返回值不带BaseResponse', 'Ret': -1000, 'RawMsg': 'no BaseResponse in raw response'}}
Start auto replying.
```

您的itchat版本为：`1.2.32`   Python 版本为 3.7

具体的代码如下
```
itchat.auto_login(hotReload=True,enableCmdQR=2)
memberList = itchat.get_friends()[1:5]
# 创建群聊，topic键值为群聊名
chatroomUserName = itchat.create_chatroom(memberList, 'test chatroom')
print(chatroomUserName)
itchat.run(debug=True)
```
[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by chyroc** [comment]
duplicate : https://github.com/littlecodersh/ItChat/issues/734
