### ISSUE TITLE
在ipython notebook中创建的二维码清晰度太低，扫描失败

### ISSUE THREAD

**Issue by RainFung** [littlecodersh/ItChat#733]
在ipython notebook中创建的二维码清晰度太低，扫描失败

**Comment by minda163** [comment]
遇到同样的问题，请问你解决了吗? 是怎么解决的啊？ @yuwillrun 

已经解决，
![image](https://user-images.githubusercontent.com/33540791/52911494-7bf10680-32df-11e9-8f08-d053aeabf86b.png)

**Comment by RainFung** [comment]
没有解决
