### ISSUE TITLE
如何获得一个群聊的群名？

### ISSUE THREAD

**Issue by 9cat** [littlecodersh/ItChat#75]
如何获得一个群聊的群名？

我试了用：
itchat.auto_login(hotReload = True)
chatrooms = itchat.get_chatrooms()
print chatrooms

返回的是一个空的

[]

**Comment by bibotai** [comment]
我记得只能获取保存到通讯录的群聊名

**Comment by 9cat** [comment]
我有保存到通讯录的，但为何返回的是空呢？

**Comment by 9cat** [comment]
确认保存通讯录后， 全关了微信重开， 再重新扫了登录好就能正常显示微信群名了。 @bibotai 感谢。 我关了这个。
