### ISSUE TITLE
内容中emoji表情的一种处理方法

### ISSUE THREAD

**Issue by 6bigfire** [littlecodersh/ItChat#76]
有人的昵称中有很多emoji符号，在群聊回复时，每个emoji符号会变成这样的字符串：
`"<span class=\"emoji emoji1f639\"></span>"`
穿插在内容中接收端无法正常显示。

其实emoji1f639就是'\u1f639'的unicode编码，但是试了好几种方法都没有正常让接收端显示成功，只好暂时放弃了，用了一个很笨的方法先把这些emoji符号暂时全部过滤掉，实现方法如下：
在clint.py文件中，导入BeautifulSoup模块
`from bs4 import BeautifulSoup`
修改send_msg函数，将'Content'赋值修改为如下方式：
`'Content': BeautifulSoup(msg,"lxml").get_text(),`

目前功能使用正常，但是没有检查数据库中用户昵称的一致性问题。

**Comment by littlecodersh** [comment]
@6bigfire 请尝试更新itchat版本，该问题在主分支中已经被修复了很久了。

**Comment by 6bigfire** [comment]
how？？？%>_<%

**Comment by littlecodersh** [comment]
@6bigfire 
```bash
python -m pip install itchat --upgrade
```

**Comment by 6bigfire** [comment]
我是说问题是如何修复的呢？

**Comment by littlecodersh** [comment]
就是做了一个简单的替换，具体的实现你可以看[emoji_formatter][code]。

[code]: https://github.com/littlecodersh/ItChat/blob/master/itchat/tools.py

**Comment by 6bigfire** [comment]
%>_<%我在python3下试试，之前手工转了显示不正常

**Comment by littlecodersh** [comment]
好的
