### ISSUE TITLE
程序存活但无法正常交互

### ISSUE THREAD

**Issue by Lampere1021** [littlecodersh/ItChat#77]
使用的screen把机器人服务挂起
29357.wxrobot2 (Detached) 9月12号11：17 挂起
29357.wxrobot2 (Detached) 9月13号08：35 机器人无法服务

但是机器人没有退出，因为在手机端能看到显示是在网页版微信登录中。和机器人聊天、发文件没有任何回应。像是挂了一样。
在手机上退出网页版微信登录能看到挂起机器人的那个进程在屏幕上显示出来了LOG OUT。可以确定机器人这个进程没有退出，为什么不正常提供服务呢

**Comment by littlecodersh** [comment]
@Lampere1021 微信后台在特定情况下会不再返回相关消息，具体的情况我这里也在研究。
如果需要修复的话重新登陆即可。
另，建议使用ios微信并保持在线。

**Comment by Lampere1021** [comment]
收到，十分感谢。能留个联系方式嘛，遇到问题可以及时沟通！

在 2016年9月13日 下午12:36，LittleCoder <notifications@github.com>写道：

**Comment by littlecodersh** [comment]
@Lampere1021 好的，i7meavnktqegm1b@qq.com
