### ISSUE TITLE
我有一个不成熟的想法……

### ISSUE THREAD

**Issue by maxoyed** [littlecodersh/ItChat#793]
通过`itchat`和`flask`开发一系列微信的API给小程序端调用，是不是就能在微信里再开个微信了[Smirk]

**Comment by weathon** [comment]
理论上没必要，你只需要在小程序里套一个网页微信就够了 @maxoyed

**Comment by GenkunAbe** [comment]
听起来不错，像 Android 端的小程序是支持在最近任务界面显示的，很方便切换，这样的话就可以同时开两个聊天窗口了（同一个微信帐号）。

**Comment by AllennewLuo** [comment]
既然是安卓了，多开有什么地方不满足需求？

**Comment by GenkunAbe** [comment]
@AllennewLuo 就是同一个帐号下同时跟两个人聊天的情况，或者一个打开公众号另一个打开聊天窗口。

**Comment by AllennewLuo** [comment]
原来是一个账号，看漏了，公众号文章我习惯了悬浮

发自我的 iPhone
