### ISSUE TITLE
友情链接请求：Wechaty（Javascript个人微信号机器人）

### ISSUE THREAD

**Issue by zixia** [littlecodersh/ItChat#8]
[Wechaty](https://github.com/zixia/wechaty) Wechaty is wechat for bot in Javascript(ES6). It's a Personal Account Robot Framework/Library.

交换个友情链接吧，我已经加了你的。:)
https://github.com/zixia/wechaty#see-also

**Comment by littlecodersh** [comment]
@zixia 我给加上了：[这里](https://github.com/littlecodersh/ItChat#see-also)
项目介绍我自作主张翻译成了中文，如果有不妥我再改。
帮我改个项目介绍吧：微信个人号接口（支持文件、图片上下载）、微信机器人及命令行微信。三十行即可自定义个人号机器人。

**Comment by zixia** [comment]
已经按照你的介绍说明，帮你的改好：
https://github.com/zixia/wechaty/commit/c762d1b9351e3e69bca07f6b768dd30596ddd655

你可不可以帮我把链接里面的“基于JS(ES6)的微信个人账号机器人框架/库”，改为：
> 基于Javascript(ES6)的微信个人账号机器人NodeJS框架/库

谢谢啦。:)

**Comment by littlecodersh** [comment]
@zixia 改好了~
