### ISSUE TITLE
钉钉有没有类似的项目（网页版）

### ISSUE THREAD

**Issue by fbigun** [littlecodersh/ItChat#811]
钉钉网页版实现的项目有吗，钉钉开放平台的上机器人限制太多。想将自己的个人号变成机器人。
搜索没有发现有这个类型的项目，都是封装钉钉开发的机器人。

**Comment by noyyyy** [comment]
同问。上面的大佬有解决方案了吗

**Comment by fbigun** [comment]
没有，估计没什么人玩
