### ISSUE TITLE
自动加好友的功能必须要开启加好友验证才会处理，而且经常会停掉不响应加好友申请

### ISSUE THREAD

**Issue by yangyunxiao** [littlecodersh/ItChat#82]

**Comment by littlecodersh** [comment]
@yangyunxiao 不开启好友验证不就直接加上了吗？
停掉的时候自动回复还可以运行吗？

**Comment by yangyunxiao** [comment]
不开启好友验证的话  没响应    停掉之后其他的消息没影响的   研究了好久你的代码还是没看出来问题啊

**Comment by littlecodersh** [comment]
@yangyunxiao 没响应具体指什么？你可以尝试把通过好友的命令的返回值调出来看一下返回值里面的错误信息是什么。

**Comment by kael777** [comment]
好友加不上，add_friend的返回值打印出来是{u'BaseResponse': {u'ErrMsg': u'', u'Ret': 1}}

**Comment by littlecodersh** [comment]
@kael777 你尝试更新一下1.1.7

**Comment by 9cat** [comment]
这个问题解决了吗？ 我在版本1.2.18用以下代码， 不开验证， 还是无法反过来加对方。
`@itchat.msg_register('Friends')
def add_friend(msg):
	itchat.add_friend(**msg['Text']) # 该操作会自动将新好友的消息录入，不需要重载通讯录
	itchat.send_msg('感谢您添加xxxxx号', msg['RecommendInfo']['UserName'])`

**Comment by littlecodersh** [comment]
@9cat 不开验证的话是不行的，这是通过好友验证的方式。
