### ISSUE TITLE
传送图片出现'Ret': 1101 无法传送

### ISSUE THREAD

**Issue by alexsamtw** [littlecodersh/ItChat#820]
在提交前，请确保您已经检查了以下内容!

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ ] 我已经阅读并按[文档][document] 中的指引进行了操作
- [ ] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [ ] 本问题确实关于`itchat`, 而不是其他项目.
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

您的itchat版本为：`1.3.10`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：
 4/29上午11点最后传送图片可成功，服务器回传讯息为BaseResponse': {'Ret': 0, 'ErrMsg': '请求成功', 'RawMsg': '请求成功'}，下午2点左右传送图片从服务器端收到'BaseResponse': {'Ret': 1101, 'ErrMsg': '', 'RawMsg': ''}，就无法传送图片了。

这个项目真的很棒，如果不维护了真是可惜....

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by chenbotao828** [comment]
+1 貌似是四分之一左右机率发生，其他的时候发送成功

**Comment by qq502746484** [comment]
+1 29号下午开始，一旦重连就不能再推图了

**Comment by LiaoLIDIP** [comment]
我也遇到这个问题了  有什么办法嘛。。。

**Comment by alexsamtw** [comment]
刚才测试jpg已可以成功传送，包含网页版也是
