### ISSUE TITLE
命令行二维码图像显示不全

### ISSUE THREAD

**Issue by Rongpeng** [littlecodersh/ItChat#83]
我在运行这个例子的时候出现了二维码显示不全的情况，请coder看下。https://github.com/littlecodersh/ItChat/archive/robot.zip

![img_20160921_203359](https://cloud.githubusercontent.com/assets/3080138/18736366/4134d12e-803b-11e6-9608-e78f8e453450.jpg)

**Comment by littlecodersh** [comment]
@Rongpeng 目前robot分支已经不更新了，所以这个问题只能建议你使用主分支了。
```python
itchat.auto_login(enableCmdQR=2)
```
