### ISSUE TITLE
添加好友失败

### ISSUE THREAD

**Issue by wanhmr** [littlecodersh/ItChat#84]
def add_friend(msg):
    print(msg[TEXT])
    itchat.add_friend(**msg['Text'])
    itchat.send_msg('项目主页：github.com/littlecodersh/ItChat\n'
        + '源代码  ：回复源代码\n' + '图片获取：回复获取图片\n'
        + '欢迎Star我的项目关注更新！', msg['RecommendInfo']['UserName'])
这段代码执行了, 但是好友没有添加成功, msg[TEXT]是有输出的
使用的 python3.5

**Comment by xufangda** [comment]
不好使+1；

代码：
itchat.add_friend(userName=msg['Text']['userName'],
status=3, 
ticket=msg['Text']['userInfo']['Ticket'],
userInfo=msg['Text']['userInfo'])

**Comment by xufangda** [comment]
这种也试验了
b=itchat.add_friend(**msg['Text'])

返回值都是
{'BaseResponse': {'Ret': 1, 'ErrMsg': ''}}

**Comment by hadagfem** [comment]
不好使+1；

**Comment by xufangda** [comment]
谁的好使了，给贴个代码呗

**Comment by littlecodersh** [comment]
@xufangda @hadagfem 是我这里的1.1.6版本更新的时候出现的问题，升级1.1.7即可
