### ISSUE TITLE
二维码不通过命令行显示

### ISSUE THREAD

**Issue by L1cardo** [littlecodersh/ItChat#840]
在提交前，请确保您已经检查了以下内容!

- [no] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [yes] 我已经阅读并按[文档][document] 中的指引进行了操作
- [yes] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [yes] 本问题确实关于`itchat`, 而不是其他项目.
- [yes] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

您的itchat版本为：`[1.3.10]`。

其他的内容或者问题更详细的描述都可以添加在下面：

> [您的内容]

设置如下，但是二维码不通过命令行显示，而是直接打开二维码图片
<img width="526" alt="屏幕快照2019-06-15上午1 14 58" src="https://user-images.githubusercontent.com/33802186/59526452-888f0f80-8f0b-11e9-8f93-346064fd3e8f.png">

**Comment by weathon** [comment]
因为你设置了－1
@L1cardo

**Comment by L1cardo** [comment]
你这里不是要求设置-1嘛...
![4FA78A49-8544-4132-B19D-58050A7BECBF](https://user-images.githubusercontent.com/33802186/59545197-c90f7d00-8f4d-11e9-9631-dd8061c08db2.jpeg)

那我应该怎么设置呢？

**Comment by L1cardo** [comment]
@weathon 你知道怎么设置吗？

**Comment by bufeii** [comment]
设置为1+1>1
2019年6月15日, 09:13，在 Licardo <notifications@github.com<mailto:notifications@github.com>> 已写:

你这里不是要求设置-1嘛...
[4FA78A49-8544-4132-B19D-58050A7BECBF]<https://user-images.githubusercontent.com/33802186/59545197-c90f7d00-8f4d-11e9-9631-dd8061c08db2.jpeg>

那我应该怎么设置呢？

**Comment by L1cardo** [comment]
我是在mac上面运行   mac的终端是白底的 ，你不是说要设置为负值嘛？
我现在设置为  `itchat.auto_login(enableCmdQR=1+1>1)`   
这样对吗？

**Comment by bufeii** [comment]
是不是缺少相应的库啊？？
看看了看文档，浅色是－1.

**Comment by L1cardo** [comment]
`pip3 install itchat`  我是这样安装的
那个需要什么库？你知道吗？

**Comment by bufeii** [comment]
itchat.run(debug=True)
贴一下Debug日志吧




2019年6月15日, 21:30，在 Licardo <notifications@github.com<mailto:notifications@github.com>> 已写:

pip3 install itchat 我是这样安装的
那个需要什么库？你知道吗？

**Comment by weathon** [comment]
想起来了，命令行显示要安装pillow @L1cardo

**Comment by L1cardo** [comment]
@weathon 安装了 还是不行

**Comment by weathon** [comment]
那我不太清楚了，我也不是开发者
