### ISSUE TITLE
itchat.run()这个语句是起什么作用的？

### ISSUE THREAD

**Issue by grant36x** [littlecodersh/ItChat#842]
login之后，再加itchat.run()这个语句是起什么作用呢，如果不加的话，后续操作也能用吧？

**Comment by leochen4891** [comment]
没有先读一读文档的习惯么。。。

**Comment by htyangya** [comment]
很显然和所有gui、webui一样，是启动框架自己的主循环用的，你注册的监听函数通通都得在程序的主循环里等待被调用。。。
