### ISSUE TITLE
请问关键词自动回复该怎么设置呢

### ISSUE THREAD

**Issue by liuguangsai** [littlecodersh/ItChat#86]
请问关键词自动回复该怎么设置呢 比如存一个文档里  格式为   “关键词  | 回复内容”   代码该怎么写呢   本人刚接触  不甚感激！

**Comment by xufangda** [comment]
ItChat_robot.py那个文件里，有一段叫代码
if “pic” in msg('text')
     itchat.send('内容')

pic就是你的关键词，内容就是你的内容。这样就可以按关键词回复。

你这文档和代码都不看，作者估计很无语。

**Comment by liuguangsai** [comment]
@xufangda 非常感谢  我也很想多看下相关文档和代码介绍的  但是没找到这块   谢谢你的解答！
