### ISSUE TITLE
打算用c# 写一个微信桌面版，有人能提供API接口吗？

### ISSUE THREAD

**Issue by JohnnyZhang0628** [littlecodersh/ItChat#865]
目前打算机器人自动回复，消息类型目前只考虑文本类型（语音、文件）不考虑

**Comment by kamike** [comment]
现成的api没有了，需要自己去破解客户端，应该不是http请求

**Comment by JohnnyZhang0628** [comment]
> 现成的api没有了，需要自己去破解客户端，应该不是http请求

是的。PC的版的，我抓包都没有http请求。web版又不能用。

**Comment by WangPney** [comment]
超稳定MAC和Ipad混合协议， 公司API接口接入合作，需要的可以先看资料：https://wkteam.gitbook.io/doc/~~~
