### ISSUE TITLE
加好友，能获取到信息，但无法自动同意

### ISSUE THREAD

**Issue by poach123** [littlecodersh/ItChat#87]
> @itchat.msg_register(FRIENDS)
> def add_friend(msg):
>     print msg
>     itchat.add_friend(**msg['Text']) # 该操作会自动将新好友的消息录入，不需要重载通讯录
>     itchat.send_msg('Nice to meet you!', msg['RecommendInfo']['UserName'])

能够打印出json的新的好友信息，但并不能自动同意。

**Comment by littlecodersh** [comment]
@poach123 是我这里的1.1.6版本更新的时候出现的问题，升级1.1.7即可
