### ISSUE TITLE
这有款超稳定的微信API，大家可以看下，https://wkteam.gitbook.io/doc/~~~

### ISSUE THREAD

**Issue by WangPney** [littlecodersh/ItChat#874]
超稳定MAC和Ipad混合协议， 公司API接口接入合作，需要的可以先看资料：https://wkteam.gitbook.io/doc/~~~

**Comment by soulmachine** [comment]
楼上垃圾。骗钱且技术还不行。

https://github.com/wechaty/wechaty   这个项目是开源的，也有iPad和Mac协议，**开源**且免费。

楼上敢开源吗？
