### ISSUE TITLE
这框架目前不更新了，大家可以看这个 https://wkteam.gitbook.io/api/ 缺点是收费

### ISSUE THREAD

**Issue by WangPney** [littlecodersh/ItChat#875]

**Comment by chuanwu** [comment]
我近期会发布一版不收费的。但是只能满足大家日常使用的基础功能。

**Comment by soulmachine** [comment]
> 我近期会发布一版不收费的。但是只能满足大家日常使用的基础功能。

坐等楼主开源

**Comment by 897385237** [comment]
> 我近期会发布一版不收费的。但是只能满足大家日常使用的基础功能。

厉害 可以的~~

**Comment by chuanwu** [comment]
@soulmachine @897385237 
有兴趣的朋友可以先加到 [Telegram WeChatGroup](https://t.me/joinchat/Dg969BctogAnNuyvf1iN2Q)

**Comment by chuanwu** [comment]
@soulmachine @sunyi00 @897385237 
有兴趣的朋友可以先加到[Telegram WechatGroup](https://t.me/joinchat/Dg969BctogAnNuyvf1iN2Q)
或者是添加微信搜索`xriv3r`

**Comment by harrett** [comment]
> 我近期会发布一版不收费的。但是只能满足大家日常使用的基础功能。

楼主有进展吗？

**Comment by chuanwu** [comment]
@harrett 
[WechatBot传送门](https://github.com/chuanwu/WechatBot)

**Comment by soulmachine** [comment]
楼上垃圾。骗钱且技术还不行。

https://github.com/wechaty/wechaty   这个项目是开源的，也有iPad和Mac协议，**开源**且免费。

楼上敢开源吗？
