### ISSUE TITLE
🙂上不去

### ISSUE THREAD

**Issue by 2048537793** [littlecodersh/ItChat#879]
1

**Comment by saaak** [comment]
你这是推销吧，好几个下面都看见你了

**Comment by 2048537793** [comment]
不是 宣传开源框架------------------ 原始邮件 ------------------
发件人: "王康"<notifications@github.com>
发送时间: 2019年12月6日(星期五) 中午11:37
收件人: "littlecodersh/ItChat"<ItChat@noreply.github.com>;
抄送: "Mr.Li"<2048537793@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [littlecodersh/ItChat] 关于itchat解决新号登录不了的说明（新手必看！！！） (#879)



你这是推销吧，好几个下面都看见你了
 
&mdash;

**Comment by StormFeng** [comment]
什么JB玩意儿，净TM污染这环境

**Comment by saaak** [comment]
> 什么JB玩意儿，净TM污染这环境

举报了

**Comment by 2048537793** [comment]
> 什么JB玩意儿，净TM污染这环境

嘴吃屎了？ 老子又没逼你用 

> > 什么JB玩意儿，净TM污染这环境
> 
> 举报了

您开心就好

**Comment by 2048537793** [comment]
> 什么JB玩意儿，净TM污染这环境

嘴吃屎了？
