### ISSUE TITLE
国际版微信网页端上传下载报错

### ISSUE THREAD

**Issue by littlecodersh** [littlecodersh/ItChat#88]
@wenzhoou 在Issue#1中提出，确认为bug故新建issue。
## 原文
在国外上传下载会出现问题。

**第一**
 也许是我在GFW外面的原因，upload的服务器地址和目前程序不一样。
手动修改地址就可以上传了。
```python
url = 'https://file%s.wx.qq.com/cgi-bin/mmwebwx-bin/webwxuploadmedia?f=json'
改成
url = 'https://file%s.web.wechat.com/cgi-bin/mmwebwx-bin/webwxuploadmedia?f=json'
```

webwxuploadmedia地址你会反馈到代码上吗，那个我弄的不对，
https://file.web.wechat.com/ 是存在的。
https://file2.web.wechat.com/  应该改为 https://file.web2.wechat.com/  。

**第二**
发现有的图片能下载有的不能下载，
我在这里添加了一个配置就可以了
```python
url = '%s/webwxgetmsgimg' % self.loginInfo['url']
payloads = {
    'MsgID': m['NewMsgId'],
    'skey': self.loginInfo['skey'],
    'type': 'big',}    # <----- 添加这个代码
```
## 现存疑问
1. 由于微信存在两个主页：wx.qq.com与web.wechat.com，是否你那里两个都可以登录
2. 如果可以，那么wx.qq.com主页登陆进去后是否会自动转跳
3. 以及，上传下载的url是否还是变成了web.wechat.com

@wenzhoou 望解答，祝好！

**Comment by wenzhoou** [comment]
@littlecodersh 
1.是的都可以登陆
2.如你所说，的确是自动跳转到了web.wechat.com
3.上传下载的url 还是变成了xxxx.wechat.com 我这里观察除了一些静态资源文件，css, js, 和联系人图片一些东西以外基本上都是xxxx.wechat.com了

另外是不是可以搞个vpn这样子你也能直接验证自己的一些想法。
vpn我有些不太会，你可以告诉我怎么搞，我来做vpn主机。

itchat是个非常棒的项目，谢谢你的分享。祝好。

**Comment by littlecodersh** [comment]
@wenzhoou 了解！
非常感谢你的帮助，目前的话还不需要麻烦你那里设置vpn。
通过我自己的主机已经复现了这个问题，确认具体情况相同的话我就着手开始修复了。

**Comment by huming2207** [comment]
@littlecodersh 刚看到这个你们issue，试了下。
本人在澳洲墨尔本，运营商是TPG和RMIT的AARNET（土澳教育网），测试发现好像并没有跳转。但两者ping时解析出来的IP不同：

```
hu-mac:work Jackson$ ping web.wechat.com
PING web1.wechat.com (203.205.147.171): 56 data bytes
64 bytes from 203.205.147.171: icmp_seq=0 ttl=54 time=137.717 ms
64 bytes from 203.205.147.171: icmp_seq=1 ttl=54 time=136.848 ms
64 bytes from 203.205.147.171: icmp_seq=2 ttl=54 time=138.242 ms
^C
--- web1.wechat.com ping statistics ---
4 packets transmitted, 3 packets received, 25.0% packet loss
round-trip min/avg/max/stddev = 136.848/137.602/138.242/0.575 ms
hu-mac:work Jackson$ ping wx.qq.com
PING wx1.qq.com (203.205.151.221): 56 data bytes
64 bytes from 203.205.151.221: icmp_seq=0 ttl=51 time=140.224 ms
64 bytes from 203.205.151.221: icmp_seq=1 ttl=51 time=139.622 ms
64 bytes from 203.205.151.221: icmp_seq=2 ttl=51 time=141.548 ms
64 bytes from 203.205.151.221: icmp_seq=3 ttl=51 time=142.148 ms
64 bytes from 203.205.151.221: icmp_seq=4 ttl=51 time=141.574 ms
^C
--- wx1.qq.com ping statistics ---
5 packets transmitted, 5 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 139.622/141.023/142.148/0.943 ms

```

我这在macOS下试的，等啥时候有空进Windows用fiddler看一下详细情况。

**Comment by littlecodersh** [comment]
@wenzhoou 我尝试做了一个修复，生成了新的[wheel][itchat-1.1.12]，帮忙测试下是否还存在问题吧。

**安装**
先将[wheel][itchat-1.1.12]下载到本地，之后运行该命令：
```bash
pip install itchat-1.1.12-py2.py3-none-any.whl
```
**测试程序**
主要测试图片的上传和下载，特别注意web2.wechat.com的情况，可以使用如下程序：
```python
import itchat
from itchat.content import *

@itchat.msg_register(PICTURE)
def reply(msg):
    msg['Text'](msg['FileName'])
    return '@img@' + msg['FileName']

itchat.auto_login(True)
itchat.run()
```

@huming2207 的确很多墙外的地方都是不转跳的，不过确实ip不同也存在转跳的地方，所以我这里还是需要进行一个修复。

[itchat-1.1.12]: http://7xrip4.com1.z0.glb.clouddn.com/ItChat/Issues/itchat-1.1.12-py2.py3-none-any.whl

**Comment by wenzhoou** [comment]
感觉这个whl有问题。刚刚测试，结果是无法login，提示
Failed to get QR Code, please restart the program

**Comment by littlecodersh** [comment]
@wenzhoou 前面这一段没有改，你再试试登陆？

**Comment by wenzhoou** [comment]
我这里现在动作正常。
