### ISSUE TITLE
微信的新功能成语接龙

### ISSUE THREAD

**Issue by KermitLee** [littlecodersh/ItChat#887]
微信的新功能成语接龙。触发条件是，在对话框里面输入，报名、成语接龙等关键词。然后换行1、小明 换行 2、
此时，就会出发到成语接龙的程序。
想问一下，如果我现在使用itchat去写，怎么触发这个功能呢？

**Comment by RobinRush** [comment]
别闹，写代码的逻辑也来当issue报有点过分了。
你可以在私聊回调里，加入关键字的对比。如果比对成功了，进入成语接龙模式。

**Comment by KermitLee** [comment]
好的，感谢指点。
