### ISSUE TITLE
初始化的时候群有的时候取不到

### ISSUE THREAD

**Issue by wenzhoou** [littlecodersh/ItChat#89]
@littlecodersh 根据个人分析。
https://web.wechat.com/cgi-bin/mmwebwx-bin/webwxinit
返回了群的id
但是被忽略了。
而且这个群的id在https://web.wechat.com/cgi-bin/mmwebwx-bin/webwxgetcontact
的时候并不会返回。
导致在接收到这个群的信息之前
用代码都无法检索到这个群

**Comment by wenzhoou** [comment]
补充说明：

这里是webinit截图
![image](https://cloud.githubusercontent.com/assets/7395961/19020305/013ca102-88e0-11e6-91c4-29793390a1db.png)
返回response
![image](https://cloud.githubusercontent.com/assets/7395961/19020312/44c7e670-88e0-11e6-90e5-6bbca9bdba24.png)
其中第二条为群组。

getcontact没有返回这个群：
![image](https://cloud.githubusercontent.com/assets/7395961/19020330/91575d0e-88e0-11e6-9026-d86a99e135ae.png)

**Comment by littlecodersh** [comment]
@wenzhoou 的确存在忽略的群聊的问题。

我当时关于这一点的考虑是这样的：
1. 如果忽略初始化时的群聊，itchat初始获取的群聊就有了一个明确的标准：即保存到通讯录的群聊
2. 如果需要获取特定的群聊，可以将其添加至通讯录中，初始化中对群聊群聊的处理可替代

所以我当时做出了不添加初始化时返回的群聊的判断，不知道是否合适？

**Comment by wenzhoou** [comment]
哦。我不知道怎么样把群聊保存到通讯录里面。你说的有道理。因为就算是webinit里面保存群聊了。但是如果用getcontact重现取得联系人，也会被清空掉。
可否教我一下怎么样把群聊保存到通讯录里？谢谢

**Comment by littlecodersh** [comment]
@wenzhoou 清空的话代码上做处理还是挺容易解决的，如果有必要也是能写的，可以不把这个考虑进去。
保存到通讯录的话是这样的：在群聊的聊天信息界面，在消息免打扰和置顶聊天下面有一个保存到通讯录，选上即可。

**Comment by wenzhoou** [comment]
个人觉得不改也行，我自己保存到通讯录好了。BUG算不上。

另外，如果不改的话暂时把他加到FAQ里面好些。我觉得。
要说修改的好处那我觉得是和官方网页版的处理更像一些。
要说修改的缺点的话，我觉得就是占用内存以及处理会变慢呀这些。
权衡利弊吧。

再啰嗦一句，如果改的话也又一个方案，可以提供一个选项：要不要加载未保存的群聊。

**Comment by littlecodersh** [comment]
@wenzhoou 好的，了解！

**Comment by littlecodersh** [comment]
@wenzhoou 在新的更新中已经修复该问题。
目前群聊的逻辑为：
* 获取并自动更新所有扫码终端上的群聊
* 若update设为True，返回保存到通讯录中的群聊，但不会清空后台其他群聊的数据

**Comment by HuangKBAaron** [comment]
@littlecodersh ChatRoom是否能加入一个保存群聊到通讯录的方法？是不是只有保存到通讯录的群聊才会有群的Uin？
