### ISSUE TITLE
文档的问题

### ISSUE THREAD

**Issue by zohoFrank** [littlecodersh/ItChat#9]
https://itchat.readthedocs.io/zh/latest/5.Reply/#send
send_msg send_img等小标题下的“方法”中，方法名都是send，与其下方例子不一致，似乎不合本意？

另外根据例子的话，send_img也要标注 '@ img@图片地址' 嘛？

**Comment by littlecodersh** [comment]
符合本意的，itchat有两个方法
* 发送所有类型文件的`send`（需要通过`@img@`类似的限定类型）
* 发送特定类型文件的方法：例如`send_img`

我想`send`的实现能够让你更好的理解这个问题：
```python
def send(msg, toUserName = None):
    if msg is None: return False
    if msg[:5] == '@fil@':
        return __client.send_file(msg[5:], toUserName)
    elif msg[:5] == '@img@':
        return __client.send_image(msg[5:], toUserName)
    elif msg[:5] == '@msg@':
        return __client.send_msg(msg[5:], toUserName)
    else:
        return __client.send_msg(msg, toUserName)
```

**Comment by zohoFrank** [comment]
谢谢回复，明白你的意思，我指的是文档的措辞的问题，比如现在的内容是

### send_img方法
* 方法:  
`send(fileDir, toUserName = None)`

是否应该改成send_img?因为前文已经提过了send的方法？

**Comment by littlecodersh** [comment]
@zohoFrank 是的，我编写文档的时候疏忽了。
非常感谢:)
