### ISSUE TITLE
【新手必看！！！】做微信机器人，淘宝客、社群助手、营销系统，客服系统，监管系统的、企业合作或者个人寻求稳定API的，可以看下这个API https://docs.wkteam.cn

### ISSUE THREAD

**Issue by 1732073705** [littlecodersh/ItChat#912]
17年前登陆过web网页版的微信可以登录并使用此框架，17年后的新注册微信号包括以前没有登陆过web网页版微信的号无法使用此框架，想搞着自己的机器人搞着玩的，可以去购买支持web登录微信号，如果是公司开发需要，那么唯一选择就是找正规企业合作API，（因为大家github搜索出来的基本都是网页版 wxpy wechaty itchat等等都是基于网页微信开发的）。所以以寻找API提供商，不过著名的提供商入门条件较高5W起步，QQ 微信提供的一堆二手骗子， 容易封号，无法维护， 赚一波钱就跑（微信一升级，API就废了，但是价格便宜 和割韭菜一样），所以推荐大家 寻找：有官网、API、系统、有能力提供协议升级稳定的企业（二手骗子一般没有）

**Comment by 1732073705** [comment]
API相关资料：https://docs.wkteam.cn 打不开可以自备梯子访问
公司介绍：http://www.wkgjkj.com/pc/
PostMan在线测试：https://documenter.getpostman.com/view/1268847/SzKQxKf5?version=latest

商务合作微信：LoChaX、licx758 (可以添加客服微信索要资料)

**Comment by soulmachine** [comment]
楼上垃圾。骗钱且技术还不行。

https://github.com/wechaty/wechaty   这个项目是开源的，也有iPad和Mac协议，**开源**且免费。

楼上敢开源吗？

**Comment by LiChangXing** [comment]
> 楼上垃圾。骗钱且技术还不行。
> 
> https://github.com/wechaty/wechaty 这个项目是开源的，也有iPad和Mac协议，**开源**且免费。
> 
> 楼上敢开源吗？

。。。。。麻烦提供下我们骗钱 和技术的不行的证据，您用过吗？还有wechaty是ipad mac是收费的，而且他们已经不提供api转型系统了，他也是我们合作伙伴，谢谢，麻烦了解清楚再来诋毁。

**Comment by soulmachine** [comment]
@LiChangXing 

* 你在别人的项目issue里面发广告，这跟公共场合随地大小便一样，没素质
* <https://github.com/songtianyi/wechat-go> 这个项目你仅仅贡献了14行代码，而且还是文档，也就是说你一行代码都没写，也好意思说这项目是你开源的？

**Comment by 1732073705** [comment]
> @LiChangXing
> 
> * 你在别人的项目issue里面发广告，这跟公共场合随地大小便一样，没素质
> * https://github.com/songtianyi/wechat-go 这个项目你仅仅贡献了14行代码，而且还是文档，也就是说你一行代码都没写，也好意思说这项目是你开源的？
> 
> Shame on you!

我们研发开源的，这位是android开发，不是go工程师。
