### ISSUE TITLE
Mac OS 不支持？

### ISSUE THREAD

**Issue by hktalent** [littlecodersh/ItChat#920]
itchat.auto_login()
Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Your wechat account may be LIMITED to log in WEB wechat, error info:
<error><ret>1203</ret><message>To protect your account, logging in to WeChat via the web has been suspended. Use WeChat for Windows or WeChat for Mac to log in on a computer. Download WeChat for Windows or Mac at http://wechat.com.</message></error>

**Comment by shirubei** [comment]
Get source from this thread  https://github.com/littlecodersh/ItChat/pull/935  ( https://github.com/luvletter2333/ItChat )
   and check if you can login. If it works, then that's all.
  If not , your account had been blocked for using WEB wechat.  No solution.
