### ISSUE TITLE
好用

### ISSUE THREAD

**Issue by 2905683882** [littlecodersh/ItChat#926]
挺好用的

**Comment by oliverchu** [comment]
大快人心，一大波卖茶叶的一夜间失业

**Comment by JKinGH** [comment]
> 你好 作者，我们是Wechat合作的API团队，我微信LoChaX，基于github在中国那么多的开发者，且很多机器助手一类的项目有很多个人使用，因web版本关闭，导致很多优秀的项目从此无人问津，我们团队目前想和很多优秀的开源的项目合作，我们提供API底层，你负责功能开源，合作搞些技术开源的东西，服务于大众，有兴趣我们可以沟通一下，如何更好为开源社区的技术们提供一些便捷的功能，且双方也可以因此获取企业合作青睐，实现共赢，这是我们技术文档 https://docs.wkteam.cn
> ，有意愿我们可以沟通下~

把个人的API 免费开源出来再谈吧，企业服务收费可以理解，个人的都收费还谈何开源？

**Comment by ycsddn** [comment]
个人测试199元/月，你这开毛线源

**Comment by leeguooooo** [comment]
> 你好 作者，我们是Wechat合作的API团队，我微信LoChaX，基于github在中国那么多的开发者，且很多机器助手一类的项目有很多个人使用，因web版本关闭，导致很多优秀的项目从此无人问津，我们团队目前想和很多优秀的开源的项目合作，我们提供API底层，你负责功能开源，合作搞些技术开源的东西，服务于大众，有兴趣我们可以沟通一下，如何更好为开源社区的技术们提供一些便捷的功能，且双方也可以因此获取企业合作青睐，实现共赢，这是我们技术文档 https://docs.wkteam.cn
> ，有意愿我们可以沟通下~

贵的要死 大家别去看了 收费的  不是开源的

**Comment by nnewkin** [comment]
> 你好 作者，我们是Wechat合作的API团队，我微信LoChaX，基于github在中国那么多的开发者，且很多机器助手一类的项目有很多个人使用，因web版本关闭，导致很多优秀的项目从此无人问津，我们团队目前想和很多优秀的开源的项目合作，我们提供API底层，你负责功能开源，合作搞些技术开源的东西，服务于大众，有兴趣我们可以沟通一下，如何更好为开源社区的技术们提供一些便捷的功能，且双方也可以因此获取企业合作青睐，实现共赢，这是我们技术文档 https://docs.wkteam.cn
> ，有意愿我们可以沟通下~

真恶心

**Comment by LiuSiT** [comment]
打肿脸充官方
