### ISSUE TITLE
如何保存语音进指定目录？

### ISSUE THREAD

**Issue by huming2207** [littlecodersh/ItChat#94]
各位好，

想请教一下如何把语音文件保存进指定目录？

看了下文档的handler章节部分，以及源码（hclient.py），是只能把语音文件保存在python脚本的运行目录中吗？还是可以自定义呢？

Regards,
Jackson.

**Comment by littlecodersh** [comment]
@huming2207 用这个命令：
```python
msg['Text'](theDirYouWantWithFileName)
```
源码的话在client.py的318行：
```python
with open(voiceDir, 'wb') as f: f.write(tempStorage.getvalue())
```

**Comment by huming2207** [comment]
@littlecodersh 哦哦这回明白了
不是很熟Python所以之前有点没懂哈哈

谢谢了！

**Comment by littlecodersh** [comment]
@huming2207 没事，有不懂的都可以提Issue，我会尽快回复的。

**Comment by scjiaer** [comment]
想请教一下原始语音的保存格式和编码，保存为MP3/WAV/OGG/AMR这些格式在Ubuntu下均支持播放，但是如果将保存后的文件直接拿去做语音识别，均会报无法识别文件的错误（猜测可能缺少部分头文件信息），通过pydub读取再重新转成wav，虽然不报错，但是识别结果基本不靠谱，故想请教一下解决方案，感谢！

**Comment by littlecodersh** [comment]
@scjiaer 看文件头是个id3的metadata，我目前也没有找到转换的方法。

**Comment by scjiaer** [comment]
@littlecodersh 多谢，如有新的进展还望不吝分享:)
