### ISSUE TITLE
解决微信无法登录微信web 问题

### ISSUE THREAD

**Issue by gitgzz** [littlecodersh/ItChat#957]
无法使用微信网页版的账号解锁方法：
(非+86账号无效)

截止发文前测试有效，如有需要可尝试

1.登录微信新上线的网页版文件传输助手
 https://filehelper.weixin.qq.com

2.登录微信网页版，即可正常登录
https://wx.qq.com

(非本人发现，为其它相关项目人员提及，代发帖)

已被TX修复,无法使用

**Comment by SuperChay** [comment]
你这不行啊

**Comment by lasncc2** [comment]
已经封了

**Comment by WangPney** [comment]
登录不上了
