### ISSUE TITLE
itchat可以通过搜索公众号，对公众号添加关注吗

### ISSUE THREAD

**Issue by dingwa990** [littlecodersh/ItChat#96]
如题。我看更多的是关于消息和聊天的。里面也有个添加朋友的方法，公众号不知道是否可以添加关注呢？？？？

**Comment by littlecodersh** [comment]
@dingwa990 可以呀，可以通过名片添加关注。
```python
import itchat

@itchat.msg_register(itchat.content.CARD)
def print_cd(msg):
    r = itchat.add_friend(msg['RecommendInfo']['UserName'], 1)

itchat.auto_login(True)
itchat.run()
```

**Comment by dingwa990** [comment]
名片只能几个或少量可以。批量的公众号的话还是通过搜索出来关注。
另外请问，SyncCheck返回：window.synccheck={retcode:"1101",selector:"0"}，retcode有几种意思？1101表示什么？

**Comment by littlecodersh** [comment]
@dingwa990 目前网页版微信没有办法搜索公众号，所以就没有办法了。
1101一般来说就是手机端退出了登陆。

**Comment by dingwa990** [comment]
@littlecodersh 手机端没退出哦，刚刚登录的还。

**Comment by dingwa990** [comment]
哦，对了，刚才调试。

**Comment by littlecodersh** [comment]
@dingwa990 ？

**Comment by dingwa990** [comment]
SyncCheck请求时候，为什么经常报：“基础连接已关闭，连接被意外关闭” 呢？

**Comment by littlecodersh** [comment]
@dingwa990 因为你网络环境不好吧

**Comment by dingwa990** [comment]
梭嘎，好了。好像是和网络有关系，我吧无线关了。
