### ISSUE TITLE
123131313

### ISSUE THREAD

**Issue by 2905683882** [littlecodersh/ItChat#964]
123131331

**Comment by WangPney** [comment]
服务好用倒是很好用，我们公司用了3年多了，就是没有红包类的，我们做社群红包裂变需要呀！

**Comment by 2048537793** [comment]
我之前试了itchat，10个微信都上不了itchat，后来没办法，用不了web，就用这个服务，正好是这个，还算不错，比某Y强多了，某Y是一点技术支持没，不过个8级英语看不懂文档
