### ISSUE TITLE
【研发必看！！】无法使用itchat的平替框架，支持开发机器人/客服/监管/淘客系统

### ISSUE THREAD

**Issue by 2048537793** [littlecodersh/ItChat#969]
挺好用的品牌https://www.wkteam.cn/ 
这个技术比较简单，不会崩溃及莫名卡死，直接调用，挺好用的推荐下
就是付费的，请知悉

**Comment by chxt100016** [comment]
有中国人的地方就有垃圾广告

**Comment by 2905683882** [comment]
> 有中国人的地方就有垃圾广告

这倒还好，能解决问题就行，itchat还能不能用，大家心里也清楚，平白浪费测试时间，其他平台打着免费的幌子二次收费，让人唾弃，有些新的个人开发者的框架，用了后封号，不更新，炸锅，我给公司做一个小功能，天天换框架，新用户自己搞着玩 不做业务  用pc hook 比如 鬼手逆向，ntchat，都可以，要是企业业务 必须还是用收费的 类似wehchaty的 padlocal 或者可爱猫 或者E云管家这种平台

**Comment by chxt100016** [comment]
我已经收到你的邮件，谢谢。

**Comment by WangPney** [comment]
前公司用的还不错

**Comment by gybin02** [comment]
itchat 已经不能用了 2022.10

**Comment by chxt100016** [comment]
我已经收到你的邮件，谢谢。

**Comment by chxt100016** [comment]
我已经收到你的邮件，谢谢。
