### ISSUE TITLE
如何转发完整的Sharing 

### ISSUE THREAD

**Issue by 9cat** [littlecodersh/ItChat#97]
在Share type中，我了解可以如下的方式分解出内容 ：
 "Sharing" in type:
		link = msg['Url']
		text = msg['Text']

但是如果我要再转到另一个群中，而用微信的方式 ， 应该如何 发送？
例如 ：

![image](https://cloud.githubusercontent.com/assets/1379110/19324403/412671ce-9076-11e6-80b4-288b44da75d2.png)

这样的话， 我应该如何 construct 然后send?

**Comment by littlecodersh** [comment]
@9cat 我在22号issue里面记录了这个问题，目前还没有找到解决办法。
